### PR TITLE
Fix #2258: Update error color for A11y Scanner Contrast Ratio

### LINKED ISSUE #2258: Changes needed in Add Profile Activity [A11y]
**Describe the bug**

Add Profile Activity is not fully compatible with some users from the Accessibility point of view.

Screenshot_2020-12-06-23-20-28-91_80a9469f53bfe75dbc6e8989be28e2f0

Issue 1 - The circular image view, edit image button does and info button do not have any content label.
Issue 2 - The Profile Input Views present for Entering
 - Name of the user
 - 3-digit Pin
 - Confirming that pin 
 
Does not have a content label

Issue 3 - Certain Views does not have the correct contrast ratios (Inactive state) as mentioned in the screenshots. To solve this one must find a way to make the views disabled instead of being in the non-clickable state only

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and try to add a new user. 
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    | Issue 3 |
|:--------:|:-------------:|:-:|
|Screenshot_2020-12-06-23-19-56-73_80a9469f53bfe75dbc6e8989be28e2f0|  Screenshot_2020-12-06-23-20-07-56_80a9469f53bfe75dbc6e8989be28e2f0 | Screenshot_2020-12-06-23-22-31-88_80a9469f53bfe75dbc6e8989be28e2f0 | 
|Screenshot_2020-12-06-23-20-02-50_80a9469f53bfe75dbc6e8989be28e2f0| Screenshot_2020-12-06-23-22-10-00_80a9469f53bfe75dbc6e8989be28e2f0 | Screenshot_2020-12-06-23-22-25-24_80a9469f53bfe75dbc6e8989be28e2f0 | 
|Screenshot_2020-12-06-23-20-11-66_80a9469f53bfe75dbc6e8989be28e2f0 (1) | Screenshot_2020-12-06-23-22-16-36_80a9469f53bfe75dbc6e8989be28e2f0| Screenshot_2020-12-06-23-22-38-88_80a9469f53bfe75dbc6e8989be28e2f0 | 

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #2258 

### Problem
We need to update the error color so that the contrast ratio is more than 4.5

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
Does it updates to all the places where we have such errors?

**Comment by rt4914** [comment]
> Does it updates to all the places where we have such errors?

@anandwana001 Yes. And that's exactly what is desired as the previous color will fail on all screens.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @rt4914

**Comment by rt4914** [comment]
Merging this now as it is needed for other issues.

**Pull request merged**
