### PR TITLE
Fix #456: HtmlParser Bullet spacing improvisation

### LINKED ISSUE #456: HtmlParser bullets improvisation
Screenshot_1574270483

Currently bullets appear as shown in above image, which needs improvisation.

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Screenshot_1575021866

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by veena14cs** [comment]
On itemSelection answers it is looking like this.

Screenshot_20191129-155130

**Comment by rt4914** [comment]
> On itemSelection answers it is looking like this.
> 
> Screenshot_20191129-155130

Great catch. Then I believe this change won't fix the issue. I will close this PR for now. I was just giving it a quick try.

**Comment by veena14cs** [comment]
> On itemSelection answers it is looking like this.
> 
> Screenshot_20191129-155130

We can check ULTagHandler to take care of this tags. I had tried using this but it giving me spacing problem. I think you can figure it out if you try.

**Comment by rt4914** [comment]
> > On itemSelection answers it is looking like this.
> > Screenshot_20191129-155130
> 
> We can check ULTagHandler to take care of this tags. I had tried using this but it giving me spacing problem. I think you can figure it out if you try.

Can you just create a PR with whatever you tried and based on that I will try to fix that.

**Comment by veena14cs** [comment]
> > > On itemSelection answers it is looking like this.
> > > Screenshot_20191129-155130
> > 
> > 
> > We can check ULTagHandler to take care of this tags. I had tried using this but it giving me spacing problem. I think you can figure it out if you try.
> 
> Can you just create a PR with whatever you tried and based on that I will try to fix that.

Sure I can do that.

**Comment by veena14cs** [comment]
Duplicate of this PR is created [here](https://github.com/oppia/oppia-android/pull/489)

**Pull request closed without merging**
