### PR TITLE
Fix #1057: admin auth hifi fix

### LINKED ISSUE #1057: Admin Authorization hifi(v7)
Admin Authorization hifi 
## Mocks 
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/785546bd-b160-4d9b-b5d6-53ddc1b4a80a/PC-SP-Admin-Authorization-Empty-
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/a0c84710-3970-4488-beea-6fe6abbdb38a/PC-MP-Admin-Authorization-Admin-Controls-Empty-
Reference :
https://github.com/oppia/oppia-android/pull/1034#pullrequestreview-408151326

### PR DESCRIPTION
**Pull request by nikitamarysolomanpvt**
## Explanation
Admin Authorization landscape hifi fix

https://github.com/oppia/oppia-android/pull/1034#pullrequestreview-408151326 fixed
## Screenshot
small

## Mocks 
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/785546bd-b160-4d9b-b5d6-53ddc1b4a80a/PC-SP-Admin-Authorization-Empty-
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/a0c84710-3970-4488-beea-6fe6abbdb38a/PC-MP-Admin-Authorization-Admin-Controls-Empty-

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by nikitamarysolomanpvt** [comment]
small
@mschanteltc  I found inconsistency  in color code in land scape and portrait... Please suggest final color code.

**Comment by rt4914** [comment]
@nikitamarysolomanpvt Assign me back once you get reply from @mschanteltc as currently I am also not sure which color code is final.

**Comment by mschanteltc** [comment]
> @nikitamarysolomanpvt Assign me back once you get reply from @mschanteltc as currently I am also not sure which color code is final.

Use #555555 for the description. Updated in mocks.

**Comment by nikitamarysolomanpvt** [comment]
> > @nikitamarysolomanpvt Assign me back once you get reply from @mschanteltc as currently I am also not sure which color code is final.
> 
> Use #555555 for the description. Updated in mocks.

@mschanteltc in  portrait  color code is #0000008A. hence there is still inconsistency in color code in land scape and portrait...

**Comment by mschanteltc** [comment]
Sorry about that, should be updated now!

**Review by veena14cs — APPROVED** [review]
LGTM.

**Review by rt4914 — APPROVED** [review]
LGTM

**Pull request merged**
