### PR TITLE
Fix Part of #2833 : Added missing named arguments in TopicLessonsFragmentTest 

### PR DESCRIPTION
**Pull request by E13ctron**
## Explanation

Fixes Part of #2833 : Added missing named arguments in TopicLessonsFragmentTest
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by E13ctron** [comment]
@rt4914 @anandwana001 PTAL

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @Amar-2003

**Comment by E13ctron** [comment]
> LGTM, Thanks @Amar-2003

Thanks

**Comment by E13ctron** [comment]
@rt4914 PTAL

**Comment by E13ctron** [comment]
@anandwana001 @rt4914 Why are the tests failing?

**Comment by anandwana001** [comment]
Could you try updating your fork and update this branch with the latest develop branch.

**Comment by E13ctron** [comment]
> Could you try updating your fork and update this branch with the latest develop branch.

Ok let me try :)

**Comment by E13ctron** [comment]
But I did updated my fork copy just before I started to do work @anandwana001

**Comment by anandwana001** [comment]
Currently, it's 5 commits behind, so we can give it a try and see it's it works out or not.

**Comment by E13ctron** [comment]
> Currently, it's 5 commits behind, so we can give it a try and see it's it works out or not.

ok

**Comment by E13ctron** [comment]
Done @anandwana001

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
