### PR TITLE
Fix #1846: Remove audio icon from third exploration

### LINKED ISSUE #1846: Remove voiceover from test_exp_id_0.json
**Describe the bug**
In the last `state` of `Third Exploration`, toolbar shows `audio-icon` but it does not work because the audio reference is incorrect in json files.

**To Reproduce**
1. Go to `First Test Topic`
2. Finish `Second Exploration`
3. Go to `Third Exploration`
4. Go to `END` state as shown in below image
Screenshot_1600233703

5. Click on `Audio-icon` in toolbar and play audio
6. Audio is not playable.

**Expected behavior**
Either the audio should be playable or we should remove the audio itself. 
We will remove the audio because everywhere else we are using `What is a Ratio?` exploration for audio related testing.

Update `test_exp_id_0.json` file to remove the voiceover from `END` state.

### PR DESCRIPTION
**Pull request by misterjedu**
## Explanation
Fix #1846 : Removes the voiceover audio icon from a third exploration menu 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@aggarwalpulkit596 Can you do the first pass on this PR? Else I will check this on Monday.

Thanks.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @misterjedu

**Comment by rt4914** [comment]
@misterjedu: Please change the title to:
`Fix #1846: Remove audio icon from third exploration`

**Review by rt4914 — CHANGES_REQUESTED** [review]
LGTM (Looks Good To Me).

Blocking this on above comment.

**Comment by misterjedu** [comment]
@rt4914 Done.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
