### PR TITLE
Fix #2599: Flaky tests in TopicListControllerTest

### LINKED ISSUE #2599: TopicListControllerTest is flaky
After #2272 was checked in, TopicListControllerTest became flaky: https://github.com/oppia/oppia-android/runs/1809924511. testRetrievePromotedActivityList_markAllChapDoneInAllTopics_comingSoonTopicListIsCorrect seems to intermittently fail.

Due to #2272 being quite large, I don't want to revert it but we do need to figure out where this is coming from.

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR fixes #2599 flaky tests that were generated in #2272.  Tests were flaky due to the Profile Progress that stored topic's progress and each test was checking for different topic progress list. This data was not cleared, due to which the test were already having topics in the progress list causing flakiness in the tests.

The fix was to delete the profile progress data in the `tearDown()` method of tests.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Luffy18346** [comment]
@veena14cs can you please update the checklist in PR description?

**Comment by veena14cs** [comment]
> @veena14cs can you please update the checklist in PR description?

Done.

**Comment by rt4914** [comment]
Earlier CI checks passed. Running this again to check flakiness.

**Comment by veena14cs** [comment]
> Earlier CI checks passed. Running this again to check flakiness.

ACK.

**Comment by BenHenning** [comment]
@veena14cs please include details in the PR description about what the fix itself was & why it works. While I know the context here, others probably done & that makes it harder to review.

Also, it looks like ``testGetStoryList_story0DonePlayStory1FirstTestTopic_playRatios_firstTestTopicIsLearned`` is legitimately failing, not flaking. Is there an error in the PR? Further, Bazel tests are failing. PTAL & fix before sending back for review.

**Comment by Luffy18346** [comment]
> @veena14cs can you please update the checklist in PR description?

thanks.

**Comment by veena14cs** [comment]
#2599 is fixed in #2644, hence, closing this PR as it is no longer needed.

**Pull request closed without merging**
