### PR TITLE
Fix part of #1966: Fix few test cases in InputInteractionViewTestActivityTest for Robolectric and Espresso[DO NOT MERGE]

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix part of #1966 
Fix few tests in `InputInteractionViewTestActivityTest` for espresso and Robolectric

## For Reviewers 
Need a meeting for a few test cases implementation

This PR is more of learning for @prayutsu as per his ongoing PR. Suggesting on that PR is getting complex, so I had created this PR. Once his ongoing PR gets merged, this PR can be closed. 

Screenshot 2020-11-12 at 18 16 27
Screenshot 2020-11-12 at 18 10 05

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
@anandwana001 This is draft PR.

**Comment by rt4914** [comment]
@anandwana001 Saw your detailed description and makes sense.

**Comment by prayutsu** [comment]
@anandwana001 Thank you so much!

**Comment by anandwana001** [comment]
closing this pr, as this is only for learning purpose

**Pull request closed without merging**
