### PR TITLE
Fix #2546: Renamed OngoingStory to PromotedStory at required places.

### LINKED ISSUE #2546: Rename OngoingStory to PromotedStory
Since changing promoted stories to include recently played stories, older played stories, and suggest stories, we want to rename instances of `OngoingStory` to be called `PromotedStory` as per [this review](https://github.com/oppia/oppia-android/pull/2320#pullrequestreview-574479490).

In `RecentlyPlayedFragmentPresenter`:
- `ongoingStoryListSummaryResultLiveData` => `promotedStoryListSummaryResultLiveData`
- `fun subscribeToOngoingStoryList` => `fun subscribeToPromotedStoryList`
In `OngoingStoryViewModel`:
- class name `OngoingStoryViewModel` => `PromotedStoryViewModel` (and also it's usages elsewhere)

### PR DESCRIPTION
**Pull request by pandayed**
## Essential Checklist

- [✓] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)

- [✓] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [✓] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [✓] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [✓] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [✓] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by pandayed** [comment]
@rt4914 Can you please review this? Thanks!

**Comment by pandayed** [comment]
When I fetched the project it showed some error. The errors had nothing to do with the issue so I solved the issue and made a pull request.

**Comment by rishidyno** [comment]
@xpandeyed please link issue with yr PR.

**Comment by rishidyno** [comment]
You will have to look at dagger related files and also bazel dependencies as changing names will break many things in the codebase.

**Pull request closed without merging**
