### PR TITLE
Fix #1368: Disabling data collection via Manifest

### LINKED ISSUE #1368: Disabling Analytics data collection
Currently we are collecting analytics data from each of our app instances and putting them through to our Firebase project. However, it's not the best practice of open source to upload data of our contributors to a server without them knowing. As it's difficult to tell all the contributors (new or old) that critical analytics data will be sent to a server every time they run the app (even just for testing) we should provide an option for them to opt out of it. 

This issue mainly tracks disabling of analytics data collection from our application. These changes can be reverted in our release builds for turning it back on. Contributors who wish to enable it for themselves can revert them in their locals, but those changes should not be merged in the codebase.

### PR DESCRIPTION
**Pull request by Sarthak2601**
## Explanation

Fix #1368 
- This PR follows implementation pattern of this [link](https://firebase.google.com/docs/analytics/configure-data-collection?platform=android).
- Added meta data to the manifest to disable data collection. 
- Verified (via DebugView) that no data gets logged.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by vinitamurthi** [comment]
@BenHenning what do you think? I prefer this route as opposed to the one created in #1370 . The only thing we are sacrificing here is that we are adding the json file that has our dev project details in Github (which is something we are okay with though?)

**Review by vinitamurthi — APPROVED** [review]

**Comment by vinitamurthi** [comment]
@Sarthak2601 Please dont merge this until @BenHenning clarifies whether this is okay

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @Sarthak2601. Can we maybe add a change detector test to ensure these don't regress unintentionally?

**Review by BenHenning — APPROVED** [review]

**Comment by Sarthak2601** [comment]
> Thanks @Sarthak2601. Can we maybe add a change detector test to ensure these don't regress unintentionally?

Yes, working on it.

**Pull request merged**
