### PR TITLE
Fix #2485: Deleted dummy placeholder.png file

### LINKED ISSUE #2485: Delete dummy_place_holder.png file
Delete dummy_place_holder.png file from `drawable`.
Please make sure that it does not create any issues.

### PR DESCRIPTION
**Pull request by Mehul-Bisht**
## Explanation

Fixes #2485 Delete dummy_place_holder.png file

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by FareesHussain — CHANGES_REQUESTED** [review]
@Mehul-Bisht please revert the changes in the file `Project.xml` 
it is mentioned in the 4th point in the checklist of PR description

**Comment by Mehul-Bisht** [comment]
> @Mehul-Bisht please revert the changes in the file `Project.xml`
> it is mentioned in the 4th point in the checklist of PR description

please check once if the changes got reverted in the project.xml file

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks.

**Comment by Mehul-Bisht** [comment]
> LGTM, thanks.

Ok, So will it get merged into Oppia?

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
@Mehul-Bisht Please update the PR title to `Fix #2485: Deleted dummy placeholder.png file`

**Comment by Mehul-Bisht** [comment]
@rt4914 Hey! So is this PR ready to merge or in case there is something from my side required then please inform me! I had updated the title and reverted the autogenerated changes as said!

**Comment by rt4914** [comment]
@Mehul-Bisht This is ready for merge but @BenHenning will need to review it. Meanwhile you can work on other issues and treat this as almost finished PR.

**Comment by BenHenning** [comment]
Thanks @Mehul-Bisht! Glad to see this file getting removed.

**Review by BenHenning — APPROVED** [review]

**Pull request merged**
