### PR TITLE
Fix #559: Toolbar missing testcases

### LINKED ISSUE #559: Add missing test cases for toolbars.
Add missing test cases for toolbars in all activities/fragments

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR adds missing testcases for toolbars in the app.

### CODE REVIEW

**Comment by rt4914** [comment]
@veena14cs please add more test cases for other toolbars also.

**Review by rt4914 — COMMENTED** [review]
@veena14cs I have made one commit which fixes nit changes and introduces new test cases. Check that once to see what all test cases are introduced. 

Also, @nikitamarysolomanpvt you can review this now.

**Comment by veena14cs** [comment]
> @veena14cs I have made one commit which fixes nit changes and introduces new test cases. Check that once to see what all test cases are introduced.
> 
> Also, @nikitamarysolomanpvt you can review this now.

Thanks Rajat.

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Comment by rt4914** [comment]
@veena14cs merging this now.

**Pull request merged**
