### PR TITLE
Fix part of #5: Abstraction on top of Oppia GAE for StoryPage [Blocked: #66]

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation
PR contains story page retrofit instance and story page models.
This PR is an extension of [QuestionPlayer PR](https://github.com/oppia/oppia-android/pull/68)

## Checklist
Work items:

- [x] Identify among all existing GAE endpoints (get/post), which we can use during the prototype
- [x] Loosely identify data missing from the above endpoints (this bucket is expected to be small/non-existent), and identify which endpoints have data which needs to be changed for the Android app
- [x] Specify the Retrofit interfaces to represent all of the identified endpoints (simple interfaces/no annotations or return types needed beyond pseudocode)
- [x] Identify** what data (via pseudocode data structures/YAML/JSON/etc) we will be passing along from the backend through these endpoints
- [ ] Identify how error handling will work (e.g. what Retrofit does), whether RPC retry is supported & how it is/can be configured, etc.
- [ ] Determine the testing strategy for the GAE endpoints for downstream app components

### CODE REVIEW

**Comment by rt4914** [comment]
@BenHenning  PTAL. This PR contains all the models and retrofit instances.

**Comment by droidizer** [comment]
@rt4914  The branch has conflicts :)

**Comment by BenHenning** [comment]
Blocked on #66 being checked in.

**Comment by rt4914** [comment]
This PR has been replicated on #107 .

This PR was closed because of nit changes in all the files and also because of updated `develop` branch

**Pull request closed without merging**
