### PR TITLE
Fixed #1956: Optimise Profile_chooser_add views

### LINKED ISSUE #1956: Optimise code in profile_chooser_add_view.xml
This issue is tracking the optimization work of `profile_chooser_add_view.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all TextViews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be the same as before (or an optimized version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by Uticodes**
## Explanation
Fix #1956: Optimise Profile_chooser_add views

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

| Screenshots Before |  After
|:-------------------------:|:-------------------------:|
| Mobile Portrait |
|mobile_portrait_before | mobile_portrait_after
| Mobile Landscape |
|mobile_land_before | mobile_land_after
| Tap Portrait |
| tap_portrait_before | tap_portrait_after
| Tap Landscape |
|tap_land2_before | tap_land2_after  
| Tap LTR Portrait |
| tap_lrt_portrait_before | tap_ltr_portrait_after
| Tap LTR Landscape |
|tap_ltr_land_before | tap_ltr_land_after
| Mobile LTR Portrait |
|mobile_ltr_before | mobile_ltr_portrait_after
| Mobile LTR Landscape |
|mobile_ltr_land_before | mobile_ltr_land_after

## Accessibility Guide 
https://user-images.githubusercontent.com/43546652/206877043-0e4221bc-b991-4b4d-8ae7-785eac6d4644.mov

## Unit Test Screenshot
Screenshot 2022-12-09 at 7 52 10 AM

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@Uticodes please tag issue in both title and description like Fixed `#[issue number]`

**Comment by Uticodes** [comment]
okay, on it. thanks

**Comment by Uticodes** [comment]
> @Uticodes please tag issue in both title and description like Fixed `#[issue number]`

@MohitGupta121 Done

**Comment by chhabra-dhiraj** [comment]
@rt4914 Looks like this issue already has an ongoing PR but I cannot see any assignee. If this issue remains, I would like to take this up. Thanks!

**Comment by MohitGupta121** [comment]
@chhabra-dhiraj actually @Uticodes working on this issue #1956

**Comment by MohitGupta121** [comment]
@Uticodes are you still working on this PR?

**Comment by Uticodes** [comment]
Hi @MohitGupta121, I was still waiting for reviews but not gotten any till the bot closed the PR. Please what would you recommend I do now?

**Comment by MohitGupta121** [comment]
@Uticodes please first rebase your PR branch to upstream. After that we review it.

**Comment by Uticodes** [comment]
> @Uticodes please first rebase your PR branch to upstream. After that we review it.

Alright, on it.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Uticodes please push only the files you changed in your PR not all the files after rebase. It's making the PR too huge. See the file changes now is 190+ which is not correct.

**Comment by Uticodes** [comment]
> @Uticodes please push only the files you changed in your PR not all the files after rebase. It's making the PR too huge. See the file changes now is 190+ which is not correct.

Yeah, fixing that now

**Comment by BenHenning** [comment]
I'll have to close this and you'll need to reopen a new PR @Uticodes since the PR was force-pushed. Please try to avoid situations where you need to force push the PR as it can break reviewer history and make reviewing much more difficult.

You can open a new PR that will have a clean commit & reviewer history.

**Comment by Uticodes** [comment]
> I'll have to close this and you'll need to reopen a new PR @Uticodes since the PR was force-pushed. Please try to avoid situations where you need to force push the PR as it can break reviewer history and make reviewing much more difficult.
> 
> You can open a new PR that will have a clean commit & reviewer history.

Alright, will do that

**Pull request closed without merging**
