### PR TITLE
Fix #2732 Navigation-transition-fixed

### LINKED ISSUE #2732: Navigation Drawer screen transition animation fix
As per [this](https://github.com/oppia/oppia-android/issues/2728#issuecomment-780193599) comment:

The selected page should change in the background first before the menu slides back.

So from the Home Page, if I as a user tap the hamburger menu and select "Options," the page that is a layer below the side menu should change/fade to the Options page, and then the side menu hides. ([mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2776cbb1-22b0-42c9-b70b-2136bdb361da/))

### PR DESCRIPTION
**Pull request by vrajdesai78**
## Explanation

My PR fixes #2732 the issue of transition from navigation drawer to another fragment. 

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
This does not match as per [mocks](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/d47aa8de-a7a8-4d25-b011-5baefc7b7098/).

In mocks if you notice the fragment in the background changes first and then the navigation drawer closes.

**Comment by rt4914** [comment]
@vrajdesai78 Any updates on this PR?

**Comment by vrajdesai78** [comment]
> @vrajdesai78 Any updates on this PR?

Hey, Can you help me out to solve this issue. I have tried various ways to solve like by removing animation from closeDrawer. It would be great if you give me some hint so I can work more on this issue.

**Comment by rt4914** [comment]
@vrajdesai78 trying adding custom animation to control activity transition.

**Comment by vrajdesai78** [comment]
Sorry, @rt4914 I am not able to figure out that how to give custom transition when the navigation drawer is opened. You can unassigned me from this issue. I would like to work on some other issue.

**Comment by rt4914** [comment]
@vrajdesai78 No issues. Feel free to pick any issues from https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee

**Pull request closed without merging**
