### PR TITLE
Fix part of #2834: changed lambda function argument name in WelcomeViewModelTest

### PR DESCRIPTION
**Pull request by ravi9607**
## Explanation
- Fixes part of #2834: changed lambda function argument name in WelcomeViewModelTest.
- Changed the argument names of lambda functions in WelcomeViewModelTest from 'it' to something more descriptive.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @ravi9607 

Please update the PR title to
`Fix part of #2834: changed lambda function argument name in WelcomeViewModelTest`

For future reference, If you go through the checklist in the PR description:
```
 [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
 [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
```
The title should be either `Fix #bugnum: ` or `Fix part of #bugnum: `
The description should be either `Fixes #bugnum: ` or `Fixes part of #bugnum: `

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
@anandwana001 I will merge this or you can do that too. Just don't enable auto merge as this PR might close the original issue which we do not want and therefore will merge manually and check if issue is still open.

**Comment by anandwana001** [comment]
Sure I will do it, once the title get's fixed.

**Pull request merged**
