### PR TITLE
Fix #1794 : Remove TODO's

### LINKED ISSUE #1794: Add support for SDK 29 in tests [Blocked: #59]
**Is your feature request related to a problem? Please describe.**
The app needs to target SDK 29 for R8 compatibility when building the release app, but in #1789 we needed to limit Robolectric tests to SDK 28 since SDK 29 requires using Java 9+. As part of the Bazel migration (#59) we should ensure tests can run correctly with SDK 29.

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

Fix #1794 : Update outdated TODO's so we can close 1794. The TODOs now point to #4748. 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@seanlip @adhiamboperes PTAL, I removed the TODO's as the issue is already closed by Ben, but oppia-bot reopen it due to TODO's. Thanks!

**Review by seanlip — APPROVED** [review]
LGTM. Thanks!

**Comment by adhiamboperes** [comment]
Please re-assign once https://github.com/oppia/oppia-android/issues/1794#issuecomment-1594517385 is resolved.

**Comment by MohitGupta121** [comment]
@adhiamboperes yes you are right, whenever I remove `sdk=30` line I getting this output and test not runs: 

Screenshot 2023-06-16 at 5 43 13 PM

**Comment by adhiamboperes** [comment]
@MohitGupta121  it sounds like the TODO messages are valid, then, but outdated. Instead of removing the lines, you should update them to reference issue #4748 instead:
`TODO(#4748): Remove the need for this file after upgrading Robolectric tests to API 31`

This way we can close #1794 and still keep track of this task.

**Review by MohitGupta121 — COMMENTED** [review]
@adhiamboperes PTAL, updated TODO lines. Thanks!

**Review by adhiamboperes — APPROVED** [review]
This LGTM, thanks @MohitGupta121.

**Pull request merged**
