### PR TITLE
Fix #3473: Deleted faq_list_fragment.xml(sw600dp-land)

### LINKED ISSUE #3473: Convert faq_list_fragment.xml into single xml file
Currently `faq_list_fragment.xml` has 2 different quantifiers but we can convert this into one single file.

https://text-compare.com/ can be used to compare two versions of this file and for all the differences we can create variables in the `dimens.xml` file and use it accordingly.

Note: In PR, make sure you add before and after screenshots of `mobile-portrait`, `mobile-landscape`, `tablet-portrait`, and `tablet-landscape` for comparison and make sure that there is no difference between before and after UI.

### PR DESCRIPTION
**Pull request by UttaranDas**
## Explanation

Fixes #3473 
I have deleted the faq_list_fragment.xml(sw600dp-land) file. After the changes the app works fine on mobile devices. However in landscape orientation it crashes for tablets (Pixel C API 30).
Now @rt4914 @prayutsu @anandwana001 PTAL.
These are screenshots/recordings of before and after changes.

| Before      | After    |
|-----------|----------|
| faq_tab | https://user-images.githubusercontent.com/75847993/126872719-ace9de1f-b436-4e70-a617-173b1d9750de.mp4 |
| faq_tab_land | https://user-images.githubusercontent.com/75847993/126872825-8f75b954-11cc-4b61-8138-97637dac5054.mp4 |
| faq_phone | https://user-images.githubusercontent.com/75847993/126872887-6339edab-a6d5-459f-8df9-61c1a5a33483.mp4 |
| faq_phone_land | https://user-images.githubusercontent.com/75847993/126872911-85c3ea72-31cd-4e20-b21d-cc3c1d48dbcc.mp4 |

Here is the logcat error screenshot:
image

In-case the image isn't clear, refer the error codes: 

2021-07-25 01:01:12.892 10091-10091/org.oppia.android E/RecyclerView: No adapter attached; skipping layout
2021-07-25 01:01:28.722 10091-10091/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 10091
    java.lang.IllegalArgumentException: The tag for faq_list_fragment is invalid. Received: layout-sw600dp-land/faq_list_fragment_0
        at org.oppia.android.DataBinderMapperImpl.internalGetViewDataBinding0(DataBinderMapperImpl.java:1106)
        at org.oppia.android.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:2110)
        at androidx.databinding.MergedDataBinderMapper.getDataBinder(MergedDataBinderMapper.java:74)
        at androidx.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:130)
        at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1368)
        at org.oppia.android.databinding.FaqListFragmentBinding.inflate(FaqListFragmentBinding.java:55)
        at org.oppia.android.databinding.FaqListFragmentBinding.inflate(FaqListFragmentBinding.java:41)
        at org.oppia.android.app.help.faq.FAQListFragmentPresenter.handleCreateView(FAQListFragmentPresenter.kt:32)
        at org.oppia.android.app.help.faq.FAQListFragment.onCreateView(FAQListFragment.kt:26)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2695)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:286)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1232)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2812)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by prayutsu** [comment]
@Noobmaster-UD Can you please add the error when the app crashes in tablet landscape?

**Comment by UttaranDas** [comment]
> @Noobmaster-UD Can you please add the error when the app crashes in tablet landscape?
I have updated the PR and put the error screenshot.

**Comment by prayutsu** [comment]
@UttaranDas Can you please try cleaning the project and then rebuilding it?

**Comment by UttaranDas** [comment]
> @UttaranDas Can you please try cleaning the project and then rebuilding it?

As you suggested, I tried to clean and rebuild the project. The app is now running fine without crashing. 
The updated screenshots:
| Before   | After   |
|----------|--------|
| image | image |
| image | image|
| image | image |
| image | image |

**Comment by rt4914** [comment]
> > @UttaranDas Can you please try cleaning the project and then rebuilding it?
> 
> As you suggested, I tried to clean and rebuild the project. The app is now running fine without crashing.

@UttaranDas Can you please update your after screenshots now. Also don't put mp4 file as it does not work well for comparison with before images. Put before and after images only.

Also, please compare in terms of code also not just in terms of visuals as both the code have a different rootview which can be a problem.

**Comment by UttaranDas** [comment]
> > > @UttaranDas Can you please try cleaning the project and then rebuilding it?
> > 
> > 
> > As you suggested, I tried to clean and rebuild the project. The app is now running fine without crashing.
> 
> @UttaranDas Can you please update your after screenshots now. Also don't put mp4 file as it does not work well for comparison with before images. Put before and after images only.
> 
> Also, please compare in terms of code also not just in terms of visuals as both the code have a different rootview which can be a problem.

Here are the pictures:
|Before   |After     |
|---------|---------|
| image | image |
| image | image |
| image | image |
| image | image |

The `faq_list_fragment.xml` has recycler view contained in the `NestedScrollView` while the in the `sw600dp-land` file it is contained in the `FrameLayout`. I don't think discarding the sw600dp file will cause problems since even if new questions are added to the list nested scroll should be able to handle it.

@rt4914  PTAL.

**Comment by rt4914** [comment]
@UttaranDas Have a look ate tablet landscape screenshots. The before/after layout has changed which shows that we cannot remove `layout/sw600dp-land` file so that the UI does not change.

**Comment by rt4914** [comment]
@UttaranDas Any updates on this PR?

**Comment by UttaranDas** [comment]
> @UttaranDas Have a look ate tablet landscape screenshots. The before/after layout has changed which shows that we cannot remove `layout/sw600dp-land` file so that the UI does not change.

There were two files: a normal xml and one sw600dp-land. Deleting the land file will cause change in layout since both use different settings for the layout width. Without the land file I can't find any way to specifically get the desired layout.
@rt4914  can you please suggest what can I do.

**Comment by rt4914** [comment]
> > @UttaranDas Have a look ate tablet landscape screenshots. The before/after layout has changed which shows that we cannot remove `layout/sw600dp-land` file so that the UI does not change.
> 
> There were two files: a normal xml and one sw600dp-land. Deleting the land file will cause change in layout since both use different settings for the layout width. Without the land file I can't find any way to specifically get the desired layout.
> @rt4914 can you please suggest what can I do.

@UttaranDas We have to merge these files such that UI does not change at all. So it might happen that we have to keep 2 files instead of 1 but the important thing is that UI should not change.

**Pull request closed without merging**
