### PR TITLE
Fixes part of #4177: Dark mode Topic Activity Part 1

### LINKED ISSUE #4177: Add dark mode support to TopicActivity
Add dark mode support to TopicActivity and contained views/fragment.

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

#### Location in the app
1. Open the app
2. Go to All Topics
3. Open any topic

For on tasks in following order:
- Toolbar + Tabs in first PR
- Info tab in second PR
- Revision Card tab in third PR
- Practice tab in fourth PR
- Finally Lesson tab

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

Fixes part of #4177 : Dark mode Topic Activity Part 1 (Toolbar + Tabs)

Dark Mode Mockup:-
https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/3b067181-e5e0-4a5b-bbb8-ab5eda952549/specs/

|Default|Dark Mode|
|:----------------------------------------:|:-----------------------------------------:|
|  | Screenshot_2022-05-31-12-23-27-332_com android camera |

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@rt4914 can you please review this PR for Part 1 of #4177

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.

**Comment by rt4914** [comment]
@MohitGupta121 In future please make sure you use `Fixes part of #xxxx` in title and description as you are not finishing the entire issue in this PR. For now I have updated these.

**Comment by MohitGupta121** [comment]
> @MohitGupta121 In future please make sure you use `Fixes part of #xxxx` in title and description as you are not finishing the entire issue in this PR. For now I have updated these.

Okay thanks you, I take care next time.

**Pull request merged**
