### PR TITLE
Fix #3453: Merge admin_auth_activity.xml into one file

### LINKED ISSUE #3453: Merge admin_auth_activity.xml into single xml
Currently there are 4 versions of `admin_auth_activity.xml` file, merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

### PR DESCRIPTION
**Pull request by addy-zero**
## Explanation

Fixes #3453 by merging 4 different layout files into one

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

| Before  | After |
| ------------- | ------------- |
|   |   |
|   |    |
|   |   |
|   |   |

### CODE REVIEW

**Comment by addy-zero** [comment]
@rt4914 PTAL

**Comment by rt4914** [comment]
@adizcode Unfortunately I will have to close this PR because of **force-push**. We do not allow force-push as it tampers with the commit history. You can read more in Step 3 here https://github.com/oppia/oppia-android/wiki/making-a-code-change#making-a-code-change-using-the-terminal

You can recreate a new PR for this issue.

**Comment by addy-zero** [comment]
@rt4914 Oh, my bad. I was rebasing against the upstream for new changes.

Are we then supposed to pull the new changes on a daily basis ? That might create multiple "Merged develop into feature-branch" commits. Is that expected?

**Comment by addy-zero** [comment]
Opened PR #4180 to replace this one.

**Comment by BenHenning** [comment]
> @rt4914 Oh, my bad. I was rebasing against the upstream for new changes.
> 
> Are we then supposed to pull the new changes on a daily basis ? That might create multiple "Merged develop into feature-branch" commits. Is that expected?

To clarify on this point @adizcode yes, you should rely on merge commits to pull in the latest changes. How often you pull develop is up to you (I generally only pull develop at the beginning and end of the PR review unless the reviewer asks to sync, though it's also a good practice to resolve conflicts as they arise).

**Comment by addy-zero** [comment]
@BenHenning Understood. Thank you for clarifying. 😄

**Pull request closed without merging**
