### PR TITLE
Fix #5246: "Update the Android FAQ"

### LINKED ISSUE #5246: [Feature Request]: Update the Android FAQ
### Is your feature request related to a problem? Please describe.

The UX Writing team has done a review of the Android app FAQ and would like to propose updates to it.

### Describe the solution you'd like

FAQ items should be arranged in this order:

- What is Oppia?
- Who is an Administrator?
- How can I create a new profile?
- How do I get the app in my language?
- I found a bug. How can I report it?
- Why are there only math lessons?
- Will you be making more lessons?
- Why is the Exploration player not loading?
- Why is my audio not playing?
- How can I delete a profile?
- How can I change my email/phone number?
- How do I update the app?
- How do I update my Android OS?
- I can’t find my question here. What now?

**Updates to existing questions:**

Q: How can I create a new profile? -- should be updated:
- Current: If it is your first time creating a profile and not have a PIN:
- Updated: If it is your first time creating a profile and you do not have a PIN:

**New questions:**

- **Why are there only math lessons?**
Oppia’s mission is to help learners gain necessary life skills. Math is an essential skill in everyday life. Oppia will be offering new lessons on science and other subjects soon!

- **Will you be making more lessons?**
Yes, Oppia will be offering new lessons on science and other subjects soon. Please check back for updates!

- **I found a bug. How can I report it?**

1. From your Oppia app home screen, tap the menu in the top left corner.
2. Tap **Share feedback**.
3. Follow the instructions to report the bug or share feedback.

- **How do I get the app in my language?**
The Oppia app currently supports English, Brazilian Portuguese, Arabic, and Nigerian Pidgin. Choose one of these languages in the menu, under Options. To request the app in your language, please contact us at _email address_.

- **How do I update the app?**

1. Open the Google Play Store app.
2. Search for the Oppia app. 
3. Tap **Update**.

- **How do I update my Android OS?** 

1. Tap your phone's **Settings** app.
2. Tap **System updates**.
3. Tap **System updates** and follow the instructions to update your Android operating system. 

### Describe alternatives you've considered

N/A

### Additional context

See the original design issue at https://github.com/oppia/design-team/issues/75 for the discussion.

### PR DESCRIPTION
**Pull request by deonwaju**
## Explanation

Fixes #5246: "Update the Android FAQ"

1. Changed the order in which the FAQ questions where arranged by refactoring the property name of each string to the appropriate one based on requirements from #5246.
2. Added new questions based on requirements from #5246.
3. Refactored the faq question property names in the tests written in FAQListFragmentTest.kt according to the new order in which the questions where arranged.
4. Created a string extension file in string extensions to check if string resource contains a placeholder, to be able to dynamically replace the placeholders with the appropriate string values.
5. Used the string extension to check if any string resource file from the FAQ questions and answers contains a placeholder, then call function to replace placeholder with appropriate string value.

https://github.com/oppia/oppia-android/assets/54560535/d2c0b6cb-251b-4591-9221-1d95a308cc74

https://github.com/oppia/oppia-android/assets/54560535/7b409e30-e9f6-4b4b-80ed-5449678a184f

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by deonwaju** [comment]
@adhiamboperes PTAL

**Comment by DeonWaju** [comment]
@DeonWaju PTAL

**Comment by deonwaju** [comment]
Hello @adhiamboperes , I want to push this pr as a collaborator but when i cloned i still dont have permission to push my branch

**Comment by adhiamboperes** [comment]
> Hello @adhiamboperes , I want to push this pr as a collaborator but when i cloned i still dont have permission to push my branch

Sorry,
I don't understand your question. Could you please clarify what you mean push as a collaborator? Did you re-clone the repo?

**Comment by deonwaju** [comment]
> > Hello @adhiamboperes , I want to push this pr as a collaborator but when i cloned i still dont have permission to push my branch
> 
> Sorry, I don't understand your question. Could you please clarify what you mean push as a collaborator? Did you re-clone the repo?

Yes i did re-clone the repo, The error is a permission error,  I mean i want to push this PR after i clone the original project and not from this forked repo.

**Comment by adhiamboperes** [comment]
> > > Hello @adhiamboperes , I want to push this pr as a collaborator but when i cloned i still dont have permission to push my branch
> > 
> > 
> > Sorry, I don't understand your question. Could you please clarify what you mean push as a collaborator? Did you re-clone the repo?
> 
> Yes i did re-clone the repo, The error is a permission error, I mean i want to push this PR after i clone the original project and not from this forked repo.

You still need to work on your fork.

**Comment by deonwaju** [comment]
> > > > Hello @adhiamboperes , I want to push this pr as a collaborator but when i cloned i still dont have permission to push my branch
> > > 
> > > 
> > > Sorry, I don't understand your question. Could you please clarify what you mean push as a collaborator? Did you re-clone the repo?
> > 
> > 
> > Yes i did re-clone the repo, The error is a permission error, I mean i want to push this PR after i clone the original project and not from this forked repo.
> 
> You still need to work on your fork.

Alright, thanks just clarifying, thought addition to the codebase meant working from within the codebase. I am done with the PR, the last CI that didnt pass is a REGEX error for the word Oppia.

Screenshot 2023-11-29 at 00 47 13

I could solve it by using a placeholder %s but I would mess with the logic below @adhiamboperes 

Screenshot 2023-11-29 at 00 51 01

**Comment by adhiamboperes** [comment]
@DeonWaju, that particular code is quite brittle, and it would be great if you updated it to support the new required behaviour. We now have two questions/answers with the word Oppia, and more could be added in the future. Also, the indices could change any time, as they have now.

**Comment by deonwaju** [comment]
@adhiamboperes PTAL

**Review by adhiamboperes — APPROVED** [review]
Thanks @DeonWaju, this LGTM.

What's left here is to add a screen recording to your PR description to make it easy to verify that the questions are indeed in the new expected order.

Also kindly just add a brief explantion of the changes made in this PR(the why and how) based on the issue description.

**Comment by deonwaju** [comment]
@adhiamboperes PTAL

**Comment by adhiamboperes** [comment]
Thanks @DeonWaju. This looks great!

**Pull request merged**
