### PR TITLE
Fixes part of #1346: Fix test cases for ExplorationActivityTest

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes part of #1346 

The `ExplorationActivityTest` are currently failing on develop and earlier we were planning to fix them on Espresso as well as Roboelectric but because of roboelectric test cases failing under various attempts it was becoming a blocker for landscape mode support and therefore the test cases have been updated to make sure that they atleast pass on `Espresso` and unblocks the other work items.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by veena14cs — CHANGES_REQUESTED** [review]
All testcases are passing on real device(Pixel 3a XL) but few are failing on emulator(Pixel 2).

Screenshot 2020-06-18 at 12 35 05 PM

**Comment by rt4914** [comment]
> All testcases are passing on real device(Pixel 3a XL) but few are failing on emulator(Pixel 2).
> 
> Screenshot 2020-06-18 at 12 35 05 PM

@veena14cs : All these tests are passing on my side. Can you make sure that you have enough memory allocated to emulator? Or else just run these failing test cases individually and you will see that all of them are passing.

**Comment by veena14cs** [comment]
> > All testcases are passing on real device(Pixel 3a XL) but few are failing on emulator(Pixel 2).
> > Screenshot 2020-06-18 at 12 35 05 PM
> 
> @veena14cs : All these tests are passing on my side. Can you make sure that you have enough memory allocated to emulator? Or else just run these failing test cases individually and you will see that all of them are passing.

I tried running individually, but it failed. May be memory issue. I will approve this as it is running on real device.

**Review by veena14cs — APPROVED** [review]
LGTM. Need to make sure if testcases are passing on lower end device.

**Comment by rt4914** [comment]
> LGTM. Need to make sure if testcases are passing on lower end device.

I did try that on Nexus S and they are working on my device. But still as the lower end devices are not a priority right now, I will merge this PR.

**Pull request merged**
