### PR TITLE
TextInputLayout migration issues regarding orientation change

### LINKED ISSUE #2496: Error message disappears on configuration changes for AddProfileActivity
**Describe the bug**
Error message in TextInputLayout disappears on configuration changes for AddProfileActivity

same for the AdminPinActivity, ProfileRename, AdminSettings, ProfileResetPin

**Expected behavior**
Error message should remain same after orientation change

### PR DESCRIPTION
**Pull request by FareesHussain**
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by FareesHussain** [comment]
@prayutsu I think `onTextChanged` is creating the issue here I've added the same logic I've used for the ResetPinDialogFragment here and it works.

**Comment by prayutsu** [comment]
@FareesHussain Before solving the issue, shouldn't we try to find the exact reason for this bug?
See this video from the PR [#2351](https://github.com/oppia/oppia-android/pull/2351)

We didn't face this issue at the time of merging this PR, so we need to investigate and find if any particular commit is responsible for this bug.
https://user-images.githubusercontent.com/54636525/103354155-ca24e280-4ad0-11eb-9c86-f1c85637c233.mp4

**Comment by FareesHussain** [comment]
> @FareesHussain Before solving the issue, shouldn't we try to find the exact reason for this bug?
> See this video from the PR [#2351](https://github.com/oppia/oppia-android/pull/2351)
> 
> We didn't face this issue at the time of merging this PR, so we need to investigate and find if any particular commit is responsible for this bug.
> https://user-images.githubusercontent.com/54636525/103354155-ca24e280-4ad0-11eb-9c86-f1c85637c233.mp4

@prayutsu Yes I've noticed that I created this draft PR just to continue the discussion after the discussion we can close this and split this into good-first-issue

**Comment by prayutsu** [comment]
@FareesHussain This regression is observed after we decided to use data binding for setting the text in the editTexts
Before [this](https://github.com/oppia/oppia-android/pull/2351/commits/62b2c4002dc86ba3217060370eaf203931912995#) commit, we didn't have this issue.

**Comment by FareesHussain** [comment]
> @FareesHussain This regression is observed after we decided to use data binding for setting the text in the editTexts
> Before [this](https://github.com/oppia/oppia-android/pull/2351/commits/62b2c4002dc86ba3217060370eaf203931912995#) commit, we didn't have this issue.

That makes sense

**Comment by FareesHussain** [comment]
Closing this as we have tracked the issue

**Pull request closed without merging**
