### PR TITLE
Fix #1980: Optimise hints_summary.xml

### LINKED ISSUE #1951: Optimise hints_summary.xml
This issue is tracking the optimisation work of `hints_summary.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all textviews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be same as before (or an optimised version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### LINKED ISSUE #1980: Optimize code in administrator_controls_account_actions_view.xml
This issue is tracking the optimization work of `administrator_controls_account_actions_view.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all TextViews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be the same as before (or an optimized version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by secjedi**
- Fix #1951 
- Changed the outer Linear Layout to Constraint Layout
- Adapted the styles from the styles.xml file into hint_summary.xml
- Reviewer: @MohamedMedhat1998 

## Checklist
- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by MohamedMedhat1998 — CHANGES_REQUESTED** [review]
@secjedi please update this branch with the latest develop so that only the new changes you added are highlighted.  
Please check [this reference](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a) on how to do that.

**Comment by secjedi** [comment]
> @secjedi please update this branch with the latest develop so that only the new changes you added are highlighted.
> Please check [this reference](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a) on how to do that.

**Comment by BenHenning** [comment]
@secjedi FYI that in the future you don't actually need to close the PR & delete your branch. You can instead sync your fork with the latest changes from develop following the steps here: https://github.com/oppia/oppia-android/wiki/Fork-and-Clone-Oppia-Android#updating-your-local-repository.

**Comment by secjedi** [comment]
Thanks @BenHenning. I'll work with your correction

**Pull request closed without merging**
