### PR TITLE
Fixes #3472: Deleted the landing activity xml file

### LINKED ISSUE #3472: Merge faq_list_activity into single xml layout file
Currently `faq_list_activity.xml` has 2 different quantifiers but we can convert this into one single file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in the `dimens.xml` file and use it accordingly.

Note: In PR, make sure you add before and after screenshots of `mobile-portrait`, `mobile-landscape`, `tablet-portrait`, and `tablet-landscape` for comparison and make sure that there is no difference between before and after UI.

### PR DESCRIPTION
**Pull request by yash10019coder**
## Explanation

Fix #3472 
In this, I have deleted the landscape XML  file of this as it had two files and I  also compared the two files before but they were same so there was nothing to add in dimens.xml file 
Now @rt4914 PTAL @prayutsu 

These are the screenshots of the activity
| New Screenshots         | Old Screenshots |
| -----------       | -----------      |
| Screenshot from 2021-07-23 22-13-34        | Screenshot from 2021-07-24 12-53-27     |
| Screenshot from 2021-07-23 22-14-10  | Screenshot from 2021-07-24 12-52-14        |
|Screenshot from 2021-07-23 23-13-39            |Screenshot from 2021-07-24 12-54-24       |
|Screenshot from 2021-07-23 23-14-04             |Screenshot from 2021-07-24 12-54-51         |

In the last screenshot there is a scroll view so the whole page is scrollable

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by prayutsu** [comment]
@yash10019coder From the PR description, it is not clear if the screenshots attached were taken before the changes or they have been taken after the changes, to compare we'll need both screenshots. 
You can make a table of before and after screenshots with the help of Markdown easily.
| Before      | After |
| ----------- | ----------- |
| Screenshot Before the changes      | Screenshot Before the changes       |

**Comment by yash10019coder** [comment]
> @yash10019coder From the PR description, it is not clear if the screenshots attached were taken before the changes or they have been taken after the changes, to compare we'll need both screenshots.
> You can make a table of before and after screenshots with the help of Markdown easily.
> 
> Before	After
> Screenshot Before the changes	Screenshot Before the changes

@prayutsu  Now I have mentioned that  these screenshots are after the landscape file is deleted

**Comment by yash10019coder** [comment]
> @yash10019coder From the PR description, it is not clear if the screenshots attached were taken before the changes or they have been taken after the changes, to compare we'll need both screenshots.
> You can make a table of before and after screenshots with the help of Markdown easily.
> 
> Before	After
> Screenshot Before the changes	Screenshot Before the changes

@prayutsu @rt4914  changed the PR description PTAL

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
