### PR TITLE
Fix part of #4044: Add MathEquationInput classifiers

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
Fix part of #4044

Introduce all domain classifiers for the MathEquationInput interaction.

This PR has the same classifiers and behaviors as described in #4057 except these classifiers support variables and must be formed into an equation. These classifiers' tests are also being exempted for parameterization so that they can more easily implement the tests defined in the technical spec test matrix.

This PR includes a change to the parameterized test runner to add support for variables including the '=' sign (since it was before splitting on '=' rather than treating it as a single delimiter).

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A -- This is introducing a new classifier, but it isn't yet being hooked up.

### CODE REVIEW

**Comment by BenHenning** [comment]
Hi. As of today, some main reviewers have taken time off for the next few weeks, so it may take a little while before we can look at this PR. We appreciate your patience while some of our team members recharge. We'll be fully returning on 4 January 2021.

**Comment by BenHenning** [comment]
@anandwana001 PTAL at the whole PR as part of the broader math expressions project.

**Comment by BenHenning** [comment]
This is still active.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Pull request merged**
