### PR TITLE
Fix #1949: Optimizes styling in onboarding_slide_final.xml

### LINKED ISSUE #1949: Optimise code in onboarding_slide_final.xml
This issue is tracking the optimisation work of `onboarding_slide_final.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all textviews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

3. If needed introduce common styles too in style.xml file.

While making the above changes the UI should not get affected and the end result should still be same as before (or an optimised version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by KMaragh**
## Explanation
Fixes #1949 
Added common and specific styles to the appropriate styles.xml files, and updated the onboarding_slide_final.xml to use those new styles. Also added new dimensions to the appropriate dimens.xml files.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Sarthak2601** [comment]
@KMaragh Before we proceed to review, can you please update your branch with the latest develop branch of our repo.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Thanks @KMaragh 

you don't need to create new styles. We have already created styles like `Heading1`, `heading2`, `Body`, etc.

You just have to use them correctly in these files.

Have a look at this PR for reference: https://github.com/oppia/oppia-android/pull/2005/files

**Comment by KMaragh** [comment]
@rt4914 Re did the styling to use the Styles that were present and created a common button style.

**Comment by rt4914** [comment]
> @rt4914 Re did the styling to use the Styles that were present and created a common button style.

@KMaragh We will need to close this because of force push. We should not do force push as it makes review process hard and tampers the commit history. Have a look at 5th point here https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

Closing this PR and you will need to recreate this. Thanks.

**Pull request closed without merging**
