### PR TITLE
Fix part of #5: Abstraction on top of Oppia GAE using Moshi Library

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation
I have finished first 4 work items but I was not able to check these APIs directly in current code because of following reasons:

I tried to use the NetworkDownloader.kt file from demo project but the Cronet had ERR_ACCESS_DENIED error which I was not able to resolve.
Also, I was in doubt whether we will be using the same approach for connection as you did in Demo code because for main Oppia-Android project we will be using the Retrofit and that will bring a lot of change to networking code.
So, I simply checked these Retrofit instances and Moshi model classes in your existing Oppia-Demo project and then pasted these files in main Oppia-Project. For now my focus on PR first and therefore I have not giving a lot of time in solving these errors. But I have made sure that proper TODO's are mentioned so that we do not miss these points.

## Errors in AutoJSON
I have made a PR using AutoJSON but there were a lot of commented lines because with AutoJSON I was not able to check the code properly because of null values in response.
I found an alternative library [Moshi](https://github.com/square/moshi), this library can be replaced with AutoJSON and will solve the issue of null values.

For free-form data, not yet finished. Mentioned as TODO in todo list.
Moshi does not accept ImmutableList<> and ImmutableMap<>, so for now I have changed that to List<> and Map<> and left TODO items for the same.
Not sure exactly what data type I should use for HTML data. Therefore I have left TODO's accordingly.

## Checklist
Work items:

- [x] Identify among all existing GAE endpoints (get/post), which we can use during the prototype
- [x] Loosely identify data missing from the above endpoints (this bucket is expected to be small/non-existent), and identify which endpoints have data which needs to be changed for the Android app
- [x] Specify the Retrofit interfaces to represent all of the identified endpoints (simple interfaces/no annotations or return types needed beyond pseudocode)
- [x] Identify** what data (via pseudocode data structures/YAML/JSON/etc) we will be passing along from the backend through these endpoints
- [ ] Identify how error handling will work (e.g. what Retrofit does), whether RPC retry is supported & how it is/can be configured, etc.
- [ ] Determine the testing strategy for the GAE endpoints for downstream app components

### CODE REVIEW

**Comment by BenHenning** [comment]
Thanks for starting this PR. My first concern with Moshi is that it doesn't promote immutability like AutoValue does. Although we eventually intend to move over to protobuf for RPC payloads, we should try to leverage some of the same concepts in the meantime. Does Moshi support leveraging builders/immutable Kotlin data objects? Also, do you know whether Moshi uses compile-time code generation or reflection?

Can you also convert these classes to Kotlin?

**Comment by rt4914** [comment]
> Thanks for starting this PR. My first concern with Moshi is that it doesn't promote immutability like AutoValue does. Although we eventually intend to move over to protobuf for RPC payloads, we should try to leverage some of the same concepts in the meantime. Does Moshi support leveraging builders/immutable Kotlin data objects? Also, do you know whether Moshi uses compile-time code generation or reflection?
> 
> Can you also convert these classes to Kotlin?

Moshi does not support Immutable Kotlin data objects, that's one of the biggest disadvantages. But actually I was unable to use ImmutableList/ImmutableMap with AutoValue/AutoJSON too. 

Also, I don't have detailed knowledge of compile-time code generation and reflection but after reading on the internet I think Moshi uses reflection till version 1.5 and in version 1.6 they are using code-gen. Still not sure if I have understood it clearly. [Reference Link](https://medium.com/@ZacSweers/exploring-moshis-kotlin-code-gen-dec09d72de5e)

Should I convert AutoJSON and AutoValue files to Kotlin or Moshi based code to kotlin? or Both and then make PR for both?

**Comment by rt4914** [comment]
> Thanks for starting this PR. My first concern with Moshi is that it doesn't promote immutability like AutoValue does. Although we eventually intend to move over to protobuf for RPC payloads, we should try to leverage some of the same concepts in the meantime. Does Moshi support leveraging builders/immutable Kotlin data objects? Also, do you know whether Moshi uses compile-time code generation or reflection?
> 
> Can you also convert these classes to Kotlin?

##Correct Answer

Moshi has two ways to generate these converters which are called JsonAdapters:
1. Using reflection, via the moshi-kotlin artifact. Adapters will be generated at runtime when needed, then reused. The main downside of this solution is that in order to understand metadata like nullability and default values of Kotlin properties, this artifact depends on the kotlin-reflect library, a 2.5 MiB jar file which will make your application code size grow significantly.
2. Since Moshi 1.6, adapters can also be generated at compile time using the moshi-kotlin-codegen annotation processor. This is a much better solution because it provides better performance while adding no extra dependency to your application. The only limitation of that solution compared to kotlin-reflect is that it is unable to initialize private or protected fields, but the same limitations apply when writing your parsers manually.

**Comment by BenHenning** [comment]
I believe this is made obsolete by #61 and future downstream PRs wrapping up #5.

**Pull request closed without merging**
