### PR TITLE
Disable workflow cancellation for merged PRs

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

This PR disables workflow cancellation for merged PRs to avoid past workflows failing due to being cancelled (see https://github.com/oppia/oppia-android/commits/develop). While this will slightly increase resources for subsequent PR merges, it's useful since it provides proper CI results for merged PRs (which could help isolate regressions that trigger develop CI failures that aren't caught until post-merging).

## Essential Checklist

- [ ] ~The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)~
- [X] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [X] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [X] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [X] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

N/A -- CI infrastructure change

### CODE REVIEW

**Comment by BenHenning** [comment]
@vinitamurthi could you PTAL since this is related to developer workflow?

**Comment by BenHenning** [comment]
Hi. As of today, some main reviewers have taken time off for the next few weeks, so it may take a little while before we can look at this PR. We appreciate your patience while some of our team members recharge. We'll be fully returning on 4 January 2021.

**Comment by BenHenning** [comment]
@anandwana001 could you PTAL when you get a chance?

**Review by anandwana001 — APPROVED** [review]
LGTM

**Review by vinitamurthi — APPROVED** [review]

**Comment by vinitamurthi** [comment]
Merging this!

**Comment by BenHenning** [comment]
Thanks! This should be a nice improvement. I'll keep an eye on submitted PRs to make sure it's working correctly.

**Pull request merged**
