### PR TITLE
Fix #771 : Lowfi Landscape: Options Activity

### LINKED ISSUE #771: Lowfi Landscape: OptionsActivity
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/7d442317-dd5a-40e7-adbd-25285d010874/OP-Options-Menu-

OptionsActivity should support landscape mode. Also add test cases for landscape mode too.

### PR DESCRIPTION
**Pull request by iaminamkhan**
Fixes #771 :
Added landscape support to Options activity

Added landscape support to option_fragment

Added test cases for landscape mode in OptionsFragmentTest

Solved EOF missing bug.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
@thelosergeek Thanks for this PR but actually there are not test cases. Please add test cases for checking the landscape mode is working correctly. At the same time, almost all test cases which are currently in `OptionsFragmentTest` are current and we need all similar test cases for landscape mode also in `OptionsFragmentTest` itself.

Also, you just need to make change for `OptionsFragmentTest` and not for its child activities, please keep them restricted to portrait mode only.

**Comment by rt4914** [comment]
@thelosergeek I am sure if this PR is ready for review or not. Always tag the reviewer once your PR is ready.

**Comment by iaminamkhan** [comment]
Oh okay!
I'll do it.

**Comment by rt4914** [comment]
Closing this PR as there is no update from author

**Pull request closed without merging**
