### PR TITLE
Fix #5283 :Revision cards overlapping.

### LINKED ISSUE #5283: [BUG]: Revision cards overlapping.
### Describe the bug

Revision cards overlapping .
PR https://github.com/oppia/oppia-android/pull/5095 causing the issue.

### Steps To Reproduce

1.go to any topic 
2.click on revision
3.click on any revision card
4.scroll down

### Expected Behavior

Cards should be displayed without overlapping.

### Screenshots/Videos

concept_card_overlaping

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Vishwajith-Shettigar**
## Explanation
Fixes #5283, changed wrap_content to fixed width for cardview width.

After Fix, accessibility check not suggesting text scaling( Referencing issue #4736)

WhatsApp Image 2023-12-23 at 5 43 08 PM

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
| Before| After|
|--------|--------|
|concept_card_overlaping| overlapfix | 
|cardoverlapbeforetablet| tabletcardoverlap |

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar!

In https://github.com/oppia/oppia-android/pull/5095, these changes were applied for large screens too, Please confirm via screenshots that it displays correctly on tablets.

As a note, the font scaling warning is not in accessibility scanner because of the minLines attribute, also introduced in #5095.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, made changes PTAL.

**Review by adhiamboperes — APPROVED** [review]
Thanks @Vishwajith-Shettigar! LGTM.

**Pull request merged**
