### PR TITLE
Fix #2138: Practice Tab - Top Align Subtopic Name and Checkmark

### LINKED ISSUE #2138: Practice Tab - Top Align Subtopic Name and Checkmark
Currently subtopic names are vertically aligned with the checkbox. However checkboxes need to be top aligned with the Subtopic name.

Screenshot_20201119-213417_Oppia

### PR DESCRIPTION
**Pull request by 7phalange7**
## Explanation

Fixes #2138 

The checkboxes in practice tab are top aligned now.
screenshot : 
drawing

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@mschanteltc Does the image in description matches your expectation for this issue ?

**Review by rt4914 — APPROVED** [review]
Approving as this looks good to me. Thanks

**Comment by mschanteltc** [comment]
Yes, this looks good to me!

**Comment by rt4914** [comment]
> Yes, this looks good to me!

Thanks Chantel.

**Pull request merged**
