### PR TITLE
 Fixes #3826 : Resolved black square that was being displayed around the profile picture

### LINKED ISSUE #3826: Black square around the profile picture
**Describe the bug**
On editing the profile picture, a black square appears around the profile pic.

**To Reproduce**
1. Go to Oppia app
2. Click on user profile
3. Click on edit - pencil icon over the profile picture 
4. Change the profile picture
5. Save
6. See error 

**Expected behavior**
Profile picture should not have anything surrounding it - it should be displayed in a circle.

**Screenshots**
image

**Device**
- Device - TBD
- SDK version - TBD
- App version - 0.6-alpha-908d57b2b1

**Additional context**
Device language was selected as Portuguese for testing.

### PR DESCRIPTION
**Pull request by coder2699**
## Explanation

Fixes #3826 : Adding "whiteLight" background to circular image view in "profile_progress_header.xml" file solves the existing bug.
Checkout the video: https://drive.google.com/file/d/12Wn486QD0Bi4qXBr6y7MzW5W8LSDz-6u/view?usp=sharing

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by srushtirk — COMMENTED** [review]
@anandwana001 please let me know if this looks good, and I can approve.

**Comment by anandwana001** [comment]
@coder2699 could you please add some screenshots showing this is fixed?

**Comment by coder2699** [comment]
> @coder2699 could you please add some screenshots showing this is fixed?

@anandwana001 I have already added the working video in the description (https://drive.google.com/file/d/12Wn486QD0Bi4qXBr6y7MzW5W8LSDz-6u/view?usp=sharing)

Here are few screenshots regarding the same:-

**Comment by anandwana001** [comment]
Deferring to @rt4914 as he is the codeowner here.

**Review by rt4914 — COMMENTED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
@coder2699 Just merge with latest develop and also reformat the files. 
Press `Control + Alt + L` - reformatting shortcut to fix the formatting.

**Comment by coder2699** [comment]
> @coder2699 Just merge with latest develop and also reformat the files. Press `Control + Alt + L` - reformatting shortcut to fix the formatting.

@rt4914 sure, I will make the changes and let you know

**Review by srushtirk — APPROVED** [review]

**Comment by coder2699** [comment]
@rt4914 @srushtirk One test case is failing, can any of you help me regarding it.

**Comment by FareesHussain** [comment]
@coder2699 check the suggestions in the failed test case
i.e,
```
app/src/main/res/layout-sw600dp-port/profile_progress_header.xml:45: Use start/end versions of layout properties, instead, for proper RTL support
app/src/main/res/layout-sw600dp-port/profile_progress_header.xml:42: Drawable start/end/top/bottom & image source should use the compat versions, instead, e.g.: app:drawableStartCompat or app:srcCompat, to ensure that vector drawables can load properly in SDK <21 environments.
Refer to https://github.com/oppia/oppia-android/wiki/Static-Analysis-Checks#regexpatternvalidation-check for more details on how to fix this.
```

**Comment by coder2699** [comment]
@rt4914 PTAL

**Review by rt4914 — APPROVED** [review]
LGTM

**Pull request merged**
