### PR TITLE
Fix #854: Question Player Input Interactions And Submitted Answer content items hifi

### LINKED ISSUE #854: question player interactions items and  answer items hifi
High- fi of
- Input interactions items 
- Feedback item
- Previous response item
- Submitted answer item
##  Mock

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/bed05d74-07dd-475b-abbe-295709b6c7ed/PM-Q2-Text-Input-Continue-

### PR DESCRIPTION
**Pull request by nikitamarysolomanpvt**
## Explanation
Duplicate of #869 
PR includes hifi of the below

- Input interactions items 
- Feedback item
- Previous response item
- Submitted answer item

For checking multiple choice please refer: https://gist.github.com/nikitamarysolomanpvt/40b46c066db14c76febb986d33af3381 
As there are some ambiguity in alignments in mock please follow :
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/91c4a1ac-dbfe-4616-80b1-f77b82bb5f41/PM-Q6-Text-Input-w-Units-Inputted-Answer-2-
For knowing the branches of Question Player hifi please refer: https://docs.google.com/document/d/1hUCHfKeJePvYaYlwhg23JZ-H85fz1wi00Y42N7w854U/edit?usp=sharing

## Mock

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/91c4a1ac-dbfe-4616-80b1-f77b82bb5f41/PM-Q6-Text-Input-w-Units-Inputted-Answer-2-

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/eeed0f6c-54ca-4371-ab23-5199abd87f28/PM-Q2-Text-Input-Keyboard-1-

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/bed05d74-07dd-475b-abbe-295709b6c7ed/PM-Q2-Text-Input-Continue- 

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/825e927e-66ee-4268-84f0-126e0eb3a187/PM-Q4-Checkboxes-Checkbox-2-

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/b749c7eb-156a-47f4-86f1-2e51a5d43b82/PM-Q4-Checkboxes-Continue-/

## Screen shot

small
small
s1

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

## Known issues 
bulletted Submitted answer content yet to fix would be fixed by rajat in explorations
(Specially the one with image).

##  Accessibility Scanner Results
Screenshot_20200406-163521

### CODE REVIEW

**Review by veena14cs — APPROVED** [review]
LGTM

**Review by rt4914 — CHANGES_REQUESTED** [review]
The application is not running for me. 
`drawable/ic_check_primary` is missing in `question_player_submitted_answer_item`

**Comment by veena14cs** [comment]
> The application is not running for me.
> `drawable/ic_check_primary` is missing in `question_player_submitted_answer_item`

+1

**Review by veena14cs — CHANGES_REQUESTED** [review]
Assign me back once the error is fixed.

**Comment by nikitamarysolomanpvt** [comment]
Duplicate of #1322

**Pull request closed without merging**
