### PR TITLE
Fix part of #4251: Update app version name & codes for alpha MR4

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fix part of #4251

This bumps the minor version & related version codes in preparation for cutting alpha MR4. Note that the extra '+4' is because we shipped a prerelease version of the app and didn't correspondingly commit the increment (normally we increment the version codes by +4 since there are 4 flavors built in each release, but we didn't account for the 4 used in the prerelease version).

Furthermore, alpha MR4 will include an extra version for an upcoming research study project, so the version codes will need to be incremented an extra '+1' next time (this is tracked by #4348).

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

N/A

### CODE REVIEW

**Comment by BenHenning** [comment]
@seanlip PTAL.

/cc @ankita240796  for FYI.

**Review by rt4914 — COMMENTED** [review]
@BenHenning I am unable to understand the PR decription. It says +4 but the PR has +8

**Comment by BenHenning** [comment]
I updated the description to clarify @rt4914. PTAL and let me know if that's clear, or if more context is needed.

**Review by rt4914 — APPROVED** [review]
Lgtm thanks

**Comment by BenHenning** [comment]
Thanks @rt4914!

**Pull request merged**
