### PR TITLE
Fix #3189: Create BUILD.bazel for parser package in utility module

### LINKED ISSUE #3189: Create a BUILD.bazel file in each of the subdirectories of util/parser
**Describe the solution you'd like**
We want to make each package in util/parser a buildable unit in Bazel.

**Additional context**
There will be references between the packages, so we will have to migrate all the packages together.

### PR DESCRIPTION
**Pull request by jonathanalvares9009**
Created BUILD.bazel for parser package in utility module.
Fixes #3189 
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by jonathanalvares9009** [comment]
Hi @fsharpasharp, here's the PR and here the screenshot.

Screenshot 2021-05-13 at 2 25 32 PM

**Comment by jonathanalvares9009** [comment]
Hi @fsharpasharp, I'm getting "cycle in dependency graph bazel" error but they are dependent on each other is there a way to resolve this?

**Comment by jonathanalvares9009** [comment]
Hi @fsharpasharp , these files are dependent on each other so it gives cycle dependency errors should we make separate BUILD files or one BUILD file for all three packages?

**Comment by fsharpasharp** [comment]
> Hi @fsharpasharp , these files are dependent on each other so it gives cycle dependency errors should we make separate BUILD files or one BUILD file for all three packages?

We might have to create one BUILD file. How does the cyclic dependency look like? I.e..which files?

**Comment by jonathanalvares9009** [comment]
@fsharpasharp it revolves around image_loader and scalble_vector_graphics

**Comment by jonathanalvares9009** [comment]
Tried to resolve it but some other file pops up with bazel cycle error

**Comment by fsharpasharp** [comment]
I will take a look during the weekend. We might have to reconsider the subdirectories so that we can have the cyclic dependency as one library.

**Comment by jonathanalvares9009** [comment]
Yeah was thing 'bt it. Could you take a look plz for some workarounds, I'll try my best.

**Comment by jonathanalvares9009** [comment]
@fsharpasharp can we just take the files causing cyclic error out of the sub directories and put them together in the parser BUILD.bazel file. ig The problem should be solved after this?

**Comment by fsharpasharp** [comment]
Yes, we could do that. I'll leave it to your discretion to make it build so feel free to do that. I'm still debating whether the current division with the subpackages makes sense.

**Comment by fsharpasharp** [comment]
@jonathanalvares9009, do you want to have a quick meeting where we can discuss this issue and future tasks for you?

**Comment by jonathanalvares9009** [comment]
Hi @fsharpasharp sure would like to

**Comment by jonathanalvares9009** [comment]
Had a cyclone at my place so no internet and current. Couldn't do anything since past 5 days

**Comment by jonathanalvares9009** [comment]
Hi @fsharpasharp, I work in IST timezone and I can attend the meeting at any time coz I'm on vacations. You could schedule between IST 9am to IST 11pm.

**Comment by fsharpasharp** [comment]
@jonathanalvares9009 sorry to hear about the cyclone. I'm available at 10am - 10 pm CEST. Let me know what is a good time for you.

**Comment by jonathanalvares9009** [comment]
Hi @fsharpasharp are you free now? We could have a call or 6pm CEST?

**Comment by fsharpasharp** [comment]
> Hi @fsharpasharp are you free now? We could have a call or 6pm CEST?

Monday next week works really well for me. Are you available on that day?

**Comment by jonathanalvares9009** [comment]
I don't have an issue but wanted to solve this issue. If your busy we could have it on Monday I have no issues. Just tell me the time @fsharpasharp and we'll have a call.

**Comment by fsharpasharp** [comment]
When it comes to this task, feel free to move files to resolve the circular dependency. The subpackages did not come out as modular as I wanted, so it's fine if we break that structure.

**Comment by jonathanalvares9009** [comment]
Screenshot 2021-05-20 at 7 46 56 PM

Hi @fsharpasharp I'm getting this error after pulling the latest commit from develop, should I delete this branch and then create a new branch out of develop and work on this issue as I don't get this error

**Comment by fsharpasharp** [comment]
> Screenshot 2021-05-20 at 7 46 56 PM
> 
> Hi @fsharpasharp I'm getting this error after pulling the latest commit from develop, should I delete this branch and then create a new branch out of develop and work on this issue as I don't get this error

Sounds like a good idea. Did it work?

**Comment by jonathanalvares9009** [comment]
@fsharpasharp found out that this package isn't as independent as I thought should I make a single BUILD.bazel file under parser? As they have to be put in a single file to avoid cyclic issues any thoughts?

**Comment by fsharpasharp** [comment]
> @fsharpasharp found out that this package isn't as independent as I thought should I make a single BUILD.bazel file under parser? As they have to be put in a single file to avoid cyclic issues any thoughts?

Sounds good to me. Try to move the files into the parser directory as well, we can rethink the subdirectories down the line.

**Comment by jonathanalvares9009** [comment]
Screenshot 2021-05-24 at 2 06 45 PM

Hi @fsharpasharp don't know why I'm getting these errors could you help me?

**Comment by fsharpasharp** [comment]
> Screenshot 2021-05-24 at 2 06 45 PM
> 
> Hi @fsharpasharp don't know why I'm getting these errors could you help me?

Those look like warnings except for the R one. If we're removing all the subpackages, do take a look at https://github.com/oppia/oppia-android/pull/3158/files to revert those changes. It might be easier to revert the change first and then add the BUILD.bazel file.

**Comment by jonathanalvares9009** [comment]
Hi @fsharpasharp  I'm having problem solving this issue could we have a quick meeting?

**Comment by jonathanalvares9009** [comment]
Hi @fsharpasharp I'll close this PR and create a new PR to solve this issue

**Pull request closed without merging**
