### PR TITLE
Revisit all xml drawables files for Dark Mode audit

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

Revisit all xml drawables files for Dark Mode audit:

- Prohibited use of color other than component_colors in xml drawables file except vector assets, graphics- added regex check
- Remove unused Drawables files

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by MohitGupta121 — COMMENTED** [review]
@BenHenning PTAL, Thanks.

As I talk to Rajat in chat and he said we only keep use of component_color in all xml files (include drawables, layouts) but except images, graphics, icons, vector assets and also add regex for all xml.

So in this PR I do all these things, and added separate regex check for drawables and layout. Is it fine?

**Comment by BenHenning** [comment]
Apologies @MohitGupta121 will need to look at this tomorrow.

**Comment by MohitGupta121** [comment]
@BenHenning no problem totally fine.

**Review by BenHenning — APPROVED** [review]
Thanks @MohitGupta121. This LGTM!

**Pull request merged**
