### PR TITLE
Fix part of #5195: using viewLifecycleOwner

### PR DESCRIPTION
**Pull request by sichchurov**
#### Fix part of #5195: using viewLifecycleOwner.
It is not a good idea to use a fragment as a lifecycle owner when subscribing to liveData objects. It would be correct to use viewLifecycleOwner.

Lint report before:

Lint report after

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by sichchurov** [comment]
@adhiamboperes, PTAL
Thanks

**Review by adhiamboperes — COMMENTED** [review]
Thanks @sichchurov.

I noticed that there are many other FragmentPresenters that use a fragment as a lifecycle owner when subscribing to liveData (Ctrl+Shift+F for .observe), yet only these two that you have changed are raising the lint warning. Can you pinpoint what makes them different?

**Comment by sichchurov** [comment]
> Thanks @sichchurov.
> 
> I noticed that there are many other FragmentPresenters that use a fragment as a lifecycle owner when subscribing to liveData (Ctrl+Shift+F for .observe), yet only these two that you have changed are raising the lint warning. Can you pinpoint what makes them different?

Lint doesn't show an error in file QuestionPlayerFragmentPresenter.kt. But in this class the fragment also subscribes to LiveData object, so I've decided to modify it as well. I've noticed there are many others FragmentPresenters where the fragment subscribes to LiveData object. 

I think that the reason why Lint is missing it in its report is the realization of handleCreateView() method.

In SurveyFragmentPresenter.kt method handleCreateView() has `fragment: SurveyFragment` in parameter.
In QuestionPlayerFragmentPresenter class method handleCreateView() doesn't have a fragment in parameters but use a reference from a constructor. And some others FragmentPresenters have the same handleCreateView() method

Look at my screenshots:



 I can check this version and show it in PR later

Upd..

I was right. @adhiamboperes, please look at my last commit. After adding fragment in handleCreateView() parameters, the lint begins warning about using fragment as lifecycleOwner

lifecycleowner_problem_list

**Comment by adhiamboperes** [comment]
> I was right. @adhiamboperes, please look at my last commit. After adding fragment in handleCreateView() parameters, the lint begins warning about using fragment as lifecycleOwner

Thanks for investingating this. @sichchurov, 
It seems that passing in a fragment like that can cause a memory leak, so in the case of SurveyFragmentPresenter, I think it is worth modifying such that we use a fragment from the constructor, and not  passed in the handleCreateView().

Also, when adding new information to the discussion, do create a new comment or reply, since I won't get a notification if you modify an existing comment.

**Comment by sichchurov** [comment]
In case of SurveyFragmentPresenter in method handleCreateView() we can't use a fragment from the constructor because for initialization of some interfaces and abstract class required fragment of type SurveyFragment (it implements these interfaces and abstract class). That is why we use pass this fragment to handleCreateView() parameters.

I have tried some other variants, but for the lint warning resolution I see only: Use viewLifecycleOwner in subscribeToCurrentQuestion()

**Comment by adhiamboperes** [comment]
> In case of SurveyFragmentPresenter in method handleCreateView() we can't use a fragment from the constructor because for initialization of some interfaces and abstract class required fragment of type SurveyFragment (it implements these interfaces and abstract class). That is why we use pass this fragment to handleCreateView() parameters.
> 
> I have tried some other variants, but for the lint warning resolution I see only: Use viewLifecycleOwner in subscribeToCurrentQuestion()


Sounds good to me.

**Comment by adhiamboperes** [comment]
Can you change your PR from draft to ready, unless there's some more work you need to do.

**Comment by sichchurov** [comment]
> Can you change your PR from draft to ready, unless there's some more work you need to do.

Everything is done

**Review by adhiamboperes — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
