### PR TITLE
Fix #1908:Changed comments in Proto files

### LINKED ISSUE #1908: Fix comments broken in #1876
#1876 updated proto file comments incorrectly, e.g.:

``// Maps from: data/src/main/java/org/oppia/data/backends/gae/model/GaeVoiceover.kt`` in voiceover.proto was incorrectly replaced with ``// Maps from: data/src/main/java/org.oppia.android.android/data/backends/gae/model/GaeVoiceover.kt``. It should be: ``// Maps from: data/src/main/java/org/oppia/android/android/data/backends/gae/model/GaeVoiceover.kt``.

This issue is tracking checking all proto files for these incorrect paths & fixing them.

### PR DESCRIPTION
**Pull request by Victor-Titan**
## Explanation
- Fixes #1908
- Changed org.oppia.android.android/ to org/oppia/android/android/ in the comments of the proto files

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Victor-Titan** [comment]
@anandwana001 @aggarwalpulkit596 @prayutsu PTAL

**Comment by aggarwalpulkit596** [comment]
@Victor-Titan it was fixed in the latest development or you just explicitly avoided that file?

**Comment by Victor-Titan** [comment]
> @Victor-Titan it was fixed in the latest development or you just explicitly avoided that file?


It was fixed in the latest developement

**Comment by aggarwalpulkit596** [comment]
LGTM Thanks :)

**Review by aggarwalpulkit596 — APPROVED** [review]

**Comment by prayutsu** [comment]
@Victor-Titan Is your issue resolved?

**Comment by Victor-Titan** [comment]
@prayutsu Yeah my issue is resolved

**Comment by prayutsu** [comment]
@Victor-Titan PR looks good to me, Thanks!!

**Review by prayutsu — APPROVED** [review]

**Comment by Victor-Titan** [comment]
@aggarwalpulkit596 @prayutsu Since you've both approved the PR, do I have to tag someone else for it to be merged or the merge will occur when an authorized user is free to look at the list of approved PRs?

**Comment by prayutsu** [comment]
> @aggarwalpulkit596 @prayutsu Since you've both approved the PR, do I have to tag someone else for it to be merged or the merge will occur when an authorized user is free to look at the list of approved PRs?

Just wait for some time, It will get merged most probably by tomorrow morning

**Comment by aggarwalpulkit596** [comment]
@Victor-Titan it's usually merged by someone on the team but since this one is your first PR, I wanted one more member to approve the request before i merge the req.

**Comment by Victor-Titan** [comment]
@aggarwalpulkit596 So should I tag someone else as well?

**Comment by aggarwalpulkit596** [comment]
I have already assigned it to @anandwana001.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @Victor-Titan 
@aggarwalpulkit596 You can merge this one.

**Pull request merged**
