### PR TITLE
Fix #4366, #3611, #4323: Add app data reset flow to facilitate being able to reset the admin pin

### LINKED ISSUE #3611: Uninstalling & reinstalling application does not reset administrator PIN
**Describe the bug**
If you forget your Administrator PIN number, the Oppia instructions are to uninstall the app and then reinstall it to reset it. Due to the data back up on Android, this does not work. When you uninstall the app and then reinstall it, the account is not reset, and you remain unable to log into the Administrator profile. 

**To Reproduce**
1. Set Administrator PIN 
2. Uninstall application
3. Reinstall application
4. Attempt to log in and see that the account/PIN have not been reset. 

**Expected behavior**
Uninstalling and reinstalling the app should reset the data, so you can create a new Administrator PIN and log into the application 

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Device**
- Google Pixel 5
- Alpha release 

**Additional context**

### LINKED ISSUE #4323: App doesn't open on every alternate tap on the icon
**Describe the bug**
App doesn't open on every alternate tap on the icon

**To Reproduce**
1. Go to Home page
2. Tap on Oppia
3. Page blinks and app doesnt open
4. Tap on Oppia icon again 
5. App opens properly

**Expected behavior**
App should open when the user tries to open it

Actual Result:
App doesn't open and page blinks on every 1st, 3rd and 5th tap on the Oppia icon but opens on 2nd, 4th and 6th tap

https://user-images.githubusercontent.com/101634267/165509752-80500abb-6220-48d9-beb9-331870728550.mp4

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

### LINKED ISSUE #4366: On trying to change admin password, it is asking to uninstall and reinstall the app. Even after doing it unable to change the pin
**Describe the bug**
On trying to change admin password, it is asking to uninstall and reinstall the app

**To Reproduce**
1. Go to 'Profile selection page'
2. Click on 'Admin'
3. In the Enter PIN dialog box click on I forgot my pin link
4. Uninstall and Install the app
5. The PIN is not changed 

**Expected behavior**
Admin should be able to change the PIN

https://user-images.githubusercontent.com/101634267/169010373-deec27ef-004f-4aab-bee9-850340fa2ce8.mp4

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
Fixes #4366
Fixes #3611
Fixes #4323

This PR introduces a data reset flow for cases when the user fails to remember their administrator pin. Since there's no remote profile support currently, the only option is to clear all profiles on the device. This is done using a two-step dialog since the action is permanent (at least for now--in the future we could consider making a local backup that could be restored, but that could become pretty complicated).

While this isn't a great solution, it's better than not having an option at all since users can currently get permanently stuck (see #3611). While this doesn't directly fix #3611, it mitigates it by providing a proper in-app means of resetting app data.

#4323 seems unrelated, but resetting the app required routing back to SplashActivity which means this PR needed to introduce a robustness mechanism to not set the app locale unless it wasn't already initialized (which bypasses the bug mentioned by that issue).

Mechanically, the deletion process involves:
- Deleting all profiles on the device
- Updating the in-memory cache (which causes a few UI glitches)
- "Restarting" the app by ending the activity and routing back to SplashActivity

This replaces the existing "forgot PIN" flow for admins, and it technically does not reset non-profile data (such as the device installation ID, onboarding status, analytics/crash events, and some device-wide preferences).

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
This PR is using the app's existing alert dialog theme, so it's not particularly interesting to show landscape/tablet screenshots as the UI isn't fundamentally different. The same is the case for special internationalization or accessibility concerns.

In terms of a demonstration of the new flow, see the following video:

https://user-images.githubusercontent.com/12983742/186572278-d0238e62-d013-419a-9c49-afe97cd10a5d.mp4

#4567 is tracking introducing tests, and the PR addressing it for these changes will include demonstrations of changed Espresso tests.

### CODE REVIEW

**Comment by BenHenning** [comment]
@seanlip what are your thoughts on the video demonstrating the new flow? Happy to take easy suggestions (such as wording), or feedback on if you think there's something especially problematic with the new flow.

**Comment by BenHenning** [comment]
Remaining tasks before force-merge:
- [x] Passing CI
- [x] Finished description
- [x] Sign-off from product (done, just need to make an adjustment)
- [x] Fix caching issue wherein new profiles temporarily show their previous profile slot's progress
- [x] Change forgot pin wording per Sean's suggestion below

**Comment by seanlip** [comment]
Just to check, you've verified that profiles actually get deleted on reset, and that if they are recreated with the same profile name, the old data no longer shows? The video doesn't show that so I wanted to double-check.

Otherwise, the only suggestion I have is to change "I forgot my pin" to "Forgot PIN?"; I think the rest seems OK to me.

Thanks!

**Comment by seanlip** [comment]
Also @BenHenning, just a note for next time, please assign me explicitly if you want me to take action in any way (I depend on this somewhat to manage the incoming PR queue). Thanks!

**Comment by BenHenning** [comment]
Thanks @seanlip. The name doesn't matter, but thanks for bringing up that flow. There's an in-memory cache inconsistency here for saved progress where a new profile will have the same transient progress as the previous one (for that slot--name doesn't matter here). Restarting the app shows the correct reset progress, so I need to look into why this is happening.

**Comment by BenHenning** [comment]
So digging into the issue a bit more, the main problem is that all of the caches throughout the app that depend on profiles are not considering the files being removed like they are in this use case. We can certainly add cataloging to fix this, but I'm not sure it's worth the long-term maintenance cost (as it will affect all future cache stores, too).

The workaround is to forcibly close the app and instruct the user to reopen it manually. This isn't a great option, but automatically opening the app is tricky (Android provides mechanisms, but they are either inexact in *when* they'll run, or they will eventually require user-revokable permissions in later versions of Android which is just a bit messy). Given how rare this case is expect to happen, having the user reopen the app seems reasonable I think.

**Comment by BenHenning** [comment]
Due to the importance of getting this PR in ASAP for Beta MR1, I will be force-merging this once the CI checks come back passing. #4567 is tracking finishing the PR's tests, and ensuring the PR is reviewed later.

**Pull request merged**
