### PR TITLE
Fix part of #2516: Introduce appversion build.bazel

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix part of #2516 
Adding BUILD.bazel file for AppVersion directory

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
@fsharpasharp  PTAL
Sending a Draft PR by introducing a file and keeping the test function in it. 

Could you give some pointers on how should we shift respective viewmodels/listeners?

**Comment by fsharpasharp** [comment]
Hey @anandwana001, after talking with @BenHenning I realized this issue as a whole was not that straightforward because of the underlying dependencies. I've marked the issue as blocked until I can dig deeper and write some more detailed instructions. If you still want to work on this issue, I'll message you as I figure it out. Or if you are interested you can try to help me figure out how we should pull out the circular dependencies in this task.

**Comment by anandwana001** [comment]
Sure, let me think about this and we can discuss more on this.

**Comment by anandwana001** [comment]
@fsharpasharp Let's plan a meeting and we can discuss on this and create a strategic doc which could be include with the release too.

**Comment by fsharpasharp** [comment]
That would be great, how should I reach you? @anandwana001

**Comment by anandwana001** [comment]
Closing this PR as per our discussion.

**Pull request closed without merging**
