### PR TITLE
Fix #5395: Fixed concept card not closing when opened from hint

### LINKED ISSUE #5395: [BUG]: Concept Card does not close when opened from within a hint
### Describe the bug

When a concept card is opened from a link within a hint dialog, the **X** close button does not work. The only way to close the card is by clicking the back button.

### Steps To Reproduce

- In the developer version of the app, start playing **first test topic**.
- In the first question, enter a wrong answer twice to trigger a hint being revealed.
- View the hint and click on the link to view the concept card.
- In the concept card, click on the X button. See that nothing happens.

### Expected Behavior

I expected the concept card to be closed and I be directed back to the hints dialog.

### Screenshots/Videos

[device-2024-05-14-152057.webm](https://github.com/oppia/oppia-android/assets/59600948/85e71a93-d926-45c3-8f57-af287119a7b7)

### What device/emulator are you using?

 Pixel 3a emulator.

### Which Android version is your device/emulator running?

API 29

### Which version of the Oppia Android app are you using?

develop branch

### Additional Context

It might be worth it creating a debugging doc with this template: https://docs.google.com/document/d/1qRbvKjJ0A7NPVK8g6XJNISMx_6BuepoCL7F2eIfrGqM/edit

### PR DESCRIPTION
**Pull request by Vishwajith-Shettigar**
## Explanation
Fixes #5395.

`(fragment.requireActivity() as? ConceptCardListener)?.dismissConceptCard()` in `ConceptCardFragmentPresenter` calls the `dismissConceptCard()` method in` ExplorationActivity` since `ExplorationActivity `implements `ConceptCardListener` and overrides the `dismissConceptCard()` method.
This makes call `dismissAll()` in  `ConceptCardFragment` through `StateFragment` there it passes its `childFragmentManager`.

Even though it managed to call the `dismissAll()` method in `ConceptCardFragment`, but the wrong fragment manager was passed. We passed `StateFragment's childFragmentManager`, but `ConceptCardFragment `is nested within `HintAndSolutionFragment`, so it should be passed `HintAndSolutionFragment's childFragmentManager`.

[concept_card.webm](https://github.com/user-attachments/assets/d1959296-79bf-4e4f-b2d9-04acff089c37)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar, this looks good so far. Please add tests that confirm the bug is fixed. You can use https://github.com/oppia/oppia-android/pull/4939 as reference to some concept card tests.

**Comment by Vishwajith-Shettigar** [comment]
> Thanks @Vishwajith-Shettigar, this looks good so far. Please add tests that confirm the bug is fixed. You can use #4939 as reference to some concept card tests.

I think the changes I have made already have relevant tests.

**Comment by adhiamboperes** [comment]
> > Thanks @Vishwajith-Shettigar, this looks good so far. Please add tests that confirm the bug is fixed. You can use #4939 as reference to some concept card tests.
> 
> I think the changes I have made already have relevant tests.

The tests do not catch the bug addressed by this PR, so we do want to add a test for that scenario so that it does not happen again.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

**Review by adhiamboperes — APPROVED** [review]
This LGTM, thanks @Vishwajith-Shettigar!

**Pull request merged**
