### PR TITLE
Fix #3089: Removed unnecessary context initialization in RevisionCardFragmentTest

### LINKED ISSUE #3089: Remove context initialization in RevisionCardFragmentTest
**Describe the bug**
In file`RevisionCardFragmentTest` context is intialising in function `setUp()` But we are also injecting it through dagger. 

**Expected behavior**
As we are injecting it through dagger, no need for initialization. 

### How to send a PR 
1. Run test file on espresso
2. Add a screenshot in the PR description showing all the test in this file are passing.

### PR DESCRIPTION
**Pull request by Pranav-Bobde**
RevisionCardFragmentTests Passed

## Explanation
Fixes #3089: In RevisionCardFragmentTest,  in function setUp() there's no need for initializing context we are already injecting it through dagger.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by prayutsu** [comment]
@Pranav-Bobde Can you also add a screenshot of test results on robolectric?

**Comment by anandwana001** [comment]
@Pranav-Bobde Thanks for the second PR. 
Please follow the checklist given in the PR description.

**Comment by anandwana001** [comment]
> @Pranav-Bobde Can you also add a screenshot of test results on robolectric?

@prayutsu  I don't it's required as the robolectric tests are running on GitHub actions. We always need espresso, because, it's not there in the actions.

**Comment by Pranav-Bobde** [comment]
@anandwana001  
so what do i need to do now to solve that last error?
i have shared screenshot of espresso (instrumented test only no?)

**Comment by anandwana001** [comment]
Re running checks

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @Pranav-Bobde

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
