### PR TITLE
Fix #3755: Administration controls invisible but actionable

### LINKED ISSUE #3755: AdministratorControlsActivity tablet has Fragment management issues
**Describe the bug**
ONLY IN TABLETs
In Administrator Controls -> Edit Profiles, the list of Profiles of Profiles goes INVISIBLE but not GONE.

**To Reproduce**
1. Go to  'Administrator Controls'
2. Click on 'App Version'
3. Click on the blank space on the right side.

**Expected behavior**
When you click on the blank area on the right side, you'll see that the corresponding profile from the list of profiles from the 'Edit profiles' gets clicked/open.

**Video**
https://user-images.githubusercontent.com/66965591/131714591-c1e48cd3-baf4-47de-933d-b748e8e50d57.mp4

**Device**
- Any Tablet (In video: 10.1 WXGA(Tablet))
- SDK version 28

**Additional context**
There might be some changes needed in `AdministratorControlsActivityPresenter` to fix this issue but it needs full investigation first.

### PR DESCRIPTION
**Pull request by masclot**
## Explanation
Fix #3755: AdministratorControlsActivity tablet has Fragment management issues

The "App Version" fragment was being added on top of the previous fragment, instead of replacing it.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

The following videos show how you can click on a hidden ui control in the current version, but you cannot after the changes in this cl.
|current|new|
|-|-|
|[current_administration_controls_invisible_but_actionable.webm](https://user-images.githubusercontent.com/103062089/225941610-d41ed412-625c-45de-b18c-3279bd2d2401.webm)|[new_administration_controls_invisible_but_actionable.webm](https://user-images.githubusercontent.com/103062089/225941644-7b3598ba-89c5-4a8b-9611-ecc751ea1b25.webm)|

Screenshot with test failure when app-version goes back to use add fragment, instead of replace fragment.

Test failure when app-version adds fragment, instead of replacing it

### CODE REVIEW

**Comment by masclot** [comment]
@adhiamboperes PTAL

**Review by adhiamboperes — COMMENTED** [review]
Thanks @masclot!

Can you add some  screenshots or a video since this is a UI issue?

**Comment by masclot** [comment]
Sure. The video shows how you can click on a hidden ui control in the current version, but you cannot after the changes in this cl.


|current|new|
|-|-|
|[current_administration_controls_invisible_but_actionable.webm](https://user-images.githubusercontent.com/103062089/225941610-d41ed412-625c-45de-b18c-3279bd2d2401.webm)|[new_administration_controls_invisible_but_actionable.webm](https://user-images.githubusercontent.com/103062089/225941644-7b3598ba-89c5-4a8b-9611-ecc751ea1b25.webm)|

**Review by adhiamboperes — APPROVED** [review]
Nice catch! This LGTM.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @masclot! I agree--this is a nice find. Two things:

1. Can you please move the before/after video to the PR description (under the UI section, per its instructions)?
2. Can you add a test to verify that replace() is being used as expected? This test should fail if you temporarily revert back to 'replace'.

**Comment by masclot** [comment]
> * Can you please move the before/after video to the PR description (under the UI section, per its instructions)?
> * Can you add a test to verify that replace() is being used as expected? This test should fail if you temporarily revert back to 'replace'.

Done

**Comment by masclot** [comment]
@BenHenning PTAL

**Review by BenHenning — COMMENTED** [review]
Thanks @masclot! The PR LGTM, but can you please include a screenshot showing the test failing when the fix is temporarily reverted (just to demonstrate that it can correctly catch the issue)?

**Comment by masclot** [comment]
> Thanks @masclot! The PR LGTM, but can you please include a screenshot showing the test failing when the fix is temporarily reverted (just to demonstrate that it can correctly catch the issue)?

Screenshot added to the PR description

**Comment by masclot** [comment]
@BenHenning PTAL

**Review by BenHenning — APPROVED** [review]
Thanks @masclot. This LGTM!

**Comment by BenHenning** [comment]
Syncing with latest develop & enabling auto-merge.

**Pull request merged**
