### PR TITLE
Fix #1894 : Thoroughly test FractionInputIsLessThanRuleClassifier

### LINKED ISSUE #1894: Thoroughly test FractionInputIsLessThanRuleClassifier
Since the FractionInputIsLessThanRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation

Fixes #1894 
Tests are added for FractionInputIsLessThanRuleClassifier
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by MohamedMedhat1998 — CHANGES_REQUESTED** [review]
Just 1 simple change. Please follow the suggested naming convention by Ben in his comment [here](https://github.com/oppia/oppia-android/pull/1922#discussion_r499992095)

**Comment by prayutsu** [comment]
@MohamedMedhat1998 PTAL

**Review by MohamedMedhat1998 — APPROVED** [review]
LGTM, Thanks!

**Comment by MohamedMedhat1998** [comment]
@rt4914 any idea why this check is failing?  
I have tried running some of these test cases on my local and they passed

**Comment by prayutsu** [comment]
@MohamedMedhat1998 @rt4914 Even they passed on my local machine

**Comment by anandwana001** [comment]
@prayutsu 
1. Could you update your branch with latest develop and check if it fails?
2. Could you run these 5 failing test case on local and check if they are passing?

**Comment by prayutsu** [comment]
> @prayutsu
> 
> 1. Could you update your branch with latest develop and check if it fails?
> 2. Could you run these 5 failing test case on local and check if they are passing?

Screenshot from 2020-10-07 19-57-51

**Comment by prayutsu** [comment]
@anandwana001 Can you please tell which specif 5 tests, because I am not able to figure out exactly which tests are failing.

**Comment by BenHenning** [comment]
QuestionPlayerActivityTest also flakes me locally if run as part of the whole app module test suite. I'm currently working to submit #1939 so that when we hit this again we will see the full stack trace.

Not sure what's going on with ProfileProgressFragmentTest.

**Comment by rt4914** [comment]
@prayutsu These are the same test cases which failing in this latest PR too. https://github.com/oppia/oppia-android/pull/1939/checks?check_run_id=1221502103#step:5:961

Lets wait for that PR to get merged and then we might see more information about the actual issue.

**Comment by MohamedMedhat1998** [comment]
give @prayutsu 25 points

**Pull request merged**
