### PR TITLE
Fix #645: Lowfi Landscape: AdminAuth Screen

### LINKED ISSUE #645: Lowfi Landscape: AdminAuth Screen
Mock Link: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/6722d327-0ea3-4a80-8370-69ce85f308f5/RG-MN-Register-Empty-22

Helpful Resource: https://github.com/oppia/oppia-android/wiki/Working-on-UI

Currently Admin Auth Screen does not support Landscape mode, we need to update the code to make it landscape compatible.

### PR DESCRIPTION
**Pull request by EdOates84**
Lowfi Landscape: AdminAuth Screen

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
Please make the following changes to your PR:

1. The title of this PR is incorrect, it should be:
`Fix #645: Lowfi Landscape: AdminAuth Screen`
2. The description should include the mock link as well as before and after screenshots.
3. You will need to add test cases too for this. Check landscape related test cases in other files for more help. (I would expect you to try to find some lead on this but you get stuck feel free to ask me as it is fairly hard task to write test cases as a new comer. https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing)
4. Your checklist is not marked:
Screenshot 2020-02-12 at 9 59 17 PM
Checking other Pull Requests on this project to see how to mark checklist.

Thanks a lot @EdOates84

**Comment by EdOates84** [comment]
I've already add screenshots https://github.com/oppia/oppia-android/issues/645

**Comment by rt4914** [comment]
> I've already add screenshots #645

@EdOates84 Actually I have mentioned in https://github.com/oppia/oppia-android/issues/645#issuecomment-585289780 , that screenshots should not be mentioned in issues, rather they should be attached in PR description.

**Comment by EdOates84** [comment]
Ok sir 👍

**Comment by rt4914** [comment]
@EdOates84 one more general comment, the branch name that you have written is not correct as per our convention. We normally write branch name in all small letters which related to the issue. In your case it could have been `landscape-admin-auth` or `admin-auth-ui` or `admin-auth-landscape`. In this PR we cannot fix that but in upcoming PRs we can keep this in mind.

**Comment by EdOates84** [comment]
Ok sure

**Comment by EdOates84** [comment]
What should i do next?

**Comment by EdOates84** [comment]
Hey @rt4914 
### fix: Lowfi Landscape: AdminAuth Screen

### Before

Screenshot_20200212_172508

### After

Screenshot_20200212_172527

**Comment by rt4914** [comment]
Closing this PR as there has been no reply from the contributor on this.

**Pull request closed without merging**
