### PR TITLE
Fix #4722: Created date not fully visible for certain devices and languages

### LINKED ISSUE #4722: Portugese: In edit profile page the created date is not seen completely
**Describe the bug**
Portugese: In edit profile page the created date is not seen completely

Pre-Requisite:
Change system language to Portugese

**To Reproduce**
1. Go to Administrator Controls
2. Click on Edit Profiles
3. Select any profile
4. See Created date time and year

**Expected behavior**
The year 2022 should also be seen completely

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
edit profiles

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android version 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

### PR DESCRIPTION
**Pull request by antonmagnus**
## Explanation
Fixes issue #4772

This PR adds some margin to the end of the created date text on the edit profile view to make sure that it's fully visible.

The main development was done on a pixel 3a on API 29 (see the screenshots below). However, since the issue was reported on a Infinix SMART 5 the changes have also been tested on a device with a similar screen resolution (Galaxy Nexus on API 29).

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### Previous version
oppia_old_version_port

### New version
oppia_port

oppia_port_land

oppia_eng

oppia_arabic

### ProfileEditFragmentTest
Screenshot 2022-11-23 at 10 29 42

### CODE REVIEW

**Comment by BenHenning** [comment]
@antonmagnus could you please update the PR description to match the PR template, and make sure that each section is filled out?

**Comment by antonmagnus** [comment]
> @antonmagnus could you please update the PR description to match the PR template, and make sure that each section is filled out?

Updated and included the template checklist.

**Comment by BenHenning** [comment]
Thanks @antonmagnus. Can you make sure that the explanation portion is in the 'Explanation' section, and that the screenshots are in the 'For UI-specific PRs only' section?

See #4685 for an example PR description.

**Comment by antonmagnus** [comment]
> Thanks @antonmagnus. Can you make sure that the explanation portion is in the 'Explanation' section, and that the screenshots are in the 'For UI-specific PRs only' section?
> 
> See #4685 for an example PR description.

I have now updated the description in accordance with the template. Do you have any further suggestions?

**Comment by BenHenning** [comment]
> > Thanks @antonmagnus. Can you make sure that the explanation portion is in the 'Explanation' section, and that the screenshots are in the 'For UI-specific PRs only' section?
> > See #4685 for an example PR description.
> 
> I have now updated the description in accordance with the template. Do you have any further suggestions?

I think it's much better, but I suggest a few small changes to help with readability (& to ensure GitHub correctly closes the corresponding issue once this is closed):

```markdown
Fixes issue #4772

This PR adds some margin to the end of the created date text on edit profile view to make sure that it's fully visible.

The main development was done on a pixel 3a on API 29 (see the screenshots below). However, since the issue was reported on a Infinix SMART 5 the changes have also been tested on a device with similar screen resolution (Galaxy Nexus on API 29).
```

Notice how I formatted the 'fixes' part, and also re-worded the explanation to read more as "Did X to fix Y" to be really clear on what the PR is doing.

**Comment by antonmagnus** [comment]
> > > Thanks @antonmagnus. Can you make sure that the explanation portion is in the 'Explanation' section, and that the screenshots are in the 'For UI-specific PRs only' section?
> > > See #4685 for an example PR description.
> > 
> > 
> > I have now updated the description in accordance with the template. Do you have any further suggestions?
> 
> I think it's much better, but I suggest a few small changes to help with readability (& to ensure GitHub correctly closes the corresponding issue once this is closed):
> 
> ```gfm
> Fixes issue #4772
> 
> This PR adds some margin to the end of the created date text on edit profile view to make sure that it's fully visible.
> 
> The main development was done on a pixel 3a on API 29 (see the screenshots below). However, since the issue was reported on a Infinix SMART 5 the changes have also been tested on a device with similar screen resolution (Galaxy Nexus on API 29).
> ```
> 
> Notice how I formatted the 'fixes' part, and also re-worded the explanation to read more as "Did X to fix Y" to be really clear on what the PR is doing.

Thank you for the suggestions, I agree that it is clearer now.
 I have updated the description based on your suggestions.

**Comment by BenHenning** [comment]
Thanks @antonmagnus. Note that, when you're done addressing a reviewer's comments, you should let them know by saying 'PTAL @<name>' so that they are aware that they need to take another review pass.

@rt4914 PTAL for codeowners.

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks @antonmagnus

**Comment by BenHenning** [comment]
Resolving the conflict & marking this PR for auto-merge since it's been approved.

**Pull request merged**
