### PR TITLE
Fix #4760: In Terms of Service the website is displayed as a link and is made clickable

### LINKED ISSUE #4760: In Terms of Service the website should be displayed as link and should be clickable
**Describe the bug**
In Terms of Service the website should be displayed as link and should be clickable

**To Reproduce**
1. Go to Menu - Help
2. Click on Terms of Service
3. In the 1st paragraph look at the website link 

**Expected behavior**
The link https://www.oppia.org should be displayed as a link and it should be clickable.
The sentence ' Thanks for your interest in Oppia Foundation Inc., a nonprofit that operates the website located at https://www.oppia.org (the Website).'

Website is mentioned twice in the statement.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
Screenshot_20221124-143700

**Environment**
Device/emulator being used: Infinix smart 5A
Android or SDK version (e.g. Android 5 or SDK 21): Android version 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

### PR DESCRIPTION
**Pull request by pratyaksh1610**
## Explanation
Fix #4760 
In Terms of Service the website is displayed as a link and is made clickable

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## Before
before

## After

https://user-images.githubusercontent.com/76740999/204264399-63f5e84c-d908-476b-b50c-dae3c42c2fbd.mp4

### CODE REVIEW

**Comment by BenHenning** [comment]
Thanks @pratyaksh1610! The solution seems sensible, but could you also add a test to verify that the link works as expected?

@rt4914 PTAL as code owner.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@pratyaksh1610 The solution does look correct. Add test to verify this.

**Comment by pratyaksh1610** [comment]
I am working on it

**Comment by pratyaksh1610** [comment]
Tests are not working on my machine, figuring out.

**Pull request closed without merging**
