### PR TITLE
[RunAllTests] Fix #3157: Bazel Build Maven Fetch Error

### LINKED ISSUE #3157: Bazel Build Maven Fetch Error
**Describe the bug**
Currently, Bazel build is causing error while fetching Maven dependencies on GitHub actions as well as on local Bazel build. 

**Expected behavior**
Bazel build should fetch Maven dependencies without throwing any error.

**Additional context**
```console
ERROR: /home/runner/work/oppia-android/oppia-android/third_party/BUILD.bazel:22:17: 
//third_party:javax_inject_javax_inject depends on @maven//:javax_inject_javax_inject in 
repository @maven which failed to fetch. no such package '@maven//': Error while fetching 
artifact with coursier: Exception in thread "main" java.lang.NumberFormatException: For input string: "intot"
```

```console
ERROR: /home/runner/work/oppia-android/oppia-android/third_party/BUILD.bazel:22:17: 
//third_party:androidx_appcompat_appcompat depends on 
@maven//:androidx_appcompat_appcompat in repository @maven which failed to fetch. no such 
package '@maven//': Error while fetching artifact with coursier: Exception in thread "main" 
java.lang.NumberFormatException: For input string: "intot"
```

Digging deep
```
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_akshaynandwana/0e0a7569f455d331a530cc35527abf40/external/rules_jvm_external/coursier.bzl", line 710, column 38, in _coursier_fetch_impl
                dep_tree = make_coursier_dep_tree(
        File "/private/var/tmp/_bazel_akshaynandwana/0e0a7569f455d331a530cc35527abf40/external/rules_jvm_external/coursier.bzl", line 649, column 13, in make_coursier_dep_tree
                fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Exception in thread "main" java.lang.NumberFormatException: For input string: "intot"
```

`/private/var/tmp/_bazel_akshaynandwana/0e0a7569f455d331a530cc35527abf40/external/rules_jvm_external/coursier.bzl`
```
exec_result = repository_ctx.execute(
        cmd,
        timeout = timeout,
        environment = environment,
        quiet = not _is_verbose(repository_ctx))
    if (exec_result.return_code != 0):
        fail("Error while fetching artifact with coursier: " + exec_result.stderr)
```

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #3157 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
Trying with keeping our original rules_jvm version and remove bintray repository.

**Comment by anandwana001** [comment]
@BenHenning @fsharpasharp I think we can skip compute affected test, right?

**Comment by BenHenning** [comment]
@anandwana001 that would lead to us not fully verifying Bazel is now working, I think. We should add '[RunAllTests]' to the title, then push an empty commit to retrigger the tests such that all are run.

Also, I followed up on the issue--I think more work may be needed here.

**Comment by anandwana001** [comment]
@BenHenning ok, before going with more work stage, is there any specific thing we can do so that PRs not get blocked to merge?

**Review by BenHenning — APPROVED** [review]
As discussed over chat, we actually only need https://jcenter.bintray.com/ not the other bintray URL so we can remove that given it now appears to redirect to a blog post. I think they intentionally left one up & not the other, but this might have been a last minute and poorly communicated change on JFrog's part. Either way, this seems like a nice fix since we're still keeping jcenter deps for now.

Thanks @anandwana001!

**Pull request merged**
