### PR TITLE
Remove self code owners until 24 May 2021

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
I will have limited availability over the next two weeks, so removing/replacing code owners to ensure we have coverage & availability.

**Code reviewers**: Please confirm your adjusted code owners via approval. If you're ensure of anything, please reach out.

### CODE REVIEW

**Review by seanlip — APPROVED** [review]

**Review by fsharpasharp — APPROVED** [review]
Looks good for the ones concerning me.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by vinitamurthi — APPROVED** [review]

**Comment by vinitamurthi** [comment]
LGTM! Merging this

**Pull request merged**
