### PR TITLE
Fix #2530: Double line issue in Profile Chooser in Tablets

### LINKED ISSUE #2530: Double line issue in Profile Chooser in Tablets.

### PR DESCRIPTION
**Pull request by Mehul-Bisht**
## Explanation

  
This issue was arising due to divider Item in both profile_chooser_profile_view and profile_chooser_add_view, I removed the background color from the `View` in the tablet layout orientations. Since these views will only be visible when the user has not created any new profiles, I assume this shouldn't be causing any issues. 
 
## Portrait Mode
| After Changes |
:-------------------------:
portrait

## Landscape Mode
| After changes |
:-------------------------:
landscape

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
This solution is incorrect. The reason behind this divider line is following:
To make UI look almost perfect we divided this divider line of 1dp in 0.5dp, 0.5dp each in following files: `profile_chooser_add_view` and `profile_chooser_profile_view`.

Now as were your changes there are two issues: (a.) you have tried remove only the one part of line (0.5 only) as the other part is in another file. (b.) Infact you have not removed the 0.5dp line but you have just removed its background so technically line is still there but its not visible.


## Suggested solution:

Remove one of these lines (0.5) from one type of file (suggested: profile_chooser_add_view) and in other file (which is profile_chooser_profile_view) change the height of the line from `0.5` to `1` . 
If you try this solution make sure you apply this solution for all layout - mobile-landscape/portrait and tablet landscape/portrait.

Thanks.

**Comment by Luffy18346** [comment]
@Mehul-Bisht PTAL

**Comment by Mehul-Bisht** [comment]
> @Mehul-Bisht PTAL

Currently working on this PR

**Comment by Mehul-Bisht** [comment]
## Update

## Landscape Mode:
| Status |
:-------------------------:
double_line_portrait

## Portrait Mode:
double_line_land

**Comment by Mehul-Bisht** [comment]
@rt4914 Kindly check the recent changes

**Review by rt4914 — CHANGES_REQUESTED** [review]
@Mehul-Bisht this solution does work nicely. Can you make similar change for mobile related xml files too considering that there also we are using two lines.

Thanks

**Comment by Mehul-Bisht** [comment]
>Can you make similar change for mobile related xml files too considering that there also we are using two lines.

@rt4914 I've made changes for mobile layouts. PTAL

**Review by rt4914 — APPROVED** [review]
Thanks a lot.

**Pull request merged**
