### PR TITLE
Fixes #1977 : Optimise code in administrator controls profile view.xml

### LINKED ISSUE #1977: Optimise code in administrator_controls_profile_view.xml
This issue is tracking the optimization work of `administrator_controls_profile_view.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all TextViews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be the same as before (or an optimized version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by Austinepass**
Fix #1977 Styled the TextViews with the suitable styles defined in the style.xml file

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Austinepass** [comment]
@MohamedMedhat1998 PTAL

**Comment by prayutsu** [comment]
@Austinepass You can prepend `Fixes #1977 : ` to your PR title so that it matches with our PR guideines

**Comment by Austinepass** [comment]
> @Austinepass You can prepend `Fixes #1977 : ` to your PR title so that it matches with our PR guideines

@prayutsu Done.

**Comment by Austinepass** [comment]
@MohamedMedhat1998 can you also PTAL

**Review by MohamedMedhat1998 — CHANGES_REQUESTED** [review]
Please update your forked repo with the latest develop. You can do this by following the steps in [this blog post](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a).

**Comment by Austinepass** [comment]
> Please update your forked repo with the latest develop. You can do this by following the steps in [this blog post](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a).

I have done that @MohamedMedhat1998. Do I have to submit a new PR for this issue?

**Comment by MohamedMedhat1998** [comment]
> > Please update your forked repo with the latest develop. You can do this by following the steps in [this blog post](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a).
> 
> I have done that @MohamedMedhat1998. Do I have to submit a new PR for this issue?

No, you don't have to.  
The current problem is that there are 7 changed files, and this PR should only contain 3 files, which are:
1. `layout/administrator_controls_profile_view.xml`
2. `layout-land/administrator_controls_profile_view.xml`
3. `layout-sw600dp/administrator_controls_profile_view.xml`  

If you only changed these 3 files, and there are 7 changed files in the PR, then you may need to update your branch with the latest develop.

**Comment by Austinepass** [comment]
> > > Please update your forked repo with the latest develop. You can do this by following the steps in [this blog post](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a).
> > 
> > 
> > I have done that @MohamedMedhat1998. Do I have to submit a new PR for this issue?
> 
> No, you don't have to.
> The current problem is that there are 7 changed files, and this PR should only contain 3 files, which are:
> 
> 1. `layout/administrator_controls_profile_view.xml`
> 2. `layout-land/administrator_controls_profile_view.xml`
> 3. `layout-sw600dp/administrator_controls_profile_view.xml`
> 
> If you only changed these 3 files, and there are 7 changed files in the PR, then you may need to update your branch with the latest develop.


> > > Please update your forked repo with the latest develop. You can do this by following the steps in [this blog post](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a).
> > 
> > 
> > I have done that @MohamedMedhat1998. Do I have to submit a new PR for this issue?
> 
> No, you don't have to.
> The current problem is that there are 7 changed files, and this PR should only contain 3 files, which are:
> 
> 1. `layout/administrator_controls_profile_view.xml`
> 2. `layout-land/administrator_controls_profile_view.xml`
> 3. `layout-sw600dp/administrator_controls_profile_view.xml`
> 
> If you only changed these 3 files, and there are 7 changed files in the PR, then you may need to update your branch with the latest develop.

@MohamedMedhat1998 I have updated my branch, the 7 changed files instead of 3 files issue stems from the fact that I forgot to create a new branch after I submitted a PR for a different issue i worked on earlier(I made the commits on the same branch). Is there a way to fix this or I should submit a new PR? I have spent majority of my day trying to figure it out.

**Comment by MohamedMedhat1998** [comment]
> > > > Please update your forked repo with the latest develop. You can do this by following the steps in [this blog post](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a).
> > > 
> > > 
> > > I have done that @MohamedMedhat1998. Do I have to submit a new PR for this issue?
> > 
> > 
> > No, you don't have to.
> > The current problem is that there are 7 changed files, and this PR should only contain 3 files, which are:
> > 
> > 1. `layout/administrator_controls_profile_view.xml`
> > 2. `layout-land/administrator_controls_profile_view.xml`
> > 3. `layout-sw600dp/administrator_controls_profile_view.xml`
> > 
> > If you only changed these 3 files, and there are 7 changed files in the PR, then you may need to update your branch with the latest develop.
> 
> > > > Please update your forked repo with the latest develop. You can do this by following the steps in [this blog post](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a).
> > > 
> > > 
> > > I have done that @MohamedMedhat1998. Do I have to submit a new PR for this issue?
> > 
> > 
> > No, you don't have to.
> > The current problem is that there are 7 changed files, and this PR should only contain 3 files, which are:
> > 
> > 1. `layout/administrator_controls_profile_view.xml`
> > 2. `layout-land/administrator_controls_profile_view.xml`
> > 3. `layout-sw600dp/administrator_controls_profile_view.xml`
> > 
> > If you only changed these 3 files, and there are 7 changed files in the PR, then you may need to update your branch with the latest develop.
> 
> @MohamedMedhat1998 I have updated my branch, the 7 changed files instead of 3 files issue stems from the fact that I forgot to create a new branch after I submitted a PR for a different issue i worked on earlier(I made the commits on the same branch). Is there a way to fix this or I should submit a new PR? I have spent majority of my day trying to figure it out.

I'm not sure whether we can fix this or not, but I suggest creating a new PR anyways (because now we have 16 changed files)  
Also, please make sure to follow the points in the PR checklist:

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

**Comment by MohamedMedhat1998** [comment]
@Austinepass you can mention the reason for closing the PRs so that people can track your work easily.  
The reason for closing this PR is that we have opened #2011 which is a cleaner version of this PR.

**Comment by Austinepass** [comment]
> @Austinepass you can mention the reason for closing the PRs so that people can track your work easily.
> The reason for closing this PR is that we have opened #2011 which is a cleaner version of this PR.

Since you've mentioned it, is there still need to mention it.

**Comment by MohamedMedhat1998** [comment]
> > @Austinepass you can mention the reason for closing the PRs so that people can track your work easily.
> > The reason for closing this PR is that we have opened #2011 which is a cleaner version of this PR.
> 
> Since you've mentioned it, is there still need to mention it.

No no, just mention that in the future reviews only, thanks.

**Comment by Austinepass** [comment]
> > > @Austinepass you can mention the reason for closing the PRs so that people can track your work easily.
> > > The reason for closing this PR is that we have opened #2011 which is a cleaner version of this PR.
> > 
> > 
> > Since you've mentioned it, is there still need to mention it.
> 
> No no, just mention that in the future reviews only, thanks.

Noted with thanks.

**Pull request closed without merging**
