### PR TITLE
Disable experimental Coroutines Warnings in Domain module.

### PR DESCRIPTION
**Pull request by jaimehta19**
## Explanation

This Pull Request disables the experimental Coroutines warning for Domain module in the bazel file.

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by FareesHussain** [comment]
@jaimehta1912 Can you add a screenshot where it disables the earning

And how is it related to bazel

**Comment by BenHenning** [comment]
Thanks @jaimehta1912. I think we were looking into doing this earlier, but ran into some issues (see #3484 for context). Could you provide the details @FareesHussain is asking for? I'm also really interested in seeing whether this addresses the issue since I don't expect it to.

**Comment by jaimehta19** [comment]
@FareesHussain @BenHenning  Do you mean you want the Screenshot from the Profiler or how it is concerned with the Bazel?

**Comment by FareesHussain** [comment]
@jaimehta1912 what I meant was.
A screenshot without your implementation that shows the warning and a screenshot with your implementation that doesn't show the warning. to verify it is actually working.

**Pull request closed without merging**
