### PR TITLE
Fixes #4539: Replace CaseSensitiveEquals by Equals in dev assets

### LINKED ISSUE #4539: Submit button is not enabled after inputting the answer
**Describe the bug**
The Submit button highlight is not enabled after user inputs answer instead throws exception..

Exception: 
```
2022-08-09 21:13:49.707 21191-21191/org.oppia.android E/StateFragment: Failed to retrieve answer outcome
    java.lang.IllegalStateException: Expected interaction TextInput to have classifier for rule type: CaseSensitiveEquals, but only has: [Contains, Equals, FuzzyEquals, StartsWith]
        at org.oppia.android.domain.classify.AnswerClassificationController.classifyAnswer(AnswerClassificationController.kt:62)
        at org.oppia.android.domain.classify.AnswerClassificationController.classify(AnswerClassificationController.kt:39)
        at org.oppia.android.domain.exploration.ExplorationProgressController$submitAnswerImpl$2.invokeSuspend(ExplorationProgressController.kt:573)
        at org.oppia.android.domain.exploration.ExplorationProgressController$submitAnswerImpl$2.invoke(Unknown Source:10)
        at org.oppia.android.domain.exploration.ExplorationProgressController.tryOperation(ExplorationProgressController.kt:731)
        at org.oppia.android.domain.exploration.ExplorationProgressController.tryOperation$default(ExplorationProgressController.kt:727)
        at org.oppia.android.domain.exploration.ExplorationProgressController.submitAnswerImpl(ExplorationProgressController.kt:554)
        at org.oppia.android.domain.exploration.ExplorationProgressController$createControllerCommandActor$1.invokeSuspend(ExplorationProgressController.kt:435)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
``` 

**To Reproduce**
1. Go to 'Topic Ratios and Proportions - Lessons Tab'
2. Click on 'Expand Ratios: Part 1.'
3. Scroll down to 'exercises in “Order is important”'

https://user-images.githubusercontent.com/31986629/187138908-cb654cb4-d163-4c79-b0f3-1c0fcffc1524.mp4

**Expected behavior**
The submit button should be enabled after the correct answer, is entered.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

**Environment**
- Device/emulator being used: **TECHNO POP 2F**
- Android or SDK version (e.g. Android 5 or SDK 21): **Android 10**
- App version (you can get this through system app settings or via the admin controls menu in-app): <app version 1.0>

**Additional context**

### PR DESCRIPTION
**Pull request by masclot**
## Explanation
Fixes #4539: Replace the rule type CaseSensitiveEquals by Equals in dev assets. This only affects the topics used in dev environment. The rule type CaseSensitiveEquals is no longer supported.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

**Videos**

|current|new|
|-|-|
|[fix_for_CaseSensitiveEquals_current.webm](https://github.com/oppia/oppia-android/assets/103062089/0ad9f1e9-a991-4908-8576-1aba964fadcb)|[fix_for_CaseSensitiveEquals_new.webm](https://github.com/oppia/oppia-android/assets/103062089/298270d9-6af2-4cb8-a9f0-6445e5abfdd6)|

**Screenshots**

|current|new|
|-|-|
|Screenshot fix_for_CaseSensitiveEquals_current|Screenshot fix_for_CaseSensitiveEquals_new|

### CODE REVIEW

**Comment by masclot** [comment]
I tested this by running the app from both gradle and bazel; then doing the "Order is Important" chapter from the story "Ratios: Part 1".

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @masclot.

Since we don't have automated tests for these assets, what you can do is add before/after videos and screenshots. If you check out this branch, a video recording should show that the bug does not occur, and a logcat screenshot should show the stacktrace is not logged. Similarly, if you check out develop, the original bug and error log should be seen in the video and screenshot. Please add these to your PR description and reassign once done.

**Comment by masclot** [comment]
> Thanks @masclot.
> 
> Since we don't have automated tests for these assets, what you can do is add before/after videos and screenshots. If you check out this branch, a video recording should show that the bug does not occur, and a logcat screenshot should show the stacktrace is not logged. Similarly, if you check out develop, the original bug and error log should be seen in the video and screenshot. Please add these to your PR description and reassign once done.

Done. PTAL @adhiamboperes

**Review by adhiamboperes — APPROVED** [review]
LGTM, thanks @masclot!

**Review by BenHenning — APPROVED** [review]
Thanks @masclot! This LGTM.

**Comment by BenHenning** [comment]
Restarting failing CI (since it appears to be an infrastructure flake) and enabling auto-merge.

**Pull request merged**
