### PR TITLE
Screenshot testing

### PR DESCRIPTION
**Pull request by MohamedMedhat1998**
## Explanation
This PR implements the [screenshot testing library from Facebook](https://facebook.github.io/screenshot-tests-for-android/).  
In this PR, I have tried to apply the screenshot testing to `admin_auth_activity` xml file.  
## Code snippet
```
@Test
  fun runScreenshotTesting() {
    val context = InstrumentationRegistry.getInstrumentation().targetContext
    val view = LayoutInflater.from(context).inflate(R.layout.admin_auth_activity, null, false)
    ViewHelpers.setupView(view)
      .setExactWidthPx(300)
      .layout()
    Screenshot.snap(view)
      .record()
  }
```
## Issues
Screenshot testing fails but the reason is still ambiguous  
## Errors
image
Log:  
```
android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class com.google.android.material.appbar.AppBarLayout
at android.view.LayoutInflater.inflate(LayoutInflater.java:561)
at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
at org.oppia.app.screenshottesting.ScreenshotTesting.runScreenshotTesting(ScreenshotTesting.kt:15)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1890)
Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class com.google.android.material.appbar.AppBarLayout
at android.view.LayoutInflater.createView(LayoutInflater.java:672)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
... 29 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at android.view.LayoutInflater.createView(LayoutInflater.java:641)
... 34 more
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:213)
at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:148)
at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
at com.google.android.material.appbar.ViewUtilsLollipop.setStateListAnimatorFromAttrs(ViewUtilsLollipop.java:46)
at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:207)
at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:193)
... 36 more
```
Xml file that contains the problem `admin_auth_activity`
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:profile="http://schemas.android.com/tools">

  <data>

    <variable
      name="viewModel"
      type="org.oppia.app.profile.AdminAuthViewModel" />
  </data>

  <androidx.constraintlayout.widget.ConstraintLayout
    android:id="@+id/admin_auth_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/addProfileBackground">

     <!--Line 19 that causes the problem-->
    <com.google.android.material.appbar.AppBarLayout
      android:id="@+id/admin_auth_app_bar_layout"
      android:layout_width="0dp"
      android:layout_height="wrap_content"
      android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
      app:layout_constraintEnd_toEndOf="parent"
      app:layout_constraintStart_toStartOf="parent"
      app:layout_constraintTop_toTopOf="parent">

      <androidx.appcompat.widget.Toolbar
        android:id="@+id/admin_auth_toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:fontFamily="sans-serif"
        android:minHeight="?attr/actionBarSize"
        android:textSize="20sp"
        app:navigationContentDescription="@string/admin_auth_close"
        app:navigationIcon="@drawable/ic_close_white_24dp"
        app:title="@string/admin_auth_toolbar"
        app:titleTextAppearance="@style/ToolbarTextAppearance"
        app:titleTextColor="@color/white" />
    </com.google.android.material.appbar.AppBarLayout>

    <FrameLayout
      android:layout_width="0dp"
      android:layout_height="0dp"
      app:layout_constraintBottom_toBottomOf="parent"
      app:layout_constraintEnd_toEndOf="parent"
      app:layout_constraintStart_toStartOf="parent"
      app:layout_constraintTop_toBottomOf="@id/admin_auth_app_bar_layout">

      <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <TextView
          android:id="@+id/admin_auth_heading_textview"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:layout_marginStart="28dp"
          android:layout_marginTop="40dp"
          android:layout_marginEnd="28dp"
          android:fontFamily="sans-serif-medium"
          android:maxLines="2"
          android:text="@string/admin_auth_heading"
          android:textColor="@color/oppiaPrimaryText"
          android:textSize="20sp"
          app:layout_constraintEnd_toEndOf="parent"
          app:layout_constraintStart_toStartOf="parent"
          app:layout_constraintTop_toTopOf="parent" />

        <TextView
          android:id="@+id/admin_auth_sub_text"
          android:layout_width="0dp"
          android:layout_height="wrap_content"
          android:layout_marginStart="28dp"
          android:layout_marginTop="12dp"
          android:layout_marginEnd="28dp"
          android:fontFamily="sans-serif"
          android:text="@string/admin_auth_sub"
          android:textColor="@color/black_54"
          android:textSize="16sp"
          app:layout_constraintEnd_toEndOf="parent"
          app:layout_constraintStart_toStartOf="parent"
          app:layout_constraintTop_toBottomOf="@id/admin_auth_heading_textview" />

        <org.oppia.app.profile.ProfileInputView
          android:id="@+id/admin_auth_input_pin"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:layout_marginTop="16dp"
          android:addTextChangedListener="@{viewModel.inputPinTextWatcher}"
          android:imeOptions="actionDone"
          app:inputLength="5"
          app:isPasswordInput="true"
          app:label="@string/admin_auth_pin"
          app:layout_constraintEnd_toEndOf="parent"
          app:layout_constraintStart_toStartOf="parent"
          app:layout_constraintTop_toBottomOf="@id/admin_auth_sub_text"
          profile:error="@{viewModel.errorMessage}"
          profile:labelMargin="@{@dimen/margin_8}" />

        <Button
          android:id="@+id/admin_auth_submit_button"
          style="@style/StateButtonActive"
          android:layout_marginTop="44dp"
          android:layout_marginEnd="28dp"
          android:layout_marginBottom="44dp"
          android:background="@{viewModel.isSubmitButtonActive ? @drawable/state_button_primary_background :@drawable/start_button_transparent_background}"
          android:clickable="@{viewModel.isSubmitButtonActive}"
          android:minHeight="48dp"
          android:text="@string/admin_auth_submit"
          android:textColor="@{viewModel.isSubmitButtonActive ? @color/white : @color/submitButtonInactiveText }"
          app:layout_constraintBottom_toBottomOf="parent"
          app:layout_constraintEnd_toEndOf="parent"
          app:layout_constraintHorizontal_bias="1.0"
          app:layout_constraintStart_toStartOf="@+id/admin_auth_sub_text"
          app:layout_constraintTop_toBottomOf="@id/admin_auth_input_pin"
          app:layout_constraintVertical_bias="0.0" />
      </androidx.constraintlayout.widget.ConstraintLayout>

      <View
        android:id="@+id/admin_auth_toolbar_shadow_view"
        android:layout_width="match_parent"
        android:layout_height="6dp"
        android:background="@drawable/toolbar_drop_shadow" />
    </FrameLayout>
  </androidx.constraintlayout.widget.ConstraintLayout>
</layout>
```
## Steps to replicate the error
1. Implement the [screenshot testing library](https://facebook.github.io/screenshot-tests-for-android/)  
   1. Insert this line in the dependencies in **project level** `build.gradle` file  
`classpath 'com.facebook.testing.screenshot:plugin:0.12.0'`  
   2. Apply the screenshot-testing plugin in the **app module** `build.gradle` file
`apply plugin: 'com.facebook.testing.screenshot'`
   3. Add these implementations to the dependencies in **app module** `build.gradle` file   
`'com.facebook.testing.screenshot:layout-hierarchy-common:0.12.0'`
`'com.facebook.testing.screenshot:layout-hierarchy-litho:0.12.0'`
   4. Sync the project
   5. Create a custom test Runner like this one:  
```
class TestRunner : AndroidJUnitRunner() {

  override fun onCreate(arguments: Bundle?) {
    ScreenshotRunner.onCreate(this, arguments)
    super.onCreate(arguments)
  }

  override fun finish(resultCode: Int, results: Bundle?) {
    ScreenshotRunner.onDestroy()
    super.finish(resultCode, results)
  }
} 
```
Use the custom runner you just created in the **app module** `build.gradle` file this way  
`testInstrumentationRunner "org.oppia.app.screenshottesting.TestRunner"`  
2. Create a test class and add a test function  
```
class ScreenshotTesting {

  @Test
  fun runScreenshotTesting() {
    val context = InstrumentationRegistry.getInstrumentation().targetContext
    val view = LayoutInflater.from(context).inflate(R.layout.item_selection_interaction_items, null, false)
    ViewHelpers.setupView(view)
      .setExactWidthPx(300)
      .layout()
    Screenshot.snap(view)
      .record()
  }
} 
```
3. Add the external storage permission in the `AndroidManifest.xml` file
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE " />`  
4. Run the test on your device  

**Important Note:**  
Please make sure that you have installed these packages before trying.  
```
$ pip install mock
$ pip install Pillow
```

### CODE REVIEW

**Review by rt4914 — COMMENTED** [review]
I tried running the tests and some commands on this link (https://facebook.github.io/screenshot-tests-for-android/) but none of this seems to work.


Also, please add information to your description because this way we cannot assign this PR to anyone else because no one else will know the context of what it is about. So add information like why this PR is created, what resource you used to create this PR, error screenshot, steps to produce that save error.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> I tried running the tests and some commands on this link (https://facebook.github.io/screenshot-tests-for-android/) but none of this seems to work.
> 
> Also, please add information to your description because this way we cannot assign this PR to anyone else because no one else will know the context of what it is about. So add information like why this PR is created, what resource you used to create this PR, error screenshot, steps to produce that save error.

Updated the PR descriptions  
According to the commands, I run them from this menu  
Screenshot (179)

**Comment by BenHenning** [comment]
@rt4914 when you run the sample screenshot tests locally are you seeing the same error?

The theme error is likely due to the theme not being correctly specified for the activity under test. However, AdminAuthActivity does have a Theme.AppCompat theme assigned to it:https://github.com/oppia/oppia-android/blob/b0458e143fd757d074d20cac13c5ce447087c630/app/src/main/AndroidManifest.xml#L71. Is the plugin doing something fancy with resources?

A lot has also changed with aapt in the past. I wonder if the screenshot tool was updated to properly support AndroidX & Android Studio 3.6.

**Comment by BenHenning** [comment]
So looking through the documentation a bit more carefully, I think you still need to set up the test like you would any other Espresso test. If you can get the test to run correctly on Espresso without the screenshot functionality, try then turning on the screenshot functionality and see if that works.

**Comment by MohamedMedhat1998** [comment]
> So looking through the documentation a bit more carefully, I think you still need to set up the test like you would any other Espresso test. If you can get the test to run correctly on Espresso without the screenshot functionality, try then turning on the screenshot functionality and see if that works.

Can you explain more please? @BenHenning

**Comment by seanlip** [comment]
Hi Mohamed -- please explain in more detail what you don't understand, and
what you have tried in response to Ben's previous comment. Otherwise, it's
going to be harder for Ben to give you feedback. Thanks!

**Comment by MohamedMedhat1998** [comment]
@seanlip I think he was talking to @rt4914 but I thought he was talking to me 😅

**Comment by rt4914** [comment]
I was now able to run all the test cases without making any change to any code. I had to install two packages:

```
$ pip install mock
$ pip install Pillow
```
Reference: https://medium.com/xcnotes/snapshot-testing-in-espresso-e159cba817d6

Also, the results of the tests are here: 
I did this by using the following options from `Task List`
1. `recordDebugAndroidTestScreenshotTest`
2. `verifyDebugAndroidTestScreenshotTest`

https://gist.github.com/rt4914/79c889211741b5b8bf7b1d60d02e636f

@MohamedMedhat1998 Please check that installing the packages mentioned above works for you or not?

**Comment by rt4914** [comment]
@BenHenning @MohamedMedhat1998 I tried solving all the issues that I was facing and still there are errors. PTAL at this document: https://docs.google.com/document/d/1c96S0pDpvzlMpHHbN-oTbYZgy5KT3utkvQ-1QA7Hsfw/edit?usp=sharing

**Comment by MohamedMedhat1998** [comment]
> I was now able to run all the test cases without making any change to any code. I had to install two packages:
> 
> ```
> $ pip install mock
> $ pip install Pillow
> ```
> 
> Reference: https://medium.com/xcnotes/snapshot-testing-in-espresso-e159cba817d6
> 
> Also, the results of the tests are here:
> I did this by using the following options from `Task List`
> 
> 1. `recordDebugAndroidTestScreenshotTest`
> 2. `verifyDebugAndroidTestScreenshotTest`
> 
> https://gist.github.com/rt4914/79c889211741b5b8bf7b1d60d02e636f
> 
> @MohamedMedhat1998 Please check that installing the packages mentioned above works for you or not?

I have done this step before. I should have mentioned that in the PR description.  
My apologies, I'll mention it right now.  
But that was not the problem, the problem is that the test cases fail because of something related to the `styles` in the `Material Design` library.

> @BenHenning @MohamedMedhat1998 I tried solving all the issues that I was facing and still there are errors. PTAL at this document: https://docs.google.com/document/d/1c96S0pDpvzlMpHHbN-oTbYZgy5KT3utkvQ-1QA7Hsfw/edit#heading=h.tb62cg3qxutu

The link asks for permission to enter.
image

**Comment by rt4914** [comment]
> > I was now able to run all the test cases without making any change to any code. I had to install two packages:
> > ```
> > $ pip install mock
> > $ pip install Pillow
> > ```
> > 
> > 
> > Reference: https://medium.com/xcnotes/snapshot-testing-in-espresso-e159cba817d6
> > Also, the results of the tests are here:
> > I did this by using the following options from `Task List`
> > 
> > 1. `recordDebugAndroidTestScreenshotTest`
> > 2. `verifyDebugAndroidTestScreenshotTest`
> > 
> > https://gist.github.com/rt4914/79c889211741b5b8bf7b1d60d02e636f
> > @MohamedMedhat1998 Please check that installing the packages mentioned above works for you or not?
> 
> I have done this step before. I should have mentioned that in the PR description.
> My apologies, I'll mention it right now.
> But that was not the problem, the problem is that the test cases fail because of something related to the `styles` in the `Material Design` library.
> 
> > @BenHenning @MohamedMedhat1998 I tried solving all the issues that I was facing and still there are errors. PTAL at this document: https://docs.google.com/document/d/1c96S0pDpvzlMpHHbN-oTbYZgy5KT3utkvQ-1QA7Hsfw/edit#heading=h.tb62cg3qxutu
> 
> The link asks for permission to enter.
> image

@MohamedMedhat1998 I have updated the link. https://docs.google.com/document/d/1c96S0pDpvzlMpHHbN-oTbYZgy5KT3utkvQ-1QA7Hsfw/edit?usp=sharing

**Comment by BenHenning** [comment]
Please re-assign to me once you need my input again.

**Comment by MohamedMedhat1998** [comment]
The **solution** is to use a `ThemedContext` instead of the regular `Context`. So, instead of  
```
val context = InstrumentationRegistry.getInstrumentation().targetContext
val view = LayoutInflater.from(context).inflate(R.layout.admin_auth_activity, null, false)
```
we should write
```
val context = InstrumentationRegistry.getInstrumentation().targetContext
val themedContext = ContextThemeWrapper(context, R.style.AppTheme)
val view = LayoutInflater.from(themedContext).inflate(R.layout.activity_main, null, false)
```
Where `R.style.AppTheme` is a child of `Theme.MaterialComponents`.
[Reference](https://github.com/facebook/screenshot-tests-for-android/issues/253)

**Pull request closed without merging**
