### PR TITLE
Fix part of #4470: Save state of pending answer on configuration change in StateFragment

### PR DESCRIPTION
**Pull request by masclot**
## Explanation

Fix part of #4470: Save state of pending answer on configuration change in StateFragment. This PR only creates the infrastructure and applies to one single answer type: SelectionInteraction. If the approach is accepted, it can then be applied to other answer types in follow-up PRs.

The state is saved in a Bundle, using onSaveInstanceState. The ViewModels are not used as they are recreated on every configuration change.

[Demo onSaveInstanceState in StateFragment.webm](https://github.com/oppia/oppia-android/assets/103062089/94e589dd-13e4-4182-ad44-2a5fa58d752b)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by masclot** [comment]
@adhiamboperes PTAL
Please note that this is a draft. I'm looking for a LGTM for the strategy. I'll add tests once I have this draft LGTM.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Hey @masclot, thanks for putting this up.

While this is a good start, I am wondering if there is a way to do this without passing the entire Bundle first to the presenter then to the viewmodel?

An approach I saw in #4668 is to use a proto model to hold the answer, and onCreateView(), pass this proto to the presenter and subsequently to the view model.
This has the advantage that we can define keys for various information we want to restore, and we will retrieve them as needed, and only pass to the viewmodel information that is relevant.

I have previously experienced scenarios where a bundle is too large and that causes an app crash.

**Comment by masclot** [comment]
> Hey @masclot, thanks for putting this up.
> 
> While this is a good start, I am wondering if there is a way to do this without passing the entire Bundle first to the presenter then to the viewmodel?
> 
> An approach I saw in #4668 is to use a proto model to hold the answer, and onCreateView(), pass this proto to the presenter and subsequently to the view model.
> This has the advantage that we can define keys for various information we want to restore, and we will retrieve them as needed, and only pass to the viewmodel information that is relevant.
> 
> I have previously experienced scenarios where a bundle is too large and that causes an app crash.

I'm not sure I understand. I see two options:

The entire thing needs to be stored in a Bundle (it is a requirement of onSaveInstanceState), so if the Bundle is too big, the app will crash. If we use a protocol buffer as an intermediate data format, that's fine to me, but please take into account that we are doubling the memory footprint.


Alternatively, if what you're saying is to not store the data in the Bundle, but to use onSaveInstanceState as a signal to store the data in another medium, be it memory or disk, this approach has the following problems from the top of my head:
- onSaveInstanceState must run on UI thread. You cannot do IO there. If the data is saved to disk, it must be scheduled to a background thread and then there is no guarantee the OS will allow it to run.
- if storing the data in memory, then we are basically either rewriting ViewModels (which I wouldn't do) or creating a new ViewModel to store the data of the other ViewModels (in the right way this time). ViewModels are faster than Bundles, but cover less cases than onSaveInstanceState as Ben explained.

Do you have any other option in mind?

**Comment by adhiamboperes** [comment]
> > Hey @masclot, thanks for putting this up.
> > While this is a good start, I am wondering if there is a way to do this without passing the entire Bundle first to the presenter then to the viewmodel?
> > An approach I saw in #4668 is to use a proto model to hold the answer, and onCreateView(), pass this proto to the presenter and subsequently to the view model.
> > This has the advantage that we can define keys for various information we want to restore, and we will retrieve them as needed, and only pass to the viewmodel information that is relevant.
> > I have previously experienced scenarios where a bundle is too large and that causes an app crash.
> 
> I'm not sure I understand. I see two options:
> 
> The entire thing needs to be stored in a Bundle (it is a requirement of onSaveInstanceState), so if the Bundle is too big, the app will crash. If we use a protocol buffer as an intermediate data format, that's fine to me, but please take into account that we are doubling the memory footprint.
> 
> Alternatively, if what you're saying is to not store the data in the Bundle, but to use onSaveInstanceState as a signal to store the data in another medium, be it memory or disk, this approach has the following problems from the top of my head:
> 
> * onSaveInstanceState must run on UI thread. You cannot do IO there. If the data is saved to disk, it must be scheduled to a background thread and then there is no guarantee the OS will allow it to run.
> * if storing the data in memory, then we are basically either rewriting ViewModels (which I wouldn't do) or creating a new ViewModel to store the data of the other ViewModels (in the right way this time). ViewModels are faster than Bundles, but cover less cases than onSaveInstanceState as Ben explained.
> 
> Do you have any other option in mind?

To clarify, my suggestion was to use a proto model to represent the data that we are storing in the bundle.
For example, if we had 3 different objects we wanted to store in the saved bundle, we could represent them as named objects of a class, so that when we need a particular piece of data, 1 of the 3, we would retrieve it using the key associated with it, then send it to the viewmodel for processing. This is different from the current approach in this draft, where you are passing the entire bundle to the viewmodel.

**Comment by masclot** [comment]
I changed the PR to use protos to save the state
@adhiamboperes PTAL

**Comment by adhiamboperes** [comment]
Hi @masclot, I'll look this on Wednesday.

**Comment by adhiamboperes** [comment]
Hey @masclot, I have looked into this and I am unable to approve this implementation approach for various reasons:
1.  We are saving an entire InteractionObject in the savedInstance bundle, and I don't hink this is advisable. We should instead prefer to save just the [simple information](https://proandroiddev.com/customizing-the-new-viewmodel-cf28b8a7c5fc) necesarry to restore the UI such as the selected item ids, etc. 
2. I have read up a bit on this and there seems to be a Saved State module for viewmodels that we can use, which sounds much simpler to me, and it is not clear to me why the issue description discourages using viewmodels. I am not sure if @vrajdesai78 considered the use of the [Savedstate](https://developer.android.com/jetpack/androidx/releases/savedstate) library. I would also like to know some examples of screens with multiple interactions.
3. Overall, I think this should be shelved until we can support the decision to use savedInstance as the best approach here.
I am going to unassign you from this issue for now.

Aside from the above, I think your overall approach was good. Thanks!

**Comment by masclot** [comment]
> 1. We are saving an entire InteractionObject in the savedInstance bundle, and I don't hink this is advisable. We should instead prefer to save just the [simple information](https://proandroiddev.com/customizing-the-new-viewmodel-cf28b8a7c5fc) necesarry to restore the UI such as the selected item ids, etc.

We are only storing the selected item ids. InteractionObject is a one-of. This object is the same that is sent on submit so it contains only what's needed. I could create another object just for saving the state, but my intuition tells me that the new object will end up looking very similar to InteractionObject, if not equal, once we add support for the other interaction types. That said, if you prefer that, I am also fine with it.

**Comment by masclot** [comment]
> 2\. I have read up a bit on this and there seems to be a Saved State module for viewmodels that we can use, which sounds much simpler to me, and it is not clear to me why the issue description discourages using viewmodels. I am not sure if @vrajdesai78 considered the use of the [Savedstate](https://developer.android.com/jetpack/androidx/releases/savedstate) library. I would also like to know some examples of screens with multiple interactions.

First time I hear about SavedState in ViewModels. Thanks for sharing!
Remember though that we are not using ViewModels properly in recently played UI: the ViewModels are recreated new, every time by Dagger, so the SavedState library won't help.

The only workaround I see, without fixing the current ViewModel usage, is to create yet another ViewModel, non-dagger, just for the saved state, and have the new ViewModel and the old ones talk to each other. I think this would be confusing and probably more complicated than onSavedInstanceState.

**Comment by masclot** [comment]
> 3\. Overall, I think this should be shelved until we can support the decision to use savedInstance as the best approach here.
>     I am going to unassign you from this issue for now.

Ok. I'm interested in knowing the result and motivation of the final decision, even if the issue is assigned to someone else.

**Comment by adhiamboperes** [comment]
> > 3. Overall, I think this should be shelved until we can support the decision to use savedInstance as the best approach here.
> > I am going to unassign you from this issue for now.
> 
> Ok. I'm interested in knowing the result and motivation of the final decision, even if the issue is assigned to someone else.

Let's discuss this a bit more at the meeting.

**Comment by adhiamboperes** [comment]
> > 3. Overall, I think this should be shelved until we can support the decision to use savedInstance as the best approach here.
> > I am going to unassign you from this issue for now.
> 
> Ok. I'm interested in knowing the result and motivation of the final decision, even if the issue is assigned to someone else.



@Vishwajith-Shettigar, could you please summarize the solution you created for this issue?

**Comment by Vishwajith-Shettigar** [comment]
@masclot, @adhiamboperes, to retain user input when device configurations change, I used savedInstanceState. Whenever the user enters input, we store it in savedInstanceState before the activity gets destroyed and use it after the activity is recreated. We only store necessary input data along with the answer error category. For text-based inputs(eg:- number, fraction, ratio, math expressions, text inputs), we store only the text, and for selection-based inputs, we store only the index of the selected items.

Here is the structure:
```
// Represents the state of item selection answers that the user has selected.
message ItemSelectionAnswerState {
  // List of selected item indices.
  repeated int32 selected_indexes = 1;
}

// Represents the user's answer state, retained across configuration changes.
message UserAnswerState {
  // Represents the last error state.
  AnswerErrorCategory answer_error_category = 1;

  // Type of answer input:
  oneof answer_input_type {
    // User's selection for selection input interactions.
    ItemSelectionAnswerState item_selection = 2;
    // Raw answer entered by the user in text-based interactions.
    string text_input_answer = 3;
  }
}

```

Saved answers will be removed when the user hits the submit button to ensure that no saved data will persist into upcoming interactions. This also ensures that no data pile-up occurs.

**Pull request closed without merging**
