### PR TITLE
Add LifecycleOwner support to BindableAdapter

### PR DESCRIPTION
**Pull request by BenHenning**
This PR introduces support for automatically setting the lifecycle owner for bindings inflated through ``BindableAdapter``. Without this functionality, it's tricky to properly set lifecycle owner (which is needed when binding ``LiveData``s to recycler view item layouts, otherwise bugs like the one described in https://github.com/oppia/oppia-android/pull/2392#issuecomment-765042367 are possible).

Some notes about this PR:
- I removed example.proto in favor of a sealed class test model which also supports LiveData (which was needed for the new tests)
- I found a way to remove the test activity/fragment from the top-level application component & activity components. This isn't quite sufficient to avoid packaging the test activities in the production build, but it's a really nice step along the way. This might help greatly simplify modularizing the Bazel libraries (FYI @fsharpasharp). Unfortunately, it required a bunch of rewiring in the test Dagger arrangement (note that I think this is the first time we've tried overriding the subcomponents in the graph).
- I verified that the new adapter tests pass on both Espresso & Robolectric
- I verified that the relevant new tests properly fail without the lifecycle binding built into the adapter (which triggers the bug seen in #2392)
- The runtime crash for when the weak reference is lost cannot be trivially tested since it depends too much on JVM/Dalvik to clean up the reference, so I'm opting out of trying to test that for now
- I noticed some comment/styling issues in ``BindableAdapter`` & ``BindableAdapterTest``, so I went ahead and cleaned those up
- I'm a little sad about using inheritance for the ``BindableAdapter`` builder classes, but it seemed like the best way to avoid redundant arrangement for the lifecycle owner

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
Overall changes look good but I am not able run the test cases.
`Error: No local test cases found.`

Things tried:
Rebuild the entire project.
Invalidate Caches and Restart.

@anandwana001 Do you face the same? Anything else that I can try to run tests?

**Comment by FareesHussain** [comment]
> Overall changes look good but I am not able run the test cases.
> `Error: No local test cases found.`
> 
> Things tried:
> Rebuild the entire project.
> Invalidate Caches and Restart.
> 
> @anandwana001 Do you face the same? Anything else that I can try to run tests?

@rt4914 I had the same issue but once I installed the app and re-run the test (BindableAdapterTest) it works

**Comment by BenHenning** [comment]
Hmm @rt4914 not sure why that would happen. The PR is just changing existing tests, so I don't think that's tied to the PR itself.

**Comment by rt4914** [comment]
> > Overall changes look good but I am not able run the test cases.
> > `Error: No local test cases found.`
> > Things tried:
> > Rebuild the entire project.
> > Invalidate Caches and Restart.
> > @anandwana001 Do you face the same? Anything else that I can try to run tests?
> 
> @rt4914 I had the same issue but once I installed the app and re-run the test (BindableAdapterTest) it works

@FareesHussain Tried doing this. Did not work. I tried this on Pixel 3A emulator and Pixel 3 real device. Also, I tried to run individual test case too and that too had same error.

**Comment by rt4914** [comment]
@BenHenning I did try this again as per my above comment but its still giving me same error. Any suggestions?
Also, if @anandwana001 and @vinitamurthi can approve this then based on their judgement I can approve this PR.

**Review by jcqli — APPROVED** [review]
Looks good to me

I also can't run the tests with `No tests were found` but I've always been having issues with Espresso tests.

**Comment by anandwana001** [comment]
Screenshot 2021-01-27 at 11 01 25

Screenshot 2021-01-27 at 11 18 15


working for me

**Review by anandwana001 — APPROVED** [review]
LGTM

**Review by rt4914 — APPROVED** [review]
Yeah, I have found that the issue is with my project setup.

**Comment by BenHenning** [comment]
Thanks everyone!

**Comment by BenHenning** [comment]
@vinitamurthi PTAL as codeowner. :)

**Review by vinitamurthi — APPROVED** [review]
LGTM as codeowner

**Review by FareesHussain — CHANGES_REQUESTED** [review]
@BenHenning please check the conflicts.

**Comment by BenHenning** [comment]
Done! Should be resolved now. Just waiting on CI checks to merge.

**Pull request merged**
