### PR TITLE
Fix #3141 Moved OptionsFragmentTest.kt from unit test folder to Instrumentation test folder

### LINKED ISSUE #3141: Shift Instrumentation test written in Unit Test directory for OptionsFragmentTest
**Describe the bug**
There are some test cases written in `src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt` which are instrumentation test but the file exist in unit test folder. 

**Expected behavior**
Look for the instrumentation tests in this file and shift them to the instrumentation test directory. 

**Additional context**
[How to test on Espresso?](https://developer.android.com/codelabs/advanced-android-kotlin-training-testing-basics#4)

**How to send a Pull Request for this Issue**
Add screenshot showing shifted tests are passing on Espresso.

### PR DESCRIPTION
**Pull request by Arnold2381**
## Explanation
Fixes #3141 
Screenshot of all the instruments tests passing.
image
Screenshot of the unit test passing
image

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
@Arnold2381 Thanks for the PR
Please follow this section on getting PR review from the codeowners - https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

Also, please follow the format given in the first point in the checklist in the PR description. 

Please add the screenshot of the Espresso test result. The current screenshot is of Robolectric.

**Comment by Arnold2381** [comment]
@anandwana001 when I am running instrumentation tests I am getting this

image

**Comment by FareesHussain** [comment]
@Arnold2381 use an emulator with api 28 for instrumentation tests.

**Comment by Arnold2381** [comment]
@FareesHussain thank you!! will try that.

**Comment by Arnold2381** [comment]
@FareesHussain same results.

**Comment by FareesHussain** [comment]
Are you running the tests on a real device?

**Comment by Arnold2381** [comment]
> Are you running the tests on a real device?

No. After you told me to run it on emulator, I ran it on emulator but got the same results.

**Comment by FareesHussain** [comment]
can you add the screen shot to the error again

**Comment by Arnold2381** [comment]
> can you add the screen shot to the error again

image

**Comment by FareesHussain** [comment]
I'm not sure how to fix this.
can you check if the app is installed in the emulator

**Comment by Arnold2381** [comment]
Yes it is, i first installed the app and then ran the tests.

**Comment by anandwana001** [comment]
Could you try clean project, then rebuild it, and then run the test?

**Comment by Arnold2381** [comment]
I tried that too yesterday itself. Nothing worked. 
https://stackoverflow.com/questions/22582021/android-studio-no-tests-were-found
I almost tried everything in this, nothing worked.

**Comment by anandwana001** [comment]
ah, you had shifted the instrumentation test file to the unit test directory. 
Please check.

**Comment by anandwana001** [comment]
Instrumentation test - `oppia-android/app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt`
Unit test  - `oppia-android/app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt`

We don't need to shift the file, only the required tests from Unit test to Instrumentation test

**Comment by Arnold2381** [comment]
Okayy!! I will make the changes and rebase.

**Comment by Arnold2381** [comment]
@anandwana001 I didn't know how to assign you back the PR, couldn't see the option anywhere.

**Comment by anandwana001** [comment]
@Arnold2381 closing this PR due to force push

**Pull request closed without merging**
