### PR TITLE
Fix #1042 Status bar color for pre-lollipop versions

### LINKED ISSUE #1042: Status bar color fix for pre-lollipop versions
Reference: https://stackoverflow.com/questions/22192291/how-to-change-the-status-bar-color-in-android/26215844#26215844

The status bar color in various android screens is inconsistent. Update status bar color code as per the mocks and spreadsheet:
https://docs.google.com/spreadsheets/d/1XphP6nWoUdOZn9pY2kdgfqMWfJjMfKMb98MXM5rp2HY/edit#gid=0
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/

Comment Reference: https://github.com/oppia/oppia-android/pull/1023#issuecomment-623466182

### PR DESCRIPTION
**Pull request by prathameshbhalekar**
## Explanation
Fixes #1042. I have made changes to the util.statusbarcolor file. I have also added a view in xml files of fragments which required changes. I have also added passed the view in the chengestatubarcolor method in the presenters of above mentioned fragments. I inspected the code with android studio and the rest are the changes from that process. .

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by prathameshbhalekar** [comment]
@nikitamarysolomanpvt I created new pull request. Can you please check it out?

**Comment by aggarwalpulkit596** [comment]
@mschanteltc sure go ahead.

**Comment by mschanteltc** [comment]
> @mschanteltc sure go ahead.

Is this tag meant for me?

**Comment by rt4914** [comment]
> > @mschanteltc sure go ahead.
> 
> Is this tag meant for me?

@mschanteltc There is some mistake. As I don't see any particular question directed to you. So. i think you can avoid this. Thanks.

**Comment by nikitamarysolomanpvt** [comment]
> @nikitamarysolomanpvt I created new pull request. Can you please check it out?

@prathameshbhalekar Could you please put the screenshots with the device specifications that you used for testing. When i checked it is not working properly.

**Comment by rt4914** [comment]
Closing this PR as there has been no updates on this PR from contributor.

**Pull request closed without merging**
