### PR TITLE
Fix #2271: [RTL] High-fi Topic Revision Cards

### LINKED ISSUE #2271: [RTL] High-fi Topic Revision Cards
`Topic Revision Tab` needs RTL support as shown in below screen.
TP (Revision)-RTL

**Do not focus on tabs RTL in this issue.**

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by Luffy18346**
## Explanation

Fixes #2271 : Resolves RTL Issue in High-fi Topic Revision Cards
Earlier the RTL View in Topic Revision Cards was not appropriate. This PR resolved the issue.

## Screenshots

(1) Screenshot with even number of cards 

WhatsApp Image 2020-12-16 at 11 34 33 PM

(2) Screenshot with odd number of cards

WhatsApp Image 2020-12-17 at 12 01 15 AM

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Luffy18346** [comment]
Screenshots 

WhatsApp Image 2020-12-16 at 11 34 33 PM

**Comment by rt4914** [comment]
Assigning @FareesHussain for a PR Review.

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
> LGTM, thanks.

Thanks @FareesHussain

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by BenHenning — APPROVED** [review]
Thanks @Luffy18346! This is definitely a case where having screenshot tests would have been very nice. :(

**Pull request merged**
