### PR TITLE
Fix #1767: Revert "Fixes part of #40 & #42: Generalisation Highfi Mobile Portrait + Landscape - Buttons"

### LINKED ISSUE #1767: Trying to input answers in landscape is impossible due to keyboard automatically dismissing.
**Describe the bug**
When you try to input anything in landscape, the keyboard automatically dismisses.

**To Reproduce**
1. Open the app
2. Navigate to the prototype exploration
3. Rotate to landscape
4. Continue to the second state (fractions)
5. Select the fraction input box
6. Observe the soft keyboard open
7. Observe the soft keyboard immediately close

**Expected behavior**
The soft keyboard shouldn't be automatically closing.

**Screen recording**
auto_close_keyboard

**Device**
- Device: Pixel XL
- SDK version: SDK 29

**Additional context**
This is definitely a regression since StateFragmentTest was passing 2 weeks ago (the last time I tried these scenarios).

### PR DESCRIPTION
**Pull request by BenHenning**
Reverts oppia/oppia-android#1653
Fixes #1767

This is a clean revert.

### CODE REVIEW

**Comment by BenHenning** [comment]
We will need to reopen #40 and #42. @rt4914 are there any aspects that were fixed in the original PR that will block alpha?

**Comment by rt4914** [comment]
> We will need to reopen #40 and #42. @rt4914 are there any aspects that were fixed in the original PR that will block alpha?

@BenHenning This will block alpha but it should be doable in less time now because I have mentioned margins/paddings in comments in each button files which makes it easy to implement.

**Comment by BenHenning** [comment]
@rt4914 can you clarify why this blocks alpha? In general, most hi-fi tasks don't block alpha unless they inhibit the core user experience.

**Comment by rt4914** [comment]
> @rt4914 can you clarify why this blocks alpha? In general, most hi-fi tasks don't block alpha unless they inhibit the core user experience.

The reason behind mentioning that this will block alpha is because all other items like `ContentView`, `FeedbackView`, `Interactions` are already done and because of which the buttons UI might look a bit off.

But I ran the app and saw it does not look that bad without this PR. So it **won't block alpha**

Screenshot_1599043146

**Comment by BenHenning** [comment]
Thanks for clarifying @rt4914. That sounds good.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by BenHenning** [comment]
Thanks @rt4914!

**Pull request merged**
