### PR TITLE
Fix #2989, part of #1274, part of #2951: Add tests for TestCoroutineDispatcher implementations

### LINKED ISSUE #2989: Create a BUILD.bazel file for the time package in the testing module
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## Task

1. Create a BUILD.bazel file in

`testing/src/main/java/org/oppia/android/testing/time`

2. Define the kt_android_library library/libraries

Based on the imports in the Kotlin files, add the required third_party dependencies to make the libraries build. Check the Useful links section for a list of third_party dependencies. You will also need to add the non third_party dependencies.

3. Remove the directory from the srcs glob in the testing library (testing/BUILD.bazel).

Create a variable to collect all the migrated packages in one place. See https://github.com/oppia/oppia-android/blob/develop/utility/BUILD.bazel for an example of this.
 
4. Add the libraries to the list of deps dependencies in the targets that require the library

You will have to set the apropriate visbility. See the list of visibilities in the link below. Since this is part of the testing module, the apropriate visibility should be oppia_testing_visibility.

5. Clean up any unused deps dependencies

6. Verify that the app builds

## Useful links

- [BUILD.bazel files](https://github.com/oppia/oppia-android/search?q=filename%3ABUILD.bazel&type=code)
- [Visibilities](https://github.com/oppia/oppia-android/blob/76dc13dba3ad77aecd2218a5372949d6551f12fe/BUILD.bazel)
- [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl)

### PR DESCRIPTION
**Pull request by BenHenning**
Fix part of #1274: add tests for TestCoroutineDispatchers
Fix #2989: modularize time package in testing module
Fix part of #2951: this establishes a properly enforced contract for TestCoroutineDispatchers prior to switching out the implementation with custom executors (a prerequisite for ensuring Retrofit can be properly synchronized in test environments)

## Explanation
This PR ultimately aims to prepare for #2951 by ensuring test coroutine dispatchers are thoroughly tested before switching out the dispatcher's implementation with a new one.

However, in order to even add tests for these implementations a bunch of other work & considerations were needed:
- The robolectric implementation for TestCoroutineDispatcher had some known race conditions in it. These were addressed while debugging unrelated problems, but actual issues in the implementation were also fixed to ensure the implementation was fulfilling TestCoroutineDispatcher's defined contract
- The espresso implementation for the TestCoroutineDispatcher had some issues around time tracking that needed to be addressed
- Neither implementations needed to actually be DelayControllers, so I went ahead and cleaned up that code
- Some lack of clarity in TestCoroutineDispatcher's defined API led to an interesting scenario when writing tests wherein I wasn't sure whether the observed failing test was correctly failing. This ended up with a slight clarification that certain behaviors (particularly around whether a task is considered completable/pending) are actually implementation-specific.
- I wanted to share tests across the two implementations which introduces a new test base pattern. I'm not keen on this, but it seems to be the only approach. We should **only** use test inheritance for this purpose, and **never** for sharing functionality.
- The last point required introducing a shared test library to hold common tests; to make this cleaner, I went ahead and introduced our first separate Bazel test targets
- I split up the testing package module by moving the coroutine bits underneath a new threading subpackage
- Organizing the new threading subpackage required two more changes: new robolectric and time subpackages under the testing module to avoid circular dependencies
- Note that the Espresso-specific implementation is particularly complex: it's running in Robolectric with real threads which is why certain liberties needed to be taken to ensure stability (such as ``Thread.sleep`` & infinite while loops). These are carefully built, but could potentially introduce issues in the future.
- This PR led to the discovery of #3052.

The new Espresso-specific and Robolectric-specific test suites were shown to be stable across 1000 runs locally: both passed with 0 failures across 1000 runs.

Note that this PR does not introduce tests for TestCoroutineDispatchers. That can happen in a later PR as it's not necessary for the Retrofit work.

### CODE REVIEW

**Comment by BenHenning** [comment]
Correction to commit message: https://github.com/oppia/oppia-android/pull/3061/commits/dc8be268f37a8c839cce8e57298dfc091ccec184 should be indicating that I moved the CoroutineExecutorService + test to be part of the new threading package.

Also, waiting to assign based on a local Gradle run of app module tests to make sure they're passing.

**Comment by BenHenning** [comment]
*sigh* the Gradle build failed. Digging into why.

**Comment by BenHenning** [comment]
Hmm odd. It worked when I tried it a second time. *Shrug* that's good enough for me to assign this out & see what CI says.

**Comment by BenHenning** [comment]
@rt4914 / @vinitamurthi / @anandwana001 / @fsharpasharp PTAL at your respective codeowners files + Bazel files for Jan.

**Comment by BenHenning** [comment]
The test failure is due to the compute test target issue per #2691.

**Review by rt4914 — APPROVED** [review]
LGTM for code-owner files.

**Review by fsharpasharp — APPROVED** [review]
BUILD files look good to me!

**Review by anandwana001 — APPROVED** [review]
Test files lgtm

**Comment by BenHenning** [comment]
Thanks all! @vinitamurthi PTAL when you get a chance.

**Review by vinitamurthi — APPROVED** [review]

**Comment by vinitamurthi** [comment]
Tests seem to be failing for bazel

**Comment by BenHenning** [comment]
@vinitamurthi see https://github.com/oppia/oppia-android/pull/3061#issuecomment-816363873. These is a known failure unrelated to this change.

**Comment by BenHenning** [comment]
Thanks all for the reviews! Syncing then merging this.

**Comment by BenHenning** [comment]
The Gradle & Bazel fixes are both build errors due to changes in develop. We should be able to rely on Gradle passing to merge this PR (no need to wait for the full Bazel test suite).

**Pull request merged**
