### PR TITLE
(Should fix) #3789: Fix flaky test retry mechanism for Bazel CI

### LINKED ISSUE #3789: Sharded Bazel tests are build-flaky in CI
The issue described in #3759 is not properly mitigated in CI and is causing issues (full runs seem to always have at least 1 failure due to this build error). From looking at the code, I think the retry mechanism isn't being set up correctly.

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

(Should fix) #3789

See https://github.com/oppia/oppia-android/issues/3789#issuecomment-937111144 for context on the root issue. This PR fixes the retry mechanism by temporarily disabling early exit when performing the Bazel buld retry, and then re-enables it & conditionally exits with error code if the _last_ command fails (since Bazel should guarantee that if any of the iterations result in a passing build, all subsequent ones should).

Note that actually fixing this does mean that legitimate build failures will result in spammier output since they'll be retried multiple times, but that should probably be fine until we can fix the Jettifier issue long-term (#3759).

Finally, I can't actually seem to verify that this is working until the PR is merged (I tried multiple times in #3790 to trigger a scenario in the PR, but couldn't). I think it's reasonable to merge this as-is, and then close #3789 once it's been verified (I'm intentionally not linking the PR & issue for this reason since we can't be sure it's fixed until a few days after merging).

For partial verification:
- See https://github.com/oppia/oppia-android/pull/3908/checks?check_run_id=3820241376#step:15:824 for demonstrating that the retry mechanism is actually running when things are passing
- See https://github.com/oppia/oppia-android/pull/3908/checks?check_run_id=3820789138#step:15:415 for retry occurring with a build failure (& that the failure repeated 5 times due to retry)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A

### CODE REVIEW

**Comment by BenHenning** [comment]
Reopening to trigger run-all-tests workflow.

**Comment by BenHenning** [comment]
Follow-up: I can't seem to unlink #3789 so I'll need to manually reopen it.

**Comment by BenHenning** [comment]
TODO script failure is probably due to an out-of-date base branch. Syncing to see if CI now passes.

Edit: it seems to be passing now.

**Review by anandwana001 — APPROVED** [review]
As this can be verified after few days of merging so this LGTM and we can merge it.

**Comment by BenHenning** [comment]
Thanks @anandwana001. Merging now.

**Pull request merged**
