### PR TITLE
Fix part of #1587: Made intent keys consistent in the drawer, topic and testing packages in the app module

### PR DESCRIPTION
**Pull request by janewaitara**
## Explanation

Fixes part of #1587 : Made intent keys consistent in the drawer, topic and testing packages in the app module.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by janewaitara** [comment]
@rt4914 PTAL

**Comment by janewaitara** [comment]
Please recommend how I can solve the roboelectric tests that are failing.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
The test is failing due to changes in TopicActivity, but in the test `testProfileProgressFragment_clickFirstStory_opensTopicActivity` the recorded intent is the earlier one. 

```
IntentMatcher: has extras: has bundle with: key: is "TopicActivity.topic_activity_topic_id" value: is "test_topic_id_0"

Matched intents:[]

Recorded intents:
-Intent { cmp=org.oppia.android/.app.topic.TopicActivity (has extras) } handling packages:[[org.oppia.android]], extras:[Bundle[{NavigationDrawerFragment.navigation_profile_id=0, TopicActivity.topic_id=test_topic_id_0, TopicActivity.story_id=test_story_id_0}]])
```

Look for all the test using these functions from TopicActivity, are they passing on Espresso and Robolectric both or not. 

```kotlin
fun getProfileIdKey(): String {
    return NAVIGATION_DRAWER_PROFILE_ID_ARGUMENT_KEY
}

fun getTopicIdKey(): String {
    return TOPIC_ACTIVITY_TOPIC_ID_EXTRA_KEY
}

fun getStoryIdKey(): String {
    return TOPIC_ACTIVITY_STORY_ID_EXTRA_KEY
}
```

**Review by rt4914 — CHANGES_REQUESTED** [review]
@janewaitara The naming is incorrect.

For `KEY_NAVIGATION_PROFILE_ID` you have named it correctly as `NAVIGATION_DRAWER_PROFILE_ID_ARGUMENT_KEY` which makes sense considering that this const is getting used in various other files and therefore the file name is needed.

But other key renaming are incorrect. For example:
`KEY_AUDIO_FRAGMENT_TEST_PROFILE_ID` is incorrect because you are mentioning the file name in the const name in which is not the convention suggested in the issue.
It should be renamed to:
`INTERNAL_PROFILE_ID_EXTRA_KEY` = "AudioFragmentTestActivity.internal_profile_id"

Ditto for other key changes.

**Comment by rt4914** [comment]
@janewaitara Keep the **Assignees** section up to date. Reference: https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

**Comment by rt4914** [comment]
Closing this now.

**Pull request closed without merging**
