### PR TITLE
Fix #2280 : Added RTL support to admin control profile details screen

### LINKED ISSUE #2280: [RTL] High-fi Admin Controls Profile Details
` Admin Controls Profile Details` needs RTL support as shown in below screen.
AC EP (Chantel’s Profile) – RTL

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

https://github.com/oppia/oppia-android/wiki/RTL-Guidelines

### PR DESCRIPTION
**Pull request by ForgottenProgramme**
## Explanation
Fixes #2280 
Added RTL support to the profile_edit_activity.xml file . 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Screenshots:

Mobile Portrait 
mobile_port

Mobile Landscape:
mobile_land

Tablet Portrait:

tab_port

Tablet Landscape:

tab_land

### CODE REVIEW

**Comment by ForgottenProgramme** [comment]
@rt4914 
Please have a look?

**Review by FareesHussain — CHANGES_REQUESTED** [review]
@ForgottenProgramme please add rtl for the id `profile_edit_allow_download_sub`

**Comment by ForgottenProgramme** [comment]
> @ForgottenProgramme please add rtl for the id `profile_edit_allow_download_sub`

Yes, yes. I just noticed. 
Doing that.

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

For my reference
Screenshot_1608529539
Screenshot_1608529545

**Comment by rt4914** [comment]
Thanks @FareesHussain and @ForgottenProgramme

**Comment by BenHenning** [comment]
Hi! Sorry, will need to take a look at this tomorrow my time.

**Comment by BenHenning** [comment]
This is pending per the discussion in #2287 since I think it's the same issue (specifically that we might not actually need this).

**Comment by BenHenning** [comment]
Handing this over to @rt4914 to keep an eye on per the discussion in #2287.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Blocked on #2330

**Review by rt4914 — CHANGES_REQUESTED** [review]
@ForgottenProgramme We don't need `textAlignment="viewStart"`
You can remove this.

The reason why we need this is because of `Force RTL` from developer options.
But instead we should check the app on `pseudoLocale` something like Arabic.
To test this correctly merge your branch with latest `develop` and follow steps mentioned in this https://github.com/oppia/oppia-android/wiki/RTL-Guidelines and based on the result update your xml files.

In general you can remove `textDirection="locale"` and test app for `cibarA [XB]` language and fix UI as per your requirements.

Video Reference: https://www.youtube.com/watch?v=gc5HeuksMhc&list=PLoDt3UyLUtcgZLxUPcmyaJIajXfO62I7M&index=1

**Review by FareesHussain — CHANGES_REQUESTED** [review]
@ForgottenProgramme the only changes required are for the Toolbar text and the Profile Name
Adding Screenshot for Reference
image

**Comment by ForgottenProgramme** [comment]
revert

Except the username (wherever it appears), everything seems to follow RTL when pseudoLocalesEnabled is made true.

**Comment by ForgottenProgramme** [comment]
po

For example, here.

**Comment by FareesHussain** [comment]
@ForgottenProgramme Then you just need to make changes for the Toolbar 
as RTL doesn't work for dynamic or hardcoded strings

**Comment by Luffy18346** [comment]
Hi @ForgottenProgramme, are you still working on this?

**Comment by ForgottenProgramme** [comment]
@Luffy18346 , I am  sorry for the very late response. I haven't been active.
If you have already worked around some solution, please go ahead implement and you can take up from here.

**Comment by rt4914** [comment]
> @Luffy18346 , I am sorry for the very late response. I haven't been active.
> If you have already worked around some solution, please go ahead implement and you can take up from here.

@ForgottenProgramme Akash Koradia (@Luffy18346 ) won't be working on this. That being said if you want to un-assign yourself, feel free to do that.

**Comment by rt4914** [comment]
Closing this PR for now.

**Pull request closed without merging**
