### PR TITLE
Fix #2642: Fix data module tests and make them run on Github Actions

### LINKED ISSUE #2642: Fix data module tests & add them to CI
At some point, we deleted the TestMessage proto that was used specifically in tests without updating PersistentCacheStoreTest. That means that test is currently failing, and needs to be fixed. This also illustrates the need to add our data module tests to our CI workflow. This issue is tracking:
1. Running all [data](https://github.com/oppia/oppia-android/tree/develop/data) module tests locally & noting which ones are failing
2. Fix all of the failing tests (e.g. [PersistentCacheStoreTest](https://github.com/oppia/oppia-android/blob/develop/data/src/test/java/org/oppia/android/data/persistence/PersistentCacheStoreTest.kt) & any others that are failing)
3. Update our [CI workflow](https://github.com/oppia/oppia-android/blob/develop/.github/workflows/main.yml#L48) to also run the data module tests

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation

Fixes #2642:
Fixed `PersistentCacheStoreTest.kt` and verified all other test cases are passing and added them to CI.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

<details>

<summary>Screenshots of all tests passing - </summary>

*NetworkInterceptorTest*

Screenshot from 2021-03-06 12-31-24

*MockTopicTest*

Screenshot from 2021-03-06 12-31-03

*MockSubTopicTest*

Screenshot from 2021-03-06 12-30-42

*MockStoryTest*

Screenshot from 2021-03-06 12-30-26

*MockQuestionPlayerTest*

Screenshot from 2021-03-06 12-30-08

*MockExplorationTest*

Screenshot from 2021-03-06 12-29-44

*MockConceptCardTest*

Screenshot from 2021-03-06 12-29-26

*MockClassroomTest*

Screenshot from 2021-03-06 12-29-03

*PersistentCacheStoreTest*

Screenshot from 2021-03-06 12-28-20

</details>

### CODE REVIEW

**Comment by prayutsu** [comment]
@BenHenning PTAL.

**Review by BenHenning — APPROVED** [review]
Nice--thanks @prayutsu!

**Comment by BenHenning** [comment]
It appears this introduced #2870 and will need to be reverted.

**Comment by FareesHussain** [comment]
```
farees@elementary-os:~/opensource/oppia-android$ sudo ./gradlew --full-stacktrace :data:testDebugUnitTest
[sudo] password for farees:     
Downloading https://services.gradle.org/distributions/gradle-6.8-bin.zip
......................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-6.8-bin/1jblhjyydfkclfzx1agp92nyl/gradle-6.8-bin.zip to /root/.gradle/wrapper/dists/gradle-6.8-bin/1jblhjyydfkclfzx1agp92nyl
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-6.8-bin/1jblhjyydfkclfzx1agp92nyl/gradle-6.8/bin/gradle

Welcome to Gradle 6.8!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
WARNING: The following project options are deprecated and have been removed: 
android.databinding.enableV2
Databinding v1 is removed.


Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :data
WARNING: The following project options are deprecated and have been removed: 
android.databinding.enableV2
Databinding v1 is removed.


Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :domain
WARNING: The following project options are deprecated and have been removed: 
android.databinding.enableV2
Databinding v1 is removed.


Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :testing
WARNING: The following project options are deprecated and have been removed: 
android.databinding.enableV2
Databinding v1 is removed.


Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
testing: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.google.auto.service:auto-service:1.0-rc4'.

> Configure project :utility
WARNING: The following project options are deprecated and have been removed: 
android.databinding.enableV2
Databinding v1 is removed.


Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Task :utility:kaptDebugKotlin
Note: [1] Wrote GeneratedAppGlideModule with: []dmlib-26.6.1.jar
> Task :testing:kaptDebugKotlin
Annotation processors discovery from compile classpath is deprecated.
Set 'kapt.includeCompileClasspath = false' to disable discovery.
Run the build with '--info' for more details.

> Task :testing:compileDebugKotlin
w: /home/farees/opensource/oppia-android/testing/src/main/java/org/oppia/android/testing/FakeSystemClock.kt: (101, 16): Type mismatch: inferred type is Any? but Any was expected
w: /home/farees/opensource/oppia-android/testing/src/main/java/org/oppia/android/testing/OppiaTestRunner.kt: (86, 12): Type mismatch: inferred type is Any? but Any was expected
w: /home/farees/opensource/oppia-android/testing/src/main/java/org/oppia/android/testing/TestCoroutineDispatchersRobolectricImpl.kt: (158, 14): Type mismatch: inferred type is Any? but Any was expected

> Task :data:kaptDebugUnitTestKotlin
Annotation processors discovery from compile classpath is deprecated.
Set 'kapt.includeCompileClasspath = false' to disable discovery.
Run the build with '--info' for more details.

> Task :data:compileDebugUnitTestKotlin
w: /home/farees/opensource/oppia-android/data/src/test/java/org/oppia/android/data/persistence/PersistentCacheStoreTest.kt: (117, 33): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'

> Task :data:testDebugUnitTest

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_updated_noInMemoryCacheUpdate_newCache_newObserver_observesNewVal PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testMultipleCaches_oneUpdates_newCacheSameNameDiffInit_observesUpdatedValue PASSED

org.oppia.android.data.backends.test.MockExplorationTest > testExplorationService_usingFakeJson_deserializationSuccessful PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_registerObserver_updateAfter_observerNotifiedOfNewValue PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_update_existingObserver_clear_isNotifiedOfClear PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_update_clear_resetsCacheToInitialState PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_clear_initialState_keepsCacheStateTheSame PASSED

org.oppia.android.data.backends.test.MockSubtopicTest > testSubtopicService_usingFakeJson_deserializationSuccessful PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_nonDefaultInitialState_toLiveData_loaded_providesCorrectInitialVal PASSED

org.oppia.android.data.backends.test.MockTopicTest > testTopicService_usingFakeJson_deserializationSuccessful PASSED

org.oppia.android.data.backends.test.MockStoryTest > testStoryService_usingFakeJson_deserializationSuccessful PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testMultipleCaches_diffNames_oneUpdates_cachesRecreated_onlyOneObservesVal PASSED

org.oppia.android.data.backends.test.MockConceptCardTest > testConceptCardService_usingFakeJson_deserializationSuccessful PASSED

org.oppia.android.data.backends.test.MockQuestionPlayerTest > testQuestionPlayerService_usingFakeJson_deserializationSuccessful PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testExistingDiskCache_newObject_updateMemThenRead_primed_receivesNewVal PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_toLiveData_initialState_isPending PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testMultipleCaches_differentNames_oneUpdates_otherDoesNotObserveChange PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testNewCache_fileCorrupted_providesError PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_primed_afterStoreUpdateWithoutMemUpdate_notForced_observesOldValue PASSED

org.oppia.android.data.backends.test.MockClassroomTest > testClassroomService_usingFakeJson_deserializationSuccessful PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_updated_newCache_newObserver_observesNewValue PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testExistingDiskCache_newObject_updateNoMemThenRead_primed_receivesPrevVal PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_update_newCache_observesInitialState PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_primed_afterStoreUpdateWithoutMemoryUpdate_forced_observesNewValue PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_noMemoryCacheUpdate_updateAfterReg_observerNotNotified PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_noMemoryCacheUpdate_updateBeforeReg_observesUpdatedState PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_toLiveData_loaded_providesInitialValue PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testExistingDiskCache_newCacheObject_updateNoMemThenRead_receivesNewValue PASSED

org.oppia.android.data.persistence.PersistentCacheStoreTest > testCache_registerObserver_updateBefore_observesUpdatedStateInitially PASSED

org.oppia.android.data.backends.test.NetworkInterceptorTest > testNetworkInterceptor_withXssiPrefix_removesXssiPrefix PASSED

org.oppia.android.data.backends.test.NetworkInterceptorTest > testNetworkInterceptor_withoutXssiPrefix_removesXssiPrefix PASSED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6m 31s
99 actionable tasks: 17 executed, 82 up-to-date

```

**Pull request merged**
