### PR TITLE
Fix #5073, #5062, #5099, and part of #1723: Improve Onboarding Documentation

### LINKED ISSUE #5062: [Feature Request]: Add wiki documentation for how to pick the emulator/android version when running Espresso tests.
**Is your feature request related to a problem? Please describe.**
Developers aren't sure whether there is a recommended setup for choosing the emulator + Android version when running Espresso tests. See https://github.com/oppia/oppia-android/discussions/4868#discussioncomment-4889299.

@BenHenning provided a response [here](https://github.com/oppia/oppia-android/discussions/4868#discussioncomment-4889299) and suggested providing wiki instructions for how to pick an API/form-factor combination. This issue tracks that.

**Describe the solution you'd like**
The wiki page should have clear instructions on what setup to pick. It should provide a prescriptive path (that new contributors can use without further investigation) and list other potential options that would be valid as well.

This could perhaps go in the wiki page on testing, or possibly be part of the instructions on "how to make your PR". They should be part of an explanation of the steps that contributors need to take in order to run those tests.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### LINKED ISSUE #5073: [Feature Request]: Add instructions to the wiki for how to assign a reviewer.
### Is your feature request related to a problem? Please describe.

The wiki page https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section explains what to do when sending a PR for review. However, new contributors don't have permissions to update the assignee fields in GitHub, so the instructions aren't followable as-is.

### Describe the solution you'd like

Explain, in that section, how to add assignees in such cases (e.g. explaining how to leave a comment like "@reviewer PTAL" so that Oppiabot assigns the reviewer for them).

### LINKED ISSUE #5099: [Feature Request]: Reorganize the Project Setup Documentation
### Is your feature request related to a problem? Please describe.

Many new contributors run into issues setting up the project, especially on a Windows SDE. Having run tthrough the setup instructions myself, I noticed that while all the information needed to setup is present, a bit of reorganization would be useful to minimize skipping some important setup steps, which will in turn minimize the number of reported setup issues.

Some problems I noticed with the current instructions are:
- The [main setup page](https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android) contains instructions for setting up the development environment for all the OSes together with a number of external links. This means contributors have to keep going back and forth between tabs, and may lose their place, which often results into skipping steps.
- The current setup steps advise to install the latest Android Studio version, but our project does not support the latest gradle  versions bundled with newer IDE versions.
- Steps [2 and 3 ](https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android#prepare-developer-environment)of the setup instructions involve setting up Java 8. This is not an actual pre-requisite to getting the project running, yet it is a non-trivial task. Android Studio comes with its own embedded JDK, and it is possible to install additional versions from within the IDE if needed. Our project can build on gradle with JDKs 8-11, which are sufficient for getting started on a first issue.
- In relation to the JDK step above, there are missing instructions on specifying the compile jdk version from within Android studio --- even if you set the java home variable, Android Studio defaults to its embedded jdk.
- Most contributors never run the `bash setup.sh` command, missing out on important pre-push checks.

### Describe the solution you'd like

I do think that, pre full bazel migration, we should allow our contributors to get started with just gradle as this lowers the barriers to start contributing. Most of the starter issues for the foreseable future do not need interaction with Bazel.

Some changes we can make to improve the setup Wiki:
- From the onset, split the setup instructions per OS. This means that the [first page](https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android#prepare-developer-environment) of setup instructions will have a format like this:
   ```
    - Select your operating system to get the setup instructions:
       - Linux
       - Windows
       - MacOs
    ```
Then on each OSs page, we will have the complete OS specific setup instructions, numbered.
- Update the required Android Studio Version instructions to Bumblee Bee Patch 3 ([direct  download url)](https://redirector.gvt1.com/edgedl/android/studio/install/2021.1.1.23/android-studio-2021.1.1.23-windows.exe)
- Move the Java 8 and `$JAVA_HOME` setup instructions to the Bazel set up section on each page, since they are only relevant there.
- Add instructions on how to select the compile JDK from within Android Studio Settings.
- Update outdated instructions related to SDK path in Android studio and that of downloading the `google files check` file. 
- Include a post-setup checklist to verify all the setup steps have been completed. 

### Describe alternatives you've considered

- Adding instructions about common set up issues, their causes and how to fix them.

This option is reactive rather than preventive.

We can still however have a section for this, especially for issues that cannot be prevented such as https://github.com/oppia/oppia-android/discussions/4966#discussioncomment-6524813.

### Additional context

https://github.com/oppia/oppia-android/discussions/5061

https://github.com/oppia/oppia-android/discussions/4858

https://github.com/oppia/oppia-android/discussions/4432

### PR DESCRIPTION
**Pull request by adhiamboperes**
## Explanation

Fix #5073:  Add instructions to the wiki for how to assign a reviewer.
Fix #5062:  Add wiki documentation for how to pick the emulator/android version when running Espresso tests.
Fix #5099:  Reorganize the Project Setup Documentation
Fix part of #1723: ensure the onboarding flow leads into follow-up documentation: architecture overview, code style, submission guidelines, how to make UX changes, how to contribute large projects (which should tie into design documents), and best practices
Fix part of #1723: Known issues that have come up in discussions

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by adhiamboperes** [comment]
Screenshot 2023-10-04 at 18 49 55
Screenshot 2023-10-04 at 18 29 10
Screenshot 2023-10-04 at 18 28 21

Screenshot 2023-10-04 at 18 25 55

Screenshot 2023-10-04 at 18 22 18

Screenshot 2023-10-04 at 17 34 40
Screenshot 2023-10-04 at 17 39 41

**Comment by adhiamboperes** [comment]
@MohitGupta121, could you PTAL and let me know your thoughts?

**Review by MohitGupta121 — COMMENTED** [review]
@adhiamboperes LGTM, Thanks!
Very clear and to the point instructions now.

**Review by MohitGupta121 — APPROVED** [review]

**Comment by adhiamboperes** [comment]
@seanlip, PTAL for codeowners, (If possible).

**Review by seanlip — APPROVED** [review]
Thanks @adhiamboperes! LGTM. You might need to fix the sidebar merge conflict though.

**Pull request merged**
