### PR TITLE
Fix #4959 : Voiceover button is too small

### LINKED ISSUE #4959: Oppia's android app voiceover button is too small
### Is your feature request related to a problem? Please describe.

During my user research, I noticed that the design of the play button/icon was small and our different users kept clicking multiple times before they got it to play. This made them frustrated.

### Describe the solution you'd like

The solution will be to increase the size of the "play" button by making it as big as the chat bubble on the right.

### Describe alternatives you've considered

I've had to continue playing it like that and reporting it in my UX Research for consolidation.

### Additional context

image

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

Fix #4959 : Voiceover button is too small

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

| Before | After |
| ------ | ------ |
|   |  |

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by MohitGupta121 — COMMENTED** [review]
@BenHenning PTAL, Thanks.

**Comment by BenHenning** [comment]
Apologies @MohitGupta121 will need to look at this tomorrow.

**Comment by MohitGupta121** [comment]
No problem @BenHenning, totally fine.

**Review by BenHenning — APPROVED** [review]
Thanks @MohitGupta121. LGTM.

**Pull request merged**
