### PR TITLE
Fix #2716: Resolve ktlint max line in ImageRegionSelectionInteractionView

### LINKED ISSUE #2716: Resolve ktlint max line in ImageRegionSelectionInteractionView
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name.
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the line of code under 100 char length.

Where to start?
1. Complete all installation steps before starting with this issue - https://github.com/oppia/oppia-android/wiki#installation
2. 
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/main/java/org/oppia/android/app/player/state/ImageRegionSelectionInteractionView.kt#L162

Possible fix for this issue
```kotlin
    this.addOnLayoutChangeListener {
      _,
      left,
      top,
      right,
      bottom,
      oldLeft,
      oldTop,
      oldRight,
      oldBottom ->
      // Update the regions, as the bounds have changed
```

### PR DESCRIPTION
**Pull request by abhinav12k**
## Explanation
Fixes #2716 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by abhinav12k** [comment]
@anandwana001 PTAL

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @abhinav12k

**Review by BenHenning — APPROVED** [review]
Thanks @abhinav12k! LGTM.

**Comment by BenHenning** [comment]
@anandwana001 please watch for merging.

**Pull request merged**
