### PR TITLE
Fix part of #89: Clean up test dispatchers

### PR DESCRIPTION
**Pull request by BenHenning**
Fix part of #89: broadly cleans up test dispatchers throughout the codebase.

TestCoroutineDispatchers have been used in a few heavy Robolectric tests for a couple months now, without issue. This change broadly migrates all test dispatchers over to TestCoroutineDispatchers and TestDispatcherModule, resulting in significant and broad cleanups.

This change also includes broadly removing now-unnecessary uses of various Kotlin coroutine annotations, and runBlockingTest() since TestCoroutineDispatchers replaces this functionality & does it more correctly.

Some things to note:
1. This change also includes moving ProfileTestHelper to the testing module since it's been changed to rely on TestCoroutineDispatcher (which improves downstream test stability in the app module).
2. MainThreadExecutor was removed as the test disaptcher in StateFragmentTest and HomeActivityTest which may cause failures in these tests. Since neither test is part of the non-flaky test run, this is considered fine here.
3. Notice that runCurrent() has been moved around or added in a bunch of places--this is to be expected. TestCoroutineDispatchers always operates in a paused state, whereas before all test dispatchers were generally operating in a running state. These additional calls are needed to synchronize access. In some special cases, an additional coroutine dispatcher is being used to demonstrate blocking functionality without interfering with TestCoroutineDispatcher functionality. Also, note that missing runCurrent() in app module tests that depend on waitFor() can result in long failures (30 seconds for the timeout), so long-term tests should opt to avoid using waitFor() since TestCoroutineDispatchers also has an idling resource for Espresso use cases.

This change also updates all tests to use the paused looper mode when running in Robolectric. This is the recommended mode to run all Robolectric tests, and it interoperates better with TestCoroutineDispatchers.

This change includes some functional changes to AudioPlayerControllerTest. Before, the audio track being played was 1 second long, and 1 second needs to be waited before audio is detected as playing. These race against each otehr in paused looper mode, so extending the track duration to 2 seconds fixes the situation. I also made some minor cleanups elsewhere in the test.

Finally, it enables running tests and ktlint for the testing module since this wasn't added earlier.

### CODE REVIEW

**Comment by BenHenning** [comment]
@rt4914 @vinitamurthi @anandwana001 if this PR is too large to review, I suggest adding other team members & dividing it up (maybe by name). The PR is straightforward, and only affects tests (so tests passing generally indicates the PR is fine). Please let me know if you have any specific concerns around this change.

**Review by vinitamurthi — APPROVED** [review]

**Comment by vinitamurthi** [comment]
Thanks for this! After this goes in, I will check if we can add more tests into CI if they are not flaky anymore

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by BenHenning** [comment]
Thanks for the quick reviews!

**Pull request merged**
