### PR TITLE
Fixes part of #2196: Changes in Onboarding Screens[a11y]

### LINKED ISSUE #2196: Changes needed in Onboarding Screens [A11y] [BLOCKED]
**Describe the bug**

Onboarding Screens are not fully compatible with some users from the Accessibility point of view.
Issue 1 - No Item Label present in the bottom arrow button 
Issue 2 - Multiple items have the same Description as that of Image on all the screens
Issue 3 - The Contrast ratio (between foreground and background) of the Image resource used in the Second screen is 2.55 but the required one 3.00 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and scan the screenshots with the Accessibility Scanner
3. You will see the tests that are not passed by that screen
4. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    |  Issue 3 |
|:--------:|:-------------:|:---------:|
| Screenshot_2020-11-29-17-06-23-04_80a9469f53bfe75dbc6e8989be28e2f0 |  Screenshot_2020-11-29-17-05-06-94 |   Screenshot_2020-11-29-17-06-09-87_80a9469f53bfe75dbc6e8989be28e2f0   |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

### PR DESCRIPTION
**Pull request by Arjupta**
## Explanation

Fixes part of #2196
( Issue 3 )Set the ImageView in Onboarding Slide to not important for a11y check as per Chantel's suggestion
|Before|After|Tests|
|:-:|:-:|:-:|
|Screenshot_1611482182 | Screenshot_1611482951 | Screenshot_1611482035 |
|Screenshot_1611482200 |Screenshot_1611482055 | Screenshot_1611482062|

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by rt4914 — CHANGES_REQUESTED** [review]
I missed few changes:
1. Remove `contentDescription` as it is no more needed.
2. Make this change part of `onboarding_final_slide` too.

**Comment by Arjupta** [comment]
> I missed few changes:
> 
> 1. Remove `contentDescription` as it is no more needed.
> 2. Make this change part of `onboarding_final_slide` too.

Done,
After removing the `contentDescription` from the images, the tests related to check the description failed. So i had to remove them. PTAL

|Before Tests were removed|After Tests were removed|
|:-:|:-:|
| Screenshot 2021-01-24 141907| Screenshot 2021-01-24 142711|

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
