### PR TITLE
Fix part of #2833: Added named arguments in TopicRevisionFragmentTest.

### PR DESCRIPTION
**Pull request by justdvnsh**
## Explanation
Fix part of #2833: Added named arguments in the functions

## Checklist
- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by FareesHussain** [comment]
@justdvnsh why does it show the whole file as edited here

**Comment by FareesHussain** [comment]
Just to confirm, Have you created a fresh branch from develop?
if you've created a new branch from the previous branch this might have caused this.

**Comment by justdvnsh** [comment]
@FareesHussain I think, because i just pasted the complete file from before which had the changes. That's why !! 

Did I do something wrong again ?

**Comment by FareesHussain** [comment]
Can you create a fresh branch and make the required changes (without pasting the previous one) 
and share the link of the branch (don't create a PR for that it is just to confirm if is a local issue or not)
I'll have a check if it is a local issue.

**Comment by anandwana001** [comment]
@justdvnsh Also, please use the PR title more descriptive. 
Example - https://github.com/oppia/oppia-android/issues/2833

**Comment by justdvnsh** [comment]
@FareesHussain Done. Here is the link to the branch
https://github.com/justdvnsh/oppia-android/tree/test/requested_branch

**Comment by FareesHussain** [comment]
@justdvnsh https://github.com/oppia/oppia-android/compare/develop...justdvnsh:test/requested_branch

This shows the changes as expected. also please follow branch name separated by `-`

**Comment by justdvnsh** [comment]
@FareesHussain So now. Do i make a new PR with that branch instead?

**Comment by FareesHussain** [comment]
yes

**Comment by justdvnsh** [comment]
@FareesHussain Done. Here 
https://github.com/oppia/oppia-android/pull/2913

**Comment by prayutsu** [comment]
Thanks, @justdvnsh for fixing it.

**Comment by justdvnsh** [comment]
@prayutsu No problem. I liked the standards of the organisation.

**Pull request closed without merging**
