### PR TITLE
Fix #2488 Required Reformatting for administrator_controls_general_view.xml

### LINKED ISSUE #2488: Required Reformatting for administrator_controls_general_view.xml
The following files require reformatting
 - layout/administrator_controls_general_view.xml
 - layout-land/administrator_controls_general_view.xml
 - layout-sw600dp/administrator_controls_general_view.xml 

Recommended to set up [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

### PR DESCRIPTION
**Pull request by chrk2205**
Fixes #2488
Reformatted:
layout/administrator_controls_general_view.xml
layout-land/administrator_controls_general_view.xml
layout-sw600dp/administrator_controls_general_view.xml
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
Thanks for being so cooperative @chrk2205 
LGTM

**Comment by chrk2205** [comment]
> Thanks for being so cooperative @chrk2205
> LGTM

its okay @rt4914 
Is there any alternative instead of force-push in the previous PR
I mean i tried to rebase and push but it did not worked!!
Thanks

**Comment by rt4914** [comment]
> > Thanks for being so cooperative @chrk2205
> > LGTM
> 
> its okay @rt4914
> Is there any alternative instead of force-push in the previous PR
> I mean i tried to rebase and push but it did not worked!!
> Thanks

@chrk2205 Just create a new commit each time.
Point 3 in https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

**Comment by chrk2205** [comment]
> > > Thanks for being so cooperative @chrk2205
> > > LGTM
> > 
> > 
> > its okay @rt4914
> > Is there any alternative instead of force-push in the previous PR
> > I mean i tried to rebase and push but it did not worked!!
> > Thanks
> 
> @chrk2205 Just create a new commit each time.
> Point 3 in https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change
@rt4914 
i made a new commit and tried to push
its says that i should either merge or rebase in order to push changes

**Comment by rt4914** [comment]
> > > > Thanks for being so cooperative @chrk2205
> > > > LGTM
> > > 
> > > 
> > > its okay @rt4914
> > > Is there any alternative instead of force-push in the previous PR
> > > I mean i tried to rebase and push but it did not worked!!
> > > Thanks
> > 
> > 
> > @chrk2205 Just create a new commit each time.
> > Point 3 in https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change
> > @rt4914
> > i made a new commit and tried to push
> > its says that i should either merge or rebase in order to push changes

You are using git from terminal or Android Studio? @chrk2205

**Pull request merged**
