### PR TITLE
Introduce nested data provider

### PR DESCRIPTION
**Pull request by BenHenning**
Introduce a dynamic nested data provider. This behaves essentially the same as transformAsync, except the data provider being transformed can be changed. This is specifically needed by questions in order to handle multiple sessions (e.g. each new session involves generating another list of questions to play, and that list is subsequently transformed into the ephemeral state of the question session). See #397 for specifics.

### CODE REVIEW

**Comment by BenHenning** [comment]
For future me, proposed tests that could be added (incomplete):
```kotlin
fun testNestedXformedProvider_toLiveData_deliversTransformedValue()
fun testNestedXformedProvider_toLiveData_diffValue_notifiesNested_deliversXformedValueTwo()
fun testNestedXformedProvider_toLiveData_diffValue_notifiesBase_deliversXformedValueTwo()
fun testNestedXformedProvider_toLiveData_diffVal_notifiesXform_deliversXformedValueTwo()
fun testNestedXformedProvider_diffValue_notifiesNested_observeNested_deliversSecondVal()
fun testNestedXformedProvider_differentValue_notifiesBase_observeNested_deliversFirstVal()
fun testNestedXformedProvider_diffValue_notifiesXformed_observeNested_deliversFirstVal()
fun testNestedXformedProvider_diffValue_notifiesNested_observeBase_deliversSecondVal()
fun testNestedXformedProvider_differentValue_notifiesBase_observeBase_deliversSecondVal()
fun testNestedXformedProvider_diffValue_notifiesXformed_observeBase_deliversFirstVal()
fun testNestedXformedProvider_toLiveData_nestedPending_deliversPending()
fun testNestedXformedProvider_toLiveData_nestedFailure_deliversFailure()
fun testNestedXformedProvider_toLiveData_withObserver_callsNestedProvider()
fun testNestedXformedProvider_toLiveData_noObserver_doesNotCallNestedProvider()
```

These are based on the transform async tests except there are some minor alterations (and overall a bunch of simplifications).

Edit: actually, these are missing some tests that aren't focusing on the transform function that's passed in. These need to be updated yet.

**Review by rt4914 — APPROVED** [review]
LTGM, thanks.

**Review by vinitamurthi — APPROVED** [review]

**Review by aggarwalpulkit596 — APPROVED** [review]

**Comment by BenHenning** [comment]
@aggarwalpulkit596 de-assigning you since it seems you completed your review without any follow up action items.

**Comment by BenHenning** [comment]
Thanks for the reviews!

**Pull request merged**
