### PR TITLE
Fixes part of #2326: Changes in Views inside Practice Tab [A11y]

### PR DESCRIPTION
**Pull request by Mehul-Bisht**
## Explanation

Fixes part of #2326: Changes in Views inside Practice Tab [A11y] for Tablet layouts
Fixed issue with checkbox accessibility for all tablet layouts, I had already fixed the issue with mobile layouts in earlier PR here: #2525 

## Portrait Mode
| Before |
:-------------------------:
practice_tab_portrait_before
| After |
practice_tab_portrait_after

## Landscape Mode
| Before |
:-------------------------:
practice_tab_landscape_before
| After |
practice_tab_landscape_after

### CODE REVIEW

**Comment by Mehul-Bisht** [comment]
@ARJUPTA @rt4914 kindly check the changes

**Comment by rt4914** [comment]
@Mehul-Bisht Has this change been suggestion or discussed with Chantel?

From what I see this PR introduces 2 dp change which means UI will slightly change which we general don't want.
If this has not been confirmed with Chantel, then i suggest either look for alternate solution of discuss this with Chantel whether this change is allowed or not.

**Comment by Mehul-Bisht** [comment]
> @Mehul-Bisht Has this change been suggestion or discussed with Chantel?

No it was not discussed with her. @mschanteltc Kindly tell if I should be adding 2 dp padding to the checkboxes in tablet layout to remove the accessibility issue mentioned in the second issue (Issue 2) here: #2326

**Comment by mschanteltc** [comment]
> > @Mehul-Bisht Has this change been suggestion or discussed with Chantel?
> 
> No it was not discussed with her. @mschanteltc Kindly tell if I should be adding 2 dp padding to the checkboxes in tablet layout to remove the accessibility issue mentioned in the second issue (Issue 2) here: #2326

The item's height should be a multiple of 4. The accessibility checker used here recommends a size of at least 48 dp, although the UI [guidelines](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html) I suggest we follow recommends that touch targets should be at least 44 CSS pixels. When you convert the item size from dp to px, does this meet this latter requirement?

**Comment by Mehul-Bisht** [comment]
>I suggest we follow recommends that touch targets should be at least 44 CSS pixels. When you convert the item size from dp to px, does this meet this latter requirement?

@mschanteltc Although I am not sure about this, but I found this conversion [here](https://graphicdesign.stackexchange.com/a/55107) 
image

As per this, 48 dp equals 28.8 px

**Comment by Mehul-Bisht** [comment]
And [this answer](https://stackoverflow.com/a/31715400/13343177) states that dp and px can be used interchangeably. Chantel if you are aware about the exact conversion, let me know.

**Comment by Mehul-Bisht** [comment]
@mschanteltc Any updates regarding this?

**Comment by mschanteltc** [comment]
> @mschanteltc Any updates regarding this?

I still say let's only use 44 dp for the checkbox and ignore the 48 dp minimum requirement. As long as it is following the W3 [guidelines](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html), this should suffice. Also is it possible we can center horizontally center the touch target with the checkbox and skill name?

**Comment by Mehul-Bisht** [comment]
>I still say let's only use 44 dp for the checkbox and ignore the 48 dp minimum requirement. As long as it is following the W3 guidelines

@mschanteltc the initial value of the height was 46 dp, so should I change it to 44 dp then? Also, the UI will shift if we make it horizontally centred, should I still be considering it?

**Comment by mschanteltc** [comment]
> > I still say let's only use 44 dp for the checkbox and ignore the 48 dp minimum requirement. As long as it is following the W3 guidelines
> 
> @mschanteltc the initial value of the height was 46 dp, so should I change it to 44 dp then? Also, the UI will shift if we make it horizontally centred, should I still be considering it?

Yes change to 44dp, since I assume changing it to 48dp means that the checkboxes would be more spaced out from each other. 

Can you show me screenshots of how the page looks like when the checkboxes are top-aligned with the touch target and horizontally-centered with the touch target? We can choose from there.

**Comment by Mehul-Bisht** [comment]
This is the screenshot after changing to 44dp 

| Reverted to 44 dp | 
:----------------|
practice_44dp

And since the text is not a separate part than the tap target (the checkbox has text within it), so this is how it will look if I change the width of the checkbox to "wrap_content" instead of "match_parent" 

| checkbox width | 
:----------------|
practice_wrap

**Comment by Mehul-Bisht** [comment]
> > > I still say let's only use 44 dp for the checkbox and ignore the 48 dp minimum requirement. As long as it is following the W3 guidelines
> > 
> > 
> > @mschanteltc the initial value of the height was 46 dp, so should I change it to 44 dp then? Also, the UI will shift if we make it horizontally centred, should I still be considering it?
> 
> Yes change to 44dp, since I assume changing it to 48dp means that the checkboxes would be more spaced out from each other.
> 
> Can you show me screenshots of how the page looks like when the checkboxes are top-aligned with the touch target and horizontally-centered with the touch target? We can choose from there.

@mschanteltc  PTAL

**Comment by mschanteltc** [comment]
> > > > I still say let's only use 44 dp for the checkbox and ignore the 48 dp minimum requirement. As long as it is following the W3 guidelines
> > > 
> > > 
> > > @mschanteltc the initial value of the height was 46 dp, so should I change it to 44 dp then? Also, the UI will shift if we make it horizontally centred, should I still be considering it?
> > 
> > 
> > Yes change to 44dp, since I assume changing it to 48dp means that the checkboxes would be more spaced out from each other.
> > Can you show me screenshots of how the page looks like when the checkboxes are top-aligned with the touch target and horizontally-centered with the touch target? We can choose from there.
> 
> @mschanteltc PTAL

Sorry I believe I used the wrong terminology. I think I meant that the checkbox and skill name should be vertically centered in respect to the touch target, like in the one below:
TP (Practice, Unchecked)

**Comment by Mehul-Bisht** [comment]
By Shifting half of the padding above the checkbox i was able to achieve this

practice_tab_Center

**Comment by Mehul-Bisht** [comment]
@mschanteltc kindly check the changes and let me know if there is still some issue.

**Comment by mschanteltc** [comment]
> By Shifting half of the padding above the checkbox i was able to achieve this
> 
> practice_tab_Center

LGTM!

**Comment by Mehul-Bisht** [comment]
@rt4914 @ARJUPTA Please review this PR once so that it is ready to merge

**Review by rt4914 — CHANGES_REQUESTED** [review]
@Mehul-Bisht There are two issues with solution.
1. The box and the text is actually not correctly aligned. If you run the app in mobile you will notice hat text and the box are correctly aligned.
2. Also, the box should always be on the top-right corner.




## Mobile Output

**Comment by Mehul-Bisht** [comment]
@rt4914 the reason why this is happening is due to the gravity of checkbox and shifting half of the padding above the checkbox. In mobile layouts the gravity is set to `top` but for tablet layouts I had changed it to `center_vertical` as suggested by Chantel to make the checkbox and the text to be vertically centred. When I revert this change the layout for both mobile and tab layout behaves similar as shown:

## Tablet Layout
| After Change |
:---------------:
practice_tab_gravity

## Mobile Layout
| No Change |
:---------------:
Screenshot_1614864624

**Comment by anandwana001** [comment]
@rt4914 PTAL

**Comment by rt4914** [comment]
@Mehul-Bisht I tried to solve this locally but haven't found any solution yet.

**Pull request closed without merging**
