### PR TITLE
Implementation approach for SpanCount RoboelectricTest for ongoing_story_recycler_view

### PR DESCRIPTION
**Pull request by MohamedMedhat1998**
## Explanation
This draft PR contains an implementation approach that contains an error.  
Please refer to [this doc](https://docs.google.com/document/d/1vBcFd2GS55zFZ0rZtbkggves3RNIqRV1kOQ2SJRurGQ/edit?usp=sharing) which contains detailed information about the bug I'm facing.

### CODE REVIEW

**Comment by rt4914** [comment]
@MohamedMedhat1998 Replied on your document.

**Comment by MohamedMedhat1998** [comment]
After using `@LooperMode(LooperMode.Mode.PAUSED)` for the test cases, the `android.view.InflateException` error was solved.  
Another error occurred which is `kotlin.KotlinNullPointerException`, full log:  
```
kotlin.KotlinNullPointerException
	at org.oppia.app.testing.RecentlyPlayedSpanTest.getOngoingStoryRecyclerView(RecentlyPlayedSpanTest.kt:160)
	at org.oppia.app.testing.RecentlyPlayedSpanTest.getOngoingStoryRecyclerViewGridLayoutManager(RecentlyPlayedSpanTest.kt:156)
	at org.oppia.app.testing.RecentlyPlayedSpanTest.access$getOngoingStoryRecyclerViewGridLayoutManager(RecentlyPlayedSpanTest.kt:72)
	at org.oppia.app.testing.RecentlyPlayedSpanTest$testA$$inlined$use$lambda$1.perform(RecentlyPlayedSpanTest.kt:124)
	at org.oppia.app.testing.RecentlyPlayedSpanTest$testA$$inlined$use$lambda$1.perform(RecentlyPlayedSpanTest.kt:72)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:551)
	at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:561)
	at org.oppia.app.testing.RecentlyPlayedSpanTest.testA(RecentlyPlayedSpanTest.kt:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```  
@rt4914 @veena14cs PTAL

**Review by rt4914 — CHANGES_REQUESTED** [review]
@MohamedMedhat1998 The approach you suggested earlier was correct. We will need to create a dummy test activity which can contain dummy data similar to the implementation of `ProfileChooserFragmentTestActivity` and its presenter. 

Because in the new introduced test file we cannot use domain layer functions to help us create dummy data.

Thanks.

**Comment by MohamedMedhat1998** [comment]
`kotlin.KotlinNullPointerException` is now solved. I only needed to add `android:tag` attribute in the `RecyclerView`
```
<androidx.recyclerview.widget.RecyclerView
        android:id="@+id/ongoing_story_recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:overScrollMode="never"
        android:paddingTop="8dp"
        android:paddingBottom="172dp"
        android:scrollbars="none"
        android:tag="recently_played_recycler_view" />
```
because we were searching for the view with a specific tag and this view wasn't exsist
```
private fun getOngoingStoryRecyclerView(activity: RecentlyPlayedFragmentActivityTest): RecyclerView {
    return getRecentlyPlayedFragment(activity).view?.findViewWithTag<View>(
      TAG_RECENTLY_PLAYED_FRAGMENT_RECYCLER_VIEW //Now, this is the correct tag
    )!! as RecyclerView
  }
```
Now we have two options:

1. Use the `RecentlyPlayedActivity` directly in the `RecentlyPlayedSpanTest`
2. Use the newly created `RecentlyPlayedFragmentActivityTest` instead

@rt4914 PTAL.  
Which option should I go with?

**Comment by rt4914** [comment]
> 1. RecentlyPlayedActivity

@MohamedMedhat1998 If possible try to do this with option 1 (RecentlyPlayedActivity) so that we can avoid introducing new file. But if that does not work out we can go for approach 2.

**Comment by MohamedMedhat1998** [comment]
Closing this PR to open a new one with the correct implementation

**Pull request closed without merging**
