### PR TITLE
Fix part of #4044: Enable new math classifiers

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
Fix part of #4044

This PR enables all of the new classifiers introduced in #4057, #4058, and #4059 which comprise the three new interactions being added as part of the math expressions project.

This mainly entails adding the modules to ApplicationComponent, the instrumentation test-only ApplicationComponent, and all tests that require interactions. This doesn't actually enable an UI-related changes, or even enable support for loading explorations with these interactions yet. It just enables the domain classifiers for use in a future PR.

This PR also adds a Bazel target DrawableBindingAdaptersTest since it was missed in the PR in which the suite was introduced.

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A -- While this hooks up the new classifiers, they can't yet be loaded by any explorations (hence there're no affected UIs due to this change, yet).

### CODE REVIEW

**Comment by BenHenning** [comment]
Hi. As of today, some main reviewers have taken time off for the next few weeks, so it may take a little while before we can look at this PR. We appreciate your patience while some of our team members recharge. We'll be fully returning on 4 January 2021.

**Comment by BenHenning** [comment]
Note to self: the app module failures are real & will need to be fixed.

**Comment by BenHenning** [comment]
The latest commit should fix the breakage (and it introduces a new Bazel test target that was previously missed).

**Comment by BenHenning** [comment]
PTAL @rt4914 and @vinitamurthi for codeowners.

PTAL at the whole PR @anandwana001 as part of the broader math expressions project.

**Review by rt4914 — APPROVED** [review]
Approving for codeowners.

**Review by vinitamurthi — APPROVED** [review]

**Comment by BenHenning** [comment]
This is still active.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Pull request merged**
