### PR TITLE
Fix part of #2833: Add Missing named Arguments in ProfileListFragmentTest

### PR DESCRIPTION
**Pull request by Naman-1234**
## Explanation

Fixes Part of #2833 
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
@Naman-1234 Pleasee check the error 

```
e: /home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileListFragmentTest.kt: (222, 39): Cannot find a parameter with this name: numberOfProfiles

e: /home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileListFragmentTest.kt: (222, 59): No value passed for parameter 'numProfiles'
```

**Comment by anandwana001** [comment]
What is Named Argument in Kotlin?
https://kotlinlang.org/docs/functions.html#named-arguments

Sending argument name should be the same as receiving argument name.
https://github.com/oppia/oppia-android/blob/80b2e029f4cee812421edec0d373175efff6afd3/testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt#L90

**Comment by anandwana001** [comment]
Also, please follow the checklist for PR title
```
 The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
```

**Comment by Naman-1234** [comment]
Ok sir ,Working on them.

**Comment by Naman-1234** [comment]
> @Naman-1234 Pleasee check the error
> 
> ```
> e: /home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileListFragmentTest.kt: (222, 39): Cannot find a parameter with this name: numberOfProfiles
> 
> e: /home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileListFragmentTest.kt: (222, 59): No value passed for parameter 'numProfiles'
> ```

Sir Error has been resolved.

**Review by anandwana001 — APPROVED** [review]

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
