### PR TITLE
Fix #664: Solved the UX issue with switch profile of navigation drawer

### LINKED ISSUE #664: UX issues with switch profile of navigation drawer
If we click on the switch profile button present in the navigation drawer and then close the dialog by clicking somewhere else on the screen, the dialog box gets dismissed, but the navigation drawer still remains open, with the switch profile option highlighted.

In this, if the dialog button is canceled or the dialog disappears by clicking somewhere else, then the last selection option should get re-selected. 
Example:
If you are in HomeFragment and click on `Switch Profile` in NavigationDrawer then the dialog disappears (like after clicking Cancel), in this case, HomeFragment should get re-selected. Similarly for other cases too. 

Screenshot_1581622192

### PR DESCRIPTION
**Pull request by abhinavraj23**
## Explanation
Fixes #664 - Solved the UX issue with switch profile of navigation drawer

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@abhinavraj23  Once after cancelling the dialog, when you open navigation drawer again, the `Switch Profile` is highlighted which should not happen. Also, along with this you will need to write test cases for testing this functionality.

**Review by rt4914 — CHANGES_REQUESTED** [review]
PTAL

**Comment by abhinavraj23** [comment]
@rt4914 I have solved the above-mentioned bug, but yet to write the test-cases, will write it ASAP!

**Comment by rt4914** [comment]
Also, actually there is one test case failing in this PR: `testSplashActivity_secondOpen_routesToChooseProfileActivity ` I will look into on monday, because this should not happen because of your PR.

**Comment by abhinavraj23** [comment]
Any update @rt4914?

**Comment by rt4914** [comment]
> Any update @rt4914?

Actually, your branch is behind develop. Just merge your branch with develop. Also, write test cases.

**Comment by veena14cs** [comment]
> > Any update @rt4914?
> 
> Actually, your branch is behind develop. Just merge your branch with develop. Also, write test cases.

+1

**Review by veena14cs — CHANGES_REQUESTED** [review]
Once you add testcase assign it to me.

**Comment by abhinavraj23** [comment]
@rt4914 @veena14cs I have merged with latest updates but still, the test is failing

**Review by rt4914 — COMMENTED** [review]
Actually the test case is passing in Android Studio.

Lets two things.

1. Undo the changes that you have introduced in this PR, and commit them in this branch then check if tests pass on CircleCI or not.
If they fail,
2. then create a separate PR from scratch and lets see how does that work out.

**Comment by abhinavraj23** [comment]
Sure @rt4914

**Comment by abhinavraj23** [comment]
@rt4914 it is still failing, I am making another PR

**Comment by rt4914** [comment]
Closing this PR for now.

**Pull request closed without merging**
