### PR TITLE
Fixes #1145: RecentlyPlayed - Tablet (Landscape) (Highfi)

### LINKED ISSUE #1145: RecentlyPlayed - Tablet (Landscape) (Highfi)
Mocks: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/17910ab6-21f3-4c85-9429-bea2da2b3c26/L-Recently-Played-Stories

Implement high-fi UI for **RecentlyPlayed** tablet landscape mode

**Target PR date**: 14 June 2020
**Target completion date**: 18 June 2020

### PR DESCRIPTION
**Pull request by MohamedMedhat1998**
## Important note
This PR violates the outer margins in the mocks, it uses 96dp as outer margins instead of 152dp. I have done that because we were having a problem implementing the 152dp outer margins in the HomeFragment. For more information about the problem, PTAL [here](https://docs.google.com/document/d/1Q0T-2zUfW7soyZLZL7yNfMi-pGkFd1pXAFVBsqeOxuI/edit#).  
The solution was to use 96dp instead and @mschanteltc -the UI/UX designer- and @rt4914  approved that solution, that happened in PR #1331    
So, I have applied this solution here too.  
@mschanteltc please check the screenshots below and tell me if there is something that I need to change, Thanks.
## Explanation

- Implemented high-fi tablet UI for RecentlyPlayed landscape mode
- Fixes #1145 
- Mock link: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/17910ab6-21f3-4c85-9429-bea2da2b3c26/L-Recently-Played-Stories
### 1024x768 emulator
screenshot-2020-06-17_18 10 26 8

screenshot-2020-06-18_11 22 53 692

screenshot-2020-06-18_11 23 02 581

### 2560x1800 emulator
screenshot-2020-06-17_18 20 01 894

screenshot-2020-06-18_11 29 51 941

screenshot-2020-06-18_11 29 59 061

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
Initial View looks good but please add screenshots with `Last Month` section also which contains divider too.

**Comment by mschanteltc** [comment]
Is the white portion of the card the same height in both screen sizes? That is what we would want to make sure they're consistent. Otherwise everything else LGTM :)

**Comment by MohamedMedhat1998** [comment]
> 
> 
> Is the white portion of the card the same height in both screen sizes? That is what we would want to make sure they're consistent. Otherwise everything else LGTM :)


@mschanteltc 
I think so. Because the height in the white portion is defined by the following items:
- The text size of the name text and its margins
- The text size of the category text and its margins  

And these values don't change based on the device in the code.  
If there is a subtle difference, I think it is because of how the device manipulates the dimensions. But it should be the same.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> Initial View looks good but please add screenshots with `Last Month` section also which contains divider too.

@rt4914 Done!  
I have also resolved the conflict. PTAL.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by mschanteltc** [comment]
> > Is the white portion of the card the same height in both screen sizes? That is what we would want to make sure they're consistent. Otherwise everything else LGTM :)
> 
> @mschanteltc
> I think so. Because the height in the white portion is defined by the following items:
> 
> * The text size of the name text and its margins
> * The text size of the category text and its margins
> 
> And these values don't change based on the device in the code.
> If there is a subtle difference, I think it is because of how the device manipulates the dimensions. But it should be the same.

If that's the case, then LGTM!

**Pull request merged**
