### PR TITLE
Fix #2504: Address nit for HomeActivityTest to use verifyHomeRecyclerViewHasGridColumnCount() helper

### LINKED ISSUE #2504: Nit code change in HomeActivityTest.kt
`HomeActivityTest.kt` needs to be updated as per this comment 
https://github.com/oppia/oppia-android/pull/2246#discussion_r559335629

### PR DESCRIPTION
**Pull request by yurilev**
## Explanation
Fixes #2504: Address nit from pull request [#2246](https://github.com/oppia/oppia-android/pull/2246#discussion_r559335629) to consistently use the `verifyHomeRecyclerViewHasGridColumnCount()` helper in `HomeActivityTest`. There was a sole remaining location where it wasn't used.

Note: The nit was for `testHomeActivity_allTopicsCompleted_displaysAllTopicCards()`. This method fails when running using Espresso in an Android emulator with a tablet image, because of the bigger screen size. Will file a separate issue to address that. (All tests pass in Robolectric.) Other similar test methods covering "topics":
* Have 4 versions, split into portrait/landscape and mobile/tablet.
*  Also assert the number of cards.

Also fixed an adjacent single letter typo.

## Checklist
- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by yurilev** [comment]
Robolectric (app module) fails for a single unrelated test. Did not find preexisting issue covering this, filed #2588.

**Comment by yurilev** [comment]
@rt4914 PTAL:
* I don't think have the the credentials to assign the PR to you.
* See comment about failing test. Is it a blocker? (re-run both Espresso and Robolectric and the test passes locally)

**Comment by yurilev** [comment]
Syncing and re-triggering - Robolectric passed in a different pull request. Trying again.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
