### PR TITLE
Fix #3106 buf.yaml path changed to .github/workflow/buf.yaml

### LINKED ISSUE #3106: Move buf.yml file to model package
Move https://github.com/oppia/oppia-android/blob/develop/buf.yaml to https://github.com/oppia/oppia-android/tree/develop/model and ensure nothing gets broken in CI check.

### PR DESCRIPTION
**Pull request by yashbansal130**
## Explanation
Fixes #3106: Moves buf.yml file to /.github/workflows/buf.yaml
 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by yash10019coder** [comment]
Add Fixes #3106 to the PR description

**Comment by yash10019coder** [comment]
Hi @anandwana001 can you please approve the workflow?

**Comment by yashbansal130** [comment]
@yash10019coder any changes to be made?

**Comment by yash10019coder** [comment]
Hi @yashbansal130 try to rename the paths for the codeowner file for buf.yaml and also try to reformat the changed code 
lint errors arise due to improper formatting of the code.

**Comment by yashbansal130** [comment]
@yash10019coder can u please guide me what kind of formatting is required for lint?

**Comment by yash10019coder** [comment]
> @yash10019coder can u please guide me what kind of formatting is required for lint?

General code formatting with CTRL + alt + L 
and you also need to have required plugins for the files you are formatting, like for YAML you should have YAML extension
and you can also see the tests by clicking on details and see where the test has actually failed, this helps a lot for fixing failing tests

**Comment by yash10019coder** [comment]
but currently the main error is that you have moved the file but you also have to update the places where they are currently used for now every other dependency is still consieridng at root but we have shifted it to ./github/workflow/

**Comment by yashbansal130** [comment]
@yash10019coder i changed the location in CODEOWNERS
but how to find other usages of the file

**Comment by yashbansal130** [comment]
@yash10019coder all checks passed in my forked repo, please look into it.

**Comment by yash10019coder** [comment]
Hi @anandwana001 can you approve the workflow thanks

**Comment by yash10019coder** [comment]
@yashbansal130 check all the essential checklist and appropriately tick them, thanks.

**Comment by yashbansal130** [comment]
@yash10019coder one check failed.. what now?
do i have to fix it?

**Comment by yash10019coder** [comment]
@yashbansal130  it seemed like a flaky test so I rerun the ci checks.

**Review by yash10019coder — APPROVED** [review]
@yashbansal130 this looks good for me LGTM, We'll wait for other reviews review and the CI checks to pass.

**Comment by yashbansal130** [comment]
@yash10019coder any changes to be made?

**Comment by seanlip** [comment]
@anandwana001 could you please clarify the original issue and explain why we are moving the buf.yaml file in the first place?

That file has a comment that says it should be in the root, and that more details can be found on the wiki page, but that wiki page doesn't explain why it should be in the root. [This link](https://docs.buf.build/configuration/v1/buf-yaml) also suggests that buf.yaml should be at the root of the proto source files it defines, which surely isn't going to be in .github/workflow.

Furthermore, the original issue #3106 lacks any explanation for why the move is necessary or desired.

/cc @BenHenning

**Comment by anandwana001** [comment]
@seanlip Agreed, the issue lacks the information. The original reason to file this issue is so that the buf's configuration file should be placed at the required place only, not at the root of the project. 

As per the documentation from the [link you had mentioned](https://docs.buf.build/configuration/v1/buf-yaml):
> The `buf.yaml` file defines a module, and is placed at the root of the Protobuf source files it defines. **The placement of the`buf.yaml` configuration tells buf where to search for .proto files, and how to handle imports.**

All our proto files-related stuff is in the model package only, so we can move the `buf configuration` file to the model package root.

Although, feel free to close this issue if you think that it is not required. @BenHenning

**Comment by seanlip** [comment]
@anandwana001 Could you please explain why .github/workflow is the "model package root"?

**Comment by anandwana001** [comment]
No, that was a mistake, we should not move the file to `.github/workflow`.
We can move to `mode` package as root for that particular package only.

**Comment by seanlip** [comment]
OK. Please update the title of the issue, and get confirmation from @BenHenning before assigning it to others.

**Comment by anandwana001** [comment]
@Sean Updated the issue.

@BenHenning Could you please confirm is it ok if we move the buf configuration file to the model package as all our proto file is in that package only. As per the documentation, the `buf.yaml` can be at the root where all the proto files exist.

@yashbansal130 Apologies for the misunderstanding here. Once we get the confirmation from the @BenHenning you can go ahead with this PR. By the time I would suggest checking other issues or let me know if you struggle in finding new issues to work on.

**Comment by BenHenning** [comment]
> @sean Updated the issue.
> 
> @BenHenning Could you please confirm is it ok if we move the buf configuration file to the model package as all our proto file is in that package only. As per the documentation, the `buf.yaml` can be at the root where all the proto files exist.
> 
> @yashbansal130 Apologies for the misunderstanding here. Once we get the confirmation from the @BenHenning you can go ahead with this PR. By the time I would suggest checking other issues or let me know if you struggle in finding new issues to work on.

I'm not keen on that, actually. The proto files being stuck in model/ is a Gradle limitation that, once Gradle is gone (i.e. #59), will go away and allow us to place protos closer to where they're used (i.e. throughout other packages). Given that, the common root probably will be the top-level source root.

I wouldn't be opposed putting this in config/ since that's a reasonable place for it, but if the tool expects it to be in the source root then that's probably where it needs to go.

**Comment by anandwana001** [comment]
Thanks, @BenHenning for clarification on long-term goals here. 

@yashbansal130 As per our long-term goal for the model package, I think it will be better to keep this file where it is right now only (no changes required). I appreciate the time and effort you had given on this PR, but unfortunately, we have to close this PR and issue. 
You can continue with other issues or let us know if you find any difficulty in finding issues to work on.

**Pull request closed without merging**
