### PR TITLE
Fix #5381 Talkback reads 14 underscore in a question in What is a ratio chapter

### LINKED ISSUE #5381: Talkback reads 14 underscore in a question in What is a ratio chapter
**Describe the bug**
Talkback reads 14 underscore in a question in What is a ratio chapter

**To Reproduce**
Pre- requisite: Enable Talkback
1. Go to 'Ratios and Proportions'
2. Click on 'What is Ratio'
3. Click on Continue till you reach to page 'James turned the page and saw a recipe for banana smoothie.'

Actual behavior:
Talkback is reading 14 underscores. This might be a bit difficult for users to understand that it is a blank left for a question

**Demonstration**
Screenshot_2022-12-12-15-39-57-27_943a62cb4c6fb83e010e1c2e82766a17

Device/emulator being used: One plus nord2 5g
Android or SDK version (e.g. Android 5 or SDK 21): Android version 12
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

### PR DESCRIPTION
**Pull request by subhajitxyz**
## Explanation
Fix #5381
This PR includes adding a function replaceRegexWithBlank, which replaces "2+ underscores with space/punctuation on both sides" with "blank" and returns a Spannable. Finally, it is set into the content description of the TextView.

**Screenshots**
1. First screenshot and screen record represent the content present in the ratio page.
2. Second screenshot and screen record is for testing purpose.
In the second screenshot, markings are present. These markings should be read as "blank" (1, 3, 4, 8).

<p align="center">
  Screenshot 1
  Screenshot 2
</p>

https://github.com/user-attachments/assets/c0bee11a-0df9-4524-84b6-5b1bd88b0107

**Testing**

https://github.com/user-attachments/assets/aa1fa28c-9ddc-47c5-ad21-f9511ab3ecfb

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by subhajitxyz** [comment]
@adhiamboperes ,PTAL.

**Comment by adhiamboperes** [comment]
@BenHenning, could you PTAL a high level look at the solution proposed in this PR?

**Comment by BenHenning** [comment]
Thanks @subhajitxyz and @adhiamboperes. It makes sense to compute a separate content description that eliminates extra characters like these. I think the problems here are ultimately:

1. What's the correct pedagogical way to solve the problem?
2. How do we solve this in a technically clean way?

Per (1), it would be helpful to get your thoughts @seanlip. This probably affects web with a screenreader as well, and I'm curious if there's a better way for us to communicate a "fill in the blank" (maybe using a custom tag or avoiding fill in the blank). WDYT?

(2) is pretty dependent on (1), but one existing issue I see is making sure that we localize 'Blank' properly. That being said, I think we need to wait on understanding (1) first since another option is also to process this information as part of the lesson download script.

**Comment by seanlip** [comment]
> Thanks @subhajitxyz and @adhiamboperes. It makes sense to compute a separate content description that eliminates extra characters like these. I think the problems here are ultimately:
> 
> 1. What's the correct pedagogical way to solve the problem?
> 2. How do we solve this in a technically clean way?
> 
> Per (1), it would be helpful to get your thoughts @seanlip. This probably affects web with a screenreader as well, and I'm curious if there's a better way for us to communicate a "fill in the blank" (maybe using a custom tag or avoiding fill in the blank). WDYT?
> 
> (2) is pretty dependent on (1), but one existing issue I see is making sure that we localize 'Blank' properly. That being said, I think we need to wait on understanding (1) first since another option is also to process this information as part of the lesson download script.

@BenHenning Thanks for looping me in. I think what @subhajitxyz shows in their current demo is fine, i.e. replacing long strings of underscore characters with "blank". I also think that using the blank is a reasonable way to present a question and we should support it if we can. I don't think it's a common enough use case to merit a custom tag.

If it is technically difficult to support, we can perhaps modify the present card to end with an ellipsis, i.e. "We'll need to mix milk and banana puree in the ratio ...".  But I think blanks are going to be used in other lessons, such as English, so it would be nice to support them out of the box.

Please let me know if you need further information/clarification. Thanks!

**Comment by BenHenning** [comment]
> > Thanks @subhajitxyz and @adhiamboperes. It makes sense to compute a separate content description that eliminates extra characters like these. I think the problems here are ultimately:
> > 
> > 1. What's the correct pedagogical way to solve the problem?
> > 2. How do we solve this in a technically clean way?
> > 
> > Per (1), it would be helpful to get your thoughts @seanlip. This probably affects web with a screenreader as well, and I'm curious if there's a better way for us to communicate a "fill in the blank" (maybe using a custom tag or avoiding fill in the blank). WDYT?
> > (2) is pretty dependent on (1), but one existing issue I see is making sure that we localize 'Blank' properly. That being said, I think we need to wait on understanding (1) first since another option is also to process this information as part of the lesson download script.
> 
> @BenHenning Thanks for looping me in. I think what @subhajitxyz shows in their current demo is fine, i.e. replacing long strings of underscore characters with "blank". I also think that using the blank is a reasonable way to present a question and we should support it if we can. I don't think it's a common enough use case to merit a custom tag.
> 
> If it is technically difficult to support, we can perhaps modify the present card to end with an ellipsis, i.e. "We'll need to mix milk and banana puree in the ratio ...". But I think blanks are going to be used in other lessons, such as English, so it would be nice to support them out of the box.
> 
> Please let me know if you need further information/clarification. Thanks!

Thanks @seanlip.

For additional context, Sean and I discussed this further in a meeting last week. We're essentially in agreement that having a different readout for accessibility use cases makes sense (since the underscore readout isn't great), but we differ on approach. As a result:
- Content will continue using underscores to represent blanks since it's reasonable.
- On Android, we'll probably prefer to use a custom tag that's injected as part of the lesson import process (via the lesson download script) which we can then hook into the existing custom tag system for content description generation.
- The previous approach will require some long-term fixes we've thought of doing to the custom tag system to properly support content description generation (see #4848).
- These are longer-term solutions, so I think it makes sense to get this current PR into a reasonable state and check it in and file an issue to track the preferred, longer-term solution of using a custom tag.

In order to get this PR into a good state, it still needs:
- To use a string for the "Blank" text so that it can be correctly translated.
- To introduce tests to verify that the updated content description is correct.

@adhiamboperes do you have any thoughts on this?

@subhajitxyz I think you can go ahead and work on the last 2 items listed above to get this PR into a viable state for merging.

**Comment by subhajitxyz** [comment]
PTAL, @adhiamboperes .

**Review by adhiamboperes — APPROVED** [review]
Thanks @subhajitxyz! This LGTM.

**Comment by subhajitxyz** [comment]
Thank you.

**Pull request merged**
