### PR TITLE
Fix #1978: Optimised code in administrator_controls_download_permissions_view.xml    

### LINKED ISSUE #1978: Optimise code in administrator_controls_download_permissions_view.xml
This issue is tracking the optimization work of `administrator_controls_download_permissions_view.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all TextViews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be the same as before (or an optimized version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by Aarkin7**
…l #1978

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@BenHenning @Sarthak2601 Any idea why this particular test case is failing?

Screenshot 2020-10-13 at 8 25 15 PM

**Comment by rt4914** [comment]
@Aarkin7 Can you update your branch with latest develop ? Maybe that will help to pass the tests.

**Comment by Aarkin7** [comment]
@rt4914 I checked, but my branch is up to date with the latest develop.

**Comment by rt4914** [comment]
> @rt4914 I checked, but my branch is up to date with the latest develop.

@Aarkin7 Actually it is upto date with your forked develop, not the `oppia-android/develop`.
Screenshot 2020-10-13 at 9 04 44 PM

https://github.com/Aarkin7/oppia-android/tree/develop

**Comment by Sarthak2601** [comment]
> @BenHenning @Sarthak2601 Any idea why this particular test case is failing?
> 
> Screenshot 2020-10-13 at 8 25 15 PM

I think updating with develop resolved the problem.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
