### PR TITLE
Fix #689: My Download Item in Nav Drawer

### LINKED ISSUE #689: Lowfi MyDownloads option Navigation Drawer
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/42d3b9aa-8cb7-4ff0-b375-42117c3aed7e/PM-EN-Play-Tab-Side-Menu-

MyDownloadsActivity has already been created but has not been linked to NavigationDrawer, we need to link that to NavigationDrawer.

Icon Link: https://drive.google.com/open?id=1CDqhmWKERmU_34_OIJh0_II5bezWozkJ

Also, add test cases to check whether on click on MyDownloads opens that activity or not.

### PR DESCRIPTION
**Pull request by SayantanBanerjee16**
## Explanation

Fixes part of #689 

My Download option is added to the Navigation Drawer. And clicking on it MyDownloads fragment open.

Also initially .idea files were tracking so I made another commit to remove those and untrack them.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
Actually this PR has been created in a wrong way.

First of all we need all the `.idea` files, so don't remove them but at the same time make sure that you don not introduce any unnecessary changes to those files.

Second, the task is just to introduce MyDownloads item in navigation and when we click on it, it should open MyDownloadsActivity, other than that you don't need to change the implementation of MyDownloads.

**Comment by rt4914** [comment]
Also, please change the PR title to :

`Fix #689: My Download Item in Nav Drawer`

**Comment by SayantanBanerjee16** [comment]
@rt4914 Thank you for your review.

Apart from introducing MyDownloads item in Navigation and on clicking it opening the My Downloads Activity, there is no toolbar present in it so as to navigate in the drawer using the hamburger icon. So I adjusted the code so as to make the toolbar present so that the user can navigate to other activities in the Navigation drawer by clicking on the hamburger icon. Should I revert from doing this? Well, it's working as expected in my device.

Also, any suggestions on how to bring back those deleted files and keep those files away from getting tracked.

Get a merge from latest develop and that should work. or else just create them with same content from develop.

**Comment by rt4914** [comment]
> @rt4914 Thank you for your review.
> 
> Apart from introducing MyDownloads item in Navigation and on clicking it opening the My Downloads Activity, there is no toolbar present in it so as to navigate in the drawer using the hamburger icon. So I adjusted the code so as to make the toolbar present so that the user can navigate to other activities in the Navigation drawer by clicking on the hamburger icon. Should I revert from doing this? Well, it's working as expected in my device.
> 
> Also, any suggestions on how to bring back those deleted files and keep those files away from getting tracked.

Actually for now we don't need to add hamburger icon to MyDownloads. Yes please revert this, the working is correct but actually the code architecture is incorrect thats why.

**Pull request closed without merging**
