### PR TITLE
Fix #2256: Pin Verification screen A11y

### LINKED ISSUE #2256: Changes needed in Pin Password Activity [A11y] [BLOCKED]
**Describe the bug**

Pin Password Activity is not fully compatible with some users from the Accessibility point of view.

Issue 1 - The pinView inside the pin_password_activity.xml does not have any content label (inactive state)
Issue 2 - The reset pin dialog box has a profile input view which also misses a label.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and try to login as a user. 
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    |
|:--------:|:-------------:|
|Screenshot_2020-12-06-23-55-11-56_80a9469f53bfe75dbc6e8989be28e2f0|  Screenshot_2020-12-06-23-54-15-94_80a9469f53bfe75dbc6e8989be28e2f0 | 
|Screenshot_2020-12-06-23-53-09-67_80a9469f53bfe75dbc6e8989be28e2f0| |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fix #2256 
Fixes part of #2627 

## Output Recording

https://user-images.githubusercontent.com/9396084/108887548-6a5e3a00-7630-11eb-945a-c832b869b2f3.mp4

## Output Text
`Showing Numeric password keyboard` , `Pin password page`, `Editing, Enter your PIN, Edit box`, `Double-tap and hold to long press`.

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@BenHenning and @mschanteltc Please address my queries mentioned in the description. Thanks.

**Comment by mschanteltc** [comment]
> @BenHenning and @mschanteltc Please address my queries mentioned in the description. Thanks.

The strings you suggested LGTM.

**Comment by rt4914** [comment]
> > @BenHenning and @mschanteltc Please address my queries mentioned in the description. Thanks.
> 
> The strings you suggested LGTM.

@mschanteltc Thanks.

**Comment by BenHenning** [comment]
Strings also LGTM. My main concern in this case would be overcontextualizing the user, but I think we're adding the correct level of detail in this context.

Thanks @rt4914.

**Comment by rt4914** [comment]
Recreated at #3060

**Pull request closed without merging**
