### PR TITLE
Fix #3803, #3804, #3853, #3669, #3383: Add basic KitKat support in Bazel

### LINKED ISSUE #3383: Find a way to use Optional below Build Version N
**Describe the bug**
Currently, the `Optional` used in the `NavigationDrawerFragmentPresenter` for checking `DeveloperOptionsStarter` works only for Build Versions greater than **N**.

**To Reproduce**
1. Go to `NavigationDrawerFragmentPresenter`
2. See TODO in `setIfDeveloperOptionsMenuItemListener` method.

**Expected behavior**
This feature should work for all Build Versions.

### LINKED ISSUE #3669: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional
**Describe the bug**
The app crashes when I press on a profile to reach the main screen.

**To Reproduce**
1. Navigate to the profile chooser screen.
2. Choose any profile.
3. App crashes.

**Expected behavior**
The app opens the home screen normally.

**Device**
- Huawei Y6 II (Cam L21)
- API level 23

**Full Log**
```
FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 28847
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1577)
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1569)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:59)
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:15)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.injectNavigationDrawerFragment(DaggerApplicationComponent.java:3436)
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.inject(DaggerApplicationComponent.java:3160)
        at org.oppia.android.app.drawer.NavigationDrawerFragment.onAttach(NavigationDrawerFragment.kt:24)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2669)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:229)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1215)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:109)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:781)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at org.oppia.android.app.home.HomeActivityPresenter.handleOnCreate(HomeActivityPresenter.kt:20)
        at org.oppia.android.app.home.HomeActivity.onCreate(HomeActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:6372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
        at android.app.ActivityThread.access$900(ActivityThread.java:168)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5659)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Optional" on path: DexPathList[[zip file "/data/app/org.oppia.android-1/base.apk"],nativeLibraryDirectories=[/data/app/org.oppia.android-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1577) 
        at org.oppia.android.app.application.DaggerApplicationComponent$PresentJdkOptionalInstanceProvider.get(DaggerApplicationComponent.java:1569) 
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:59) 
        at org.oppia.android.app.drawer.NavigationDrawerFragmentPresenter_Factory.get(NavigationDrawerFragmentPresenter_Factory.java:15) 
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.injectNavigationDrawerFragment(DaggerApplicationComponent.java:3436) 
        at org.oppia.android.app.application.DaggerApplicationComponent$ActivityComponentImpl$FragmentComponentImpl.inject(DaggerApplicationComponent.java:3160) 
        at org.oppia.android.app.drawer.NavigationDrawerFragment.onAttach(NavigationDrawerFragment.kt:24) 
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2669) 
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:229) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1215) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398) 
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:109) 
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135) 
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356) 
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:781) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:862) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:537) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:437) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170) 
        at org.oppia.android.app.home.HomeActivityPresenter.handleOnCreate(HomeActivityPresenter.kt:20) 
        at org.oppia.android.app.home.HomeActivity.onCreate(HomeActivity.kt:39) 
        at android.app.Activity.performCreate(Activity.java:6372) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539) 
        at android.app.ActivityThread.access$900(ActivityThread.java:168) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5659) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
    	Suppressed: java.lang.ClassNotFoundException: java.util.Optional
    		at java.lang.Class.classForName
```

### LINKED ISSUE #3803: Bazel/Gradle Support on Kitkat
**Describe the bug**
Currently, the Bazel build apk does not work on kitkat (API 19)

**To Reproduce**
1. Build apk using Bazel and install on API level 19.
2. App crash

**Expected behavior**
The app should run correctly without any crashes.

**Additional Context**
As per AlphaMR3, if it takes longer to bring Bazel support, use Gradle as a build system to run APK on KitKat version.

### LINKED ISSUE #3804: Bazel not support vector drawables
**Describe the bug**
Currently, the Bazel-built APK doesn't support vector drawables. 
Bazel Issue - https://github.com/bazelbuild/bazel/issues/2197 

**To Reproduce**
1. Build APK using Bazel from https://github.com/oppia/oppia-android/pull/3740
2. Run APK on any device
3. App crash with the following error

Error 1 on Kitkat
```
org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 2071
    java.lang.RuntimeException: Unable to start service androidx.work.impl.background.systemalarm.SystemAlarmService@9d18da98 with Intent { act=ACTION_RESCHEDULE cmp=org.oppia.android/androidx.work.impl.background.systemalarm.SystemAlarmService (has extras) }: java.lang.SecurityException: Neither user 10076 nor current process has android.permission.WAKE_LOCK.
```

Solution 1 (Dangerous Solution)
```
<uses-permission android:name="android.permission.WAKE_LOCK" />
```

Error 2
```
org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 2876
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.oppia.android/org.oppia.android.app.splash.SplashActivity}: android.content.res.Resources$NotFoundException: File res/drawable/splash_page.xml from drawable resource ID #0x7f080146
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/splash_page.xml from drawable resource ID #0x7f080146
        at android.content.res.Resources.loadDrawable(Resources.java:2101)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3042)
        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3085)
        at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678)
        at androidx.appcompat.app.AppCompatDelegateImpl.x(SourceFile:7864)
        at androidx.appcompat.app.AppCompatDelegateImpl.c(SourceFile:693)
        at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:170)
        at org.oppia.android.app.splash.a.a(SourceFile:34)
        at org.oppia.android.app.splash.SplashActivity.onCreate(SourceFile:17)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2097)
        at android.content.res.Resources.getDrawable(Resources.java:700) 
        at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3042) 
        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3085) 
        at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678) 
        at androidx.appcompat.app.AppCompatDelegateImpl.x(SourceFile:7864) 
        at androidx.appcompat.app.AppCompatDelegateImpl.c(SourceFile:693) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:170) 
        at org.oppia.android.app.splash.a.a(SourceFile:34) 
        at org.oppia.android.app.splash.SplashActivity.onCreate(SourceFile:17) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Expected behavior**
Find an alternative solution to support our vector drawable. 

**Unsupported Files**

1. ic_add_profile.xml
2. ic_admin_settings_icon_black_24dp.xml
3. ic_admin_settings_icon_brown_24dp.xml
4. ic_admin_settings_icon_grey_24dp.xml
5. ic_arrow_back_black_24_dp.xml
6. ic_arrow_back_oppia_dark_blue_24dp.xml
7. ic_arrow_back_white_24dp.xml
8. ic_arrow_down_grey_24dp.xml
9. ic_arrow_drop_down_black_24dp.xml
10. ic_arrow_drop_up_black_24dp.xml
11. ic_arrow_forward_black_24dp.xml
12. ic_arrow_forward_oppia_dark_blue_24dp.xml
13. ic_arrow_right_alt_24dp.xml
14. ic_arrow_right_grey_24dp.xml
15. ic_arrow_up_black_24dp.xml
16. ic_audio_lang_24px.xml
17. ic_audio_streaming_off_24dp.xml
18. ic_audio_streaming_on_24dp.xml
19. ic_available_offline_icon_white_12dp.xml
20. ic_available_offline_primary_24dp.xml
21. ic_baseline_code_24.xml
22. ic_baseline_lock_24.xml
23. ic_check_24dp.xml
24. ic_check_box_checked.xml
25. ic_check_box_disabled.xml
26. ic_check_box_unchecked.xml
27. ic_check_circle_primary_24dp.xml
28. ic_check_primary.xml
29. ic_close_white_24dp.xml
30. ic_default_avatar.xml
31. ic_dot_yellow_24dp.xml
32. ic_edit_18.xml
33. ic_edit.xml
34. ic_file_download_primary_24dp.xml
35. ic_folder_open_24dp.xml
36. ic_help_grey_icon_24dp.xml
37. ic_hide_eye_icon.xml
38. ic_hint_bulb_white_24dp.xml
39. ic_home_icon_grey_24dp.xml
40. ic_info_icon_24dp.xml
41. ic_info_icon_gray_24dp.xml
42. ic_info_icon.xml
43. ic_keyboard_arrow_down_black_24dp.xml
44. ic_keyboard_arrow_up_black_24dp.xml
45. ic_landscape_onboarding_0_tablet.xml
46. ic_landscape_onboarding_0.xml
47. ic_landscape_onboarding_1_tablet.xml
48. ic_landscape_onboarding_1.xml
49. ic_landscape_onboarding_2_tablet.xml
50. ic_landscape_onboarding_2.xml
51. ic_landscape_onboarding_3_tablet.xml
52. ic_landscape_onboarding_3.xml
53. ic_language_icon_grey_24dp.xml
54. ic_lessons_icon_24dp.xml
55. ic_merge_icon_24.xml
56. ic_options_icon_grey_24dp.xml
57. ic_pause_circle_filled_white_24dp.xml
58. ic_pending_24dp.xml
59. ic_play_circle_filled_white_24dp.xml
60. ic_portrait_onboarding_0.xml
61. ic_portrait_onboarding_1.xml
62. ic_portrait_onboarding_2.xml
63. ic_portrait_onboarding_3.xml
64. ic_practice_icon_24dp.xml
65. ic_profile_exit.xml
66. ic_refresh_white_24dp.xml
67. ic_revision_icon_24dp.xml
68. ic_settings_grey_48dp.xml
69. ic_show_eye_icon.xml
70. ic_start_over_24dp.xml
71. ic_unlink_icon_24.xml
72. ic_upload_photo.xml
73. lesson_thumbnail_graphic_baker.xml
74. lesson_thumbnail_graphic_child_with_book.xml
75. lesson_thumbnail_graphic_child_with_cupcakes.xml
76. lesson_thumbnail_graphic_child_with_fractions_homework.xml
77. lesson_thumbnail_graphic_duck_and_chicken.xml
78. lesson_thumbnail_graphic_person_with_pie_chart.xml
79. splash_page.xml

### LINKED ISSUE #3853: Unable to run app on API 19 because of Okhttp library
Unable to run app on API 19 because of Okhttp library as it requires minimum of API 21.

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fix #3803
Fix #3804
Fix #3853
Fix #3669
Fix #3383

Introducing basic KitKat support (that is, support for the app to open and be minimally stable during usage) required the following work:
1. Introducing a permission needed by AndroidX WorkManager
2. Introducing proper legacy multidex support (with Bazel-specific issues--see below & #3803)
3. Adding support for vector graphics (which is API 21+ normally -- #3804)
4. Removing/disabling OkHttp (which doesn't have KitKat support -- #3853)
5. Fixing some Java 8 incompatibilities
6. Properly setting up the build for KitKat due to build-specializations

Each of these are covered in more detail in later sections. Note that this PR continues the work from #3740 and #3723 which provided the basis for addressing the OkHttp dependency issue, and parts of the dexing issues.

### New permission
Per https://developer.android.com/reference/androidx/work/package-summary AndroidX WorkManager requires the WAKE_LOCK permission before SDK 23 in order to properly handle background service/keep-device-awake scenarios for triggering workflows depending on certain conditions. This isn't KitKat specific, but it was a prerequisite for the app to run on KitKat devices.

### Legacy multidex support in Bazel
Bazel supports three types of multidex modes: legacy, native, and manual. Native relies on the native ART environment to support reading from multiple dex fiiles at runtime, and works without issue.

Legacy assumes that the application extends AndroidX's multidex application to handle scenarios where multidex is needed (which it is for Oppia since we have 3 dex files compiled for the size of the developer flavor of the app). However, a big part of this is computing what files should go into the main dex file list for the app. Bazel uses some mechanism to compute this list (which I think uses D8 via a compatibility bridge in Android buiol-tools), but unlike Gradle it seems to have issues computing a list that can actually fit within the main dex list. This is a problem because the main dex list needs to contain everything necessary to load the main application class so that multidex can kick in & initialization can start (more on this later). It's not clear to me why Gradle works and Bazel fails (as in, will fail with a compiler error when trying to use "legacy"), but I suspect it has to do with Gradle using the new R8 dexer (which isn't yet available via Bazel per #3748). Finally, this isn't an issue for the alpha version of the app since Proguard brings the dex file list much lower (down to 2), so Bazel seems fine computing a proper main dex list.

Given neither native nor legacy are options for a KitKat-enabled dev build with Bazel, we are left with using the manual list. Some background on how multidex works might be helpful for why this is needed. Android 19 and prior assumed there is only ever 1 dex file on the system (and prior to I think SDK 4 it wasn't even possible to load more than one at runtime). This is an issue when the app exceeds dex file limits (such as having more than 64K methods), so multidex was introduced to allow loading additional dex files at runtime to extend the size potential of apps. This comes at a large performance cost, but it provides more flexibility. However, the main dex list still must contain *the entire dependency closure of the core application class pathway* in order for multidex to be initialized. I think this is why Bazel's computation breaks down because OppiaApplication references the core Dagger component which, in turn, essentially references every class in the Oppia codebase.

In reality, we actually need a much smaller minimal list to run. I started off by using Facebook's redex utility (https://github.com/facebook/redex/blob/master/docs/interdex.md which required some monkeypatching due to a Python incompatibility) to generate an initial list (https://gist.github.com/BenHenning/23b4887f94c42e8654bf552d26376fcc) of ~16k dependencies that was weeded down to the bare minimum necessary for the central pathway to work. Note that the main dex file will still be filled up with other dependencies that Bazel thinks are likely to be loaded early on, but the list guarantees that at least those files will be present. Note that this approach has a few drawbacks:
1. Minimizing the startup dependencies will result in a potentially less efficient startup compared with a fine-tuned list (though that would likely require automation like redex to keep it up-to-date)
2. Changes to the OppiaApplication class or certain third-party dependencies can very likely break the KitKat startup flow, so introducing a KitKat e2e test that runs in CI will be really important (#3911 is tracking introducing the test).

### Support for vector graphics on API 19
Support for vector drawables weren't added until API 21. There are essentially three ways to work around this issue:
1. Don't use vector drawables (not preferable since vectors are smaller in file size, higher fidelity, more VCS-friendly, and easier to manually change if needed)
2. Generate PNGs for vector drawables at different display densities as a fallback on SDK 19 & below (Gradle-only; not an option on Bazel--see #3804)
3. Use the compatibility portion of the AndroidX library to load vector drawables at runtime through AndroidX rather than native Android

Given (1) isn't an option, I spent some time trying to get (2) to work by introducing a custom routine that would convert vector drawables to SVGs (taking inspiration from posts like https://stackoverflow.com/a/46350218/3689782), where I then planned to render out the SVGs as PNGs using https://github.com/sterlp/svg2png. There were other libraries I came across that tried to compute SVGs from vector drawables (essentially the reverse of Android Studio's import process), but they didn't work for vector drawables that use linear gradients as a fill type (which some of Oppia Android's do). I built an initial script (which can be viewed in one of the commits in the history of this branch) that successfully converted about 40% of Oppia Android's vector drawables, but given the additional work to bring in PNG support & convert to the correct display density, it seemed better to go with (3).

For (3), I came across resources:
- https://medium.com/androiddevelopers/using-vector-assets-in-android-apps-4318fd662eb9
- https://developer.android.com/reference/androidx/vectordrawable/graphics/drawable/VectorDrawableCompat
- https://medium.com/androiddevelopers/appcompat-v23-2-age-of-the-vectors-91cbafa87c88

All of which were really helpful in outlining the core considerations when trying to properly hook into the compat library for vectors. These are (in no particular order):
- Needing to use the 'compat' variants for drawable attributes, particularly for image:src, android:drawableStart, android:drawableTop, etc.
- Needing to enable replacing the resource loading pipeline for drawables to route through AndroidX (to cover cases when attributes aren't replaced, such as compound drawables, layer-lists, and background drawables)
- Needing to ensure that when running AAPT2 not to inadvertently move vector drawables to an API 21+ qualified resource folder since they're technically unsupported below that version \*

This PR makes the compat changes & adds both new regex checks & corresponding tests to ensure these stay correct long-term. It also updates OppiaApplication to enable the pipelining bit, though this does come at some potential cost to memory and stability (see medium articles above & https://issuetracker.google.com/issues/37090849 for some background). It's much more straightforward than the alternative (which would probably requiring abstraction _all_ of our drawable loading to ensure mistakes aren't introduced that would caused tricky-to-anticipate crashes on KitKat devices), so I think it's a reasonable first step until we get more data on general app stability on KitKat devices. Another need for this is that the databinding library itself will load drawables through the native resources object rather than utilizing the compat library (see https://issuetracker.google.com/issues/111345022 for the open issue tracking this).

Note also that some binding adapter changes were needed to accommodate the new uses of compat attributes, but none of these seemed too unusual (though do note that some layout uses needed to be updated to use databinding).

Finally, https://stackoverflow.com/a/41855830/3689782 is a really nice infographic someone made that better explains the situation (we fall under the bottom case since we decided to leverage the compatibility bridge).

\* Note that I didn't do anything extra here for Bazel since it seems to already pass the correct flag. Gradle requires additional configuration (see the medium articles above), but I didn't bother since it already generates the PNG variants today & we are planning to utilize Bazel as our distribution build system for alpha MR3 & onward.

### OkHttp dependency workaround
The previous PRs cover this topic in good detail, but just to recap so that it's in one place: OkHttp dropped KitKat support (see https://github.com/oppia/oppia-android/pull/3723#discussion_r695156461 for thoughts & context).

We're still trying to figure out from the product side what we should do about the de facto networking library no longer supporting KitKat, but at the moment since the app doesn't actually rely on networking for core functionality we decided just to hide Retrofit (which uses OkHttp underneath) behind an Optional wherein it's absent on KitKat devices to avoid loading in the OkHttp stack. Longer-term, this ought to be compiled-out entirely in KitKat builds (another TODO was added on #1720 to track this).

A new test suite was added to verify that Retrofit & services are properly present/absent when expected.

### Java 8 incompatibility fix
There are some unexpected incompatibilities when trying to desugar Java 8 APIs for KitKat. It's not entirely clear to me why this is broken (seemingly for both Bazel & Gradle builds), but the easy workaround was to use Guava's Optional instead (since we're already pulling in Guava for select other uses).

To ensure compatibility, a new regex check was added to ensure that only Guava Optionals are used in the future (since another case of Java 8 Optional needed to be fixed in order to resolve an incompatibility which inadvertently fixed #3383).

There may be other Java 8 desguaring incompatibilities that we will run into later, but for now we'll continue heavily using Kotlin collections since they reduce this risk.

### Build specializations for KitKat & version code changes
In order to simplify build management, some big changes were made around our build flavors:
- //:oppia was updated so that it actually uses version codes & a transformed manifest for parity with its AAB counterpart
- An //:oppia_kitkat build was introduced for parity with //:oppia, but for KitKat-compatibility
- oppia_dev & oppia_alpha AAB flavors now have KitKat complements: oppia_dev_kitkat & oppia_alpha_kitkat, respectively
- The "KitKat" variants of each of the above leverage a different minimum SDK & manual dex list, and the non-KitKat versions are L+ with native multidex configured for better performance (and eventual true build differences once Dagger Hilt is supported)

Version codes were updated to be flavor-specific (based on AABs since these are what we're planning to ship). This is the first iteration of multiple future changes around building an automated release flow. The numbers themselves are starting at 10 since version codes 9 and before have been used on the Play Store or in previous APKs we've used in prototypes, demos, or studies. The order is intentional such that KitKat is always lower than non-KitKat (so that non-KitKat devices prefer the non-KitKat variant), and more stable builds are higher precedence than less table (i.e. alpha > dev).

CI has been updated to include steps for each of the 3 new KitKat builds (not separate jobs). This *might* cause an issue with longer CI runtimes (particularly for alpha since there could be 2 Proguard builds in sequence in the future per the Bazel Proguard/main dex list issue mentioned below), but if that happens we can split up each build to its own workflow (preferably with a shared action script since the workflows are becoming highly redundant at this point).

Finally, note that there's one issue with the alpha KitKat builds. Bazel seems to have an issue when trying to use a manual main dex class list with Proguard and just fails. #3886 is tracking this, but the takeaway is that we won't be able to ship a Proguard optimized version of the app for KitKat. This is fine in our current release stage, but it's definitely not optimal and something we'll want to fix once we see broader KitKat usage.

### Script pattern changes & miscellaneous considerations (including Glide stability issues)
- See the vector graphics section for details on the regex pattern & test changes for drawable-related patterns
- The shadow, tests, and implementation for BidiFormatter were updated to use AndroidX's instead since the built-in BidiFormatter isn't available on API 19
- A new regex pattern was added to ban Java 8 Optional per the incompatibility mentioned above
- I only tested this on an emulator since I don't have access at the moment to a physical KitKat device (though I'm working with a PM contributor to get this tested on a physical KitKat device)
- I noticed upon testing that Glide seems to have some issues when loading & transforming vector drawables from disk. I don't have an immediate fix, but #3887 is tracking the issue.
- I added myself as the codeowner for the new main dex file list since I think I have the best context to maintain this file at this point, but it's something that could go to a general release team in the future

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
There are no UI-specific changes corresponding to this PR since it's simply providing basic KitKat support.

### CODE REVIEW

**Comment by BenHenning** [comment]
The PR is looking pretty good locally, so I'm going ahead and sending this into review now. There might be some CI hiccups, but I'll address them tomorrow my time.

@rt4914 PTAL for codeowners.
@seanlip PTAL for new codeowner file/change.
@anandwana001 PTAL for codeowners & the general Bazel setup going on here since it'd be good to get a set of eyes on those changes.

**Review by seanlip — APPROVED** [review]
Thanks @BenHenning! LGTM for codeowners.

**Review by anandwana001 — APPROVED** [review]
LGTM 🎉

**Comment by BenHenning** [comment]
Note that the builds in CI seem to be working well. See https://github.com/oppia/oppia-android/pull/3910/checks?check_run_id=3824699336 for artifacts (you can easily download & try out the KitKat builds if you'd like).

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by BenHenning** [comment]
Thanks all! Merging now.

**Pull request merged**
