### PR TITLE
Fix #2491: Required Reformatting for administrator_controls_account_actions_view.xml

### LINKED ISSUE #2491: Required Reformatting for administrator_controls_account_actions_view.xml
The following files require reformatting
 - layout/administrator_controls_account_actions_view.xml
 - layout-land/administrator_controls_account_actions_view.xml
 - layout-sw600dp/administrator_controls_account_actions_view.xml 

Recommended to set up [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

### PR DESCRIPTION
**Pull request by Manikant25**
## Explanation
Fixes #2491 , Reformated 
- layout/administrator_controls_account_actions_view.xml
- layout-land/administrator_controls_account_actions_view.xml
- layout-sw600dp/administrator_controls_account_actions_view.xml

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by FareesHussain** [comment]
@Manikant25 can you please recheck this file for reformatting
`layout/administrator_controls_account_actions_view.xml`

**Comment by Manikant25** [comment]
Okay I check

**Comment by Manikant25** [comment]
@FareesHussain I checked again when I applied for reformating, it says code is already formated

**Comment by FareesHussain** [comment]
> @FareesHussain I checked again when I applied for reformating, it says code is already formated

Can you update your branch and recheck it? for me, it is not reformatted yet

**Review by FareesHussain — CHANGES_REQUESTED** [review]
@Manikant25 You've already made changes for 
`layout/administrator_controls_account_actions_view.xml`

please update 
`layout-land/administrator_controls_account_actions_view.xml` as well

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Blocking as per this comment: https://github.com/oppia/oppia-android/pull/2534#pullrequestreview-573996635

**Comment by rt4914** [comment]
@Manikant25 PTAL

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
