### PR TITLE
Fix #2148: [RTL] High fi Topic-Info tab

### LINKED ISSUE #2148: [RTL] High fi Topic-Info tab
`Topic-Info` needs RTL support as shown in below screen.
TP (Overview)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by MaskedCarrot**
## Explanation

Fixes #2148

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### phone
portrait | landscape
--- | --- 
Screenshot_1606739088|Screenshot_1606739107

### tablet
portrait | landscape
--- | --- 
Screenshot_1606739296|Screenshot_1606739287

### CODE REVIEW

**Comment by MaskedCarrot** [comment]
@rt4914 I need some help. Can you please give me a few more pointers on what needs to be done to fix this issue. I did what the article said on medium but I am not sure that the work here is compete.

**Comment by MaskedCarrot** [comment]
@rt4914 I need some help. Can you please give me a few more pointers on what needs to be done to fix this issue. I did what the article said on medium but I am not sure that the work here is compete

**Comment by MaskedCarrot** [comment]
I need some help. Can you please give me a few more pointers on what needs to be done to fix this issue? I did what the article said on medium but I am not sure that the work here is compete

**Comment by MaskedCarrot** [comment]
If i am using `android:textDirection="loacale" then the output is like this`

Screenshot_1606323421

If i am using `android:textAlignment="viewStart" then the output is like this`

Screenshot_1606323707


which one should I use?

**Comment by rt4914** [comment]
> If i am using `android:textDirection="loacale" then the output is like this`
> 
> Screenshot_1606323421
> 
> If i am using `android:textAlignment="viewStart" then the output is like this`
> 
> Screenshot_1606323707
> 
> which one should I use?

@MaskedCarrot I am confused here because the screenshots that you have placed are completely different and because of which its not easy to understand what you are trying to communicate.
Can you please add same configuration screenshot for different the code changes? That way we can easily understand what you are trying to communicate and what we have to focus on.

**Comment by MaskedCarrot** [comment]
i have one question regarding the alignment of the text. The current alignment of the text as shown by the screenshots in the pr description, the text `1 Story` is aligned as it is aligned in the screenshot of the issue #2168. But shouldn't we align this as `Story 1` for the languages written this in rtl?

**Comment by rt4914** [comment]
> i have one question regarding the alignment of the text. The current alignment of the text as shown by the screenshots in the pr description, the text `1 Story` is aligned as it is aligned in the screenshot of the issue #2168. But shouldn't we align this as `Story 1` for the languages written this in rtl?

@MaskedCarrot Yes you are absolutely right. It should be `Story 1` and the same thing applies for topic size too. It should be `KB 100` for RTL and `100 KB` for LTR.

**Comment by rt4914** [comment]
For Reference:
Tablet Landscape LTR | Tablet Landscape RTL
--- | ---
 | 

Tablet Portrait LTR | Tablet Portrait RTL
--- | ---
 | 


Mobile Landscape LTR | Mobile Landscape RTL
--- | ---
 | 

Mobile Portrait LTR | Mobile Portrait RTL
--- | ---
 |

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
