### PR TITLE
Fix #2145, Added RTL Support for Ongoing_topic_item (Topics In Progress)

### LINKED ISSUE #2145: [RTL] Highfi Topics In Progress / OngoingTopicList
`TopicsInProgress` or `OngoingTopicList` needs RTL support as shown in below screen.
UP (Topics in Progress)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by ForgottenProgramme**
**Fix #2145**
**RTL support was added for 'Topics In Progress' or 'ongoing_topic_item'.**
gravity was changes from "top" to "start" and android:textAlignment="viewStart" was added in the ongoing_topic_item.xml file is the following folders:
1. layout-land
2. layout-sw600dp-land 
3. layout-sw600dp-port folder
4. layout

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Screenshots: 

Mobile Portrait: 

mobile_portrait

Mobile Landscape: 

mobile_landscape

Tab Portrait: 
tab_portrait

Tab Landscape:

tab_landscape

### CODE REVIEW

**Comment by ForgottenProgramme** [comment]
@rt4914 , I have tried to solve #2145 by creating this PR. 
Please have a look. 

Also, Rajat, I see that my PR shows that I have made changes in 7 files. I don't know why that is. I only made changes in 4 files. 
The checklist in the PR template said that there should not be any unnecessary auto generated code by android studio. I think those other 3 files contain that auto generated code.
I couldn't figure out how to undo/remove it. 

Please kindly let me know if something needs to be done about it, and how? 
Thankyou. :)

**Comment by FareesHussain** [comment]
Check the changes made in those files
https://github.com/oppia/oppia-android/pull/2172/files
i.e Project.xml, Build.gradle, graddle-wrapper.properties

You can revert them just by copy paste from the following links
https://github.com/oppia/oppia-android/blob/develop/.idea/codeStyles/Project.xml
https://github.com/oppia/oppia-android/blob/develop/build.gradle
https://github.com/oppia/oppia-android/blob/develop/gradle/wrapper/gradle-wrapper.properties

and then commit those changes

**Comment by ForgottenProgramme** [comment]
Update: 
@rt4914 , with @FareesHussain 's help, I was able to revert the unnecessary changes I had made by mistake. 
Thankyou @FareesHussain.

**Comment by rt4914** [comment]
Adding Screenshots for reference:
## LTR
Screenshot_1606392475
Screenshot_1606392483
Screenshot_1606392886
Screenshot_1606392889

##RTL

Screenshot_1606392909
Screenshot_1606392920
Screenshot_1606392949
Screenshot_1606392957

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
