### PR TITLE
Fixes Part of #4195 : Dark mode implementation - Different Interactions items of Questions and Exploration

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

Fixes Part of #4195 : Dark mode implementation - Different Interactions items of Questions and Exploration

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### Different Interactions

   

   

   

   

   

   

   

   

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by MohitGupta121 — COMMENTED** [review]
@rt4914 PTAL, can you please review this PR.

**Review by rt4914 — CHANGES_REQUESTED** [review]
The radio button and checkbox have different color as compared to white in dark-mode 

https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/1b989f5c-a308-4b50-a2f6-c33cd1358f19/

https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/0dad002b-0619-4c52-9dca-e19ca1a5d449/

**Comment by MohitGupta121** [comment]
> The radio button and checkbox have different color as compared to white in dark-mode

Okay I will change it.

**Comment by MohitGupta121** [comment]
@rt4914 PTAL, now updated the requested changes.
Also updating the PR description screenshots.

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.

**Pull request merged**
