### PR TITLE
CODEOWNERS CI validation + pattern fixes

### PR DESCRIPTION
**Pull request by BenHenning**
It seems the previous layout pattern wasn't actually matching to @rt4914. I'm hoping the adjustment fixes the issue.

Also, I'm going to try removing my global ownership & instead rely on a CI check to verify that new files that aren't owned are properly checked (https://github.com/mszostok/codeowners-validator). In particular, this enables the following checks:
- Checking for files not covered by CODEOWNERS ([example with multiple files](https://github.com/oppia/oppia-android/runs/1699249920), [example when creating a new file](https://github.com/oppia/oppia-android/runs/1699603642))
- Checking for invalid syntax ([example](https://github.com/oppia/oppia-android/runs/1699568417))
- Patterns that don't correspond to real files ([example](https://github.com/oppia/oppia-android/runs/1699534276))
- Duplicate patterns ([example](https://github.com/oppia/oppia-android/runs/1699534276))

Note that there are a bunch of new CODEOWNERS changes to cover the missing files from the removal of the global code ownership line.

Separately, the new static checks workflow is meant to contain all static-type checks in the future (including linters and our future custom static analysis checks). For now, it will just contain the CODEOWNERS check. I'll be making it a required check once this PR is merged.

### CODE REVIEW

**Comment by BenHenning** [comment]
Reopening to restart CI.

**Comment by seanlip** [comment]
Just FYI, we already have codeowner lint checks in https://github.com/oppia/oppia/blob/develop/scripts/linters/codeowner_linter.py, in case they are useful for you!

**Comment by BenHenning** [comment]
Thanks @seanlip. I was aware of that, but the approach taken here seems a bit simpler fortunately for a few reasons:
1. We have so far avoided adding Python/Pip as a dependency to Oppia Android, and I want to continue with that as long as we can :)
2. The existing CI action seems to cover all of the cases we need
3. The more advanced checks of codeowner_linter don't seem needed (currently) for Oppia Android

**Comment by BenHenning** [comment]
@seanlip PTAL.

**Review by seanlip — APPROVED** [review]

**Pull request merged**
