### PR TITLE
Fix #478:Image is cut off in learner's answer. 

### LINKED ISSUE #478: Image is cut off in learner's answer.

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR  fixed image alignment.

image

### CODE REVIEW

**Comment by rt4914** [comment]
@veena14cs Please check this, image is not even visible

The issue is in develop itself, but still needs solution, meanwhile I am also checking this.

Screenshot_1574855775

**Review by rt4914 — COMMENTED** [review]
PTAL

**Review by rt4914 — APPROVED** [review]
I am approving this, if you wish to check the problem mentioned in some other issue, then file it on github and merge this.

**Comment by veena14cs** [comment]
> I am approving this, if you wish to check the problem mentioned in some other issue, then file it on github and merge this.

I will check this if I can fix in the same PR.

**Comment by veena14cs** [comment]
> I am approving this, if you wish to check the problem mentioned in some other issue, then file it on github and merge this.


I think it took time to load the image on your phone.

Screenshot_20191127-185020

**Comment by rt4914** [comment]
This PR is not related to the issue that I was pointing out, so better just merge this and I will file an issue for that.

**Comment by veena14cs** [comment]
> This PR is not related to the issue that I was pointing out, so better just merge this and I will file an issue for that.

Okay got it.

**Comment by BenHenning** [comment]
@veena14cs why did we change text justification for the answer to right? I think that's causing the bullet list items to look wrong, and I don't think that's what we want to do per the mocks. It also causes paragraph wrapping to look wrong:

image

Filed #499 to track this.

**Pull request merged**
