### PR TITLE
Fix Part of #2833 : Add missing named argument in RecentlyPlayedFragmentTest

### PR DESCRIPTION
**Pull request by techjd**
## Explanation
Fixes Part of #2833 Added Missing Named Argument in RecentlyPlayedFragmentTest

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by techjd** [comment]
@anandwana001 I was working on RecentlyPlayedFragmentTest. I was merging other latest updates with my repo but it did not went well and somehow ended with 44 commits ahead . How should I solve this ? I have only changed 1 file on which I was working .

**Comment by anandwana001** [comment]
@techjd is this a new branch you had created?
How did you merge the latest updates?

1. You can check if your origin and upstream are correctly set up using `git remote -v`.
2. How we update our fork is `git pull upstream develop` - here upstream is the oppia-android one.
3. `git push` - this will push to your origin which is your forked repository and update done.
4. Then you usually create a new branch and work on it further.

**Comment by techjd** [comment]
@anandwana001 This is my origin and upstream . 
remote
I have updated my fork using the same command mentioned by you `git pull upstream develop` and then finally `git push` . I did this 1-2 times which resulted in 45 commits . 

**What should I do , Is there any solution ?**

**Comment by prayutsu** [comment]
@techjd Can you mention the full command you used to push the changes?

**Comment by anandwana001** [comment]
@techjd Looks like you had created a branch from another branch, not from develop. I suggest to close this PR and create a fresh one with the new branch.

**Pull request closed without merging**
