### PR TITLE
Fix #1793 : Pin screen lost after app minimise

### LINKED ISSUE #1793: AdminPin screen lost after app minimize
**Describe the bug**
When we are on the admin pin screen to create pin, and minimize the app and coming back will take us back to the profile chooser screen

**To Reproduce**
1. Install app -> open administrator controls from profile chooser screen
2. Minimize app and open app again from minimized stack ->  profile chooser screen will apear

**Expected behavior**
We should be back to admin pin screen after opening minimized app

### PR DESCRIPTION
**Pull request by chrk2205**
## Explanation

Fix #1793 : Pin screen lost after app minimise
The cause of the Bug was that the activity used "FLAG_ACTIVITY_NO_HISTORY". 
To Deal with it, I replaced the Flag with activity.finish() wherever required. 
Changes were made in 
->AdminAuthActivity and AdminAuthActivityPresenter
->AdminPinActivity and AdminPinActivityPresenter
->PinPasswordActivity
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by chrk2205** [comment]
@rt4914 @anandwana001 review the PR
Thanks

**Comment by anandwana001** [comment]
Please Follow the checklist in the PR description, before review process begins.

**Comment by chrk2205** [comment]
> 
> 
> Please Follow the checklist in the PR description, before review process begins.


@anandwana001 @rt4914 please review my PR.

**Comment by anandwana001** [comment]
> > Please Follow the checklist in the PR description, before review process begins.
> 
> @anandwana001 @rt4914 please review my PR.

@chrk2205 Please check the first 2 points of the checklist in the PR description.

**Comment by chrk2205** [comment]
> > > Please Follow the checklist in the PR description, before review process begins.
> > 
> > 
> > @anandwana001 @rt4914 please review my PR.
> 
> @chrk2205 Please check the first 2 points of the checklist in the PR description.

@anandwana001 
I tagged the issue and also explained the changes.
Sorry, if anything is missing please point it out.
Thankyou.

**Comment by rt4914** [comment]
@chrk2205 Based on first point from checklist your PR title should be `Fix #1793 : Pin screen lost after app minimise`.

**Comment by chrk2205** [comment]
> @chrk2205 Based on first point from checklist your PR title should be `Fix #1793 : Pin screen lost after app minimise`.

modified the PR title
thankyou. @rt4914

**Comment by rt4914** [comment]
> > @chrk2205 Based on first point from checklist your PR title should be `Fix #1793 : Pin screen lost after app minimise`.
> 
> modified the PR title
> thankyou. @rt4914

You have updated it in `description`. You need to update this in `Title`.

Screenshot 2020-10-28 at 12 12 57 AM

**Comment by chrk2205** [comment]
sorry for the trouble!!
Thanks @rt4914

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks. 

Will wait for @anandwana001 's approvals.

**Comment by rt4914** [comment]
> sorry for the trouble!!
> Thanks @rt4914

No issues. Thanks.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @chrk2205 
Always follow the checklist before creating a PR else it might delay in review. 

@rt4914 Do we need any test case on this?

**Comment by chrk2205** [comment]
> LGTM, Thanks @chrk2205
> Always follow the checklist before creating a PR else it might delay in review.
> 
> @rt4914 Do we need any test case on this?

yeah,
Thanks

**Pull request merged**
