### PR TITLE
Fix #407: Submit button should be visible above keyboard 

### LINKED ISSUE #407: Submit button should be visible above keyboard
State Navigation buttons should be visible above keyboard, as shown in this image.

Screenshot_1574069735

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR fixes the submit button visibility above keyboard.

### Screenshot
untitled

### CODE REVIEW

**Review by nikitamarysolomanpvt — CHANGES_REQUESTED** [review]
small
PTAL keyboard is appearing and scrolling to bottom

**Comment by rt4914** [comment]
> small
> 
> PTAL keyboard is appearing and scrolling to bottom

For what its worth, I have not encountered this issue, but still @veena14cs take a deeper look into this.

Also, there is a lot of gap between button and keyboard, which will not look good on smaller screens.
Screenshot_1574657447

**Comment by veena14cs** [comment]
> small
> 
> PTAL keyboard is appearing and scrolling to bottom

I couldn't reproduce this. Please could you reproduce it so that I can fix it.

**Comment by veena14cs** [comment]
> > small
> > PTAL keyboard is appearing and scrolling to bottom
> 
> For what its worth, I have not encountered this issue, but still @veena14cs take a deeper look into this.
> 
> Also, there is a lot of gap between button and keyboard, which will not look good on smaller screens.
> Screenshot_1574657447

I have reduced bottom padding please check.

**Review by rt4914 — APPROVED** [review]
LGTM

**Review by nikitamarysolomanpvt — APPROVED** [review]
The issue i mentioned was occurring only on emulator API 25 and in Fraction Topic.

**Pull request merged**
