### PR TITLE
Fixed #4791 :  Dark Mode the white corners of Stories Cards

### LINKED ISSUE #4791: In Dark Mode the white corners of Stories Cards are visible.
In dark mode if you notice closely at the edges, you will see that there are white corners which are visible. They should not be visible.

For example in `prmoted_story_card` this is happening because we are using `app:roundedRectDrawableWithColor="@{viewModel.promotedStory.lessonThumbnail.backgroundColorRgb}"`
So basically to fix this in `promoted_story_card`, we first need to remove `app:roundedRectDrawableWithColor="@{viewModel.promotedStory.lessonThumbnail.backgroundColorRgb}"` and then in `PromotedStoryCardView` we should add `app:cardBackgroundColor="@android:color/transparent"` which should give correct results in both dark mode and light mode.

This above solution is for `promoted_story_card` only but we have various other cards too like `topics`, `ongoing_topic`, `completed_story`, etc so please focus on them too.

 

**To reproduce**
Once logged in, Switch to Dark Mode, and notice the various Story/Topics Cards Corners.

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

 Fixed #4791 :  Dark Mode the white corners of Stories Cards

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### Stories Cards corners

   

   

   

   

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by MohitGupta121 — COMMENTED** [review]
@rt4914 PTAL, please review this PR as per this issue screenshot https://user-images.githubusercontent.com/76530270/206967336-8d2ffdaa-9e69-4295-ba65-1a456996a702.png

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.

**Comment by MohitGupta121** [comment]
@rt4914 can we close this? Or something left?

**Comment by MohitGupta121** [comment]
@rt4914 I think the check are failing in all PR's.
And Re-run the tests will pass all checks. As I observed.

**Comment by rt4914** [comment]
This can be merged once CI checks pass.

**Comment by MohitGupta121** [comment]
> This can be merged once CI checks pass.

See  @rt4914 now it's passed. As I say there is some issue in workflow itself.
I will raised this issues in CLAM meeting today.

**Pull request merged**
