### PR TITLE
Fixes #1129: Code optimised for Backflow code

### LINKED ISSUE #1129: Code optimisation for Backflow Exploration Support
Pr #1036 has managed to finish the exploration back flow support correctly but after finishing that PR, I realised that we can further optimise this code by making the ENUM public and use it at various values to control the flow.

Update:
The code needs to follow approach mentioned here: https://github.com/oppia/oppia-android/pull/2566#issuecomment-772960035

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #1129

The `ExplorationActivity` when closed can go to different screens as per below mentioned scenarios:
1. When opened from `RecentlyPlayedActivity`, closing `ExplorationActivity` should open `TopicInfoTab`.
2. When opened from `StoryActivity`, closing `ExplorationActivity` should open `StoryActivity`.
3. When opened from `TopicLessonsTab`, closing `ExplorationActivity` should open `TopicLessonsTab`.

This implementation is working correctly in current code but it uses a term called `backflow` and it uses integer values to control various condition which makes it difficult to understand which screen will get opened just by looking at the code.

Therefore this PR introduces `ParentScreenForExplorationEnum` which is to make sure that the code becomes much more descriptive and understandable.

## How to Test:
Make sure that the app still fulfil these scenarios
1. When opened from `RecentlyPlayedActivity`, closing `ExplorationActivity` should open `TopicInfoTab`.
2. When opened from `StoryActivity`, closing `ExplorationActivity` should open `StoryActivity`.
3. When opened from `TopicLessonsTab`, closing `ExplorationActivity` should open `TopicLessonsTab`.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by BenHenning** [comment]
Sorry, will need to take a look at this tomorrow. FYI you have broken Bazel tests @rt4914.

**Comment by BenHenning** [comment]
Hmm lost track of this PR somehow.

I don't think I reviewed the original backflow PR, but @rt4914 can you clarify the core problem being solved here? It feels a bit like dependency creep for the exploration player to have any idea of how it was navigated to or where it should go next. Activities ought to operate independently in their scope.

I'm slightly wondering if we need a separate router utility that properly maps all activities to all activities given some sort of navigation context. That removes the responsibility from the activity itself & lets us centrally manage routing functionality. Would that address the issue? An enum may still be a good fit depending on how that's modeled--I'm not sure.

**Comment by Luffy18346** [comment]
@rt4914 PTAL

**Comment by rt4914** [comment]
> Hmm lost track of this PR somehow.
> 
Actually I un-assigned you because of test failure.

> I don't think I reviewed the original backflow PR, but @rt4914 can you clarify the core problem being solved here? It feels a bit like dependency creep for the exploration player to have any idea of how it was navigated to or where it show go next. Activities ought to operate independently in their scope.
> 
Copying from description:
The ExplorationActivity when closed can go to different screens as per below mentioned scenarios:
1. When opened from RecentlyPlayedActivity, closing ExplorationActivity should open TopicInfoTab.
2. When opened from StoryActivity, closing ExplorationActivity should open StoryActivity.
3. When opened from TopicLessonsTab, closing ExplorationActivity should open TopicLessonsTab.

As per this the parent information is needed inside `ExplorationActivity` so that when we finish it we can decide which screen to open.

> I'm slightly wondering if we need a separate router utility that properly maps all activities to all activities given some sort of navigation context. That removes the responsibility from the activity itself & lets us centrally manage routing functionality. Would that address the issue? An enum may still be a good fit depending on how that's modeled--I'm not sure.

So will this be sort of a map between "SourceActivity" and "DestinationActivity" ? I think it can make sense but don't know what are the advantages as compared to the current implementation where we use single route interface files in its particular package.

**Comment by BenHenning** [comment]
Thanks for clarifying the problem @rt4914. I think I did interpret it correctly, then.

My concern is that an activity that knows where it came from is a bit fragile: it's hard to host that activity elsewhere (which might actually matter here: I anticipate needing to introduce exploration deep-linking so that lessons themselves can be shared with other people via links in the future). The router abstracts away _where_ an activity needs to go next by deferring that specific responsibility to a central utility. This actually gets even easier now that we can pass enums to activities and fragments due to #2561. Consider something like this:

```kotlin
// Pseudocode

interface ActivityRouter {
  // May need a more complex argument--see comment in proto file
  fun routeToScreen(destination: ScreenDestination)
}
```

```proto
// Probably needs a better name since it should be destinations post-profile selection to avoid needing to support complex cross-profile navigation situations. Or, we could use a message instead of an enum with a oneof to handle those cases (since a profile ID may also need to be passed around).
// Alternatively, we may want just the screen to be represented in an enum & leverage a more complex class for the actual "route to this place". oneof works really well there since we can also add extra payload information to properly navigate there.
enum ScreenDestination {
  HOME_SCREEN,
  TOPIC,
  EXPLORATION
  ...
}

message ExplorationActivityIntentExtras {
  // Where the app should be navigated to after exiting an exploration. Note to Rajat: this may need to be framed carefully since we assume 'Return to Topic' returns to the topic. That's fine to be a baked-in assumption, but may need to require the activity to be started in a certain mode (e.g. 'topic mode' where the exploration UI specifically is set up for this use case).
  ScreenDestination exit_destination = 1;
}
```

Then routing becomes more centralized, and we can support fairly complex navigation patterns with ease & portability. E.g. if someone navigates to exploration activity & wants to navigate back, it may use a simple pattern that triggers the router just to end the activity, or possibly to navigate back with a new intent payload (conveniently, the router could be stateful & be aware of the current activity backstack).

The core pattern itself doesn't seem too complicated (though admittedly I haven't thought this through), whereas the applications  seem cleaner. It is semantically similar to what we have today, it just avoids having something like ExplorationActivity needing to have code to map an enum or integer to a particular screen (we instead make the router do that). WDYT?

**Comment by Luffy18346** [comment]
@rt4914 PTAL

**Comment by rt4914** [comment]
> @rt4914 PTAL

@Luffy18346 Thanks. Keeping this open considering I will need to prioritise a11y work currently.

**Comment by rt4914** [comment]
Closing this as not on priority and also updated the issue description.

**Pull request closed without merging**
