### PR TITLE
Fix #2553 : Reformatted layout files

### LINKED ISSUE #2553: Reformatting Required for the following files
The following files require reformatting
 - layout-land/fraction_interaction_item.xml
 - layout/help_item.xml
 - layout-land/help_item.xml
 - layout/hints_and_solution_fragment.xml
 - layout-land/hints_and_solution_fragment.xml
 - layout-sw600dp-land/hints_and_solution_fragment.xml
 - layout-sw600dp-port/hints_and_solution_fragment.xml
 - layout/hints_summary.xml
 - layout-land/hints_summary.xml
 - layout-sw600dp-land/hints_summary.xml
 - layout-sw600dp-port/hints_summary.xml

Recommended to setup [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References 
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

### PR DESCRIPTION
**Pull request by rawlin**
## Explanation

Fixes #2553 
Reformatted the following files
- layout-land/fraction_interaction_item.xml
- layout/help_item.xml
- layout-land/help_item.xml
- layout/hints_and_solution_fragment.xml
- layout-land/hints_and_solution_fragment.xml
- layout-sw600dp-land/hints_and_solution_fragment.xml
- layout-sw600dp-port/hints_and_solution_fragment.xml
- layout/hints_summary.xml
- layout-land/hints_summary.xml
- layout-sw600dp-land/hints_summary.xml
- layout-sw600dp-port/hints_summary.xml

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@rawlin Update title to
`Fix #2553 : Reformatted layout files`

**Comment by rawlin** [comment]
> @rawlin Update title to
> `Fix #2553 : Reformatted layout files`

**Comment by rawlin** [comment]
@rt4914 could you review this

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks

**Review by Arjupta — APPROVED** [review]
LGTM

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
