### PR TITLE
Fixes part of #3363: Ignore flaky tests in AddProfileActivity

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes part of #3363: Ignore flaky tests in AddProfileActivity

In `AppProfileActivity` 3 tests are passing and failing on different devices. Until we solve this error we are ignoring them so that other developers can work on other related items.

## Output

Screenshot 2021-07-09 at 11 55 22 AM

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by anandwana001 — APPROVED** [review]
LGTM

**Comment by anandwana001** [comment]
@Sparsh1212 Could you check the failing check here?

**Comment by Sparsh1212** [comment]
We have to add the failing files to test_file_exemptions.textproto 
Please refer to the documentation of script_exemptions.proto on how to format the exemption in the textproto file.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
blocking merge till test pass

**Review by anandwana001 — APPROVED** [review]

**Pull request merged**
