### PR TITLE
[RunAllTests] Fix #3217, part of #2923: migrate flexbox dependency to pull from Google's Maven repository instead of JCenter/bintray

### LINKED ISSUE #3217: Update Flexbox dependency
Host moved to google maven - https://github.com/google/flexbox-layout/releases/tag/3.0.0

### PR DESCRIPTION
**Pull request by BenHenning**
Fix #3217.
Fix part of #2923.

## Explanation
This updates the Bazel & Gradle builds to use the new version & group ID for flexbox-layout so that the build pulls the dependency from Google Maven instead of JCenter/Bintray (per https://github.com/google/flexbox-layout/issues/566#issuecomment-844630491). While Bintray is promising long-term hosting for dependencies, it's immutable which means new versions can't be received. Beyond that, we've had reliability issues with our JCenter/Bintray dependencies. This removes one JCenter/Bintray dependency.

This should have no side effects with the current project since 3.0.0 is meant to be identical with 2.0.1. I'll be using CI & a manual verification of the APK (to ensure the walkthrough experience, our only screen that uses flexbox layout, works correctly) for validity checking.

### CODE REVIEW

**Comment by anandwana001** [comment]
This PR fixing https://github.com/oppia/oppia-android/issues/3217 too

**Comment by BenHenning** [comment]
Thanks @anandwana001. Updated the PR to mark that issue as fixed.

The 2 Bazel failures here seem unrelated to the change, and I don't think either test would be affected by this, anyway, so I'm not going to re-run them.

**Comment by BenHenning** [comment]
The build seems to be working correctly locally, and relevant CI are passing. @rt4914 & @fsharpasharp PTAL.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by fsharpasharp — APPROVED** [review]
The changes look good to me.

**Pull request merged**
