### PR TITLE
Fix #856 : Reordering in Android Manifest file.

### LINKED ISSUE #856: Reordering in Android Manifest file.
In android manifest file we have been following the alphabetical convention in activity declaration.

Some of these activities are not in alphabetical order. Rearrange them.

```
    <activity android:name=".testing.RecentlyPlayedFragmentTestActivity" />
    <activity
      android:name=".testing.NavigationDrawerTestActivity"
      android:screenOrientation="portrait"
      android:theme="@style/OppiaThemeWithoutActionBar" />
```

### PR DESCRIPTION
**Pull request by MohamedMedhat1998**
## Explanation

Fixes #856: Reordering in Android Manifest file.
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by MohamedMedhat1998** [comment]
@rt4914  please check this PR

**Comment by MohamedMedhat1998** [comment]
@rt4914  1 test  failed and 1 passed  
What should I do?

**Comment by SayantanBanerjee16** [comment]
> @rt4914 1 test failed and 1 passed
> What should I do?

@MohamedMedhat1998 As long as the `non_flaky_tests` are passing, we are good to go.

Also, rename `Fixes` to `Fix `in your PR title.

**Comment by MohamedMedhat1998** [comment]
@SayantanBanerjee16 Done  
Does that mean my PR will be merged without problems?

**Review by rt4914 — APPROVED** [review]
LGTM thanks.

**Comment by rt4914** [comment]
@MohamedMedhat1998 For now, only non_flaky_tests will pass

**Comment by MohamedMedhat1998** [comment]
Now I can delete the branch, correct?

**Comment by SayantanBanerjee16** [comment]
> Now I can delete the branch, correct?

Yes, you can.

**Pull request merged**
