### PR TITLE
Fix #653 : Landscape add profile

### LINKED ISSUE #653: Lowfi Landscape: Add Profile
Mock Link:
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/645052fe-103b-4ca0-8250-e3b0d50bb169/PC-SP-Add-Profile-

## Checklist
- [ ] Lowfi Landscape
- [ ] Test cases for Landscape

### PR DESCRIPTION
**Pull request by MohamedMedhat1998**
## Explanation
 -Fixes #653 : Landscape add profile

## Before
The **AddProfileActivity** was locked to portrait mode, when you rotate the device, nothing happens

Screenshot_2020-03-08-09-08-18

## After
The **AddProfileActivity** now supports the landscape mode, and that is how it looks after the modification

Screenshot_2020-03-08-14-07-22

Screenshot_2020-03-08-14-08-27

Screenshot_2020-03-08-14-08-34

Screenshot_2020-03-08-14-08-37

## Checklist
- [x] Lowfi Landscape
- [x] Test cases for Landscape

### CODE REVIEW

**Comment by Sarthak2601** [comment]
Hi @MohamedMedhat1998, 

Few suggestions :-)  

- Your PR title should be `Fix #653 : Landscape add profile`
- Please enter the details about your code changes according to the given PR Template only 
- Do follow these [PR Guidelines](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR), they will help you in getting your PR reviewed.  
- Don't push the changes made to the `.idea` files. They are auto-generated by your Android Studio and are not required.

**Comment by MohamedMedhat1998** [comment]
## Explanation

-Fixes #653 : Landscape add profile

## Checklist
- [x] Lowfi Landscape
- [x] Test cases for Landscape

## Before
The **AddProfileActivity** was locked to portrait mode, when you rotate the device, nothing happens

Screenshot_2020-03-08-09-08-18

## After
The **AddProfileActivity** now supports the landscape mode, and that is how it looks after the modification

Screenshot_2020-03-08-14-07-22

Screenshot_2020-03-08-14-08-27

Screenshot_2020-03-08-14-08-34

Screenshot_2020-03-08-14-08-37

**Comment by MohamedMedhat1998** [comment]
@Sarthak2601  please check

**Comment by Sarthak2601** [comment]
> @Sarthak2601 please check

Hi, 
- PR Title is still the same. 
- Avoid the` .gitignore ` approach for removing the `.idea` files
- Checkout the original PR Template and make amends in yours

**Comment by MohamedMedhat1998** [comment]
I modified the pull request description instead of adding new comment. But I don't know how to remove `.idea` files without `.gitignore`  
Can you give me a hint please?

**Comment by SayantanBanerjee16** [comment]
> I modified the pull request description instead of adding new comment. But I don't know how to remove `.idea` files without `.gitignore`
> Can you give me a hint please?

Hey @MohamedMedhat1998 ,

After making changes, before we commit, we generally tend to use `git add .` 

Now that will also include these auto-generated files. So only add those file names in which you have done code changes, and only commit those files. To refer these file names, do `git status` to get the modified/newly added file names. In this way, one can ignore those auto-generated codes from pushing.

For now, one thing you can do is to revert those changes you made or the other way around is again start from scratch and drop this pull request and make a fresh one. Go forward with whichever you prefer.

**Comment by Sarthak2601** [comment]
> I modified the pull request description instead of adding new comment. But I don't know how to remove `.idea` files without `.gitignore`
> Can you give me a hint please?

I think you can just simply delete that from your committed files. Go to the `files changed` and delete those files which aren't required.

**Comment by Sarthak2601** [comment]
@MohamedMedhat1998 I think you can just simply delete that from your committed files. Go to the `files changed` and delete those files which aren't required.
But yes, please correct me if I am wrong :)

**Comment by rt4914** [comment]
> @MohamedMedhat1998 I think you can just simply delete that from your committed files. Go to the `files changed` and delete those files which aren't required.
> But yes, please correct me if I am wrong :)

Actually, do not follow this step, nothing should be deleted/modified directly from github, everything should be done from android studio only.

Also, thanks a lot to @Sarthak2601 @SayantanBanerjee16 for reviewing this PR and leaving comments on it. It's a great help.

**Comment by rt4914** [comment]
@veena14cs this has been assigned to you considering that you had made some progress in this earlier.

**Comment by MohamedMedhat1998** [comment]
@Sarthak2601 @SayantanBanerjee16 I have created a new fresh PR with only 3 files (2 files were added and 1 file was edited)  
So, there is no `.idea` files in the PR now  
https://github.com/oppia/oppia-android/pull/763  
@rt4914 I only was late because I had a long day at the university today, but there was only one step for me to do which is creating a new PR without the `.idea` files in order to get the PR reviewed.  
Can you re-assign the issue to me please?

**Comment by veena14cs** [comment]
@MohamedMedhat1998 If this PR is no longer used. Please close this PR adding reference to new PR.

**Comment by MohamedMedhat1998** [comment]
This PR is closed because there is a fresh one here https://github.com/oppia/oppia-android/pull/763

**Pull request closed without merging**
