### PR TITLE
Fix #1099: Linking UI Components with Analytics code

### LINKED ISSUE #1099: Linking Presenters with Analytics Wrapper [GSoC'20][Milestone 1]
Linking UI components for which analytics has to be implemented with the Analytics Wrapper. This will complete the implementation of Firebase Analytics and Crashlytics for online users.

### PR DESCRIPTION
**Pull request by Sarthak2601**
## Explanation

Fix #1099 

This PR adds custom event logging at the following places -
- Home Activity
- Exploration Activity 
- Story Activity 
- Lessons tab [Topic]
- Info tab [Topic]
- Practice tab [Topic]
- Revision tab [Topic] 

It also initialises FirebaseApp in test files. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by vinitamurthi — APPROVED** [review]
Overall this LGTM, but I would like @rt4914 to take a pass. @rt4914 : Can you take a look at whatever we are planning to log and comment on whether we have added the logging at the right place?

**Review by rt4914 — COMMENTED** [review]
@vinitamurthi @Sarthak2601 I think we should log events for `RevisionCard`, `ConceptCard` and `QuestionPlayer` also, else everything is good.

**Comment by Sarthak2601** [comment]
> @vinitamurthi @Sarthak2601 I think we should log events for `RevisionCard`, `ConceptCard` and `QuestionPlayer` also, else everything is good.

Done, PTAL :)

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by Sarthak2601** [comment]
Approval done, checks passed. Merging now!

**Pull request merged**
