### PR TITLE
Fix code formatting style[ DO NOT MERGE]

### PR DESCRIPTION
**Pull request by veena14cs**
### Explanation

This PR updates .idea files to avoid rearranging of layouts whenever code reformatter is used.

### CODE REVIEW

**Review by rt4914 — COMMENTED** [review]
@veena14cs I tried using this and this is changing the order of `data` in layouts,  as well as the widgets/views are arranged in alphabetical oder. You can check this in `add_profile_activity.xml`

**Comment by veena14cs** [comment]
> @veena14cs I tried using this and this is changing the order of `data` in layouts, as well as the widgets/views are arranged in alphabetical oder. You can check this in `add_profile_activity.xml`

This is strange. How its not doing in my system. Just try setting Predefined style to android twice -> apply and  then check.

**Comment by rt4914** [comment]
> > @veena14cs I tried using this and this is changing the order of `data` in layouts, as well as the widgets/views are arranged in alphabetical oder. You can check this in `add_profile_activity.xml`
> 
> This is strange. How its not doing in my system. Just try setting Predefined style to android twice -> apply and then check.

Okay, I will do that.

**Comment by rt4914** [comment]
@veena14cs Now I think this PR can be closed as the correct solution is in #992

**Comment by veena14cs** [comment]
Closing this as it was fixed in #992 .

**Pull request closed without merging**
