### PR TITLE
Fix Part of #2833: added missing argument of OngoingTopicListActivityTest

### PR DESCRIPTION
**Pull request by nlok5923**
Fixes part of #2833 
## Explanation

This pr resolves the missing argument of OngoingTopicListactivitytestFile

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
@nlok5923 If you are not using Windows currently, please complete all the installation steps: https://github.com/oppia/oppia-android/wiki#installation

**Comment by nlok5923** [comment]
@anandwana001 i am using windows only.

**Comment by anandwana001** [comment]
Please check the below errors and fix it.

```
********************************
Checking code formatting
********************************
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:146:24: Trailing space(s)
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:147:50: Missing newline before ")"
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:172:24: Trailing space(s)
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:199:24: Trailing space(s)
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:225:24: Trailing space(s)
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:253:24: Trailing space(s)
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:278:24: Trailing space(s)
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:305:24: Trailing space(s)
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:333:24: Trailing space(s)
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:361:24: Trailing space(s)
/home/runner/work/oppia-android/oppia-android/app/src/sharedTest/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicListActivityTest.kt:375:1: Unexpected indentation (8) (should be 6)
********************************
Ktlint issue found.
Please fix the above issues.
  You can also use the ktlint -F --android domain/src/**/*.kt utility/src/**/*.kt data/src/**/*.kt app/src/**/*.kt testing/src/**/*.kt
  command to fix the most common issues.
Please note, there might be a possibility where the above command will not fix the issue.
  In that case, you will have to fix it yourself.
********************************
```

Reference of ktlint - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide

**Comment by nlok5923** [comment]
sure @anandwana001 will resolve it in latest commit.

**Comment by nlok5923** [comment]
@anandwana001 as i am new to this project i had a little doubt will `R.id.ongoing_topic_list` be allocated to `topicListid` as i had done in this pr or i am missing something.

image

**Comment by anandwana001** [comment]
This should be simply ` recyclerView ` as we are mentioning here which recyclerView we are passing here.

**Comment by nlok5923** [comment]
@anandwana001 can you please review this pr and let me know if any changes needed.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @nlok5923

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
