### PR TITLE
Fixes part of #973: Fixed DialogBox test in AdministratorControlActivityTest 

### PR DESCRIPTION
**Pull request by abhinavraj23**
## Explanation
Fixes part of #973: The currently written tests will pass in roboelectric

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by abhinavraj23** [comment]
@rt4914 The currently written test of DialogBox works well with roboelectric, but when I try to run the same test in espresso it gives dependency errors. From what I have concluded is that things like alertDialog, Navigation bar will not work with espresso apis in roboelectric, please refer this 
[article](https://amryousef.me/robolectric-base-test)

**Comment by rt4914** [comment]
> @rt4914 The currently written test of DialogBox works well with roboelectric, but when I try to run the same test in espresso it gives dependency errors. From what I have concluded is that things like alertDialog, Navigation bar will not work with espresso apis in roboelectric, please refer this
> [article](https://amryousef.me/robolectric-base-test)

@veena14cs This PR is related to Roboelectric test case in which the author is testing the alert dialog box and he is facing issues with that as mentioned above. PTAL.

**Review by veena14cs — APPROVED** [review]
LGTM. This is working fine in roboelectric but @rt4914 I just want to clarify whether we are not going to check this in expresso. Because in express this import gives error saying `org.robolectric.shadows.ShadowDialog.getLatestDialog` is unresolved. Are we suppose to ignore this?

**Comment by rt4914** [comment]
> LGTM. This is working fine in roboelectric but @rt4914 I just want to clarify whether we are not going to check this in expresso. Because in express this import gives error saying `org.robolectric.shadows.ShadowDialog.getLatestDialog` is unresolved. Are we suppose to ignore this?

@veena14cs Actually thats the main point, the test case should pass in both espresso as well as roboelectic and the author is stuck on making it possible in this PR.

**Comment by veena14cs** [comment]
@abhinavraj23 can you try without using Shadows. Try writing testcase for AlerDialog instead of using `ShadowDialog.getLatestDialog`

**Comment by abhinavraj23** [comment]
@veena14cs I have tried various things but it seems like we cannot test AlertDialog without shadows in Roboelectric. Please let me know if you find something or what should the next step.

**Comment by veena14cs** [comment]
> @veena14cs I have tried various things but it seems like we cannot test AlertDialog without shadows in Roboelectric. Please let me know if you find something or what should the next step.

Even I am stuck on this. I will try several things and update you. @abhinavraj23 you can pick some other issue and will get back to you on this.

**Comment by anandwana001** [comment]
@abhinavraj23 Did you try putting delay after click on logout button in test?

**Comment by veena14cs** [comment]
> @abhinavraj23 Did you try putting delay after click on logout button in test?

@anandwana001 I tried adding delay but it didn't work. But adding LooperMode annotation did work that you mentioned in this comment https://github.com/oppia/oppia-android/issues/973#issuecomment-629376957

**Comment by veena14cs** [comment]
@abhinavraj23 please check this above comment and test this PR. You can remove shadowDialog and revert the testcase. Add annotation dependency for LooperMode and use it in this test. Also check other testcases in this file which are using alertdialog.

Once you are done assign me back.

**Comment by rt4914** [comment]
Closing this PR as there has been no updates on this PR from contributor.

**Pull request closed without merging**
