### PR TITLE
Fix #3782 : Made the project use Themes instead of Styles [Dark Mode Implementation].

### LINKED ISSUE #3782: Make the project use Themes instead of Styles [Dark Mode Implementation].
Making the project use themes.xml files instead of existing styles.xml by replacing the existing styles.xml files with themes.xml.

### PR DESCRIPTION
**Pull request by ayush0402**
## Explanation
Fixes #3782 
Made the project use themes.xml files instead of existing styles.xml by replacing the existing styles.xml files with themes.xml.
Edited <code>file_content_validation_checks.textproto</code> to fix regex pattern error.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
@ayush0402 This is correct. Thanks. 

You can create a new branch from this PR and continue your work on top of that. Meanwhile I will assign it to @BenHenning

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @ayush0402. Is this actually what we want to do? Per https://developer.android.com/guide/topics/ui/look-and-feel/themes it seems like styles should be the groups of attributes (that are technically currently in our styles.xml file), and themes should define just changes in the attributes. Shouldn't we be defining a new thermes.xml that only contains the attributes that need to be overwritten for dark mode rather than forking all of our styles?

**Comment by ayush0402** [comment]
@BenHenning Actually according to the discussion with @rt4914, we were originally going to get rid of styles.xml files from the project and instead create two version of the themes.xml under <code>values</code> and <code>values-night</code> (also replacing styles.xml in <code>values-v21</code> with themes.xml) and then introduce another colors.xml in <code>values-night</code> overriding colors for problematic UI elements.(This PR being the first step in that process)

Do you instead want to keep both styles.xml and themes.xml but transfer styles effecting "themes" (with semantically named color items) to new themes.xml files?

**Comment by rt4914** [comment]
> @BenHenning Actually according to the discussion with @rt4914, we were originally going to get rid of styles.xml files from the project and instead create two version of the themes.xml under `values` and `values-night` (also replacing styles.xml in `values-v21` with themes.xml) and then introduce another colors.xml in `values-night` overriding colors for problematic UI elements.(This PR being the first step in that process)
> 
> Do you instead want to keep both styles.xml and themes.xml but transfer styles effecting "themes" (with semantically named color items) to new themes.xml files?

@ayush0402 Ben's comment make more sense let's follow his approach. Thanks.

**Comment by BenHenning** [comment]
> > @BenHenning Actually according to the discussion with @rt4914, we were originally going to get rid of styles.xml files from the project and instead create two version of the themes.xml under `values` and `values-night` (also replacing styles.xml in `values-v21` with themes.xml) and then introduce another colors.xml in `values-night` overriding colors for problematic UI elements.(This PR being the first step in that process)
> > Do you instead want to keep both styles.xml and themes.xml but transfer styles effecting "themes" (with semantically named color items) to new themes.xml files?
> 
> @ayush0402 Ben's comment make more sense let's follow his approach. Thanks.

Given this, de-assigning myself. Please assign back if you need me to take another pass. Thanks!

**Pull request closed without merging**
