### PR TITLE
Fix #1593: Landscape support for Hints & Solution

### LINKED ISSUE #1593: Landscape support for Hints & Solution
**Describe the bug**
Hints and Solution screen crashed on configuration changed

**To Reproduce**
1. Go to Fraactions
2. Skip initial states to go to first question.
3. Select option 1, twice.
4. You should see a Hint icon at the bottom-left
5. Click on hint
6. In hint screen, change mobile orientation.
7. Application crashes with following error:
Screenshot 2020-08-10 at 5 49 38 PM

**Expected behavior**
The application should not crash on configuration change in Hints&Solution.

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #1593 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
@anandwana001 This PR solves the crash issue but there is still on big issue.
1. Once you reach the Hints screen, click on `Reveal`, now change to landscape, you will notice below screen:
Screenshot_1597214343

2. Also, make sure that above error is fixed for `Solution` also, meaning similar to `Hints` there is one `Solution` button also which comes when all hints are finished. Solution is present in below mentioned screen: 
Screenshot_1597214533
Screenshot_1597214619

**Comment by anandwana001** [comment]
ah, Did check the landscape thing about reveal hint. 
Thanks for pointing these, I will update.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Great. This implementation is quite nice. 

One final bug:

Once you have revealed first hint, then when you have second hint available (not revealed), expand the first hint, and now reveal the second hint and you will notice both hints are expanded.

Hints issue

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
