### PR TITLE
Fixes #4193: Added dark mode support to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity

### LINKED ISSUE #4193: Add dark mode support to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity
Add dark mode support to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity.

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

### PR DESCRIPTION
**Pull request by bhaktideshmukh**
## Explanation
Fixes #4193: This PR adds dark mode support to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity.

**Mocks links:--**

- **ProfileProgressActivity**: https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/abe3a8a6-0683-43b3-8718-d61edd9682a4/specs/

- **RecentlyPlayedActivity**: https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/2b6c8e95-5ac7-4472-bc2b-1c318a3f7e5c/specs/
- **CompletedStoryListActivity**: https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/f54ae7d1-9530-44d6-8783-21559b13635c/specs/
- **OngoingTopicListActivity**: https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/a80d1be8-d4b4-4fee-a46d-296b5aa6a110/specs/

## Screenshots

| Default | Dark mode |
|-------|---|
|||

| Default | Dark mode |
|-------|---|
|||

| Default | Dark mode |
|-------|---|
|||

| Default | Dark mode |
|-------|---|
|||

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.

**Comment by rt4914** [comment]
@bhaktideshmukh Merge with latest develop. and after that you can merge this PR. I have approved it.

**Comment by BenHenning** [comment]
@bhaktideshmukh I think conflicts need to be resolved--PTAL and then assign back once that's done & CI is passing.

**Review by BenHenning — APPROVED** [review]
Thanks @bhaktideshmukh. I took a quick pass since @rt4914 already approved the PR, and I didn't see anything problematic.

**Pull request merged**
