### PR TITLE
Fix #632: BindableAdapter for HomeFragment[DO NOT MERGE]

### LINKED ISSUE #632: Replace current recyclerview implementation with BindableAdapter usage
Currently the entire project has two types of RecyclerView implementation:
1. Recyclerview using BindableAdapter (OngoingStoryListActivity, CompletedStoryListActivity, etc.) uses it)

2. Recyclerview with the RecyclerViewAdapter which inflates multiple layouts.

We need to change the implementation such that all RecyclerViewAdapter to  use BindableAdapter (i.e. approach similar to OngoingStoryListActivity, CompletedStoryListActivity).

## Checklist
- [x] `ContinuePlaying` (assigned to @veena14cs )
- [x] `HomeFragment` (assigned to @jcqli)
- [x] `StoryActivity` (Already done)
- [x] `TopicReview/Revision` (Assigned to @Sarthak2601 )
- [x] `TopicPlay/Lessons`
- [x] `TopicTrain/Practice` (assigned to @Luffy18346 )
- [x] `HelpActivity` (Assigned to @SayantanBanerjee16 )
- [x] `HintsAndSolutionAdapter`  (Assigned to @anandwana001 )
- [x] `OngoingListAdapter`  (open)
- [x] `TopicListAdapter` (assigned to @jcqli)
- [x] `LanguageSelectionAdapter` (assigned to @FareesHussain)
- [x] `StorySummaryAdapter`  (open)
- [ ] `PromotedStoryListAdapter` (assigned to @masclot )

### PR DESCRIPTION
**Pull request by NullByte08**
## Explanation
 #632 HomeFragment:
There are errors coming in the implementation.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by NullByte08** [comment]
@rt4914 Please take a look at the code and tell me whether I am implementing the ViewModel classes in the right way. I am having problems in implementing the list of promoted stories. Should I create a design doc regarding this?

**Comment by rt4914** [comment]
> @rt4914 Please take a look at the code and tell me whether I am implementing the ViewModel classes in the right way. I am having problems in implementing the list of promoted stories. Should I create a design doc regarding this?

@NullByte08 Actually I haven't been able to find an issue yet. Maybe a design doc can be a good idea. So that I can defer it to Ben who can bring in more light on this. Mostly I am assuming that the BindableAdapter itself will need to be modified to support HomeFragment items.

**Comment by NullByte08** [comment]
@rt4914 Ok

**Comment by rt4914** [comment]
Closing this PR as there has been no updates on this PR from contributor.

**Pull request closed without merging**
