### PR TITLE
[Android Wiki] Fixed Typo error in Bazel Installation wiki page.

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

[Android Wiki] Fixed Typo error in Bazel Installation wiki page.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Review by MohitGupta121 — COMMENTED** [review]
@BenHenning PTAL, I make some wiki changes.

**Review by adhiamboperes — APPROVED** [review]

**Comment by adhiamboperes** [comment]
This LGTM @MohitGupta121

**Comment by MohitGupta121** [comment]
Thanks @adhiamboperes

**Review by BenHenning — APPROVED** [review]
Thanks @MohitGupta121. Nice catch!

**Comment by BenHenning** [comment]
Updating to latest develop & enabling auto-merge.

**Pull request merged**
