### PR TITLE
Fix part of #4044: Add NumericExpressionInput classifiers

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
Fix part of #4044

Introduce all domain classifiers for the NumericExpressionInput interaction.

Specific classifiers being introduced:
- MatchesExactlyWith: this performs an exact comparison check between ``MathExpression``s to match the answer (only whitespace can be ignored, even groups are checked)
- MatchesUpToTrivialManipulations: this compares ``ComparableOperation`` representations of the interaction input and answer (which allows rearranging around commutative operators, and changing of associativity)
- IsEquivalentTo: this evaluates a ``Real`` value for each expression and compares them. Note that a polynomial isn't used like later PRs because direct evaluation is equivalent and a bit more performant. Furthermore, we need the evaluator for test purposes so it might as well be used here.

More details on these classifiers can be seen in the [PRD](https://docs.google.com/document/d/1x2vcSjocJUXkwwlce5Gjjq_Z83ykVIn2Fp0BcnrOrTg/edit#heading=h.8za8vrjxlg51), [technical specification](https://docs.google.com/document/d/1JMpbjqRqdEpye67HvDoqBo_rtScY9oEaB7SwKBBspss/edit#bookmark=id.hqwadl44tk37), and [test matrix breakdown](https://docs.google.com/spreadsheets/d/1u1fQdah2WsmdYKWKGmuXy5TPT7Ot-b8A7O9iZF-j5XE/edit#gid=0).

Other changes:
- This changes the double comparison epsilon value to be a bit more flexible for testing (since it's a small change, the impact on user behavior should be negligible).
- This introduces the InteractionObject proto change for math expressions and equations (which is just a string that's parsed during classifier matching time).
- This PR also introduces support for comparing ``MathExpression``s, ``ComparableOperation``s, and ``Polynomial``s that are used here & will be used in later PRs. The reason we can't just use standard proto equality checking is because ``Real``s can contain doubles and thus need an epsilon check. Very thorough tests were added to verify these equality operations separately from where they're used.
- This PR introduces exemptions for 4 test suites to enable parameterization. In all of these cases, effectively a single behavior (or two closely related behaviors) are being tested across a bunch of examples which is a really good fit for parameterization.

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A -- This is introducing a new classifier, but it isn't yet being hooked up.

### CODE REVIEW

**Comment by BenHenning** [comment]
Hi. As of today, some main reviewers have taken time off for the next few weeks, so it may take a little while before we can look at this PR. We appreciate your patience while some of our team members recharge. We'll be fully returning on 4 January 2021.

**Comment by BenHenning** [comment]
@vinitamurthi PTAL for codeowners.

@anandwana001 PTAL at the whole PR as part of the broader math expressions project.

**Review by vinitamurthi — APPROVED** [review]
LGTM for codeowners

**Comment by BenHenning** [comment]
This is still active.

**Review by anandwana001 — APPROVED** [review]
LGTM

All the `isApproximatelyEqualTo` extensions are quite amazing and make the whole development easy and readable.

**Pull request merged**
