### PR TITLE
Fixes #3455: Deleted admin_settings_dialog.xml landscape and reset_pin_dialog.xml …

### LINKED ISSUE #3455: Merge admin_settings_dialog.xml into and reset_pin_dialog into single file
Currently there are 2 versions of `admin_settings_dialog.xml` and `reset_pin_dialog.xml` file merge it into individual xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

### PR DESCRIPTION
**Pull request by yash10019coder**
…landscape

## Explanation

Fix #3455 
I have deleted the landscape xmls of admin_settings_dialog.xml and reset_pin_dialog.xml and I have also compared the landscape and portrait files of both the xmls and they were same
Here below are the screenshots of before and after of both the files in tablet and phone emulator.
**First Four rows are of admin_settings_dialog activity and Next four rows are of reset_pin_dialog**
|        New Screenshots         |                   Old Screenshots        |
|        -----------------------------  |                   ---------------------------   |
|Screenshot_1627192853  |  Screenshot_1627192338                          |
|Screenshot_1627192848  |  Screenshot_1627192334                             |
|Screenshot_1627195236  |  Screenshot_1627195062                         |
|Screenshot_1627195232 |  Screenshot_1627195055                         |
|Screenshot_1627192889  |  Screenshot_1627191921                         |
|Screenshot_1627192883  |  Screenshot_1627191914                          |
|Screenshot_1627195115 |  Screenshot_1627193996                         |
|Screenshot_1627195112 |  Screenshot_1627193993                         |

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by yash10019coder** [comment]
@rt4914 @prayutsu PTAL

**Review by prayutsu — APPROVED** [review]
LGTM, thanks @yash10019coder.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@yash10019coder The screenshots displayed in the PR description are incorrect.

`admin_settings_dialog` -> If you check the UI in android studio `Design` section you will notice this file has a completed different UI.
Same applies for other files too.

Also, the file names uses `*_dialog.xml` which means that these xml files are used in `Dialog` but you have taken screenshots of `Fragment`.

To see the UI of `admin_settings_dialog` in app. 
- Add new profile with 3 digit pin.
- In profile selection screen, click on the profile that you created above.
- Click on forgot password.
- Now the `EditText` that you see in the dialog is shown from `admin_settings_dialog`.

Similarly try to find the `reset_pin_dialog` too.

And update screenshots of before/after accordingly.

**Comment by yash10019coder** [comment]
> @yash10019coder The screenshots displayed in the PR description are incorrect.
> 
> `admin_settings_dialog` -> If you check the UI in android studio `Design` section you will notice this file has a completed different UI.
> Same applies for other files too.
> 
> Also, the file names uses `*_dialog.xml` which means that these xml files are used in `Dialog` but you have taken screenshots of `Fragment`.
> 
> To see the UI of `admin_settings_dialog` in app.
> 
> * Add new profile with 3 digit pin.
> * In profile selection screen, click on the profile that you created above.
> * Click on forgot password.
> * Now the `EditText` that you see in the dialog is shown from `admin_settings_dialog`.
> 
> Similarly try to find the `reset_pin_dialog` too.
> 
> And update screenshots of before/after accordingly.

Ok @rt4914

**Comment by yash10019coder** [comment]
> @yash10019coder The screenshots displayed in the PR description are incorrect.
> 
> `admin_settings_dialog` -> If you check the UI in android studio `Design` section you will notice this file has a completed different UI.
> Same applies for other files too.
> 
> Also, the file names uses `*_dialog.xml` which means that these xml files are used in `Dialog` but you have taken screenshots of `Fragment`.
> 
> To see the UI of `admin_settings_dialog` in app.
> 
> * Add new profile with 3 digit pin.
> * In profile selection screen, click on the profile that you created above.
> * Click on forgot password.
> * Now the `EditText` that you see in the dialog is shown from `admin_settings_dialog`.
> 
> Similarly try to find the `reset_pin_dialog` too.
> 
> And update screenshots of before/after accordingly.

Are these screenshots correct @rt4914 
Screenshot_1627642069
Screenshot_1627642444

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
