### PR TITLE
Fix #4305: Add support for Swahili translations (app strings and content)

### LINKED ISSUE #4305: Add support for Swahili translations

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fixes #4305

This PR introduces the base support for Swahili content and audio voiceover translations, and also registers Kenya as an accepted region by the app. #4279 is introducing the initial batch of app string translations, and the content pipeline has been updated to support importing Swahili translations. See the screenshot below for a reference.

Note that there aren't really any tests to add besides the manual verification.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

This PR is changing exactly one UI surface: support for Swahili. See this screenshot for reference:
image

Note that Swahili has exposed a few text overflow situations in the app but these are acceptable in the current alpha state of the app.

### CODE REVIEW

**Comment by BenHenning** [comment]
Hi @anandwana001. PTAL at the whole PR as I plan to defer @vinitamurthi's review.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
LGTM, 

Waiting for all the checks to pass.

**Comment by BenHenning** [comment]
~TODO: Update opening comment to explain that this doesn't introduce support for audio translations & why, and how it also includes pulling in titles & descriptions from Oppia web for other languages (as part of #4306).~

Edit: The above is no longer true per the current plan.

**Comment by BenHenning** [comment]
Note that any additional changes needed in this PR will be covered in #4345 as a fast-follow.

Furthermore, @anandwana001's and @rt4914's reviews are being deferred (#4344 and #4266 are tracking each, respectively). Note that this does result in no approvals, but I've gotten confirmation from @seanlip as another technical representative that this is reasonable given the circumstances of getting these changes in quickly for an upcoming release. I'll make sure this PR does get reviewed post-submission.

**Review by anandwana001 — COMMENTED** [review]
LGTM

**Review by rt4914 — COMMENTED** [review]
LGTM, Thanks

**Review by adhiamboperes — COMMENTED** [review]
LGTM as is.

**Pull request merged**
