### PR TITLE
Fix #1645 : Rename ic_hintbulb_whilte_24dp to ic_hint_bulb_white_24dp

### LINKED ISSUE #1645: Rename ic_hintbulb_whilte_24dp drawable file to ic_hint_bulb_white_24dp
In `drawable` folder rename `ic_hintbulb_whilte_24dp ` to `ic_hint_bulb_white_24dp `

Also, make sure that this change is reflected in all files where this icon is used.

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation
Fix #1645 
Changed name of drawable file ic_hintbulb_whilte_24dp.xml
Reviewers - @rt4914 @anandwana001 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
Thanks @prayutsu 
You can mention @rt4914 or me as a reviewer for this pull request.
 
Also, please have a look at [wiki](https://github.com/oppia/oppia-android/wiki) if you miss any step which is required before starting contributing to oppia-android. 

Also, there is a [guide](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR) in the wiki which helps you in making your pull request clean and ready to review by a reviewer.

**Comment by prayutsu** [comment]
@anandwana001 Thanks! I'll keep that in mind next time.

**Comment by anandwana001** [comment]
> @anandwana001 Thanks! I'll keep that in mind next time.

Welcome, These guides are just to make our work smooth.

**Comment by prayutsu** [comment]
@anandwana001 How can I edit those sections now?

**Comment by anandwana001** [comment]
> @anandwana001 How can I edit those sections now?

Which sections specifically?

**Comment by prayutsu** [comment]
Assignees and reviewers sections

**Comment by prayutsu** [comment]
Do I need to simply mention you in the description of pr?

**Comment by anandwana001** [comment]
> Assignees and reviewers sections

Are you able to click on Reviewers or Assignees on the right side of the screen?

**Comment by prayutsu** [comment]
> > Assignees and reviewers sections
> 
> Are you able to click on Reviewers or Assignees on the right side of the screen?

Nopes

**Comment by anandwana001** [comment]
> > > Assignees and reviewers sections
> > 
> > 
> > Are you able to click on Reviewers or Assignees on the right side of the screen?
> 
> Nopes

ok, as of now you can mention in PR description. @rt4914 will guide you more o this assigning part.

**Comment by prayutsu** [comment]
@anandwana001 thank you!

**Review by rt4914 — APPROVED** [review]
LGTM, thanks @prayutsu . Congratulations on your first PR.
Regarding `Assignees` and `Reviewers`, you will be ables to access that section once your two PRs gets merged.

Also, please take latest pull from `develop` and merge it in this PR and leave a comment with my name in it, so that I will know when its updated and I will merge this PR.

Thanks.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Blocking this PR on few points:

1. Merge latest `develop` in this branch.
2. Change the PR title to `Fix #1645 : Rename ic_hintbulb_whilte_24dp to ic_hint_bulb_white_24dp`
3. In future make sure that your branch name is of lower case characters separated by underscore like `rename_drawable_file`.
4. Commits / Branches should not include your name in it.
5. Also, please go through these instructions and follow them while creating PRs:
- https://github.com/oppia/oppia-android/wiki
- https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR

**Comment by prayutsu** [comment]
@rt4914 I'll take care in the future and I have updated the branch name and also pulled changes from develop branch

**Review by rt4914 — APPROVED** [review]
LGTM (Looks Good To Me), thanks.

**Pull request merged**
