### PR TITLE
Highfi NavigrationDrawer and consistent activity management

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

The issue for this PR has already been closed as there was no landscape mock for NavigationDrawer.

So this is a direct PR which deals with final fixing of navigation drawer in terms of highfi as well as in terms of opening activities consistently.

# Mock:
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/f60dd1fb-4a6e-42ea-bb94-84a148ace7d3/Side-Drawer/
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/79c56b13-218b-48fc-a403-b085d46953f3/AC-Side-Menu-

Screenshot_1585698916
Screenshot_1585698922

Note for reviewer: The kotlin files have been optimised to make sure that there is consistency for activity closing/opening from navigation drawer. I have checked the Navigation Drawer related test cases also and all of them are passing.

## Known issues
1. The accessibility test fail for highlighted text in navigation drawer.
2. The icon color is different than the text color in selected as well as unselected state. But actually in android the default behaviour is to have same color code for both icon as well as text. So @mschanteltc can you finalise this because preferable we should keep the icon/text color code same as per android default behaviour, at the same time if it is needed that actually those two should be different than I will try to figure out something.

@mschanteltc The accessibility test fails for `#C55F45` as well as `#E76F51`. So can we use some other color here?
as_13

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by veena14cs — CHANGES_REQUESTED** [review]
Only in HomeFragment navigation drawer width is 304dp. If I open drawer in other fragments it is changing its width. Please check.
Screenshot_20200401-141229

**Comment by rt4914** [comment]
> Only in HomeFragment navigation drawer width is 304dp. If I open drawer in other fragments it is changing its width. Please check.
> Screenshot_20200401-141229

Updated the implementation.

**Review by veena14cs — APPROVED** [review]
LGTM.

**Comment by mschanteltc** [comment]
> ## Explanation
> The issue for this PR has already been closed as there was no landscape mock for NavigationDrawer.
> 
> So this is a direct PR which deals with final fixing of navigation drawer in terms of highfi as well as in terms of opening activities consistently.
> 
> # Mock:
> https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/f60dd1fb-4a6e-42ea-bb94-84a148ace7d3/Side-Drawer/
> https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/79c56b13-218b-48fc-a403-b085d46953f3/AC-Side-Menu-
> 
> Screenshot_1585698916
> Screenshot_1585698922
> 
> Note for reviewer: The kotlin files have been optimised to make sure that there is consistency for activity closing/opening from navigation drawer. I have checked the Navigation Drawer related test cases also and all of them are passing.
> 
> ## Known issues
> 1. The accessibility test fail for highlighted text in navigation drawer.
> 2. The icon color is different than the text color in selected as well as unselected state. But actually in android the default behaviour is to have same color code for both icon as well as text. So @mschanteltc can you finalise this because preferable we should keep the icon/text color code same as per android default behaviour, at the same time if it is needed that actually those two should be different than I will try to figure out something.
> 
> @mschanteltc The accessibility test fails for `#C55F45` as well as `#E76F51`. So can we use some other color here?
> as_13
> 
> ## Checklist
> * [ ]  The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
> * [ ]  The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
> * [x]  The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
> * [x]  The PR does not contain any unnecessary auto-generated code from Android Studio.
> * [x]  The PR is made from a branch that's **not** called "develop".
> * [x]  The PR is made from a branch that is up-to-date with "develop".
> * [x]  The PR's branch is based on "develop" and not on any other branch.
> * [x]  The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Use #BE563C for the orange color. I believe the accessibility requirements should pass with this.

**Pull request merged**
