### PR TITLE
Fix on issue Add dark mode support to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity

### LINKED ISSUE #4193: Add dark mode support to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity
Add dark mode support to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity.

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

### PR DESCRIPTION
**Pull request by TheSwarnim**
…lyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity

## Explanation

Fixes #4193
This PR resolved the issue to add dark mode to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity.
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by TheSwarnim** [comment]
All the relevant screenshots can be found here: https://docs.google.com/document/d/1gVtVFurb8Epzy6MiWX5oUB5A1zr-EVmcQkNjIjHkUKQ/edit?usp=sharing

**Comment by TheSwarnim** [comment]
Hi @rt4914, I've completed and added all ss of dark mode format on this [link](https://docs.google.com/document/d/1gVtVFurb8Epzy6MiWX5oUB5A1zr-EVmcQkNjIjHkUKQ/edit?usp=sharing). Please review this pr.

**Comment by rt4914** [comment]
@TheSwarnim Please make sure that the assignee section is up-to-date otherwise it will get missed. 
https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

**Comment by rt4914** [comment]
Also please update your PR description as it starts with unexpected characters.

**Comment by TheSwarnim** [comment]
Hi @rt4914, please review this pr again. I've updated the description of the pr to clearly state what issue I'm working on here.

**Comment by TheSwarnim** [comment]
All screen shots are here : [link](https://docs.google.com/document/d/1gVtVFurb8Epzy6MiWX5oUB5A1zr-EVmcQkNjIjHkUKQ/edit?usp=sharing).
For your reference

**Comment by TheSwarnim** [comment]
Hi @ayush0402, will it be possible to undo your last commit and then merge your pr after this pr, since it causing unusual conflict on my pr and it will be hard for me to resolve all the changes caused by merging your latest pr?

**Comment by ayush0402** [comment]
@TheSwarnim I am not sure about undoing the commit but we just actually renamed every color declarations to have prefix of it's file name as per this [comment](https://github.com/oppia/oppia-android/pull/4205#issuecomment-1052251992), you might have to work around those changes and rename every existing color you were using to have the prefix of its file name.

**Comment by TheSwarnim** [comment]
Hi @rt4914 @ayush0402, I've resolved the conflicts. Please review the pr again. All ss is here [link](https://docs.google.com/document/d/1gVtVFurb8Epzy6MiWX5oUB5A1zr-EVmcQkNjIjHkUKQ/edit?usp=sharing).

**Comment by TheSwarnim** [comment]
Hi @vrajdesai78, please review this pr

**Comment by ayush0402** [comment]
@TheSwarnim This PR has changes which are not supposed to be a part of it. Can you update this branch with develop?

**Pull request closed without merging**
