### PR TITLE
Fix #1317: Fix lint issues in domain module in the kotlin files

### LINKED ISSUE #1317: Fix lint issues in domain module in the kotlin files
Fix lint issues in kotlin files in the domain module. Take the package with its respective test folder and create sub pr for them.

* [x] analytics

* [x] audio

- [x] classify

    * [x] classify test 

    * [x] classify rules (continueinteraction, dragAndDropSortInput, ItemSelectionInput)

    * [x] classify rules (fractioninput, multiplechoiceinput, numberwithunits)

    * [x] classify rules (other outer rules files, textinput, numericinput)
     
    * [x] classify (files direct inside this package)  

* [x] exploration

* [x] onboarding

* [x] profile

* [x] question

* [x] state

* [x] topic

* [x] util

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #1317 
adding ktlint check in the domain module to `circleci`

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
By mistake I closed this PR in #1396 because of the issue number incorrectly written. So re-opening this PR.

**Review by vinitamurthi — APPROVED** [review]
FYI we will be moving to github actions soon..let me know when this PR goes in and I will add the domain lint check to the Github Action one as well

**Review by rt4914 — APPROVED** [review]
LGTM

**Comment by vinitamurthi** [comment]
Just checking here, I can now add this to Github Actions too right?

**Comment by anandwana001** [comment]
> Just checking here, I can now add this to Github Actions too right?

That's perfect, yeah sure, complete domain linting is done.

**Pull request merged**
