### PR TITLE
Fix #2116: Update tablet UI for profile_chooser_add_view.xml

### LINKED ISSUE #2116: Fix UI for profile chooser screen in add-view
`profile_chooser_add_view.xml` needs to be updated so that the UI looks similar to mocks.

## Mocks
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid
https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/33741ea7-89da-4e5d-b2a4-9872f6db48b4/
https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/6fb19f15-699a-40aa-8392-cdfc6d7bf8c5/

https://github.com/oppia/oppia-android/wiki/Working-on-UI

## Current Screenshot
Screenshot_1605508088
Screenshot_1605508113
Screenshot_1605508138
Screenshot_1605508141

## Device:
Nexus-9 Emulator
API 29

### PR DESCRIPTION
**Pull request by ShridharGoel**
## Explanation

Fixes #2116 

Updated margin and padding to align add profile option properly.

## Checklist
- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

## Screenshots

Screenshot - Landscape

Screenshot - Portrait

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
@ShridharGoel Thanks for the PR.

The gap between each circle is not equal. Meaning the gap between `Admin Profile` and `Test Profile` is different than `Test Profile` and `Add Profile`.

You can refer to this guide while working on UIs. 
https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by ShridharGoel** [comment]
@rt4914 Okay, I thought `Add Profile` was supposed to be a bit far from the list of profiles. Updating it.

**Comment by rt4914** [comment]
> @rt4914 Okay, I thought `Add Profile` was supposed to be a bit far from the list of profiles. Updating it.

No issues. Thanks for clarification.

**Comment by ShridharGoel** [comment]
@rt4914 Updated.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Thanks @ShridharGoel 

There is still one issue with the alignment.
Screenshot_1606281835


You can fix this by changing the `add_profile_item` width to `match_parent`

**Comment by ShridharGoel** [comment]
@rt4914 Updated accordingly.

**Comment by ShridharGoel** [comment]
`ExplorationActivityTest` seems to have failed. But on running locally, it's passing. Also, that is not related to this PR.

**Comment by ShridharGoel** [comment]
@anandwana001 @rt4914 Can you restart the tests?

**Comment by ShridharGoel** [comment]
All checks have passed now.

**Comment by rt4914** [comment]
> You can fix this by changing the `add_profile_item` width to `match_parent`

@ShridharGoel 
As per my earlier comment the changes are not correct.

You just have to update the `add_profile_item` width to `match_parent` in both portrait and landscape mode.

NOTE: That this will just solve one issue which is related to `profile_chooser_add_view` but there is still UI changes needed for `profile_chooser_profile_view` which we will do once this change is made.

**Comment by ShridharGoel** [comment]
@rt4914 But the width of `add_profile_item` is already set to `match_parent`. If you're talking about changing the width of the outer LinearLayout to `wrap_content`, I had done that to fix the issue of extra gap between the add circle and the profile circle. Should that be reverted?

**Comment by rt4914** [comment]
> @rt4914 But the width of `add_profile_item` is already set to `match_parent`. If you're talking about changing the width of the outer LinearLayout to `wrap_content`, I had done that to fix the issue of extra gap between the add circle and the profile circle. Should that be reverted?

@ShridharGoel Maybe try both as match_parent and see if the UI is correct.

**Comment by ShridharGoel** [comment]
@rt4914 Already tried that. It was creating extra gap.

**Comment by rt4914** [comment]
> @rt4914 Already tried that. It was creating extra gap.

@ShridharGoel Can you start working on some other issue? Actually I did try to solve this and its not working correctly under different circumstances. I will have to give proper time to this to fix this across all layouts.

**Comment by ShridharGoel** [comment]
@rt4914 Okay.

**Comment by rt4914** [comment]
Closing this PR, as this issue will be fixed by me.

**Pull request closed without merging**
