### PR TITLE
Fix#2483: Spacing issue in `colors` folder xml files(#2483)

### LINKED ISSUE #2483: Spacing issue in `colors` folder xml files
In below mentioned folder(s) there are 4 files which contains nit spacing issue. There should be one blank space just before `/>`.

https://github.com/oppia/oppia-android/tree/develop/app/src/main/res/color
https://github.com/oppia/oppia-android/tree/develop/app/src/main/res/color-sw600dp-port
https://github.com/oppia/oppia-android/tree/develop/app/src/main/res/color-sw600dp-land

You can also fix this by using reformatting shortcut: https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting

### PR DESCRIPTION
**Pull request by Manikant25**
## Explanation
Fixes #2483 reformating XML codes by inserting one blank space before ```/>```  .

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by chrk2205** [comment]
@Manikant25 
the PR Explanation should start with `Fixes #bugnum` as mentioned in the checklist

**Review by chrk2205 — APPROVED** [review]
LGTM thanks
@Manikant25

**Comment by Luffy18346** [comment]
@Manikant25 
the PR Explanation should start with "Fixes #bugnum" and not "Fix #bugnum" and also remove "/>" at the end of the explanation.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
