### PR TITLE
Fix #3053: Shift RichTextViewMatcher to testing module

### LINKED ISSUE #3053: Shift RichTextViewMatcher to Testing module
**Is your feature request related to a problem? Please describe.**
Currently, `RichTextViewMatcher` is inside the `sharedTest` folder of app module. 

**Describe the solution you'd like**
`RichTextViewMatcher` is a helper class. Thus, it needs ti be in the testing module. 

**Additional context**
https://github.com/oppia/oppia-android/blob/develop/app/src/sharedTest/java/org/oppia/android/app/parser/RichTextViewMatcher.kt

### PR DESCRIPTION
**Pull request by Sparsh1212**
## Explanation

Fixes #3053 : Shift RichTextViewMatcher to testing module
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Sparsh1212** [comment]
@anandwana001 
All the checks are passing except one. I am not sure why it's failing.

**Comment by anandwana001** [comment]
It's showing there is some issue in the concept card test file 

Test target: //app:src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest//utility:src/test/java/org/oppia/android/util/parser/MathTagHandlerTest

**Comment by Sparsh1212** [comment]
> It's showing there is some issue in the concept card test file
> 
> Test target: //app:src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest//utility:src/test/java/org/oppia/android/util/parser/MathTagHandlerTest

Yes, I saw this error in the GithubActions log, but I am not able to understand the issue. Am I missing to include any dependency somewhere? If yes, then please guide me on it.

**Comment by anandwana001** [comment]
I am trying to re-running the checks. 
Could you confirm if these bazel test is failing for you on local? 

Bazel Guide - https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions

**Comment by rt4914** [comment]
@fsharpasharp Can you please check why the bazel tests are failing?

**Review by rt4914 — APPROVED** [review]
Approving as it is blocked by @anandwana001 . Make sure that the bazel tests pass on this PR.

**Review by fsharpasharp — APPROVED** [review]
BUILD.bazel changes look good to me!

**Comment by Sparsh1212** [comment]
> I am trying to re-running the checks.
> Could you confirm if these bazel test is failing for you on local?
> 
> Bazel Guide - https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions

Apologies! will check the local tests by today.

**Comment by Sparsh1212** [comment]
@anandwana001 I did the Bazel checks on my local, and all of them were passing.

The `ConceptCardFragmentTest` also passed successfully.

image
image
image
image

**Review by anandwana001 — APPROVED** [review]
LGTM

**Pull request merged**
