### PR TITLE
Fix #653 : Lowfi Landscape: Add Profile

### LINKED ISSUE #653: Lowfi Landscape: Add Profile
Mock Link:
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/645052fe-103b-4ca0-8250-e3b0d50bb169/PC-SP-Add-Profile-

## Checklist
- [ ] Lowfi Landscape
- [ ] Test cases for Landscape

### PR DESCRIPTION
**Pull request by SayantanBanerjee16**
Fixes #653.

Implemented the Landscape mode and ensured all the three edit text (name, input_pin and confirm_pin fields) data remain consistent during a configuration change. Ensured it through data binding and view model.

Also related all Tests implemented, including tests to check data remain consistent during configuration change.

A bug also fixed After Selecting PIN checkbox, entering the PIN, then deselecting PIN checkbox, the user profile is created provided user name exists. Previously, the profile was not being created.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
This a very nice implementation. Awesome work.
I think we should add more correct test cases in this PR. You can keep following test cases and add some test cases with following functionality.
1. Enter name -> Orientation Change -> Is Name still visible in textview?
2. Enter name "Sean" -> Click on submit should give error-> Orientation Change -> Error should still be visible.
3. Select Checkbox -> Orientation Change -> Checkbox is still selected.
4. Enter PIN in both boxes -> Orientation Change -> Pin should be present.
5. Enter PIN in both boxes (both pin should not match) -> Click submit, which should give error -> OrientationChange -> Error should be visible.
6. Enter correct PIN in both, turn-on switch - Orientation Change - Check if switch is still on.

Thanks.

**Comment by SayantanBanerjee16** [comment]
> This a very nice implementation. Awesome work.
> I think we should add more correct test cases in this PR. You can keep following test cases and add some test cases with following functionality.
> 
> 1. Enter name -> Orientation Change -> Is Name still visible in textview?
> 2. Enter name "Sean" -> Click on submit should give error-> Orientation Change -> Error should still be visible.
> 3. Select Checkbox -> Orientation Change -> Checkbox is still selected.
> 4. Enter PIN in both boxes -> Orientation Change -> Pin should be present.
> 5. Enter PIN in both boxes (both pin should not match) -> Click submit, which should give error -> OrientationChange -> Error should be visible.
> 6. Enter correct PIN in both, turn-on switch - Orientation Change - Check if switch is still on.
> 
> Thanks.

@rt4914  Thanks for the compliment. I would implement more test cases ASAP.

**Comment by SayantanBanerjee16** [comment]
@rt4914 Test no 1 was added from previously. Rest all other tests implemented. (2 to 6).
PTAL. Thanks :)

**Review by rt4914 — CHANGES_REQUESTED** [review]
3 test case failing.
Screenshot 2020-03-23 at 12 37 24 PM

**Comment by SayantanBanerjee16** [comment]
@rt4914 Well, these 3 test cases (in fact all 44 test cases) are passing in my device. Anyways, I made a few changes which I think could be a cause for failure in other devices and not in mine., like adding `scrollTo()` and `closeSoftKeyboard()`. Can you please check again. Thanks :)

Also if it fails further, please let me know the reason for failure.

**Comment by SayantanBanerjee16** [comment]
@rt4914 All the tests previously also passed in my device. Well, I have made a few changes like the addition of `scrollTo` and  `closeSoftKeyboard` which may ensure passing in all the devices. Can you please review it again? Thanks :)

Also if it fails further, can you tell me the reason for the failure?

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
