### PR TITLE
Fix #3566: Merge profile_rename_activity.xml into single xml file

### LINKED ISSUE #3566: Merge profile_rename_activity.xml into single xml file
Currently there are 2 versions of `profile_rename_activity.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

### PR DESCRIPTION
**Pull request by MohitGupta121**
Fix Issue #3566 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

<table role="table">
<thead>
<tr>
<th>OLD Screenshots Mobile</th>
<th>NEW Screenshots Mobile</th>
</tr>
</thead>
<tbody>
<tr>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/76530270/138030278-910e64a8-6b63-4d1c-9e86-59d7bdc02e32.jpg">Screenshot_20210804_152357</a></td>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/76530270/138030276-1cb61319-5053-4724-8403-ecb6c1d40b47.jpg">Screenshot_20210804_152357</a></td>
</tr>
<tr>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/76530270/138030456-3ce25105-b32d-4b3e-bfff-5133d06c92ca.jpg">Screenshot_20210804_152412</a></td>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/76530270/138030453-a66ff27e-e2e1-4569-91e6-fd95525ae93c.jpg">Screenshot_20210804_152412</a></td>
</tr>

<thead>
<tr>
<th>OLD Screenshots TABLET</th>
<th>NEW Screenshots TABLET</th>
</tr>
</thead>
<tr>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/76530270/138030563-0610e59e-bbfb-4690-9bdf-08abd4ed3992.jpg">Screenshot_20210804_152456</a></td>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/76530270/138030567-9ad567bb-e76b-41b5-8837-c71c7737043a.jpg">Screenshot_20210804_152456</a></td>
</tr>
<tr>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/76530270/138030694-59c86b6a-6520-470b-ac28-3e2f0693f420.jpg">Screenshot_20210804_152510</a></td>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/76530270/138030692-c3205938-12f5-4ee5-96e3-e702975b0d40.jpg">Screenshot_20210804_152510</a></td>
</tr>
</tbody>
</table>

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@rt4914 bro please review my pull request for issue #3950 .

**Comment by MohitGupta121** [comment]
@rt4914 this PR is automatically closed what I can do now, can you please review this PR

**Comment by MohitGupta121** [comment]
@rt4914 can you please review my this pull request

**Comment by MohitGupta121** [comment]
@rt4914 can u please review my this pull request.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
