### PR TITLE
Fix #4470, #4472, #4473 : Handle configuration change using onSavedInstance.

### LINKED ISSUE #4470: Handle configuration change using onSavedInstance
**Problem**
For all interactions in exploration player and question player when we rotate our device, selected or entered answer doesn't persist. 

**Solution**
To solve this problem of configuration change we use onSavedInstance method to store the last entered user answer. 

**Alternatives**
- **Singleton Class Approach**: Complextiy of code will be increased if we use this approach as we have to write additional singleton class. Also, we need to handle issue of memory leak separately as it is not life-cycle aware. 
- **ViewModel Approach**: It is difficult to handle interactions when we have more than two interactions on one screen as all interactions are tightly coupled. 

Note: Closing issue #1737 as the approach for configuration change is changed to onSavedInstance from Singleton class approach.

### LINKED ISSUE #4472: Handle configuration change for ImageRegionSelectionInteraction
Handle configuration change for ImageRegionSelectionInteraction such that if screen is rotated, last selected image region should be retained. 

**Steps to Reproduce**
1. Open app and visit `ImageRegionSelection` based exploration in `Test Topic 1`
2. Click continue
3. Select some area in the given image (DO NOT SUBMIT THE ANSWER)
4. Now rotate the app
5. Notice that the selection is cleared.

**Expected Behaviour**
The selection should not get cleared.

**Similar issues**
#4471
#4474
#4473

### LINKED ISSUE #4473: Handle configuration change for DragAndDropInteraction
Configuration change should be handled for DragAndDropInteraction such that when device is rotated, last selected answer of user persist. 

**Steps to reproduce the bug**:

1. Open app and visit `Prototype Exploration`
2. Answer questions until you reach DragAndDropInteraction (mostly last second question in this exploration)
3. In DragAndDropInteraction, change the order of options (DO NOT SUBMIT THE ANSWER)
4. Now rotate your screen
5. Notice that the DragAndDropInteraction values have been reset.

**Expected behaviour**
The last order of values should persist during rotation, so that user doesn't need to re-order the values.

**Similar issues**
#4471
#4472
#4474

### PR DESCRIPTION
**Pull request by Vishwajith-Shettigar**
## Explanation
Fixes #4470, Fixes #4472, Fixes #4473.

This PR enables the retention of input when the device configuration changes using onSavedInstance.

List of interactions covered in this PR:
1. Image Region selection interaction.
2. Drag and Drop interaction

| Drag and Drop |
-------------------

 https://github.com/user-attachments/assets/1919f99d-d56d-4bbe-b0bc-6092c488165e 

| Image Region  |
-------------------

https://github.com/user-attachments/assets/ac1ebcd8-92cd-47ca-82af-1208751a7093 

Rest are covered in this PR #5458

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, could you please give this a green light for writing tests? Let me know if there are any concerns or suggestions for improvement.

**Comment by adhiamboperes** [comment]
@Vishwajith-Shettigar, I think it's good to go. We have already established the prefered solution, so feel free to complete the PR.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, In image region selection interaction, when we select any default region in portrait mode and store coordinates in saved instances, and then rotate the device (landscape), we can't actually show the exact point of the default region selection mark, because the view size would be different in portrait and landscape mode, leading to the selection mark going anywhere. For more context i have attached screen recording.

https://github.com/user-attachments/assets/972b1fde-366b-4dc6-a051-88885b4026d2


A solution would be:
Either We can just ignore the default region selection retention since it is not very important.
Or we need to find a way to map portrait mode coordinates with the landscape view and landscape mode coordinates with portrait view.

**Comment by adhiamboperes** [comment]
@Vishwajith-Shettigar, it sounds like a lot of engineering effort to map image selection cordinates on config change, that seems a bit out of scope for this issue. Besides, I tried testing with other popular apps(google apps, social media apps) to see how they handle such scenarios, and I found that they prefer to lock orientation as a workaround. So in our case,  it is safe to not save the selection.

**Comment by Vishwajith-Shettigar** [comment]
Thanks @adhiamboperes.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

**Review by adhiamboperes — APPROVED** [review]
LGTM, thanks @Vishwajith-Shettigar!

**Pull request merged**
