### PR TITLE
Fix part of #2003: Replacing space 16dp,space_12dp

### PR DESCRIPTION
**Pull request by Arjupta**
## Explanation

Fixes part of #2003 
This PR replaces the use of space_16dp and space_12dp with the dimensions having contextful names

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Arjupta** [comment]
@rt4914 I will create a final PR related to this issue but I am facing a problem in that. space_0dp is used in more than 700 places. what should I do for it.  Should I hardcode 0dp or should I make these dimensions

**Comment by rt4914** [comment]
@ARJUPTA Please update this PR with latest develop.

**Comment by rt4914** [comment]
> @rt4914 I will create a final PR related to this issue but I am facing a problem in that. space_0dp is used in more than 700 places. what should I do for it. Should I hardcode 0dp or should I make these dimensions

That depends.
1. If the `0dp` is in `layout_width` - hardcode it.
2. If the `0dp` is in `elevation` - hardcode it.
3. Else mostly it will be mentioned in xml.

I suggest create one PR for (1.) and (2.) and after that we can take care of 3rd in next PR.

**Comment by Arjupta** [comment]
> @ARJUPTA Please update this PR with latest develop.

@rt4914 I have updated it please check.

**Comment by Arjupta** [comment]
> > @rt4914 I will create a final PR related to this issue but I am facing a problem in that. space_0dp is used in more than 700 places. what should I do for it. Should I hardcode 0dp or should I make these dimensions
> 
> That depends.
> 
> 1. If the `0dp` is in `layout_width` - hardcode it.
> 2. If the `0dp` is in `elevation` - hardcode it.
> 3. Else mostly it will be mentioned in xml.
> 
> I suggest create one PR for (1.) and (2.) and after that we can take care of 3rd in next PR.

Okay.

**Comment by rt4914** [comment]
> > @ARJUPTA Please update this PR with latest develop.
> 
> @rt4914 I have updated it please check.

It is 2 commits behind develop.

Screenshot 2020-11-23 at 6 59 27 PM

**Comment by Arjupta** [comment]
> > > @ARJUPTA Please update this PR with latest develop.
> > 
> > 
> > @rt4914 I have updated it please check.
> 
> It is 2 commits behind develop.
> 
> Screenshot 2020-11-23 at 6 59 27 PM

Actually another PR got merged by the time you saw the comment

**Comment by Arjupta** [comment]
Screenshot 2020-11-23 190738

@rt4914 I have updated it. can you check it now

**Comment by rt4914** [comment]
> Screenshot 2020-11-23 190738
> 
> @rt4914 I have updated it. can you check it now

Your https://github.com/ARJUPTA/oppia-android/tree/replacing-space-16dp-12dp branch is not up-to-date. My earlier image reference was to that.

**Comment by Arjupta** [comment]
@rt4914 should i rebase it on the develop branch , because I am unable to find any other way to handle stacked PRs. Also will this effect the next PR I am going to make

**Comment by rt4914** [comment]
> @rt4914 should i rebase it on the develop branch , because I am unable to find any other way to handle stacked PRs. Also will this effect the next PR I am going to make

Just merge your current branch with latest develop and that should work.

```
git checkout replacing-space-16dp-12dp
git fetch upstream
git merge upstream/develop
git commit ... <IF NEEDED>
git push origin replacing-space-16dp-12dp
```


Something like this.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
