### PR TITLE
Fix #2202: Adding bullet points in FAQ answers

### LINKED ISSUE #2202: Some Answers in FAQ needs bullet points
**Describe the bug**
few FAQ answers does'nt have bullet points

**To Reproduce**
1. Go to 'FAQ'
2. Click on Any Question of following `How can I delete a profile?`, `Why is the Exploration player not loading?`,  `Why is my audio not playing?`
3. Check the answer contains '-' instead of a bullet point

**Expected behavior**
Bullets points in the place of '-' 

**Screenshots**

How can I delete a profile? | Why is the Exploration player not loading? | Why is my audio not playing?
--- | --- | ---
Screenshot_1606821079 | Screenshot_1606821099 | Screenshot_1606821103 

**Additional context**
[reference link](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/195a7967-e7f0-4f62-a99c-8fac560e41d8/specs/)

### PR DESCRIPTION
**Pull request by FareesHussain**
## Explanation

Fixes #2202 
 - Changed all lines with '-' to bullet points

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

 ## Screenshots
How can I delete a profile? | Why is the Exploration player not loading? | Why is my audio not playing?
--- | --- | ---
Screenshot_1606821079 | Screenshot_1606821099 | Screenshot_1606821103

### CODE REVIEW

**Comment by FareesHussain** [comment]
@anandwana001 please check

**Review by anandwana001 — APPROVED** [review]
LGTM,Thanks @FareesHussain 

Defer to @rt4914 for further merge. Also, does the line spacing in. these bullets looks correct to you?
Also, do you think we need a new pr here as there are commits which are from the different branch?

**Review by rt4914 — CHANGES_REQUESTED** [review]
@FareesHussain Blocking this PR for now because we will need to take approval from @mschanteltc first considering that in her designs she had mentioned `-` instead of bullets.

Original Designs:


How can I delete a profile? | Why is the Exploration player not loading? | Why is my audio not playing?
--- | --- | ---
Screenshot_1606821079 | Screenshot_1606821099 | Screenshot_1606821103

**Comment by mschanteltc** [comment]
@rt4914 I actually prefer the bullet point designs more than the `-` dashes since bullet points draw more attention. 

Also would it be possible we can indent all bullet points? Left aligning the bullet points with the body text makes it harder to identify the main points (i.e. "Check your internet connection:"). Indenting bullet points would make them more associated with the description that precedes it.

**Comment by rt4914** [comment]
> @rt4914 I actually prefer the bullet point designs more than the `-` dashes since bullet points draw more attention.
> 
> Also would it be possible we can indent all bullet points? Left aligning the bullet points with the body text makes it harder to identify the main points (i.e. "Check your internet connection:"). Indenting bullet points would make them more associated with the description that precedes it.

1. Sounds good.

2. I am actually not able to understand the indent part. Does this mean that we should give some start margin for bullets similar to what google doc does?

@mschanteltc

**Comment by rt4914** [comment]
> > @rt4914 I actually prefer the bullet point designs more than the `-` dashes since bullet points draw more attention.
> > Also would it be possible we can indent all bullet points? Left aligning the bullet points with the body text makes it harder to identify the main points (i.e. "Check your internet connection:"). Indenting bullet points would make them more associated with the description that precedes it.
> 
> 1. Sounds good.
> 2. I am actually not able to understand the indent part. Does this mean that we should give some start margin for bullets similar to what google doc does?
> 
> @mschanteltc

Update on this. We are merging this PR as this does not affect what @mschanteltc is suggested related to indentation. For that once @mschanteltc clarifies above question we will file a separate issue.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by mschanteltc** [comment]
> > > @rt4914 I actually prefer the bullet point designs more than the `-` dashes since bullet points draw more attention.
> > > Also would it be possible we can indent all bullet points? Left aligning the bullet points with the body text makes it harder to identify the main points (i.e. "Check your internet connection:"). Indenting bullet points would make them more associated with the description that precedes it.
> > 
> > 
> > 
> > 1. Sounds good.
> > 2. I am actually not able to understand the indent part. Does this mean that we should give some start margin for bullets similar to what google doc does?
> > 
> > @mschanteltc
> 
> Update on this. We are merging this PR as this does not affect what @mschanteltc is suggested related to indentation. For that once @mschanteltc clarifies above question we will file a separate issue.

Yes your second note is what I am suggesting. Increase the left margin of the bullet point in the same way that Google Doc does it.

**Comment by rt4914** [comment]
> > > > @rt4914 I actually prefer the bullet point designs more than the `-` dashes since bullet points draw more attention.
> > > > Also would it be possible we can indent all bullet points? Left aligning the bullet points with the body text makes it harder to identify the main points (i.e. "Check your internet connection:"). Indenting bullet points would make them more associated with the description that precedes it.
> > > 
> > > 
> > > 
> > > 1. Sounds good.
> > > 2. I am actually not able to understand the indent part. Does this mean that we should give some start margin for bullets similar to what google doc does?
> > > 
> > > @mschanteltc
> > 
> > 
> > Update on this. We are merging this PR as this does not affect what @mschanteltc is suggested related to indentation. For that once @mschanteltc clarifies above question we will file a separate issue.
> 
> Yes your second note is what I am suggesting. Increase the left margin of the bullet point in the same way that Google Doc does it.

Thanks. Filed https://github.com/oppia/oppia-android/issues/2228

**Pull request merged**
