### PR TITLE
Re-bump version codes for version 0.13 RC01 and test-only release

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
This updates version codes for the 0.13 beta release of Oppia Android. #5389 was made without an actual release taking place, and we've since launched a test version of the app using release automation that used up version code 151. Thus, this brings version codes 2 releases past version code 151:
- The earlier version codes (-7 from the ones in this PR) will be used for the 0.13 release.
- The current version codes will be used for a tester-only version of the app to verify our QA tester installation process.

## Essential Checklist
- [ ] ~The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)~
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A -- build infrastructure-only change.

### CODE REVIEW

**Review by BenHenning — COMMENTED** [review]
Self-review version changes.

**Comment by BenHenning** [comment]
@seanlip PTAL for codeowners.

**Comment by adhiamboperes** [comment]
@BenHenning, Just checking. PR description says, -7 from the version codes in this PR, do you mean Math minus since it's not clear from the values? I may have misunderstood.

**Comment by BenHenning** [comment]
> @BenHenning, Just checking. PR description says, -7 from the version codes in this PR, do you mean Math minus since it's not clear from the values? I may have misunderstood.

Apologies @adhiamboperes for the lack of clarity. What I meant was that since each release RC has 7 version codes associated with it (for each of the possible flavors of that release), this PR is bumping forward the version codes for _two_ release candidates from version code 151 (since that's the newest version pushed to play console, and we need to push releases with larger version codes).

Does that help clarify?

**Review by adhiamboperes — APPROVED** [review]
LGTM thanks.

**Comment by adhiamboperes** [comment]
> > @BenHenning, Just checking. PR description says, -7 from the version codes in this PR, do you mean Math minus since it's not clear from the values? I may have misunderstood.
> 
> Apologies @adhiamboperes for the lack of clarity. What I meant was that since each release RC has 7 version codes associated with it (for each of the possible flavors of that release), this PR is bumping forward the version codes for _two_ release candidates from version code 151 (since that's the newest version pushed to play console, and we need to push releases with larger version codes).
> 
> Does that help clarify?

Got it, Thanks. I thought that you meant the numeric dfference in previous vs current codes 😁

**Comment by BenHenning** [comment]
Thanks @adhiamboperes!

**Comment by BenHenning** [comment]
Merging since this doesn't actually need @seanlip's review, and @adhiamboperes reviewed it.

**Pull request merged**
