### PR TITLE
Fix #2304: Revert "Remove self-code ownership until 2021-01-05"

### LINKED ISSUE #2304: Restore @BenHenning code ownership after 2021-01-05
Restore @BenHenning code ownership after 2021-01-05. Also, look into fixing some of the other codeowners matching issues.

### PR DESCRIPTION
**Pull request by BenHenning**
Fix #2304

Reverts oppia/oppia-android#2305 to restore ownership to me.

### CODE REVIEW

**Comment by BenHenning** [comment]
@seanlip PTAL.

**Review by seanlip — APPROVED** [review]

**Comment by BenHenning** [comment]
Thanks! Will rely on auto-merge. :)

**Comment by BenHenning** [comment]
Hmm auto-merge didn't work. :(

**Comment by BenHenning** [comment]
(for posterity: I don't think I properly enabled auto-merge so I think we can disregard the comment above about it not working)

**Comment by seanlip** [comment]
FYI auto-merge failed for me on another PR earlier today as well (in the oppia/oppia repo). So ... it might also be the case that it isn't working properly :P

**Pull request merged**
