### PR TITLE
[RunAllTests] Fix part of #3287: Remove javax.annotation-api as prod dependency

### PR DESCRIPTION
**Pull request by BenHenning**
Fix part of #3287.

## Explanation
This PR removes a prod dependency that we only need for test environments, also avoiding needing to ship the code for this dependency.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by BenHenning** [comment]
@rt4914 & @prayutsu PTAL.

Note that I am relying on CI to verify that nothing breaks here.

**Comment by BenHenning** [comment]
Unsurprisingly, it seems like the compute affected tests script is going to hang. Restarting CI to run all Bazel tests to confirm compatibility.

**Comment by prayutsu** [comment]
@BenHenning I have verified locally that we'll don't need to pull the CDDL license if we remove this dependency.
Also, it looks like the tests are failing.

**Comment by BenHenning** [comment]
Thanks @prayutsu. I think the CI failures are revealing that Dagger might be pulling in the javax.annotation dependency indirectly in Bazel vs. requiring us to include it (for Gradle). Keeping the Bazel dep for now to make it explicit when we compute the list of dependencies for which we need licenses.

**Pull request closed without merging**
