### PR TITLE
Fix part of #2003: Replacing all dimensions except space_0dp

### PR DESCRIPTION
**Pull request by Arjupta**
## Explanation

Fixes part of #2003  This PRreplaces all the dimensions with the one having contextful names.
(except space_0dp)
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Arjupta** [comment]
@rt4914 there was no usage of space_0dp in the width or elevation property of any view. Also, I think it is better to have space_0dp as the dimension as it explains the developer that there will be no space present at the places where space_0dp is used and the dimensions elsewhere will provide the information that there will be an extra space (not caring for its value) WDYT?

**Comment by rt4914** [comment]
> @rt4914 there was no usage of space_0dp in the width or elevation property of any view. Also, I think it is better to have space_0dp as the dimension as it explains the developer that there will be no space present at the places where space_0dp is used and the dimensions elsewhere will provide the information that there will be an extra space (not caring for its value) WDYT?

Lets keep it like this only for now. We will not close the main issue but we can assign you 150 points.

**Comment by rt4914** [comment]
Also your PR description points to incorrect issue number.

**Comment by ARJUPTA** [comment]
updating it

**Comment by Arjupta** [comment]
Is it okay know

**Review by rt4914 — APPROVED** [review]
LGTM, Great work. Thanks.

**Comment by rt4914** [comment]
give @ARJUPTA 150 points

**Pull request merged**
