### PR TITLE
Fix part of #10: Hifi home part 1

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

This PR mainly works around margin/padding between varius items. The main focus in this PR was on custom SnapHelper for carousel.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/cb72aed9-af32-4ab6-9a80-394d9b30f6a3/HP-Home-Page-1

If you see the carousel in mock, when we are on second item, the left and right margins for the item are not equal, meaning the item tends to be more towards left side.

Screenshots:
## First Item
Screenshot_1575399336
## Second Item
Screenshot_1575399339
##Third Item
Screenshot_1575399342

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by mschanteltc** [comment]
LGTM

**Review by veena14cs — APPROVED** [review]
LGTM

**Comment by rt4914** [comment]
@BenHenning should we merge this in your `temp-integration-pt-3` ?

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Comment by rt4914** [comment]
This PR is getting closed as it has been recreated at #538 

This was done because this PR had base branch as `temp-integration-pt-3` and we need this code on `develop now`.

**Pull request closed without merging**
