### PR TITLE
Fix #1595 : Landscape support for ItemSelectionInteraction

### LINKED ISSUE #1595: Landscape support for ItemSelectionInteraction [Blocked on #1737]
**Describe the bug**
If learner has selected few options in `ItemSelectionInteraction` and does configuration change the selection disappears.

**To Reproduce**
1. Go to `Prototype Exploration`
2. Go to below mentioned state:
Screenshot_1597062466

3. Select 2-3 options
4. Change device configuration
5. Notice that the selection resets.

**Expected behavior**
`ItemSelectionInteraction` should persist selected items on configuration change. Fix this for question and exploration player.

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation

Fixes #1595  : Landscape support for ItemSelectionInteraction
Made some changes and pushing them to get reviews
Tried implementing saveStateHandle

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
Before pushing your code try it out locally and check whether it works or not.

**Comment by prayutsu** [comment]
> Before pushing your code try it out locally and check whether it works or not.



> Before pushing your code try it out locally and check whether it works or not.

Actually, it does not work. I just want you to take a look at it and help me out if I am going wrong.

**Comment by aggarwalpulkit596** [comment]
Yes, that is wrong and it wouldn't work that way. SavedStateHandle is wrapper class which is nothing else that stores list of key-value pairs, if you want to make it work it should be bound to an activity first.

https://developer.android.com/topic/libraries/architecture/viewmodel-savedstate read here - we are using a Custom ViewModel Provider so you need to inject saveState in that.

https://proandroiddev.com/connecting-the-dots-44d8fa79f14 
https://github.com/hansenji/ViewModelInject 

Read above if you want some context on how this can be done.

**Comment by prayutsu** [comment]
> Yes, that is wrong and it wouldn't work that way. SavedStateHandle is wrapper class which is nothing else that stores list of key-value pairs, if you want to make it work it should be bound to an activity first.
> 
> https://developer.android.com/topic/libraries/architecture/viewmodel-savedstate read here - we are using a Custom ViewModel Provider so you need to inject saveState in that.
> 
> https://proandroiddev.com/connecting-the-dots-44d8fa79f14
> https://github.com/hansenji/ViewModelInject
> 
> Read above if you want some context on how this can be done.

Okay, thanks @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
@prayutsu this one https://github.com/hansenji/ViewModelInject is also one good implementation but we would be needing this thing of our own rather than using some third-party library.

**Comment by anandwana001** [comment]
@prayutsu General point:
1. Under the explanation, you can write something like `Fix #<PR_NUMBER>`. This will connect the PR and issue and whenever the PR gets merged and close the issue will close too. Also, if anyone opens that issue, this PR will be mentioned there as the solution.  
2. As this PR is a draft, under the explanation, you can mention what sort of points you are looking a reviewer to take a look at. Just like here, you want someone to check if you are following a right path or not, you can mention the same at PR description, this will help the person mentioned to know what action to perform.

**Comment by prayutsu** [comment]
> @prayutsu this one https://github.com/hansenji/ViewModelInject is also one good implementation but we would be needing this thing of our own rather than using some third-party library.

I'll check it out. Thanks

**Comment by prayutsu** [comment]
> @prayutsu General point:
> 
> 1. Under the explanation, you can write something like `Fix #<PR_NUMBER>`. This will connect the PR and issue and whenever the PR gets merged and close the issue will close too. Also, if anyone opens that issue, this PR will be mentioned there as the solution.
> 2. As this PR is a draft, under the explanation, you can mention what sort of points you are looking a reviewer to take a look at. Just like here, you want someone to check if you are following a right path or not, you can mention the same at PR description, this will help the person mentioned to know what action to perform.

Thank you @anandwana001 
I'll surely do this

**Comment by prayutsu** [comment]
@anandwana001 I have installed ktlint successfully but I am still facing issues with installing bufbuild. I first installed homebrew to install it but that didn't work.
Lemme attach SS for the same

**Comment by prayutsu** [comment]
> @anandwana001 I have installed ktlint successfully but I am still facing issues with installing bufbuild. I first installed homebrew to install it but that didn't work.
> Lemme attach SS for the same

Screenshot from 2020-08-27 17-21-09

**Comment by anandwana001** [comment]
You have to set up brew first.

**Comment by prayutsu** [comment]
@anandwana001 One more thing, I successfully installed homebrew but even after that when I typed brew command it didn't work

**Comment by prayutsu** [comment]
> You have to set up brew first.

Actuall, I installed homebrew via this command -
```/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"```

**Comment by anandwana001** [comment]
try checking the brew version if it is successfully installed or not
brew --version

**Comment by prayutsu** [comment]
> try checking the brew version if it is successfully installed or not
> brew --version

No, it's not, so let me install homebrew once more.

**Comment by prayutsu** [comment]
I see this warning - 
Screenshot from 2020-08-27 17-30-59

**Comment by anandwana001** [comment]
The warning says that brew is not in your bin folder means you will not be able to use brew as a command. 
Try checking version now

**Comment by prayutsu** [comment]
> The warning says that brew is not in your bin folder means you will not be able to use brew as a command.
> Try checking version now

```
Command 'brew' not found, did you mean:

  command 'brec' from deb bplay (0.991-10build1)
  command 'qbrew' from deb qbrew (0.4.1-8build1)

Try: sudo apt install <deb name>```

**Comment by anandwana001** [comment]
Yes, so basically you need to add the installed brew PATH to `.bash_profile `

`export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH" `

**Comment by prayutsu** [comment]
> export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

I am trying ctrl + x but unable to save and quit

> `export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH" `

Homebrew successfully installed. Thanks, @anandwana001 . Now I'll try to install bufbuild

**Comment by prayutsu** [comment]
@anandwana001 Thanks, bufbuild got installed too

**Review by rt4914 — CHANGES_REQUESTED** [review]
@prayutsu 

Actually we cannot rely on `SavedStateHandle` and also we might remove viewmodels in future.
There is an alternate strategy that team has come up with which is mentioned in this issue: https://github.com/oppia/oppia-android/issues/1737

I suggest to close this PR because #1737 will still take time. You can pick up other tasks which are not related to `landscape orientation change`.

**Comment by prayutsu** [comment]
> @prayutsu
> 
> Actually we cannot rely on `SavedStateHandle` and also we might remove viewmodels in future.
> There is an alternate strategy that team has come up with which is mentioned in this issue: #1737
> 
> I suggest to close this PR because #1737 will still take time. You can pick up other tasks which are not related to `landscape orientation change`.

Sure @rt4914 .

**Pull request closed without merging**
