### PR TITLE
Fix #2176: Added RTL Support for Profile List Screen (profile_view_profile_list.xml file)

### LINKED ISSUE #2176: [RTL] High-fi Profile List
`Profile List` needs RTL support as shown in below screen.
Profile List RTL

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by ForgottenProgramme**
## Explanation
Fixes #2176  
Added RTL support for Profile List Screen

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Screenshots: 

port_mob

land_mob

port_tab

land_tab

### CODE REVIEW

**Comment by ForgottenProgramme** [comment]
@rt4914 , Please have a look.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @ForgottenProgramme 
Defer to @rt4914 for further merge. 

Please follow the checklist
1. PR title
2. PR description
3. Branch naming - https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change, you can follow branch naming from your next pr's

**Comment by ForgottenProgramme** [comment]
> 3. Branch naming - https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change, you can follow branch naming from your next pr's

Thankyou, @anandwana001 ! :)

I have one doubt:
Do we create a new branch every time we make a new PR ?  

> Please follow the checklist
> 
> 1. PR title
> 2. PR description

And @anandwana001 , please tell me what should I change in my PR title and description?

**Comment by anandwana001** [comment]
> > 1. Branch naming - https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change, you can follow branch naming from your next pr's
> 
> Thankyou, @anandwana001 ! :)
> 
> I have one doubt:
> Do we create a new branch every time we make a new PR ?
> 
> > Please follow the checklist
> > 
> > 1. PR title
> > 2. PR description
> 
> And @anandwana001 , please tell me what should I change in my PR title and description?

1. Yes, we always need to create a new branch for every new pr, it's like a new work/new pr.
2. For pr title and description, please check the ##Checklist in the PR description first and the second point. I had unchecked those points.

**Comment by FareesHussain** [comment]
Creating a new branch is preferable,
you can even continue with the old branch but make sure it is not linked with any open PR and is up-to-date with `develop`

change the title to `Fix #2178: Added RTL....`
change Description to `Fixes #2178 ....`

**Comment by ForgottenProgramme** [comment]
> 1. Yes, we always need to create a new branch for every new pr, it's like a new work/new pr.
> 2. For pr title and description, please check the ##Checklist in the PR description first and the second point. I had unchecked those points.

@anandwana001 , thankyou. Got it.

**Comment by rt4914** [comment]
@ForgottenProgramme Update the PR title to this format:
`Fix #2176: Added RTL Support for Profile List Screen (profile_view_profile_list.xml file)`

**Review by rt4914 — APPROVED** [review]
LGTM, Will wait for merge until the PR title is updated.

**Comment by ForgottenProgramme** [comment]
> LGTM, Will wait for merge until the PR title is updated.

Done!

**Pull request merged**
