### PR TITLE
Fixes #3231: Updated margin in styles 

### LINKED ISSUE #3231: Button Margin Updates in Style
All `StateButtonActive` using buttons have issues now because of introduction of `layout_margin="4dp"` in its style. 

    

and many other places.

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #3231: Updated margin in styles 

Check the issue which display the button displacement.

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@anandwana001 You can merge this after approval.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Blocking from merging as there are test failing

**Review by anandwana001 — APPROVED** [review]
LGTM

**Pull request merged**
