### PR TITLE
Fix #3258 - Handling Removal of the CircularImageView dependency

### LINKED ISSUE #3258: Find a maintained replacement for CircularImageView
The codebase currently depends on 2 different CircularImageView dependencies. One of them, https://github.com/sparrow007/CircularImageview, is no longer maintained and should be replaced with a dependency that's kept up-to-date. This will allow us to remove our custom fork of the library (which was needed per #2923 to remove the codebase's dependency on jcenter).

### PR DESCRIPTION
**Pull request by Rd4dev**
## Explanation

Fixes #3258 

The Pull Request [#4155](https://github.com/oppia/oppia-android/pull/4155) substituted `CircularImageView` with `ShapeableImageView`, yet the dependency persists in the project. This PR addresses the final steps of removing the remaining dependency.

**`add_shadow`** and **`shadow_radius`** were exclusive to `CircularImageView`. Upon removing the dependencies, these attributes became irrelevant, so they were omitted from the layouts. Their removal had no impact on the functioning views as they were unrelated to the actual attributes of the working views.
[Attached reference images below]

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
Having add_shadow

### Todo
Remove Dependency from Bazel and External libraries.!

### CODE REVIEW

**Comment by Rd4dev** [comment]
@adhiamboperes PTAL

**Review by adhiamboperes — COMMENTED** [review]
Thanks @Rd4dev! 

Isn't there a declaration of this in `third_party/versions.bzl`?

**Comment by Rd4dev** [comment]
Hi @adhiamboperes, 

The [third_party/versions.bzl](https://github.com/oppia/oppia-android/blob/develop/third_party/versions.bzl) file appears to be missing the **`CircularImageView`** dependency.
It seems that PR #2659 might have overlooked the addition of `com.jackandphantom.android:circularimageview`.

Two dependencies were initially employed for circular images:
- **de.hdodenhof:circleimageview:3.0.1** 
  added initally via PR #326

- **com.jackandphantom.android:circularimageview:1.2.0** 
  added initially via PR #959
  Also to note: this dependency does exist in the [third_party/versions.bzl](https://github.com/oppia/oppia-android/pull/2663/files#diff-6174f43ed4a73deab28b0408a7cd51cee0917872920e564b86d51b05eb86b657R58) file

Both dependencies were eventually mixed in layouts, with `de.hdodenhof.circleimageview.CircleImageView` predominantly 
[ref. PR #4155].

Issue #3258 mentions replacing `com.jackandphantom.android:circularimageview`, but the [comment](https://github.com/oppia/oppia-android/issues/3258#issuecomment-853664087) suggests replacing `de.hdodenhof.circleimageview.CircleImageView` as well which was implemented in PR #4155.

_Seeking clarification_ on whether it is appropriate to proceed with the removal of `de.hdodenhof.circleimageview.CircleImageView`, given that none of the layouts appear to utilize this dependency.

**Comment by adhiamboperes** [comment]
@Rd4dev , please remove the dependency as it is unused.

**Comment by Rd4dev** [comment]
@adhiamboperes PTAL

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Rd4dev, this looks good, but please resolve the merge conflict and then reassign to me.

**Comment by Rd4dev** [comment]
@adhiamboperes PTAL

**Review by adhiamboperes — APPROVED** [review]
Thanks @Rd4dev!

**Review by BenHenning — APPROVED** [review]
This is a really nice clean-up, thanks for doing this @Rd4dev! LGTM.

**Comment by BenHenning** [comment]
Updating with latest & enabling auto-merge since everything seems to look good.

**Pull request merged**
