### PR TITLE
Fix #3855: removed the Pin View library from the build and gradle files

### LINKED ISSUE #3855: Remove Pinview thirdparty library.
Older implementation of Pin Verification UI was using PinView library `io_github_chaosleung_pinview`  which was not supporting RTL. To fix this we removed this library and created new UI as per the new mocks implemented in the PR #3684.

This library has to be removed from
```
BUILD.bazel
build.gradle
versions.bzl
```

Then update `maven_intall.json` file.

### PR DESCRIPTION
**Pull request by justdvnsh**
## Explanation
Removed the PIN VIEW library from 
build.bzel
build.gradle
versions.bzl

## Essential Checklist

- [x ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by veena14cs** [comment]
@justdvnsh please start your PR description with Fix #3855 as mentioned in the PR description check list `"Fix #bugnum: "`

**Comment by BenHenning** [comment]
@justdvnsh you'll need to make sure the app builds locally using both Bazel & Gradle (note that for Bazel you'll need to re-pin the Maven dependencies; see the failure when you try to build locally or CI results for instructions on how to repin).

**Comment by BenHenning** [comment]
@justdvnsh are you still working on this?

**Comment by justdvnsh** [comment]
@BenHenning Yes. Actually i am trying to install bazel locally.

**Comment by BenHenning** [comment]
Have you been following the wiki
https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions
instructions? Happy to help if you're running into any specific issues.

**Pull request closed without merging**
