### PR TITLE
Fix #3859: deleted-landscape-file-for-the-phone

### LINKED ISSUE #3589: Merge topic_summary_view.xml into single xml file
Currently there are 3 versions of `topic_summary_view.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

### PR DESCRIPTION
**Pull request by yash10019coder**
## Explanation

Fixes #3589 
deleted the landscape file for phone of topic_summary_view.xml
| Old SS | New SS | 
| ----------| ----------- | 
| old2 | sdlkfjaksdljflkadsjfkl |
| old | new |
| the SS in last are the portrait and they are long SS | 
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by yash10019coder** [comment]
@rt4914 PTAL

**Review by rt4914 — CHANGES_REQUESTED** [review]
This issue should make sure that the final UI contains only 1 single file. Any specific reason why there are still 3 files for this ?

**Comment by yash10019coder** [comment]
@rt4914 app was crashing if I deleted tablet XML

**Comment by rt4914** [comment]
> @rt4914 app was crashing if I deleted tablet XML files that's why

In that case try to find the reason for the crash. Also in general whenever you remove xml file for tablet, perform these steps:
1. Rebuild the project
2. Uninstall the app
3. Install again.

**Comment by yash10019coder** [comment]
> > @rt4914 app was crashing if I deleted tablet XML files that's why
> 
> In that case try to find the reason for the crash. Also in general whenever you remove xml file for tablet, perform these steps:
> 
> 1. Rebuild the project
> 2. Uninstall the app
> 3. Install again.

ok thanks

**Comment by yash10019coder** [comment]
Hi @rt4914 
image
`2021-10-24 00:36:36.267 7478-7478/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 7478
    java.lang.IllegalArgumentException: The tag for topic_summary_view is invalid. Received: layout-sw600dp-land/topic_summary_view_0
        at org.oppia.android.DataBinderMapperImpl.internalGetViewDataBinding2(DataBinderMapperImpl.java:2018)
        at org.oppia.android.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:2115)
        at androidx.databinding.MergedDataBinderMapper.getDataBinder(MergedDataBinderMapper.java:74)
        at androidx.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:130)
        at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1368)
        at org.oppia.android.databinding.TopicSummaryViewBinding.inflate(TopicSummaryViewBinding.java:76)
        at org.oppia.android.databinding.TopicSummaryViewBinding.inflate(TopicSummaryViewBinding.java:62)
        at org.oppia.android.app.home.HomeFragmentPresenter$createRecyclerViewAdapter$14.invoke(HomeFragmentPresenter.kt:136)
        at org.oppia.android.app.home.HomeFragmentPresenter$createRecyclerViewAdapter$14.invoke(HomeFragmentPresenter.kt:37)
        at org.oppia.android.app.recyclerview.BindableAdapter$MultiTypeBuilder$registerViewDataBinder$viewHolderFactory$1.invoke(BindableAdapter.kt:344)
        at org.oppia.android.app.recyclerview.BindableAdapter$MultiTypeBuilder$registerViewDataBinder$viewHolderFactory$1.invoke(BindableAdapter.kt:259)
        at org.oppia.android.app.recyclerview.BindableAdapter.onCreateViewHolder(BindableAdapter.kt:76)
        at org.oppia.android.app.recyclerview.BindableAdapter.onCreateViewHolder(BindableAdapter.kt:32)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)`

**Comment by yash10019coder** [comment]
I tried deleting the tablet landscape xml file but I get this error I think that it is needed without it app crashes on tablet I have deleted the mobile landscape file and it runs perfectly 
thanks

**Comment by yash10019coder** [comment]
@rt4914 please PTAL

**Review by rt4914 — CHANGES_REQUESTED** [review]
Please have a look at these files too and try to merge them with the `layout/topic_summary_view.xml` file.

Make sure you add before/after screenshot of tablet UI too.

https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout-sw600dp-port/topic_summary_view.xml

https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout-sw600dp-land/topic_summary_view.xml

**Comment by rt4914** [comment]
@yash10019coder For tablet follow these steps:
1. Make the changes.
2. Uninstall the app.
3. `Build` -> `Rebuild` the app.
4. Install the app.

**Comment by yash10019coder** [comment]
Hi @rt4914 I am really sorry to say but I have tried to merge them but it is not working It still gives the errors changes are very different so I don't think that layouts are further mergeable 
thanks

**Comment by veena14cs** [comment]
> Hi @rt4914 I am really sorry to say but I have tried to merge them but it is not working It still gives the errors changes are very different so I don't think that layouts are further mergeable thanks

@yash10019coder You can do Invalidate cache and restart android studio. I have faced similar issues when I delete any of the xml files. Try this out. There are some internal generated files for these xml and while building the app it tries to look for this file so it is better to clean and re-build always when you delete any of the files from android studio.

**Comment by yash10019coder** [comment]
Thanks for your help I will try it

**Comment by yash10019coder** [comment]
Hi @veena14cs @rt4914 it didn't worked out getting the same error

**Comment by rt4914** [comment]
@yash10019coder Can you please mention what exact steps you have tried? For me the steps that I mentioned above are working correctly.

**Pull request closed without merging**
