### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Comment by adhiamboperes** [comment]
Hi @seanlip, there are two portuguese strings that still need to be manually updated, could you PTAL?

Script check failure:
```
2 consistency error(s) were found for BRAZILIAN_PORTUGUESE strings (file: app/src/main/res/values-pt-rBR/strings.xml):
- string unsupported_app_version_dialog_message: original translation uses 1 line(s) but translation uses 3 line(s). Please remove any extra lines or add any that are missing.
- string unsupported_app_version_dialog_close_button_text: original translation uses 1 line(s) but translation uses 3 line(s). Please remove any extra lines or add any that are missing.
```

**Comment by seanlip** [comment]
@adhiamboperes I have updated both on Translatewiki. Please let me know if there are any more. Thanks!

**Comment by adhiamboperes** [comment]
> @adhiamboperes I have updated both on Translatewiki. Please let me know if there are any more. Thanks!

Thanks, Translatewiki has pushed the fixes. Everything looks good now.

**Review by adhiamboperes — APPROVED** [review]

**Comment by adhiamboperes** [comment]
@seanlip, could you please update the branch and merge? I do not have write authorization for this branch.

**Comment by seanlip** [comment]
@adhiamboperes done, thanks! Updated and set it to auto-merge.

**Pull request merged**
