### PR TITLE
Fix #3753: Fix some translatable/untranslatable strings

### LINKED ISSUE #3753: Ensure 'Oppia' is not translatable, and all other translatable strings are part of strings.xml

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fixes #3753.

This PR:
- Marks 'Oppia' as non-translatable (since it should never be translated) & moves it to a new 'untranslatable_strings.xml' file
- Replaces all occurrences of 'Oppia' in strings to instead be parameters whereby code injects the 'Oppia' app_name string
- Moves FAQ & greeting strings to strings.xml so that they can be translated (the latter of which required moving DateTimeUtil + test to the app module; Bazel modularization for the prod utility was retained)
- Two strings that were not being used were removed
- Tests were updated accordingly, and strings have been verified
- New regex checks + tests were added to ensure strings are placed in the correct places (i.e. all translatable strings must go in strings.xml, 'Oppia' should never should up in a translatable string, non-translatable strings cannot go in the primary strings.xml file)

In passing, this also updates the regex check script to allow filepath-based matching instead of just filename, and updates the test file output for errors to be more relative.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
No UI functionality was changed. See existing home screen + FAQ screens to demonstrate existing behavior has been retained:

image

image

image

### CODE REVIEW

**Comment by BenHenning** [comment]
@rt4914 & @vinitamurthi PTAL for codeowners. @seanlip PTAL for codeowners changes.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by BenHenning** [comment]
NB: I think #3756 will remove your need to review this PR @vinitamurthi. Just waiting to see.

**Review by seanlip — APPROVED** [review]
LGTM for codeowner file

**Comment by BenHenning** [comment]
Ah nice. Looks like your review isn't needed then @vinitamurthi.

Going to go ahead and wait for CI then merge this to unblock downstream localization work.

**Pull request merged**
