### PR TITLE
Fix #1882:Shifted NumericInput Rules test to numberinput subpackage

### LINKED ISSUE #1882: Shift NumericInput Rules test to separate sub-package
`NumericInputEqualsRuleClassifierProviderTest.kt`
`NumericInputIsLessThanRuleClassifierProviderTest.kt`
`NumericInputIsLessThanOrEqualToRuleClassifierProviderTest.kt`
`NumericInputIsInclusivelyBetweenRuleClassifierProviderTest.kt`
`NumericInputIsGreaterThanRuleClassifierProviderTest.kt`
`NumericInputIsGreaterThanOrEqualToRuleClassifierProviderTest.kt`

Shift all these to separate package named `numberinput` in https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

### PR DESCRIPTION
**Pull request by soamOne**
## Explanation

  Fix #1882: In this PR we are shifting numeric input rules tests to a new subpackage called numberinput.
 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
-   @@[x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.
@rt4914 @BenHenning

### CODE REVIEW

**Comment by soamOne** [comment]
@rt4914 @BenHenning PTAL

**Comment by Sarthak2601** [comment]
Hey @soamOne, please have a look at the domain tests. It seems like they are failing. Also, PTAL at [this](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR) guide for PR submissions.

**Comment by rt4914** [comment]
@soamOne Thanks for creating this PR.
Couple of points to take care of:
1. Update your `number-input-package` branch with latest develop. Currently this branch is behind develop.
2. In the `Description` of PR, please mention details like:
```
Fix #1882 

In this PR we are shifting the numeric input test files to a separate test folder.

```

**Comment by soamOne** [comment]
Hey @Sarthak2601 @rt4914 @BenHenning  PTAL now.

**Review by Sarthak2601 — APPROVED** [review]
LGTM. Thanks @soamOne !

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by soamOne** [comment]
Thanks

**Comment by BenHenning** [comment]
Thanks @soamOne.

These files ought to go under ``numericinput`` not ``numberinput`` for parity with the other package names & for consistency with the interaction name. Also, it looks like the Bazel files weren't updated which is causing a build breakage for Bazel tests. See: https://github.com/oppia/oppia-android/blob/74db288/domain/BUILD.bazel#L64.

**Comment by soamOne** [comment]
@BenHenning  I will look into it and fix it, thanks.

**Comment by BenHenning** [comment]
Also I just realized that the original package was never updated to match the new directory structure. This is actually a case where Gradle misbehaves: it (incorrectly) doesn't require directory structures to match their directory structures, but Bazel does. Given that the build isn't actually broken, I won't revert this PR, but we should prioritize fixing that since it can lead to confusion.

Thanks @soamOne!

**Comment by soamOne** [comment]
Okay, so what all needs to be done now @BenHenning ?

**Comment by BenHenning** [comment]
@soamOne see https://github.com/oppia/oppia-android/issues/1882#issuecomment-700411557. Does that help?

**Comment by soamOne** [comment]
Yes @BenHenning, got it.
Thanks!

**Comment by soamOne** [comment]
@BenHenning @rt4914 should I open a new pull request now?

**Comment by soamOne** [comment]
Hey @BenHenning, a couple of questions:
1. Can org/oppia/domain be deleted now?
2. Should I open a new pull request?

**Comment by rt4914** [comment]
@soamOne 
1. You just need to take latest pull from develop and checkout from that to create a new branch. That should fix the issue related to your first question once you shift the files.
2. Yes you can create a new PR.

**Comment by soamOne** [comment]
@rt4914 okay, got it.
Thanks!

**Pull request merged**
