### PR TITLE
Fixes #1206: OngoingTopicList - Tablet (Landscape) (Lowfi)

### LINKED ISSUE #1206: OngoingTopicList - Tablet (Landscape) (Lowfi)
Mocks: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/e2c05498-d42e-41ac-b159-09affda9fcff/L-Topics-in-Progress  

Implement low-fi UI for **OngoingTopicList** tablet landscape mode

**Target PR date**: 30 July 2020
**Target completion date**: 3 August 2020

### PR DESCRIPTION
**Pull request by MohamedMedhat1998**
## Explanation

- Fixes #1206 
- Implemented low-fi UI for **OngoingTopicList** for landscape mode - tablet
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
LGTM, we will need to write test cases for span count check. similar to `ProfileChooserSpanTest` for this file and all the rest of the earlier files too.

**Review by rt4914 — CHANGES_REQUESTED** [review]
LGTM, we will need to write test cases for span count check. similar to `ProfileChooserSpanTest` for this file and all the rest of the earlier files too.

**Comment by BenHenning** [comment]
@MohamedMedhat1998 please update this with the latest develop.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> @MohamedMedhat1998 please update this with the latest develop.

Done

**Comment by MohamedMedhat1998** [comment]
> LGTM, we will need to write test cases for span count check. similar to `ProfileChooserSpanTest` for this file and all the rest of the earlier files too.

Done in #1415

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
