### PR TITLE
Fixes part of #2616: Admin Auth Screen[a11y]

### PR DESCRIPTION
**Pull request by Arjupta**
## Explanation

Fixes part of #2616 ie. the TalkBack response for disabled submit button by using enabled property

|When disabled| When Enabled|
|:-:|:-:|
|WhatsApp Image 2021-02-08 at 3 57 21 PM|Screenshot_2021-02-07-13-21-09-71_943a62cb4c6fb83e010e1c2e82766a17|

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Arjupta** [comment]
@rt4914 and @FareesHussain can you find why tests are failing.

**Comment by FareesHussain** [comment]
Tests needs to be re-run as these test pass locally
image

image

**Review by rt4914 — CHANGES_REQUESTED** [review]
@ARJUPTA This solution is not correct.
Couple of points:
1. `SUBMIT, Button, disabled` is not same as `Disabled Submit, Button`. In first case the `disabled` is not typed anywhere it is called by Talkback automatically. Similar to the case where `Button` is not typed anywhere but the Talkback automatically outputs that.
2. To fix this revert these changes and simply introduce: `android:enabled="@{viewModel.isSubmitButtonActive}"` and test the app again on talkback.

**Comment by rt4914** [comment]
Also add `Fixes part of #bugnumber` in description too.

**Comment by rt4914** [comment]
> @rt4914 and @FareesHussain can you find why tests are failing.

There are couple of flaky tests nothing that your PR is related to so don't worry about this.

**Comment by Arjupta** [comment]
> @ARJUPTA This solution is not correct.
> Couple of points:
> 
> 1. `SUBMIT, Button, disabled` is not same as `Disabled Submit, Button`. In first case the `disabled` is not typed anywhere it is called by Talkback automatically. Similar to the case where `Button` is not typed anywhere but the Talkback automatically outputs that.
> 2. To fix this revert these changes and simply introduce: `android:enabled="@{viewModel.isSubmitButtonActive}"` and test the app again on talkback.

Okay! doing the changes

**Comment by Arjupta** [comment]
> Also add `Fixes part of #bugnumber` in description too.

Updated the screenshot too.

**Review by rt4914 — CHANGES_REQUESTED** [review]
LGTM, thanks

**Review by rt4914 — APPROVED** [review]
Meant to approve

**Comment by Arjupta** [comment]
@rt4914 this PR is not merged, github bug i guess

**Comment by rt4914** [comment]
@ARJUPTA Once you update the branch it will get merged

**Pull request merged**
