### PR TITLE
Fix #114: Implement answer classification controller

### LINKED ISSUE #114: Implement AnswerClassificationController
There needs to be a controller that can fulfill the rule specifications of a state for a given answer submitted by the user. This classification is only using non-ML classification options.

The frontend classification service should be used as a reference for modeling this.

### PR DESCRIPTION
**Pull request by BenHenning**
This introduces all of the necessary rule classification support for the prototype, including:
- Continue
- TextInput
- NumericInput
- NumberWithUnits
- MultipleChoiceInput
- ItemSelectionInput
- FractionInput

This does not include deep tests for any of these classifiers individually (and some may have bugs), but #210 is tracking adding more thorough tests. The AnswerClassificationController is being well tested, and ExplorationProgressController from the base branch runs through real explorations end-to-end which in turn verifies that some of the classifiers are working.

This PR introduces these classifiers in a generic way so that it's easy to add both additional interactions and rule types in the future. It also does generic answer classification in a type-safe way and such that the base logic for the classification is as simple as possible (e.g. verifying strings directly for TextInput rather than extracting the normalized string and verifying that both the input and answer have the correct type).

This also makes a few adjustments in various protos, and fixes a few small issues that were found in ExplorationProgressController.

### CODE REVIEW

**Comment by BenHenning** [comment]
Folks: I can split this up, but I'd rather not since it's slightly tricky to do in a way that doesn't cause ExplorationProgressControllerTest to fail. Most of the code is boilerplate, and I actually don't care about you verifying the correctness of the classifiers beyond "does this look like the JavaScript version". Once you skip past those + the Dagger modules, there's not much code left to verify (AnswerClassificationController & ExplorationProgressController + tests are the main chunks of new code).

**Comment by BenHenning** [comment]
NB: This will be rebased onto develop, so please review as if it's going into develop (because it will be).

**Review by rt4914 — APPROVED** [review]
LGTM

**Comment by BenHenning** [comment]
@vinitamurthi / @jamesxu0 if you get a chance, please review. It'd be good to get a few folks looking at this just due to the amount of stuff being added.

**Comment by BenHenning** [comment]
Given this is blocking downstream work, I'm going to check this in.

I'm pretty confident in it, but @vinitamurthi  & @jamesxu0 please do still take a look at this & let me know if you have any concerns. I'll follow up with a fix in a subsequent PR.

**Pull request merged**
