### PR TITLE
Fix TopicPlay

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Topic Play was failing at but somehow test cases were passing. @nikitamarysolomanpvt pointed this out.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is **assigned** to an appropriate reviewer.

### CODE REVIEW

**Comment by nikitamarysolomanpvt** [comment]
testTopicPlayFragment_loadFragmentWithTopicTestId0_clickChapter_opensExplorationActivity test case failing , please do remove unused comments in TopicPlayFragmentTest

**Comment by nikitamarysolomanpvt** [comment]
> testTopicPlayFragment_loadFragmentWithTopicTestId0_clickChapter_opensExplorationActivity test case failing (in landscape mode of mobile device)

Is working when changed settings of mobile device by turning off animations.
(Developer Options>Windows, animator,transition animation scale)

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Comment by rt4914** [comment]
> > testTopicPlayFragment_loadFragmentWithTopicTestId0_clickChapter_opensExplorationActivity test case failing (in landscape mode of mobile device)
> 
> Is working when changed settings of mobile device by turning off animations.
> (Developer Options>Windows, animator,transition animation scale)

Filed and issue for this because this is an issue associated with all recyclerview test cases:

https://github.com/oppia/oppia-android/issues/288

**Pull request merged**
