### PR TITLE
Fix part of #3775: RTL Exempted file fixes

### PR DESCRIPTION
**Pull request by viktoriias**
## Explanation

Fixes part of #3775: RTL Exempted file fixes.
- Change `app:barrierDirection="right"` to `app:barrierDirection="end"` in `topic_practice_subtopic.xml` files.
- Remove fixed/non-existing files from the exempt list.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by viktoriias** [comment]
|

**Comment by viktoriias** [comment]
|

**Comment by viktoriias** [comment]
@rt4914 @veena14cs Please review.

**Review by rt4914 — APPROVED** [review]
LGTM.

## Before vs After Screenshot for reference

**Review by BenHenning — APPROVED** [review]
Thanks @viktoriias! This looks great--glad to see the cleanup!

**Pull request merged**
