### PR TITLE
[RunAllTests] Fix #3510: Set up Android SDK hermetically in GitHub Actions to workaround #3024

### LINKED ISSUE #3510: Required Bazel build CI check now failing for everyone
See #3509 for initial context.

### PR DESCRIPTION
**Pull request by BenHenning**
Fix #3510
Fix part of #2692

## Explanation
This PR introduces sufficient CI arrangement to hermetically set up the Android SDK for all Bazel-related workflows. This fixes #3510 by mitigating #3024 by forcing workflows to use an older build tools instead of the latest that's included in the GitHub CI environment. While the hermeticity is nice, it introduces about an extra minute to each Bazel workflow. We may want to consider moving back to GitHub's automatically updating environment longer term once Bazel is sufficiently stable. I've noted this in #1861.

The new setup is being used for both Bazel app builds & tests. Technically, this isn't needed for tests since they don't require dexing, but keeping a consistent and hermetic environment seems ideal for all Bazel-related workflows. Note that we're intentionally **not** using the new workflow for the script runs since they don't require the Android SDK. That being said, this *does* result in a CI behavioral change for all related Bazel workflows: it's forcing using SDK 28 instead of 30 or newer.

Note that this also fixes part of #2692 by introducing our first shareable local action & by isolating the common Bazel setup code to it. Note that local actions can only contain shell commands and not reference other actions, so we'll be a bit limited in how much we can share.

Finally, this can be validated by seeing the passing CI checks (particularly, the passing build test). I've also run all the test workflows since they've been changed here, but they're expected to stay passing.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by BenHenning** [comment]
@seanlip PTAL for codeowners change.

I'm looking for someone from the Android team to perform a full review, as well.

**Comment by BenHenning** [comment]
@anandwana001 mentioned that he's available to review this--updating assignments.

**Comment by seanlip** [comment]
Sg, thanks. @anandwana001 please reassign me once you've reviewed!

**Comment by anandwana001** [comment]
Sure, waiting for CI to pass.

**Comment by BenHenning** [comment]
@anandwana001 CI is passing now--PTAL when you get a chance.

**Review by anandwana001 — APPROVED** [review]
As CI is passing, LGTM

**Comment by BenHenning** [comment]
Thanks!

**Review by seanlip — APPROVED** [review]

**Pull request merged**
