### PR TITLE
Fix #2280 : ADD rtl support for High-fi Admin Controls Profile Details

### LINKED ISSUE #2280: [RTL] High-fi Admin Controls Profile Details
` Admin Controls Profile Details` needs RTL support as shown in below screen.
AC EP (Chantel’s Profile) – RTL

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

https://github.com/oppia/oppia-android/wiki/RTL-Guidelines

### PR DESCRIPTION
**Pull request by etigoel**
## Explanation
Fix #2280 : Add rtl support for High-fi Admin Controls Profile Details.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@etigoel This looks good but before we merge this please add "Before" and "After" screenshot for this PR.

In practice, all PRs which works on UI related issues should include appropriate screenshots in PR description.

**Comment by etigoel** [comment]
Before Fix  :

image

After Fix :

image

**Comment by etigoel** [comment]
**BEFORE**
image


**AFTER**



image

**Comment by etigoel** [comment]
**Tablet Before :** 
image

**Tablet After**

image

**Comment by etigoel** [comment]
> @etigoel This looks good but before we merge this please add "Before" and "After" screenshot for this PR.
> 
> In practice, all PRs which works on UI related issues should include appropriate screenshots in PR description.

Ack.

**Comment by rt4914** [comment]
@etigoel Thanks a lot.
One suggestion, on your emulator there is a menu on the right side, in that menu you can click on `Camera` and it will automatically save the screenshot to Desktop.
Screenshot 2021-01-19 at 1 16 14 PM

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by etigoel** [comment]
Noted with thanks.

**Pull request merged**
