### PR TITLE
Fix #1042 Status bar color for pre-lollipop versions

### LINKED ISSUE #1042: Status bar color fix for pre-lollipop versions
Reference: https://stackoverflow.com/questions/22192291/how-to-change-the-status-bar-color-in-android/26215844#26215844

The status bar color in various android screens is inconsistent. Update status bar color code as per the mocks and spreadsheet:
https://docs.google.com/spreadsheets/d/1XphP6nWoUdOZn9pY2kdgfqMWfJjMfKMb98MXM5rp2HY/edit#gid=0
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/

Comment Reference: https://github.com/oppia/oppia-android/pull/1023#issuecomment-623466182

### PR DESCRIPTION
**Pull request by prathameshbhalekar**
## Explanation

 I have made change to the util.statusbarcolor file. I have also added a view in the xml files of the fragments that require to change status bar color. Also I have passed the view in the change status bar color function in the presenters of the above mentioned fragments. I inspected the code with android studio and the rest are the changes from that process.
  

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@prathameshbhalekar PTAL
Linters test are failing

**Comment by prathameshbhalekar** [comment]
what can I do to prevent that?

**Comment by prathameshbhalekar** [comment]
> @prathameshbhalekar PTAL
> Linters test are failing

I am getting error in flaky test in part of code in which I haven't made any changes

**Comment by Sarthak2601** [comment]
> > @prathameshbhalekar PTAL
> > Linters test are failing
> 
> I am getting error in flaky test in part of code in which I haven't made any changes

It's okay, the only condition is that the `required` tests must pass, which are passing in your case.  

Please follow this [guide](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR) for getting your PR reviewed and merged eventually. Also please modify the title of your PR according to the rules present in the checklist. 
It should be `Fix #1042 : Status bar color for pre-lollipop versions`

**Comment by prathameshbhalekar** [comment]
> > > @prathameshbhalekar PTAL
> > > Linters test are failing
> > 
> > 
> > I am getting error in flaky test in part of code in which I haven't made any changes
> 
> It's okay, the only condition is that the `required` tests must pass, which are passing in your case.
> 
> Please follow this [guide](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR) for getting your PR reviewed and merged eventually. Also please modify the title of your PR according to the rules present in the checklist.
> It should be `Fix #1042 : Status bar color for pre-lollipop versions`

I have changed the name. What should I do next in order to get my request reviewed?

**Comment by rt4914** [comment]
> > > > @prathameshbhalekar PTAL
> > > > Linters test are failing
> > > 
> > > 
> > > I am getting error in flaky test in part of code in which I haven't made any changes
> > 
> > 
> > It's okay, the only condition is that the `required` tests must pass, which are passing in your case.
> > Please follow this [guide](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR) for getting your PR reviewed and merged eventually. Also please modify the title of your PR according to the rules present in the checklist.
> > It should be `Fix #1042 : Status bar color for pre-lollipop versions`
> 
> I have changed the name. What should I do next in order to get my request reviewed?

I have assigned @nikitamarysolomanpvt for the PR review. But please add details to the PR description so that the reviewer can know what all things they have to check and why this PR has been created. You can check other ongoing PRs for sample.

Also, @nikitamarysolomanpvt Please guide the contributor as this is the first PR.

**Review by prathameshbhalekar — COMMENTED** [review]
I have made change to the util.statusbarcolor file. I have also added a view in the xml files of the fragments that require to change status bar color. Also I have passed the view in the change status bar color function in the presenters of the above mentioned fragments.  I inspected the code with android studio and the rest are the changes from that process.

**Comment by nikitamarysolomanpvt** [comment]
> I have made change to the util.statusbarcolor file. I have also added a view in the xml files of the fragments that require to change status bar color. Also I have passed the view in the change status bar color function in the presenters of the above mentioned fragments. I inspected the code with android studio and the rest are the changes from that process.

@prathameshbhalekar add description above check list. Please refer other PRs for the same.

**Review by nikitamarysolomanpvt — COMMENTED** [review]
Please name the branch as per wiki doc instructions and then assign me.

**Comment by prathameshbhalekar** [comment]
> Please name the branch as per wiki doc instructions and then assign me.

I'm really sorry to bother you repeatedly, but I'm not sure how to rename my branch.
[https://multiplestates.wordpress.com/2015/02/05/rename-a-local-and-remote-branch-in-git/](url)
Should I use this tutorial?

**Comment by rt4914** [comment]
> > Please name the branch as per wiki doc instructions and then assign me.
> 
> I'm really sorry to bother you repeatedly, but I'm not sure how to rename my branch.
> [https://multiplestates.wordpress.com/2015/02/05/rename-a-local-and-remote-branch-in-git/](url)
> Should I use this tutorial?

Actually that won't work correctly. I suggest better create a new PR from start so that it becomes easy and you can follow instructions mentioned here: https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

**Comment by nikitamarysolomanpvt** [comment]
> > Please name the branch as per wiki doc instructions and then assign me.
> 
> I'm really sorry to bother you repeatedly, but I'm not sure how to rename my branch.
> [https://multiplestates.wordpress.com/2015/02/05/rename-a-local-and-remote-branch-in-git/](url)
> Should I use this tutorial?

You cannot change the branch after creating PR so you need to rename your local branch/checkout current branch with different name and then create a PR.

**Comment by nikitamarysolomanpvt** [comment]
> > > Please name the branch as per wiki doc instructions and then assign me.
> > 
> > 
> > I'm really sorry to bother you repeatedly, but I'm not sure how to rename my branch.
> > [https://multiplestates.wordpress.com/2015/02/05/rename-a-local-and-remote-branch-in-git/](url)
> > Should I use this tutorial?
> 
> You cannot change the branch after creating PR so you need to rename your local branch/checkout current branch with different name and then create a PR.

You may refer the wiki mentioned above and also you may ping me if you face any issues with the same on nikitamarysolomanpvt@gmail.com

**Comment by rt4914** [comment]
@prathameshbhalekar Please close this PR with proper reason why it is closed.
For example in your case you can write:
`Closing this PR as it as been re-created at #1086 `

**Comment by rt4914** [comment]
Closing this PR as there has been no updates on this PR from contributor.

**Pull request closed without merging**
