### PR TITLE
Fix #2460: Remove textDirection property from add_profile_activity.

### LINKED ISSUE #2460: Optimise TextInputLayout in add_profile_activity
Remove `android:textDirection="locale"` in `TextInputLayout` from the following files
 - layout/add_profile_activity
 - layout-land/add_profile_activity
 - sw600dp/add_profile_activity
 - sw600dp-land/add_profile_activity

### PR DESCRIPTION
**Pull request by dipu989**
Fixes #2460: Remove textdirection property from textInputLayout of add_profile_activity
## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by dipu989** [comment]
@FareesHussain @rt4914 PTAL!

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks

**Comment by anandwana001** [comment]
@FareesHussain is it working correctly for RTL, as earlier we added this for RTL.

**Comment by BenHenning** [comment]
Sorry for the noise here. I actually shouldn't have codeowners over these files (& I'm in the process of fixing this in #2474) so assigning over to @rt4914 who will need to approve it, anyway.

**Comment by FareesHussain** [comment]
> @FareesHussain is it working correctly for RTL, as earlier we added this for RTL.

@anandwana001 This was recently added in `styles.xml` in https://github.com/oppia/oppia-android/pull/2315

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

Please change the title to `Fix #2460: Remove textDirection property from add_profile_activity`. 

Once this is done we can merge this PR.

@dipu989

**Comment by dipu989** [comment]
@rt4914 Done!

**Comment by rt4914** [comment]
@BenHenning Any specific reason why it is stuck on **Check CODEOWNERS & Repository files** ?

**Comment by BenHenning** [comment]
Same as https://github.com/oppia/oppia-android/pull/2469#issuecomment-761283047 @rt4914 & @dipu989.

**Comment by dipu989** [comment]
@BenHenning @rt4914 Done! Please check

**Pull request merged**
