### PR TITLE
Fix #2680: Remove-interaction-object-java-proto-lite

### LINKED ISSUE #2680: Remove :interaction_object_java_proto_lite from the model library
This task is part of the build system migration from Gradle to Bazel. A prerequesite before working on this issue is that you are able to build Oppia using Bazel. Check out [Oppia Bazel guide](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Guide) for Bazel terminology and more on what Bazel does.

## 1. Remove the export

In 

`/oppia-android/model/BUILD.bazel`

Remove :interaction_object_java_proto_lite from the list of exports in the model library

```BUILD
android_library(
    name = "model",
    visibility = ["//visibility:public"],
    exports = [
        ":event_logger_java_proto_lite",
        ":exploration_java_proto_lite",
        ":interaction_object_java_proto_lite",
        ":onboarding_java_proto_lite",
        ":profile_java_proto_lite",
        ":question_java_proto_lite",
        ":subtitled_html_java_proto_lite",
        ":subtitled_unicode_java_proto_lite",
        ":thumbnail_java_proto_lite",
        ":topic_java_proto_lite",
        ":translation_java_proto_lite",
        ":voiceover_java_proto_lite",
    ],
)
```

## 2. Add public visibility to the java_lite_proto_library

Add 

`    visibility = ["//visibility:public"],`

to the java_lite_proto_library that has the name interaction_object_java_proto_lite.

## 3. Build the app using Bazel

Libraries that are indirectly depending on `interaction_object_java_proto_lite` will now fail to build.  Try to build the app with Bazel and add the deps dependency

`//model:interaction_object_java_proto_lite,`

to all the libraries that are now failing to build. You will have to look around for BUILD.bazel files that have libraries that require this replaced dependency.

These libraries will already have the //model dependency and since we removed the :interaction_object_java_proto_lite from the model library itself, they will need to add the newly available public library directly as a dependency. (Not all libraries with the //model dependency may require the newly available library)

Once the app builds, you're done!

### PR DESCRIPTION
**Pull request by yashraj-01**
## Explanation

Fixes #2680 . Remove `:interaction_object_java_proto_lite` from the model library. Added `visibility = ["//visibility:public"],` to the `java_lite_proto_library` that has the name `interaction_object_java_proto_lite`. Also, added `//model:interaction_object_java_proto_lite,` to the app level `BUILD.bazel` which resulted in successful build.
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by yashraj-01** [comment]
@fsharpasharp PTAL.

**Comment by fsharpasharp** [comment]
Looks great. Let's see if we can fix those checks as well.

**Comment by anandwana001** [comment]
Please update the branch with the latest develop and check if all check passes.

**Comment by yashraj-01** [comment]
@BenHenning @vinitamurthi PTAL.

**Comment by yashraj-iitr** [comment]
@BenHenning I resolved the merge conflicts but it disabled auto merging. PTAL. Thanks.

**Comment by yashraj-iitr** [comment]
@BenHenning I resolved the merge conflicts but it disabled auto merging. PTAL. Thanks.

**Comment by yashraj-01** [comment]
@BenHenning I have resolved the merge conflicts. PTAL.

**Comment by yashraj-01** [comment]
@fsharpasharp is there anything else that needs to be done here? PTAL. 
Thanks.

**Comment by rt4914** [comment]
@BenHenning @vinitamurthi @fsharpasharp PTAL

**Review by BenHenning — APPROVED** [review]
Thanks @yashraj-iitr. This LGTM.

Note that when you want another review pass on your PR, please make sure to assign the PR to the team members that you want to take a look. For details, see: https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#tips-for-getting-your-pr-merged-after-submission.

**Comment by BenHenning** [comment]
Bazel failure is another example of #2844.

**Pull request merged**
