### PR TITLE
Fix #4166: Add e2e test for AddProfileActivity

### LINKED ISSUE #4166: Add e2e tests for AddProfileActivity
Add End-to-End tests for the AddProfileActivity using Bazel + UiAutomator.

Test case should include the flow of
- Opening AddProfileActivity.
- Create a set of profiles with different attributes (like with and without password, long name).

To pick this issue you need:
- [Bazel setup](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) 
- to be able to run a [E2E test](https://github.com/oppia/oppia-android/wiki/End-to-End-Testing-Guide#how-to-run-an-end-to-end-test)

References for writing E2E tests
- [End to End Testing Guide](https://github.com/oppia/oppia-android/wiki/End-to-End-Testing-Guide#how-to-run-an-end-to-end-test)
- [Android Instrumentation Tests, Bazel](https://docs.bazel.build/versions/5.0.0/android-instrumentation-test.html)

### PR DESCRIPTION
**Pull request by rishidyno**
Fix #4166

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by rishidyno** [comment]
@anandwana001 as I was trying to work on this issue AS intellisense was not working.  Like could you please tell me why is this happening  Also, if I created a new file in player directory it worked fine but when I created a new directory `profile` and added a new test file  then it did not work. I understand that we don't have any Gradle dependency in instrumental e2e testing, I think this might be the reason.

**Comment by anandwana001** [comment]
> @anandwana001 as I was trying to work on this issue AS intellisense was not working. Like could you please tell me why is this happening Also, if I created a new file in player directory it worked fine but when I created a new directory `profile` and added a new test file then it did not work. I understand that we don't have any Gradle dependency in instrumental e2e testing, I think this might be the reason.

@rishidyno Could you add some screenshots and explain what exactly is not working?
Also, could you add steps on where exactly and how you are adding the directory?

**Comment by rishidyno** [comment]
@anandwana001 In following SS you can see the difference in the two files, and if that's the case it becomes quite difficult to work.

But I think it does not work in `instrumentation` module as a whole because of its independency from Gradle. As I have to write test for AddProfileActivity, so I created a new directory `profile` can be seen in SS.

Also, If I try to reference an implementation of an Import of function declared in a different file using `ctrl+click` it does not work for any of the files in this module, meaning Intellisense is not working.

Please suggest some solutions on how to deal with it. Thanks!


image

**Comment by anandwana001** [comment]
@rishidyno I will take a look at this today.

**Review by anandwana001 — COMMENTED** [review]
@rishidyno 
The reason why Android studio is not giving any suggestions in this module as this module is built in such a way that it only supports Bazel stuff, not the Gradle part.
So, in order to write the test, you had to perform all the things manually and run the test using Bazel.

@FareesHussain Do you have any shortcuts/hack to write test easily here?

**Comment by FareesHussain** [comment]
@rishidyno
As @anandwana001 said. Modules `script` and `instrumentation` are not supported with suggestions and errors since they are purely built on bazel.

Only possible approach is to setup bazel plugin with the project (I wasn't able to build it so far, you can give it a try)
I suggest using it as it is.

In case you really want android-studio support you can try a seperate [project](https://github.com/android/testing-samples/tree/main/ui/uiautomator/BasicSample) which is on gradle. just to write the code for the tests. I don't recommend this.

**Comment by vinitamurthi** [comment]
Hi @rishidyno , any update here?

**Comment by FareesHussain** [comment]
Assigning @ayush0402 to help out with this PR

**Comment by rishidyno** [comment]
@vinitamurthi @FareesHussain sorry for the late reply, actually I was busy due to personal reasons and I recently shifted to fedora, so facing some bazel installation issues. I will update pr soon.

**Comment by rishidyno** [comment]
I will continue this pr after 20th April.

**Comment by BenHenning** [comment]
Hi. Since I was requested as a reviewer on this PR: Please note that I will be away & unavailable for reviews starting today until 23 May 2022. Please try to make any progress that you can which doesn't require me, and I'll catch up on my reviews when I return. Thanks for your flexibility--I really appreciate it.

**Pull request closed without merging**
