### PR TITLE
Rename FAQ Strings

### PR DESCRIPTION
**Pull request by adhiamboperes**
## Explanation
Renamed FAQ question and answer strings from index-based to more descriptive qualifiers.
The corresponding translations to the previous strings have been deleted.
The goal is to to overwrite existing faq strings and re-translate them, since a number of updates were made in #5246 and #5332. 

[device-2024-02-22-030542.webm](https://github.com/oppia/oppia-android/assets/59600948/be9a7cc8-89eb-4a1f-a02f-1466ffb0092f)

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by adhiamboperes** [comment]
Waiting for CI to pass but LGTM from self-review.

**Comment by adhiamboperes** [comment]
@BenHenning, PTAL.

**Review by BenHenning — APPROVED** [review]
Thanks @adhiamboperes! This LGTM.

**Comment by BenHenning** [comment]
NB: The translated strings are okay to delete since much of the content has changed/moved around, so we're just going to require a re-translation of all of them. This does mean that the next app release may distribute these strings in English.

@seanlip do you see any need for us to block on FAQ translations for release 0.13?

**Comment by seanlip** [comment]
> NB: The translated strings are okay to delete since much of the content has changed/moved around, so we're just going to require a re-translation of all of them. This does mean that the next app release may distribute these strings in English.
> 
> @seanlip do you see any need for us to block on FAQ translations for release 0.13?

Thanks -- I think no need to block since I suspect this is a low-frequency screen. However I would like to ask if we could keep the existing translations for content whose ID has been renamed but the content itself has not changed, to minimize unnecessary translation work?

**Comment by BenHenning** [comment]
> > NB: The translated strings are okay to delete since much of the content has changed/moved around, so we're just going to require a re-translation of all of them. This does mean that the next app release may distribute these strings in English.
> > @seanlip do you see any need for us to block on FAQ translations for release 0.13?
> 
> Thanks -- I think no need to block since I suspect this is a low-frequency screen. However I would like to ask if we could keep the existing translations for content whose ID has been renamed but the content itself has not changed, to minimize unnecessary translation work?

I do believe this requires us to edit the strings directly in TranslateWiki, doesn't it @seanlip? Whenever we directly check in translated strings they get overwritten by TranslateWiki (though I don't recall if we've ever tried this for new strings, so it may work for those).

Edit: Also, if there's a way we can communicate the old strings to translators that might be easier for us. I'm not familiar with all the changes that were done to the English strings, so it may be possible that some only require small translation adjustments.

**Comment by seanlip** [comment]
> I do believe this requires us to edit the strings directly in TranslateWiki, doesn't it @seanlip? Whenever we directly check in translated strings they get overwritten by TranslateWiki (though I don't recall if we've ever tried this for new strings, so it may work for those).

@BenHenning Honestly I don't know. I think I'd suggest just doing it and seeing what happens, but I'm also fine either way.

Not sure of any direct way to communicate the old strings to translators, sorry.

**Comment by BenHenning** [comment]
> > I do believe this requires us to edit the strings directly in TranslateWiki, doesn't it @seanlip? Whenever we directly check in translated strings they get overwritten by TranslateWiki (though I don't recall if we've ever tried this for new strings, so it may work for those).
> 
> @BenHenning Honestly I don't know. I think I'd suggest just doing it and seeing what happens, but I'm also fine either way.
> 
> Not sure of any direct way to communicate the old strings to translators, sorry.

@adhiamboperes WDYT about trying to manually copy in the translations based on:
- The mapping of old strings names to new strings names.
- The old English strings which didn't change (only these translations should be retained).

Do you think this could be done?

**Comment by adhiamboperes** [comment]
@BenHenning, I have brought back the translations. PTAL.

**Pull request merged**
