### PR TITLE
[RunAllTests] Fix #3837 tests end in "Test"

### LINKED ISSUE #3837: Make sure all tests end in "Test"
Currently, at least two tests aren't ending with "Test": ProfileProgressSpanCount & PlayerSplitScreenTesting. Both should be renamed such that they end in "Test", and all other files in test folders should be double checked to make sure that they end with "Test".

### PR DESCRIPTION
**Pull request by rishidyno**
Fix #3837
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by rishidyno** [comment]
@BenHenning all tests have passed PTAL.

**Review by anandwana001 — APPROVED** [review]
LGTM for code owner files.

**Comment by BenHenning** [comment]
The PR LGTM, but I needed to restart the CI process to force the new tests to run (given that #4035 is still not fixed). Will approve if CI passes.

**Review by BenHenning — APPROVED** [review]
Confirming both tests ran in CI & passed. Approving & merging. Thanks @rishidyno!

**Pull request merged**
