### PR TITLE
Fixes part of #2834: changed lambda function argument name in PromotedStoryListViewModelTest

### PR DESCRIPTION
**Pull request by Abhinavtdk**
## Explanation
Changed the argument names of lambda functions in PromotedStoryListViewModelTest from 'it' to something more descriptive.
Fixes part of #2834

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Abhinavtdk** [comment]
@rt4914 PTAL

**Comment by anandwana001** [comment]
@Abhinavtdk Could you please correct the first and second point from the checklist? 
Also, update the branch with the latest develop branch.

**Review by anandwana001 — APPROVED** [review]
Approving as Issue Author

**Comment by Abhinavtdk** [comment]
> @Abhinavtdk Could you please correct the first and second point from the checklist?
> Also, update the branch with the latest develop branch.

So, I'll have to make another pr with the updated develop branch or this is ok?

**Comment by anandwana001** [comment]
> > @Abhinavtdk Could you please correct the first and second point from the checklist?
> > Also, update the branch with the latest develop branch.
> 
> So, I'll have to make another pr with the updated develop branch or this is ok?

no, you can update here only using the git command. 
`git pull upstream develop` -> this will pull the latest codebase from the develop branch and merge it into your PR branch.
then push into this PR will make this pr in base with the latest develop branch. 

learning reference - https://git-scm.com/docs/git-pull

**Comment by Abhinavtdk** [comment]
> no, you can update here only using the git command.
> `git pull upstream develop` -> this will pull the latest codebase from the develop branch and merge it into your PR branch.
> then push into this PR will make this pr in base with the latest develop branch.
> 
> learning reference - https://git-scm.com/docs/git-pull

I did that, can you check now?

**Comment by anandwana001** [comment]
You haven't push it to the PR yet.

**Comment by anandwana001** [comment]
@Abhinavtdk please check the second point in the checklist. It says to add `Fixes #2834: some explanation` under the Explanation section in pr description.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
@Abhinavtdk Just add following to the PR description and mark the second point as checked.
`Fixes part of #2834 `

**Comment by Abhinavtdk** [comment]
> @Abhinavtdk Just add following to the PR description and mark the second point as checked.
> `Fixes part of #2834 `

Done

**Pull request merged**
