### PR TITLE
Fix #3240: Fixed Hi-Fi App Version Tablet 

### LINKED ISSUE #3240: Hi-Fi App Version Tablet
Mobile - https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/79e0846d-de5c-42b7-93aa-f93d4995616d/

Tablet - https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/80d1f4d6-be84-42db-ab23-9b5e1eb6e596/

**Follow this guide**: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by Pranav-Bobde**
## Explanation
Fixes #3240: Made few tweaks according to the mock for the tablet view for the 'App Version'.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@Pranav-Bobde Please merge with latest develop and also add before/after screenshots of the screen on which you have worked.

**Comment by Pranav-Bobde** [comment]
2 checks seems to be failing. Can you tell me how to redo the check? since
i guess in the past too just renunning the checks used to resolve the
problem.

**Comment by Pranav-Bobde** [comment]
@rt4914  I have added the screenshots, lemme know if any changes needed.

After merging with the latest develop, it seems hte 'layout-sw600dp/app_version_fragment.xml' has been deleted.
So, what to do here?

(Therefore in my recent commit or the files changed, it shows the whole app_version_fragment.xml been added.)

**Comment by rt4914** [comment]
@Pranav-Bobde I think in general the entire Highfi has been automatically fixed in latest develop. But there is still one issue which we can solve.

Screenshot_1630911740


In the above screenshot on right side you can notice that there is shadow below `App Version` and above `App Version 1.0`. This shadow should not be visible in splitmode/tabletmode. But if we remove it then in `mobile` view also it won't be visible below toolbar.


So to fix this do following things:
1. Cut `View` from `app_version_fragment.xml`. Now notice that there is only `ConstraintLayout` inside `FrameLayout` which means we can remove `FrameLayout` and keep only `ConstraintLayout`
2. Now copy that `View` to `app_version_activity` such that its visible below `AppBarLayout` but is always above `app_version_fragment_placeholder`.

**Pull request closed without merging**
