### PR TITLE
Fix #535: Material card corner white spacing[ON HOLD]

### LINKED ISSUE #535: material card corner white spacing.
At the corners of the card you would find white spacing on both top corners, and white card corner below the stroke corner borders of bottom rounded corners. https://github.com/oppia/oppia-android/pull/323#discussion_r344704934

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This Pr fixes issue mentioned in #535. White spacing around the corners.

### Mock
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/2cf61633-3197-4445-adb0-b58fbe418b11/TP-CL-Auto-Scroll-Button-

### Screenshot
Screenshot_20191231-135145

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
Before passing any PR please self review first. The indentation is incorrect and remove the commented code too.

**Comment by veena14cs** [comment]
> Before passing any PR please self review first. The indentation is incorrect and remove the commented code too.

Missed to do it. Corrected indentation.

**Review by rt4914 — APPROVED** [review]
LGTM

**Review by nikitamarysolomanpvt — COMMENTED** [review]
small
PTAL on Kitkat it looks like this (API 19 4.4.2)

**Comment by veena14cs** [comment]
> small
> 
> PTAL on Kitkat it looks like this (API 19 4.4.2)

Kitkat issue is getting tracked here in issue #530 and its related PR #537 and #536. This PR is fix for high-end device.

**Comment by nikitamarysolomanpvt** [comment]
> > small
> > PTAL on Kitkat it looks like this (API 19 4.4.2)
> 
> Kitkat issue is getting tracked here in issue #530 and its related PR #537 and #536. This PR is fix for high-end device.

This issue is already fixed in #537 & #536 considering all devices.... if this changes is not addressing all then, this major change in xml that need to be updated in several screen would be a trouble later on, as we are now focusing on kitkat also

**Comment by veena14cs** [comment]
> This issue is already fixed in #537 & #536 considering all devices.... if this changes is not addressing all then, this major change in xml that need to be updated in several screen would be a trouble later on, as we are now focusing on kitkat also

I will keep this on hold. Will not merge this until #537 or #536 PR is fixed to avoid this kind of conflict.

**Comment by veena14cs** [comment]
Closing this PR as it is fixed in #537 .

**Pull request closed without merging**
