### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Review by adhiamboperes — APPROVED** [review]
This PR marks FAQ related strings as fuzzy since we renamed some of them in https://github.com/oppia/oppia-android/pull/5247

**Comment by adhiamboperes** [comment]
@seanlip, @BenHenning, should I go ahead and merge this PR?

**Review by seanlip — COMMENTED** [review]
@adhiamboperes I think you can go ahead and delete the "fuzzy" mark either here or on translatewiki, but either way it should be fine to merge IMO (though for safety maybe just test the UI in Arabic to confirm that it works, i.e. the FUZZY thing doesn't hinder any rendering). Thanks!

**Comment by adhiamboperes** [comment]
> @adhiamboperes I think you can go ahead and delete the "fuzzy" mark either here or on translatewiki, but either way it should be fine to merge IMO (though for safety maybe just test the UI in Arabic to confirm that it works, i.e. the FUZZY thing doesn't hinder any rendering). Thanks!

The easiest approach will be to do a follow up PR to de-fuzzy the strings, since this branch is protected.

**Pull request merged**
