### PR TITLE
Fix #5075: Revert "Fix #5072 : Remove condition of hex color for drawables from regex"

### LINKED ISSUE #5072: [BUG]: CI Check for color usage in vectors will never pass until minSdk is updated
### Describe the bug

File Content Validation CI check that prohibits usages of colors other than component_colors in drawable files fails correctly on CI when violated, but the pattern that is being enforced cannot be supported by our current codebase, since we have not yet removed support for kitkat.

The CI error is:
```
app/src/main/res/drawable/rounded_primary_button_grey_shadow_color.xml:5: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/drawable/survey_nps_radio_selected_color.xml:4: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/drawable/survey_nps_radio_selected_color.xml:8: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/drawable/survey_nps_radio_unselected_color.xml:4: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/drawable/survey_nps_radio_unselected_color.xml:8: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/values/color_palette.xml:256: All color declarations in component_color.xml and color_palette.xml should end with _color suffix following snake_case naming convention.
```

Upon applying the recommended fix, the project build fails with error:
```
Cause 1: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
	...
Caused by: java.lang.RuntimeException: Error while processing /Users/adhiambooyier/opensource/oppia-android/app/src/main/res/drawable/survey_nps_radio_selected_color.xml : Can't process attribute android:fillColor="@color/component_color_survey_primary_button_background_color": references to other resources are not supported by build-time PNG generation.
File was preprocessed as vector drawable support was added in Android 5.0 (API level 21)
See http://developer.android.com/tools/help/vector-asset-studio.html for details.
.android.ide.common.resources.MergedResourceWriter$FileGenerationWorkAction.run(MergedResourceWriter.java:412)
	... 34 more
```

### Steps To Reproduce

In any vector file in res/drawable, replace a `<path>` tag `fillColor` attribute color hex (e.g. #ffffff) with a color resource (e.g. @color/component_color_shared_screen_secondary_background_color) and then rebuild the app.

### Expected Behavior

I expect the project to build without errors.

### Screenshots/Videos

Screenshot 2023-06-27 at 05 24 29

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

This  check was introduced in #4960

### LINKED ISSUE #5075: [Feature Request]: Add Regex Check That Prohibits ColorHex Usage in Drawables Post Kitkat
### Is your feature request related to a problem? Please describe.

File Content Validation CI check that prohibits usages of colors other than component_colors in drawable files fails correctly on CI when violated, but the pattern that is being enforced cannot be supported by our current codebase, since we have not yet removed support for kitkat.

### Describe the solution you'd like

Add regex check for drawables here in this particular [test](https://github.com/oppia/oppia-android/blob/1c1841b36084a561c955010a34d4175b8e7e72b9/scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt#L2349) to check colors only uses from component colors.

### Describe alternatives you've considered

_No response_

### Additional context

See #5072, #5076, and https://github.com/oppia/oppia-android/pull/5081#issuecomment-1664681991

### PR DESCRIPTION
**Pull request by adhiamboperes**
Fixes #5075 :Reverts oppia/oppia-android#5076

I took another look at the regex checks and noticed that they actually generally prohibit use of color hex in any drawables other than Vector files(which were the files that caused me to request this change in #4945), so the check is valid.([Sorry](https://www.desicomments.com/dc1/01/69662/696621.jpg)!)

### CODE REVIEW

**Comment by adhiamboperes** [comment]
Hi @rt4914, as per @MohitGupta121's comment, PTAL and let us know if this sufficiently addresses https://github.com/oppia/oppia-android/issues/5114.

**Review by seanlip — APPROVED** [review]
No concerns since this is a clean revert.

**Review by MohitGupta121 — APPROVED** [review]

**Comment by adhiamboperes** [comment]
The check (to be reintroduced by this revert) is failing because of the following files introduced in #4881:

```
app/src/main/res/drawable/rounded_primary_button_grey_shadow_color.xml:5: Only colors from component_colors.xml may be used in drawables except vector assets.
89app/src/main/res/drawable/survey_nps_radio_selected_color.xml:8: Only colors from component_colors.xml may be used in drawables except vector assets.
90app/src/main/res/drawable/survey_nps_radio_unselected_color.xml:8: Only colors from component_colors.xml may be used in drawables except vector assets.
91Refer to https://github.com/oppia/oppia-android/wiki/Static-Analysis-Checks#regexpatternvalidation-check for more details on how to fix this.
92Exception in thread "main" java.lang.Exception: REGEX PATTERN CHECKS FAILED
93
94	at org.oppia.android.scripts.regex.RegexPatternValidationCheckKt.main(RegexPatternValidationCheck.kt:64)
```

After replacing the highlighted lines with component_colors:

Screenshot 2023-08-04 at 00 32 54

The project fails to build with error:

```
Cause 1: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
	at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:336)
Caused by: java.lang.RuntimeException: Error while processing /Users/adhiambooyier/opensource/oppia-android/app/src/main/res/drawable/survey_nps_radio_unselected_color.xml : Can't process attribute android:fillColor="@color/component_color_shared_white_background_color": references to other resources are not supported by build-time PNG generation.
File was preprocessed as vector drawable support was added in Android 5.0 (API level 21)
See http://developer.android.com/tools/help/vector-asset-studio.html for details.
	at com.android.ide.common.resources.MergedResourceWriter$FileGenerationWorkAction.run(MergedResourceWriter.java:420)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:348)
```
 
Which is the original cause for the reversion in #5076.

Essentially, this issue is still not fixed, so I will hold off merging this PR. It appears that the CI check is actually not entirely correct, and should be modified in order to actually fix #5075 and #5114.

**Comment by adhiamboperes** [comment]
Closing in favor of #5123

**Pull request closed without merging**
