### PR TITLE
Fix #5136: Modifies all caps buttons to sentence case

### LINKED ISSUE #5136: [Feature Request]: Remove all-caps for all buttons on Android app and change to sentence case
### Is your feature request related to a problem? Please describe.

We are currently using all-caps for buttons (ex: CONTINUE, CANCEL) and the UX writing team, with the approval of the Android design team leads, would like to move forward with changing to sentence case (ex: Continue, Cancel, Ok, Submit, Close, Skip). **This is for all buttons on the app.** 
Please see the updated Android style guide: 

https://www.figma.com/file/G0jHrMaopFzk2ZksuynBjS/Android-style-guide?type=design&node-id=2-8412&mode=design&t=7wp6FDWE94kPhUVw-0

### Describe the solution you'd like

Changing all-caps buttons to sentence case for all buttons on the Android app. Thank you!

### Describe alternatives you've considered

_No response_

### Additional context

If there is confusion on a specific button, please reach out to @jlevick.

### PR DESCRIPTION
**Pull request by theMr17**
## Explanation

Fixes #5136

This PR changes all caps buttons to sentence case. All buttons mentioned in this [comment](https://github.com/oppia/oppia-android/issues/5136#issuecomment-1731446317) are changed either by directly changing its `android:textAllCaps` to `false` in the layout files or by changing its style in the `styles.xml` file.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### _layout_

|Screen / Dialog|Button ID|Screenshots|
|--|--|--|
|`activity_input_interaction_view_test.xml`|`submit_button`|
|`add_profile_activity.xml`|`add_profile_activity_create_button`|
|`admin_auth_activity.xml`|`admin_auth_submit_button`|
|`admin_pin_activity.xml`|`submit_button`|
|`concept_card_fragment_test_activity.xml`|`open_dialog_0` `open_dialog_1`|
|`exploration_test_activity.xml`|`play_exploration_button`|
|`hint_summary.xml`|`reveal_hint_button`|image|
|`math_expression_parser_fragment.xml`|`parse_math_expression_button`|image|
|`onboarding_slide_final.xml`|`get_started_button`|image|
|`profile_list_control_buttons.xml`|`learner_analytics_share_ids_and_events_button` `learner_analytics_upload_logs_now_button`|
|`profile_rename_fragment.xml`|`profile_rename_save_button`|image|
|`profile_reset_pin_fragment.xml`|`profile_reset_save_button`|
|`replay_button_item.xml`|`replay_button`|
|`return_to_lesson_button_item.xml`|`return_to_lesson_button`|image|
|`return_to_topic_button_item.xml`|`return_to_topic_button`|
|`solution_summary.xml`|`show_solution_button`|
|`state_fragment_test_activity.xml`|`play_test_exploration_button`|
|`submit_button_item.xml`|`submit_answer_button`|image|
|`topic_practice_footer_view.xml`|`topic_practice_start_button`|
|`walkthrough_welcome_fragment.xml`|`walkthrough_welcome_next_button`|

### _layout-land_
|Screen / Dialog|Button ID|Screenshots|
|--|--|--|
|`onboarding_slide_final.xml`|`get_started_button`|image|
|`walkthrough_welcome_fragment.xml`|`walkthrough_welcome_next_button`|

### _layout-sw600dp-land_
|Screen / Dialog|Button ID|
|--|--|
|`onboarding_slide_final.xml`|`get_started_button`|

### _layout-sw600dp-port_
|Screen / Dialog|Button ID|
|--|--|
|`onboarding_slide_final.xml`|`get_started_button`|

### CODE REVIEW

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @the-mr17!

- [ ] Could you please verify that all buttons are in sentense case? To do that, you need to add some screenshots to this PR. See this PR for example, and the linked PR also contains some sample dialogs that need to be edited too.
- [ ] Per ypur CI results, `testStateFragment_nextState_viewShowSolutionDialog_clickCancel_canViewShowSolution` is failing. Looks like the updated text case does not match the expected text in the test, so you need to update the test. See [wiki](https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results) for help inetpreting CI results. 
- [ ] Some buttons are hidden behind [platform parameters,](https://github.com/oppia/oppia-android/wiki/Platform-Parameters-&-Feature-Flags) and to make sure you don't miss any, please perform a blanket search for "button"(CTRL+SHIFT+F).

**Comment by theMr17** [comment]
> * [ ]  Could you please verify that all buttons are in sentense case? To do that, you need to add some screenshots to this PR. See this PR for example, and the linked PR also contains some sample dialogs that need to be edited too.

Thanks @adhiamboperes, I am looking into it. But, I cannot find the linked PR.

**Comment by adhiamboperes** [comment]
> > * [ ]   Could you please verify that all buttons are in sentense case? To do that, you need to add some screenshots to this PR. See this PR for example, and the linked PR also contains some sample dialogs that need to be edited too.
> 
> Thanks @adhiamboperes, I am looking into it. But, I cannot find the linked PR.

Sorry, please see : https://github.com/oppia/oppia-android/pull/4946

**Comment by theMr17** [comment]
> * [ ]  Could you please verify that all buttons are in sentense case? To do that, you need to add some screenshots to this PR. See this PR for example, and the linked PR also contains some sample dialogs that need to be edited too.

@adhiamboperes Do I need to edit those dialog buttons in PR #4946 ? (for eg, OK, CANCEL, etc.). According to the [figma](https://www.figma.com/file/G0jHrMaopFzk2ZksuynBjS/Android-style-guide?type=design&node-id=2-8412&mode=design&t=7wp6FDWE94kPhUVw-0) layouts those all dialog buttons are in all caps.

**Comment by adhiamboperes** [comment]
> the

@jlevick, could you please weigh in here?

**Comment by adhiamboperes** [comment]
> > * [ ]   Could you please verify that all buttons are in sentense case? To do that, you need to add some screenshots to this PR. See this PR for example, and the linked PR also contains some sample dialogs that need to be edited too.
> 
> @adhiamboperes Do I need to edit those dialog buttons in PR #4946 ? (for eg, OK, CANCEL, etc.). According to the [figma](https://www.figma.com/file/G0jHrMaopFzk2ZksuynBjS/Android-style-guide?type=design&node-id=2-8412&mode=design&t=7wp6FDWE94kPhUVw-0) layouts those all dialog buttons are in all caps.


@jlevick, could you please weigh in here?

**Comment by jlevick** [comment]
@adhiamboperes @the-mr17 these should not be in all-caps. They should be sentence case: Ok, Cancel, etc. 
I thought the design system was changed to reflect this but I see it has not been. I'll ask the Android designers to update it. Thank you for reaching out and confirming the changes!

**Comment by theMr17** [comment]
Hi @adhiamboperes, I have done the following changes, please have a look.

> * [ ]  Could you please verify that all buttons are in sentense case? To do that, you need to add some screenshots to this PR. See this PR for example, and the linked PR also contains some sample dialogs that need to be edited too.

I have changed the dialog buttons on PR #4946 to sentence case. I have also added some screenshots on the [PR message](https://github.com/oppia/oppia-android/pull/5157#issue-1909777641) above.

> * [ ]  Per ypur CI results, `testStateFragment_nextState_viewShowSolutionDialog_clickCancel_canViewShowSolution` is failing. Looks like the updated text case does not match the expected text in the test, so you need to update the test. See [wiki](https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results) for help inetpreting CI results.

I have updated the test to match the updated text case with the expected text case in the test.

> * [ ]  Some buttons are hidden behind [platform parameters,](https://github.com/oppia/oppia-android/wiki/Platform-Parameters-&-Feature-Flags) and to make sure you don't miss any, please perform a blanket search for "button"(CTRL+SHIFT+F).

I performed a blanket search for "button" but did not find anything that needs to be changed related to this.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
I have found from your screenshots that `profile_rename_save_button` is in all lowercase instead of sentence case.
The exit profile dialog(nav drawer -> switch profile) is still in all caps. So are the start over and continue lesson buttons in the resume lesson fragment. `audio_language_select_dialog_okay_button` is also still in all caps.
||||
|--|--|--|
|Screenshot_1695923309|Screenshot_1695923581|Screenshot_1695924139|

**Comment by theMr17** [comment]
@adhiamboperes  I have done the above mentioned changes. Here are screenshots for the same.

**Review by adhiamboperes — APPROVED** [review]
Thanks @the-mr17. LGTM.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
@the-mr17 could you please fix the failing tests? See https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results

**Review by adhiamboperes — APPROVED** [review]
Thanks @the-mr17.  This LGTM.

**Pull request merged**
