### PR TITLE
Fixes #3841 'time_ago' & quantity plurals should be combined

### LINKED ISSUE #3841: 'time_ago' & quantity plurals should be combined
After #3795, TextViewBindingAdapters combines two strings (time_ago & plurals) into a single one. This ought to just be different plural options so that translators have better context when translating the full conceptual string.

### PR DESCRIPTION
**Pull request by mbobiosio**
## Explanation

Fixes #3841
This PR includes changes done in kotlin for timeago events.
The approach is creating a function the receives the timestamp and current date for ease of testing and returns a string e.g just now, 5 days ago, 2 weeks ago, 6 months ago.
This is an implementation process review PR.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by BenHenning** [comment]
@mbobiosio since this PR is in draft, what do you specifically need me to look at?

**Comment by mbobiosio** [comment]
I changed the plurals approach [here](https://github.com/oppia/oppia-android/pull/4514/files#diff-d70b7b3d9cda1678b0be7b02d12f8eba29ade84596efa4a1f84decda14612656) and added a new plurals resource file [here](https://github.com/oppia/oppia-android/pull/4514/files#diff-adee133096bf45651f166754a927b9e30cefbfb704299a55ff9172be109671d5).

I'd like to know if this fits the idea.

**Comment by BenHenning** [comment]
Thanks for clarifying @mbobiosio! A meta-note: in the future, please assign me to PRs or issues that you need my feedback/review on (that's the primary signal that I use).

I was originally thinking that we could combine all of the cases into a single plural set, but that does run into some issues with trying to represent different levels of time granularity. I find the way you've approached the problem to be quite clear. I will have a few minor suggestions for the bit I looked at when this goes through full review, but I think your approach is sound and that you can finish up this PR draft and send it for review.

**Comment by mbobiosio** [comment]
Thank you for the feedback. I did leave an email yesterday about the issue.
Maybe I can jump on my suggestion to handle this right away?

**Pull request closed without merging**
