### PR TITLE
[draft] added jacoco coverage to oppia-android

### PR DESCRIPTION
**Pull request by MaskedCarrot**
## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
Please check these comments and let me know if need any help
https://github.com/oppia/oppia-android/pull/2466#issuecomment-764551110
https://github.com/oppia/oppia-android/pull/2466#issuecomment-768055765

**Comment by MaskedCarrot** [comment]
Screenshot from 2021-02-20 22-49-30 
Screenshot from 2021-02-20 22-31-43
Screenshot from 2021-02-20 22-30-35

I ran the coverage task from Gradle.
Jacco is showing 0% coverage even though 100% of the tests are passing. Can you guide me in the right direction to fix the error?

**Comment by anandwana001** [comment]
0% are the missed instructions and missed branches. Look for what percentage of lines are covered and try to open the particular file then you will see which line is covered and which line is not covered.

**Comment by MaskedCarrot** [comment]
generated a coverage report which shows 80% coverage for app package. 
Screenshot from 2021-02-23 19-48-02
@anandwana001 PTAL

**Comment by MaskedCarrot** [comment]
Jacoco is giving the following results 
package | coverage
--- | ---
app | 80%
domain | 0%
testing | 81%
data | 0%
utility | 0%

**Comment by anandwana001** [comment]
@MaskedCarrot is this code coverage for the Test package or the main codebase?
Currently, we need to have code coverage for a test package to understand are we covering all the test cases correctly or not. 

Also, an additional point if you could try out, After generating a report using Jacoco, try to upload them to [codecov](https://about.codecov.io/) and check the result.

**Comment by MaskedCarrot** [comment]
> @MaskedCarrot is this code coverage for the Test package or the main codebase?

@anandwana001  this code coverage is for the main codebase.
> Currently, we need to have code coverage for a test package to understand are we covering all the test cases correctly or not.

What I understand is that we have to create a package `testPackage` with some sample tests and see if jacoco report shows coverage or not.

**Comment by BenHenning** [comment]
Closing & reopening to restart now that codecov/codecov-action@v1 has been enabled for actions.

**Comment by MaskedCarrot** [comment]
@BenHenning just to inform you, this is not the main PR. Peculiar is assigned to this issue I am helping her with this. I talked to her about this and we both are facing the same issue(0 coverage in domain).

**Comment by BenHenning** [comment]
With the latest re-run I see ``org.gradle.execution.TaskSelectionException: Task 'testDebugUnitTestCoverage' not found in project ':app'.``. Is this using 0.7 or 0.8?

**Comment by BenHenning** [comment]
Thanks for clarifying @MaskedCarrot. Can we maybe close this issue, then, and consolidate on that PR so that there's a single source of truth?

**Comment by MaskedCarrot** [comment]
> With the latest re-run I see `org.gradle.execution.TaskSelectionException: Task 'testDebugUnitTestCoverage' not found in project ':app'.`. Is this using 0.7 or 0.8?

i also have another pr which I did not open in oppia-android. It ran the action to upload the report to [codecov](https://app.codecov.io/gh/MaskedCarrot/oppia-android). it has a different task name. I have updated the `jacoco_coverage.yml` It should work now.

**Comment by MaskedCarrot** [comment]
> Thanks for clarifying @MaskedCarrot. Can we maybe close this issue, then, and consolidate on that PR so that there's a single source of truth?

@BenHenning should I close it after the report is uploaded to codecov? Because peculiar has not setup the yml yet. 
Also, tests are failing in github action with the same error now.

**Comment by MaskedCarrot** [comment]
closing this issue. further work on this issue will continue in peculiar's PR

**Comment by peculiaruc** [comment]
> @BenHenning just to inform you, this is not the main PR. Peculiar is assigned to this issue I am helping her with this. I talked to her about this and we both are facing the same issue(0 coverage in domain). [here](https://github.com/oppia/oppia-android/pull/2730) is the link to peculiar's pr.

Please I don't understand the issue you are referring here @MaskedCarrot

**Comment by MaskedCarrot** [comment]
@peculiaruc as per our chats on gitter you said that 100 percent of the tests are passing for the domain module but you are getting 0 percent coverage. This is the issue I am referring here

**Comment by peculiaruc** [comment]
> closing this issue. further work on this issue will continue over [here](https://github.com/oppia/oppia-android/pull/2730)

@MaskedCarrot  please is it necessary to link this pr to the main pr? @BenHenning  mentioned we need a single source. He didn't ask you to link it up.  As I explained to you in the chat that a lot you are adding to my PR were getting me confused. Please could you remove this pr so that the review will find it easy to review the main pr. I think other help has to be on the main pr.

**Comment by peculiaruc** [comment]
> @peculiaruc as per our chats on gitter you said that 100 percent of the tests are passing for the domain module but you are getting 0 percent coverage. This is the issue I am referring here


As I was about getting clearification of your comments. It was a question which I resolved and asked you never mind

**Comment by MaskedCarrot** [comment]
@peculiaruc okay but I think a pr once referenced cannot be removed.

**Comment by MaskedCarrot** [comment]
> > @peculiaruc as per our chats on gitter you said that 100 percent of the tests are passing for the domain module but you are getting 0 percent coverage. This is the issue I am referring here
> 
> 
> As I was about getting clearification of your comments. It was a question which I resolved and asked you never mind

@peculiaruc can you tell me  how did you resolve this issue ?

**Comment by peculiaruc** [comment]
> @peculiaruc okay but I think a pr once referenced cannot be removed.

Is just to resolved the difference @BenHenning mentioned

**Comment by peculiaruc** [comment]
> > > @peculiaruc as per our chats on gitter you said that 100 percent of the tests are passing for the domain module but you are getting 0 percent coverage. This is the issue I am referring here
> > 
> > 
> > As I was about getting clearification of your comments. It was a question which I resolved and asked you never mind
> 
> @peculiaruc can you tell me how did you resolve this issue ?

The issue I mentioned here is for ./gradlew :domain:jacocoTestReport.

You told @BenHenning  you are helping but you keep asking me questions as the reviewers. I think you should be providing solutions not just asking me questions.

**Pull request closed without merging**
