### PR TITLE
Improve badges in README

### PR DESCRIPTION
**Pull request by BenHenning**
README badge updates:
1. Move them to their own line (I do think this looks better @anandwana001)
2. Add link to status checks for the status check badge (at the moment it awkwardly links to the badge itself unlike the other badges). Unfortunately, it seems that we can only link to the overall results page rather than the specific failure, but it seems fine the two should be relatively close in result.

### CODE REVIEW

**Review by anandwana001 — APPROVED** [review]
This looks clean now. Thanks @BenHenning 

Though I am adding a few suggestions

As Gitter's key colour 
[Gitter](https://gitter.im/oppia/oppia-android)

-----------
In future we can add Oppia complete logo or when we have a banner image, we can add that. 
<p>

</p>

-----------

The sequence will be good this way, keeping all badges together and twitter at last.  
[CI Lint and Tests](https://github.com/oppia/oppia-android/actions?query=workflow%3A%22CI+Lint+and+Tests%22+branch%3Adevelop) [Gitter](https://gitter.im/oppia/oppia-android) [Mailing List](mailto:oppia-android-dev@googlegroups.com) [GitHub issues by-label](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) [Twitter Follow](https://twitter.com/oppiaorg)

**Comment by BenHenning** [comment]
Ah, @anandwana001 where do you think the banner should go? The title should probably be 'Oppia Android'.

Also I'm not sure I understand the color comment--should we be using the color you suggested? They look close to me, so I wasn't sure.

**Comment by anandwana001** [comment]
> Ah, @anandwana001 where do you think the banner should go? The title should probably be 'Oppia Android'.
> 
> Also I'm not sure I understand the color comment--should we be using the color you suggested? They look close to me, so I wasn't sure.

A banner can go at the very top, currently, I don't think we have any banner available, but once in future we have we can add it. 

--------
<p>

</p>

# [Oppia Android](https://www.oppia.org)

--------

Currently, we have this 
 [Gitter](https://gitter.im/oppia/oppia-android?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

And I am thinking to go for this 
[Gitter](https://gitter.im/oppia/oppia-android)

**Comment by BenHenning** [comment]
Ah, I just realize what confused me about the color thing. That makes sense, thanks!

And got it re: the banner. I think it's a bit redundant to have Oppia in 2 places, but maybe we could put it farther down in the readme.

**Comment by BenHenning** [comment]
Going ahead and merging this once the checks pass. Thanks again @anandwana001!

**Pull request merged**
