### PR TITLE
Fix #2717: Resolve ktlint max line in DragAndDropItemFacilitator 

### LINKED ISSUE #2717: Resolve ktlint max line in DragAndDropItemFacilitator
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name.
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the line of code under 100 char length.

Where to start?
1. Complete all installation steps before starting with this issue - https://github.com/oppia/oppia-android/wiki#installation
2. 
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/main/java/org/oppia/android/app/recyclerview/DragAndDropItemFacilitator.kt#L12

Possible fix for this issue
```kotlin
class DragAndDropItemFacilitator(
  private val onItemDragListener: OnItemDragListener,
  private val onDragEndedListenr: OnDragEndedListener
) : ItemTouchHelper.SimpleCallback(
  ItemTouchHelper.UP or ItemTouchHelper.DOWN,
  /* swipeDirs= */ 0
) {
```

### PR DESCRIPTION
**Pull request by adit19shah**
## Explanation
Fixes: #2717 Resolved ktlint max line in DragAndDropItemFacilitator 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by adit19shah** [comment]
@anandwana001 PTAL.

**Review by anandwana001 — APPROVED** [review]
LGTM, waiting for checks to pass

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
@BenHenning and @anandwana001 Should we merge a PR if all `Required` tests have passed and all `Optional` tests are running ?

**Comment by anandwana001** [comment]
Merging as it looks all tests passed.

**Pull request merged**
