### PR TITLE
Fix #3574 solution summary xml merged

### LINKED ISSUE #3574: Merge solution_summary.xml into single xml file
Currently there are 4 versions of `solution_summary.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

### PR DESCRIPTION
**Pull request by MohitGupta121**
Fix Issue : #3574

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

Before mobile-portrait and Landscape:- 

image

image

After Mobile-Portrait and Landscape:-

image

image

Before Tab-Portrait and Landscape:-

image

image

After Tab-Portrait and Landscape:-

image

image

I'm use online emulator apkonline.net for testing Tablet layout. Because I try with android studio emulator but its too slow and very hang in my laptop that's why.

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@rt4914 bro can u please review my PR, if any changes required I'm ready for that.

**Comment by rt4914** [comment]
@bkaur-bkj Can you please review this PR first?

**Comment by bkaur-bkj** [comment]
> Issue : #3574
> 
> ## Essential Checklist
> * [ ]  The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
> * [ ]  Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
> * [ ]  The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
> * [ ]  The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
> * [ ]  The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
> * [ ]  The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).
> 
> Before mobile-portrait and Landscape:-
> 
> image
> 
> image
> 
> After Mobile-Portrait and Landscape:-
> 
> image
> 
> image
> 
> Before Tab-Portrait and Landscape:-
> 
> image
> 
> image
> 
> After Tab-Portrait and Landscape:-
> 
> image
> 
> image
> 
> I'm use online emulator apkonline.net for testing Tablet layout. Because I try with android studio emulator but its too slow and very hang in my laptop that's why.

@MohitGupta121 kindly complete the checklist and mark [x] at each point after you have acknowledged that part
also your PR has some merge conflicts due to some recent merged PR so update your branch  from develop and resolve them locally and then make a commit again

**Comment by bkaur-bkj** [comment]
> @bkaur-bkj Can you please review this PR first?

yes sir done

**Comment by bkaur-bkj** [comment]
@MohitGupta121 you need to commit changes only which are done by you not the idea/misc and other such files, pls revert back that changes

**Comment by MohitGupta121** [comment]
> @MohitGupta121 you need to commit changes only which are done by you not the idea/misc and other such files, pls revert back that changes

Okayy, I'll do that

**Comment by MohitGupta121** [comment]
> > Issue : #3574
> > ## Essential Checklist
> > 
> > * [ ]   The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
> > * [ ]   Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
> > * [ ]   The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
> > * [ ]   The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
> > * [ ]   The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
> > * [ ]   The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).
> > 
> > Before mobile-portrait and Landscape:-
> > image
> > image
> > After Mobile-Portrait and Landscape:-
> > image
> > image
> > Before Tab-Portrait and Landscape:-
> > image
> > image
> > After Tab-Portrait and Landscape:-
> > image
> > image
> > I'm use online emulator apkonline.net for testing Tablet layout. Because I try with android studio emulator but its too slow and very hang in my laptop that's why.
> 
> @MohitGupta121 kindly complete the checklist and mark [x] at each point after you have acknowledged that part also your PR has some merge conflicts due to some recent merged PR so update your branch from develop and resolve them locally and then make a commit again

@bkaur-bkj okay I try to resolve the commit but don't know why my local repo not update.
I'll try it again.

**Comment by MohitGupta121** [comment]
@rt4914 @bkaur-bkj sorry accidentally I click on unassign can you please reassign me.

**Comment by bkaur-bkj** [comment]
> @rt4914 @bkaur-bkj sorry accidentally I click on unassign can you please reassign me.

done

**Comment by MohitGupta121** [comment]
> > @rt4914 @bkaur-bkj sorry accidentally I click on unassign can you please reassign me.
> 
> done

Yes, thanks

**Comment by MohitGupta121** [comment]
> @MohitGupta121 you need to commit changes only which are done by you not the idea/misc and other such files, pls revert back that changes

@bkaur-bkj or @rt4914  Can you please review it, I resolved all the conflict and commit only my files changes.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks. Great work.

**Comment by MohitGupta121** [comment]
@rt4914 Thanks You.
Now can I pick next Issue?

**Comment by bkaur-bkj** [comment]
> @rt4914 Thanks You. Now can I pick next Issue?

Yes by the time the PR gets approved and merged u can request to work on other issue

**Pull request merged**
