### PR TITLE
Add codeowners to translation strings files.

### PR DESCRIPTION
**Pull request by seanlip**
## Explanation
Adding @adhiamboperes and me to codeowners so that we can help with translation string file approvals (like #4969).

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by seanlip** [comment]
@BenHenning this is just a suggestion -- see if you like it. If not, totally fine to close this PR. Thanks!

**Comment by BenHenning** [comment]
I usually don't have much issue with reviewing the PRs (they're not very common); the bigger issue is that auto-assignment doesn't seem to be working with them.

My only concern with expanding the existing codeowners for localization is making sure reviewers know what to look for since we've had past strings break due to having incorrect format specifiers and some HTML formatting problems (though Translatewiki mostly covers those problems). We still need much more robust checks for strings--these haven't been implemented yet.

I'm fine with expanding codeowners here so long as you both are fine with bringing a translation PR to my attention if it even seems like it might have issues when it comes to markup or format specifiers @seanlip @adhiamboperes. Would that be fine?

**Comment by seanlip** [comment]
Yeah, that's fine with me, thanks @BenHenning.  I didn't realize we lacked validation here, it has actually broken Web in the past. Do we have an issue tracking this?

**Comment by adhiamboperes** [comment]
> I usually don't have much issue with reviewing the PRs (they're not very common); the bigger issue is that auto-assignment doesn't seem to be working with them.
> 
> My only concern with expanding the existing codeowners for localization is making sure reviewers know what to look for since we've had past strings break due to having incorrect format specifiers and some HTML formatting problems (though Translatewiki mostly covers those problems). We still need much more robust checks for strings--these haven't been implemented yet.
> 
> I'm fine with expanding codeowners here so long as you both are fine with bringing a translation PR to my attention if it even seems like it might have issues when it comes to markup or format specifiers @seanlip @adhiamboperes. Would that be fine?

Yes, this is fine.

**Comment by BenHenning** [comment]
> Yeah, that's fine with me, thanks @BenHenning. I didn't realize we lacked validation here, it has actually broken Web in the past. Do we have an issue tracking this?

Yep: #4562. I haven't filled in the details of it yet, I have a TDD with the high-level details that need to be distilled into that issue.

**Review by BenHenning — APPROVED** [review]
Thanks @seanlip and @adhiamboperes for confirming. Approving & enabling auto-merge.

**Pull request merged**
