### PR TITLE
Review: Navigation drawer approach1 custom fragment drawer

### PR DESCRIPTION
**Pull request by nikitamarysolomanpvt**
Navigation Drawer With Fragments And Material Design Sample Code:Custom drawer with RecyclerView items in drawer ,DrawerFragment ,fragment transaction in container activity and drawer in fragment sample code https://github.com/nikitamarysolomanpvt/navigation/blob/master/KotlinDrawerBasic/app/src/main/java/com/example/parsaniahardik/kotlindrawerbasic/MainActivity.kt
Sample code branch for different approaches for study and comparing different approaches .

### CODE REVIEW

**Comment by nikitamarysolomanpvt** [comment]
Screenshot 2019-09-03 at 4 15 42 PM

@BenHenning and @seanlip Iam not able to add Reviewers,Assignees,Labels etc

**Comment by seanlip** [comment]
Hi @nikitamarysolomanpvt, I think you need to accept the invitation on https://github.com/oppia. Can you do that and try again, please? Thanks!

**Comment by BenHenning** [comment]
@nikitamarysolomanpvt can you please merge in develop & resolve the conflicts?

**Comment by BenHenning** [comment]
Per offline discussion, this is actually just a sample spun out from #84 and the expected changes were moved to that PR. This should not be merged into develop.

**Pull request closed without merging**
