### PR TITLE
Fix #4509: Text-based interaction EditText hints sometimes disappear when the keyboard is closed

### LINKED ISSUE #4509: Text-based interaction EditText hints sometimes disappear when the keyboard is closed
**Describe the bug**
As part of fixing #4446 in #4506, I found that some text-based interaction EditTexts will continue to show their hint text upon closing the keyboard, but others won't.

**To Reproduce**
1. Open the prototype exploration.
2. Play to the numeric input interaction, open the keyboard, then close it. Notice that the hint text is still showing.
3. Play to the text input interaction and repeat the same steps. Notice that the hint text is no longer showing.

**Expected behavior**
All text-based interactions should re-show their hint text once the software keyboard is hidden. This is how they're implemented, but for some reason they do not have consistent behaviors. It seems like numeric input may be the only interaction that behaves correctly, but I'm not certain on this. Potentially affected interaction types:
- Numeric input
- Text input
- Fraction input
- Ratio input
- Math expression input

**Demonstration**
Excluded for time--please follow up if this is needed.

**Environment**
- Device/emulator being used: Device (Nexus 5X)
- Android or SDK version (e.g. Android 5 or SDK 21): SDK 27
- App version (you can get this through system app settings or via the admin controls menu in-app): Latest version of the app built with acc674d1c38b25f50dfb90ae849adc6b8f3bb0f1.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by JishnuGoyal**
## Explanation

This PR fixes #4509. This PR aims to introduce code that ensures that the hint doesn't disappear for custom input layouts upon focus change events such as keyboard open/close. This is a part of the GSoC project: Interactive Onboarding Flow.

Upon attaching a debugger to the process I was able to investigate that the variable which was responsible to hold the hint information was not being initialized at the right time which was leading to this problem. 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

Before:

https://user-images.githubusercontent.com/64526117/189248321-7795052d-1003-46bc-87cb-c402cf154c6b.mp4

After:

https://user-images.githubusercontent.com/64526117/189248333-efda8791-5b2a-4a82-a8f3-38774427e73c.mp4

### CODE REVIEW

**Comment by JishnuGoyal** [comment]
@BenHenning PTAL, thanks!

**Comment by JishnuGoyal** [comment]
@rt4914 PTAL for codeowners, thanks!

**Comment by BenHenning** [comment]
Hmm this is interesting. @JishnuGoyal do you have an explanation for why the issue existed for some of the text input interactions and not others? I don't actually think #4446 actually introduced this so far as I can tell as it seems like an existing issue.

I think you also should be adding a before/after video (or videos based on whatever works best) showing the broken and now-fixed behavior for each interaction (including ones that were already fixed--it'd be good to see that it still works for them).

Beyond that, I think we also want to add tests for these changes since the difference in code is very subtle, but some thought is going to be needed to figure out _how_ to test this change. Do you have thoughts on how to approach this?

**Comment by JishnuGoyal** [comment]
> Hmm this is interesting. @JishnuGoyal do you have an explanation for why the issue existed for some of the text input interactions and not others? I don't actually think #4446 actually introduced this so far as I can tell as it seems like an existing issue.
> 
> I think you also should be adding a before/after video (or videos based on whatever works best) showing the broken and now-fixed behavior for each interaction (including ones that were already fixed--it'd be good to see that it still works for them).
> 
> Beyond that, I think we also want to add tests for these changes since the difference in code is very subtle, but some thought is going to be needed to figure out _how_ to test this change. Do you have thoughts on how to approach this?

Ah, I have updated the description for the PR, thanks. I haven't myself checked while investigating if all of the custom inputs failed to show hints-- I checked how the fractionInput had problem. The same coding pattern that caused the problem in fractions was used in the other inputs as well, so I fixed those.

I'll be adding the videos for before and after. Where should the tests be added though? @BenHenning

**Comment by BenHenning** [comment]
@JishnuGoyal InputInteractionViewTestActivityTest and MathExpressionInteractionsViewTest would probably be the best places for those tests to be added.

**Comment by JishnuGoyal** [comment]
@BenHenning PTAL

**Review by BenHenning — APPROVED** [review]
Thanks @JishnuGoyal! I'm happy with this, per our discussion that these changes are actually probably not possible to add automated tests for, and that #4574 is tracking adding tests once feasible. I'm also glad to see how elegant and simple the solution ended up being.

**Comment by BenHenning** [comment]
This is actually a change that would be nice to pull into beta, so I'm going to go ahead and force-merge it (#4556 is tracking ensuring this gets reviewed by @rt4914 at a later date).

**Pull request merged**
