### PR TITLE
Fix #3905: A11y flow fix for ProfileProgressHeader

### LINKED ISSUE #3905: [A11Y] ProfileProgressActivity flow needs to be improved
ProfileProgressActivity flow needs to be improved. Current Flow:

https://user-images.githubusercontent.com/9396084/136251830-0aca50df-e32b-42b7-883b-c9fa686fb1f8.mp4

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fix #3905: A11y flow fix for ProfileProgressHeader

Earlier the flow for profile progress was really bad. This PR tries to improve that experience.

## Issue
https://user-images.githubusercontent.com/9396084/136251830-0aca50df-e32b-42b7-883b-c9fa686fb1f8.mp4

## New Flow
https://user-images.githubusercontent.com/9396084/137373440-12b01dc0-fa70-4e21-a0e8-200ee674bccd.mp4

## Espresso Tests are passing

Screenshot 2021-10-21 at 4 01 58 PM
Screenshot 2021-10-21 at 4 04 43 PM
Screenshot 2021-10-21 at 4 05 27 PM

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by BenHenning** [comment]
Hi @rt4914. Apologies, will need to look at this tomorrow.

**Comment by BenHenning** [comment]
Sorry, I'll need to review this on Monday.

**Review by BenHenning — COMMENTED** [review]
Thanks @rt4914! This seems sensible--is there any way to add tests for the changes, though? Also, any idea on the test failure; is it related to this PR?

**Comment by rt4914** [comment]
> Thanks @rt4914! This seems sensible--is there any way to add tests for the changes, though? Also, any idea on the test failure; is it related to this PR?

@BenHenning I have tried adding test cases and I am unable to think of any other ways we can test it but at least this strategy makes sure if something changes the test case fails.

All tests are passing now.

**Review by BenHenning — APPROVED** [review]
Thanks @rt4914. I think the new tests are a bit change-detectory, but they're probably the best we can do since there isn't a way to simulate a11y flows in Robolectric so far as I know. This will for sure ensure that we don't regress the actual fix, but won't necessarily prevent other failures occurring in the future. We'll need to rely on manual testing for those.

**Comment by BenHenning** [comment]
Merging since everything seems addressed now. Thanks @rt4914!

**Pull request merged**
