### PR TITLE
Fix issue with resume buttons not scaling as expected

### LINKED ISSUE #4710: Improve support for scaling in resume lesson screen
**Describe the bug**
When we increase the font size to very large and open resume lesson screen the button's won't scaled properly. 

**To Reproduce**
1. Increase font size to very large (largest)
2. Open resume lesson's screen

**Expected behavior**
Buttons in resume lesson screen should scale properly when we have maximum font size. 

**Demonstration**
image

**Environment**
- Device/emulator being used: Nexus 5X
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

### PR DESCRIPTION
**Pull request by KevinGitonga**
## Explanation
Fixes #4710 and #3833. The second issue was closed as it is possibly a duplicate of #4710

Updating width on both the buttons width 0dp actually gives them equal width enabling the button text and child drawables to scale as expected on max display and font config. Main issue is that the currently used width "144dp" doesn't work when the device's display and font config is set to max. This update works better and is per @adhiamboperes comments on previous PR submitted, The previous fix involved using a LinearLayout which had other caveats.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

## Before and after screenshots demo
Nexus 5x API 29
| Before Portrait            |  After Portrait |
:-------------------------:|:-------------------------:
 | 

Google Pixel 3xl
| Before Portrait            |  After Portrait |
:-------------------------:|:-------------------------:
 |

### CODE REVIEW

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @KevinGitonga.

Two things:
1. Does this actually fix #4362? It seems that issue is tied to also scaling the "resume lesson" screen and isn't particularly tied to the buttons.
2. Won't this '0dp' fix only work if the button is used in a constraint layout (since 0dp means 'match constraint')? I'm concerned with defaulting it at such a high level in styles since other uses of the button (both now and in the future) could lead to the button not displaying at all. Similarly, we need to make sure the min size of buttons is always at least 48dp per accessibility requirements, so you may need to add a ``minWidth`` to the styles as well.

**Comment by KevinGitonga** [comment]
> Thanks @KevinGitonga.
> 
> Two things:
> 
> 1. Does this actually fix #4362? It seems that issue is tied to also scaling the "resume lesson" screen and isn't particularly tied to the buttons.
> 2. Won't this '0dp' fix only work if the button is used in a constraint layout (since 0dp means 'match constraint')? I'm concerned with defaulting it at such a high level in styles since other uses of the button (both now and in the future) could lead to the button not displaying at all. Similarly, we need to make sure the min size of buttons is always at least 48dp per accessibility requirements, so you may need to add a `minWidth` to the styles as well.

Thanks @BenHenning they seem related basing on the screenshots on the PR will double check on the revision tab which is mentioned on issue #4362 and provide update on this.

**Comment by KevinGitonga** [comment]
> Thanks @KevinGitonga.
> 
> Two things:
> 
> 1. Does this actually fix #4362? It seems that issue is tied to also scaling the "resume lesson" screen and isn't particularly tied to the buttons.
> 2. Won't this '0dp' fix only work if the button is used in a constraint layout (since 0dp means 'match constraint')? I'm concerned with defaulting it at such a high level in styles since other uses of the button (both now and in the future) could lead to the button not displaying at all. Similarly, we need to make sure the min size of buttons is always at least 48dp per accessibility requirements, so you may need to add a `minWidth` to the styles as well.

Hey @BenHenning 
RE 1. they are not related so i have removed reference to #4362 from this fix as the other is related to local inapp changes in text size not working although the image demonstration convey's a different message that shows relation to #4710.
RE 2. The buttons already have a minimum width set per this file https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/values/styles.xml. The buttons are also currently referenced only from constraintlayout.

**Comment by BenHenning** [comment]
I'm not sure that fully addresses point (2) actually. Defaulting to using constraint layout is problematic since it won't be clear to users of this style in the future that the button must be in a constraint layout, leading to a potentially brittle style.

It also occurs to me that the current style very much wants the button to be the size it's set to (as the minimum is set to the same size). Perhaps we should be considering alternatives to resizing such as wrapping the buttons. Per https://m2.material.io/components/buttons#anatomy button text shouldn't ever wrap in Material design as it can hurt text legibility, so wrapping would probably be more in-line with Material as well.

**Pull request closed without merging**
