### PR TITLE
Fix #1813 : Highfi of Profile Picture Selection Dialog is not correct

### LINKED ISSUE #1813: Highfi of Profile Picture Selection Dialog is not correct
The Highfi of Profile Picture Dialog looks like this:
profile_picture_eror

Instead it should like this: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/7fcddeef-4d62-4565-b763-81e89f064a5d/

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation

Fixes #1813 
High-fi of edit Picture Dialog is fixed to have texts with proper alignments

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Device Tested - Redmi K20 Pro

Screenshot_2020-09-09-20-30-19-487_org oppia app

Nexus 10 tablet

Screenshot_1599663655

Pixel 3 - 

Screenshot_1599663819

Pixel 3a -

Screenshot_1599664120

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
This is incorrect because this leads to too much gap between the upper and lower option.

The gap between first option and second option should be `24dp` but your changes makes it `48dp`.

Suggestion:
Option:1
 - marginStart = 24dp
 - marginEnd = 24dp
 - paddingTop = 20dp  (*)
 - paddingBottom = 12dp

Option 2:
- marginStart = 24dp
 - marginEnd = 24dp
 - paddingTop = 12dp
 - paddingBottom = 24dp (*)

(*) -> You might need to do trial-and-error to have to best UI, these values might be incorrect.

Also, test this across various devices.

**Comment by prayutsu** [comment]
> This is incorrect because this leads to too much gap between the upper and lower option.
> 
> The gap between first option and second option should be `24dp` but your changes makes it `48dp`.
> 
> Suggestion:
> Option:1
> 
> * marginStart = 24dp
> * marginEnd = 24dp
> * paddingTop = 20dp  (*)
> * paddingBottom = 12dp
> 
> Option 2:
> 
> * marginStart = 24dp
> * marginEnd = 24dp
> * paddingTop = 12dp
> * paddingBottom = 24dp (*)
> 
> (*) -> You might need to do trial-and-error to have to best UI, these values might be incorrect.
> 
> Also, test this across various devices.

Changed paddingTop to 24dp(first textview) and paddingBottom to 16dp(second textview). I think this looks perfect.

**Comment by prayutsu** [comment]
@rt4914 PTAL, luckily dialog appears nice on different types of devices (please take a look at the PR description for the updated screenshots) and if we still want some minor changes, I'll do that.

**Review by rt4914 — APPROVED** [review]
Awesome work. Thanks.

**Pull request merged**
