### PR TITLE
Fixes part of #1433: Rename the logger class to consoleLogger

### PR DESCRIPTION
**Pull request by vinitamurthi**
## Explanation
With the new forms of firebase logging coming up, we would like app/domain module files to use all logging functionality from a single logger. This PR starts the work of it. See the issue for details on how we intend to restructure it.
Fixes part of #1433 

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
LGTM

**Review by Sarthak2601 — APPROVED** [review]
LGTM. Just one suggestion, shouldn't we rename the variable name to `consoleLogger` as well ? I think It would make files more readable in cases where multiple logging scenarios(console/event/exception) exist in the same file.

**Review by anandwana001 — APPROVED** [review]
LGTM, just one thing to confirm this is updated with our yesterday's ktlint app module check merge.

**Comment by vinitamurthi** [comment]
> LGTM. Just one suggestion, shouldn't we rename the variable name to `consoleLogger` as well ? I think It would make files more readable in cases where multiple logging scenarios(console/event/exception) exist in the same file.

The whole goal is to remove multiple logging scenarios :) Hence I am not changing the name. Eventually we will be replacing the consoleLogger with OppiaLogger in the app and domain modules, so I dont want to change variable names right now

**Comment by vinitamurthi** [comment]
> LGTM, just one thing to confirm this is updated with our yesterday's ktlint app module check merge.

Yep I updated the branch

**Pull request merged**
