### PR TITLE
Fix #2551: Reformatted XML files

### LINKED ISSUE #2551: Reformatting Required for the following files
The following files require reformatting
 - layout-land/topic_revision_summary_view.xml
 - layout-sw600dp-land/topic_revision_summary_view.xml
 - layout-sw600dp-port/topic_revision_summary_view.xml
 - layout/updates_tab_fragment.xml
 - layout/walkthrough_topic_list_fragment.xml
 - layout-sw600dp-land/all_topics.xml
 - layout-sw600dp-port/all_topics.xml
 - layout/app_language_fragment.xml
 - layout-land/completed_story_list_fragment.xml
 - layout-sw600dp-land/completed_story_list_fragment.xml

Recommended to setup [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References 
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

### PR DESCRIPTION
**Pull request by KartikeySharma**
## Explanation
Fixes #2551

I formatted the XML files using a macro for formatting files and optimizing imports. Resource for the same was provided in the issue statement.
Reformatted XML files are ->

- layout-land/topic_revision_summary_view.xml
- layout-sw600dp-land/topic_revision_summary_view.xml
- layout-sw600dp-port/topic_revision_summary_view.xml
- layout/updates_tab_fragment.xml
- layout/walkthrough_topic_list_fragment.xml
- layout-sw600dp-land/all_topics.xml
- layout-sw600dp-port/all_topics.xml
- layout/app_language_fragment.xml
- layout-land/completed_story_list_fragment.xml
- layout-sw600dp-land/completed_story_list_fragment.xml

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by MaskedCarrot** [comment]
@KartikeySharma add `Fixes #2551` at the start of the  PR description

**Comment by KartikeySharma** [comment]
> @KartikeySharma add `Fixes #2551` at the start of the PR description

Done

**Comment by MaskedCarrot** [comment]
@KartikeySharma  please make the PR descriptions as follows 
```
Explanation
Fixes #2551
I formatted the XML files using a macro for form.......
```

**Review by MaskedCarrot — APPROVED** [review]

**Comment by MaskedCarrot** [comment]
LGTM ,thanks

**Review by FareesHussain — CHANGES_REQUESTED** [review]
@KartikeySharma `sw600dp-land/completed_story_list_fragment.xml` is not reformatted yet.

**Comment by KartikeySharma** [comment]
> @KartikeySharma `sw600dp-land/completed_story_list_fragment.xml` is not reformatted yet.

I had applied the macro but it didn't reformat..maybe because it was already reformatted. I checked it multiple times before submitting this PR. Pls check it once @FareesHussain . If this is not the case, I will try to rebuild the project.

**Comment by FareesHussain** [comment]
> > @KartikeySharma `sw600dp-land/completed_story_list_fragment.xml` is not reformatted yet.
> 
> I had applied the macro but it didn't reformat..maybe because it was already reformatted. I checked it multiple times before submitting this PR. Pls check it once @FareesHussain . If this is not the case, I will try to rebuild the project.

Thanks for mentioning. It is not required

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks

**Comment by Luffy18346** [comment]
@rt4914 PTAL

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
