### PR TITLE
Fix #3901 : [A11Y] Terminal state question player recyclerview fix

### LINKED ISSUE #3901: [A11Y] Remove blank space from QuestionPlayer
[A11Y] Remove blank space from QuestionPlayer as it is readable by screen-reader.

### PR DESCRIPTION
**Pull request by bkaur-bkj**
## Explanation

Fixes #3901 ( its a remake of PR #3928 )
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

 Espresso test results 

test2
test1

A11Y output 

https://user-images.githubusercontent.com/64087572/142926641-9f85e501-6a8a-45b6-b0a2-cdb2ed33c4e1.mp4

### CODE REVIEW

**Review by rt4914 — COMMENTED** [review]
Looks perfect. Just one comment, pleas take a look at original PR and similar to that add screenshot of passing tests and also video of A11Y output.

**Comment by bkaur-bkj** [comment]
> Looks perfect. Just one comment, pleas take a look at original PR and similar to that add screenshot of passing tests and also video of A11Y output.

done sir

**Comment by rt4914** [comment]
@bkaur-bkj For now, just add screenshot of two test cases that you have written. I will look why other tests are failing. Mostly they are flaky.

**Review by rt4914 — APPROVED** [review]
LGTM. Thanks.

Will wait for Ben's review after 6th December.

**Comment by bkaur-bkj** [comment]
> @bkaur-bkj For now, just add screenshot of two test cases that you have written. I will look why other tests are failing. Mostly they are flaky.

done

**Comment by BenHenning** [comment]
Hi. FYI I've been out the last couple of weeks, so I'm working to catch up on my reviews. I might be delayed a couple of days, but I'll be reviewing this soon. Thanks for your patience!

**Review by BenHenning — APPROVED** [review]
This looks solid, thanks @bkaur-bkj! And, thanks @rt4914 for the first implementation that this is based on!

**Pull request merged**
