### PR TITLE
Fix #948: Highfi concept card

### LINKED ISSUE #948: Highfi ConceptCard
This issue tracks the Highfi work of Concept Card

Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/2cc59921-923b-43ef-bf11-cf7cc5f7d903/TM-EN-Concept-Card-/

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/8d692ecd-b41a-4dbf-acbf-66d1ffbaf265/PM-Q2-IA-Answered-1-1/

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #948 

This PR fixes the highfi work of `ConceptCard`

To test this in mobile you will need to change the launcher activity to `ConceptCardFragmentTestActivity`

## Mocks
https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/2cc59921-923b-43ef-bf11-cf7cc5f7d903/TM-EN-Concept-Card-/
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/8d692ecd-b41a-4dbf-acbf-66d1ffbaf265/PM-Q2-IA-Answered-1-1/

## Screenshot
Screenshot_1586244091
Screenshot_1586244094

## Accessibility Test 
The accessibility test fails for contrast color code of toolbar.
as_23

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by mschanteltc** [comment]
Let's use #BE563C instead please. This gives a 4.57 ratio.

**Comment by rt4914** [comment]
> BE563C

Thanks. This works.

**Comment by rt4914** [comment]
@veena14cs After @mschanteltc 's suggestion, all accessibility tests pass for this screen.

**Review by veena14cs — APPROVED** [review]
LGTM.

**Pull request merged**
