### PR TITLE
Fix #5399: Fix tests in LoggingIdentifierControllerTest

### LINKED ISSUE #5399: [BUG]: Some tests on the LoggingIdentifierControllerTest file are false positives
### Describe the bug

Tests in the test file that involve restarting the app and checking if the value generated is the same will always pass because of how the test file is set up. The LoggingIdentifierControllerTest initializes with the applicationIdSeed of 1L and on restart, this is the same seed used to generate the IDs and as such, any ID generated with the same seed will always be the same. Tests affected by this issue include the;
- testGetInstallationId_secondAppOpen_providerReturnsSameInstallationIdValue
- testFetchInstallationId_secondAppOpen_returnsSameInstallationIdValue
- testGetSessionId_secondCall_returnsSameRandomId

Two new test also needs to be introduced to ensure that the ID generated for the sessionID and the appSessionId values change when the app is restarted.

### Steps To Reproduce

N/A

### Expected Behavior

I expect that when the app restart is simulated, the applicationSeedId should be varied or modified on the restart to ensure that generated IDs are not the same purely on the basis of being generated with the same seed ID but because the IDs are being cached by the app itself. In the instance of the appSessionId, the ID should be different on each app restart in the tests to test the expected behaviour of the ID. 

### Screenshots/Videos

_No response_

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fixes #5399

This PR addresses the problems outlined in #5399 by:
- Ensuring that ``testGetInstallationId_secondAppOpen_providerReturnsSameInstallationIdValue`` and ``testFetchInstallationId_secondAppOpen_returnsSameInstallationIdValue`` are correctly run in a _new_ ``TestApplication`` (as inspired by ``SplashActivityTest``).
- Adding a new test to verify that session ID correctly regenerates in a new app instance (``testGetSessionId_secondAppOpen_returnsNewRandomId``) which also has the added benefit of providing confidence that the earlier tests are correctly verifying that the installation ID _isn't_ changing, as expected, on a new app instance.
- Improved the tests around cache corruption (via emptying) and deletion to ensure they correctly demonstrate the failure fallbacks (empty/null for corruption and reinitialization for deletion in the same way as a new app install).

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A -- This is fixing a specific test and has no impact on UI behaviors.

### CODE REVIEW

**Review by BenHenning — COMMENTED** [review]
Self-reviewed changes.

**Comment by BenHenning** [comment]
@adhiamboperes PTAL for codeowners.

@kkmurerwa PTAL to verify that this addresses your points in #5399 as expected. I deviated slightly from the suggestions since installation ID _should_ be retained on app restarts unless the database is deleted, whereas session ID _should_ be regenerated.

**Comment by kkmurerwa** [comment]
> @adhiamboperes PTAL for codeowners.
> 
> @kkmurerwa PTAL to verify that this addresses your points in #5399 as expected. I deviated slightly from the suggestions since installation ID _should_ be retained on app restarts unless the database is deleted, whereas session ID _should_ be regenerated.

I have looked at your changes and they address the problems I had highlighted in the issue. The only part not included in your changes are the appSessionId tests which understandably are not in the codebase yet. I will add them once this PR is merged.

**Review by kkmurerwa — APPROVED** [review]
I have looked at the changes and they address the problems I had highlighted in the issue. The only part not included are the appSessionId tests which are understandably not in the codebase yet. I will add them once this PR is merged.

**Review by adhiamboperes — APPROVED** [review]
LGTM, thanks @BenHenning !

**Comment by adhiamboperes** [comment]
Updating with latest develop and enabling auto-merge to unblock @kkmurerwa

**Comment by BenHenning** [comment]
Thanks much for the review @adhiamboperes!

**Pull request merged**
