### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Comment by rt4914** [comment]
@BenHenning How should I review this PR, any tips?

**Comment by BenHenning** [comment]
@rt4914 I'll take a first pass. We might want to change codeowners here actually.

**Comment by BenHenning** [comment]
FYI I'll take a pass on this tomorrow or later in the week.

**Comment by BenHenning** [comment]
NB: some of the strings were mistranslated and will need to be fixed now that #3754 has landed.

**Comment by BenHenning** [comment]
Filed #3786 for failing CI.

**Review by BenHenning — APPROVED** [review]
There are some issues with certain strings, but with the FAQ ones in most issues are aesthetic. We'll be doing closer QA tests later this week & can catalog specific issues that we want to fix. Otherwise, I suspect these strings are in a good place for our upcoming launch.

**Pull request merged**
