### PR TITLE
Fix #5119 TopicActivity Has Dark Mode Inconsistencies in Large Screens

### LINKED ISSUE #5119: [BUG]: TopicActivity Has Dark Mode Inconsistencies in Large Screens
### Describe the bug

In large screen devices/tablets, the `Topic` screen shows an incorrect color for both `Topic` and `Revision` tabs.

Screenshot_1690497871

Screenshot_1690497898

Screenshot_1690497901

### Steps To Reproduce

1. Install Oppia on a real tablet or emulator such as a `Nexus 9` device.
2. On a profile home screen, click on any topic.
3. On the topic list screen, see that the viewpager color is not Oppia green.
4. Switch to the *Revision* tab and observe the same outcome.

### Expected Behavior

The color should be consistent with the toolbar color above it, as seen in small screen layouts in the screenshot below:

Screenshot_1691302060

### Screenshots/Videos

_No response_

### What device/emulator are you using?

Nexus 9 emulator

### Which Android version is your device/emulator running?

Android 10

### Which version of the Oppia Android app are you using?

Developer build

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ShubhadeepKarmakar**
## Explanation
  - Fixes #5119 
tabBackground(TabLayout) is not enough for large screens, that's why I give the background to the parent i.e. background of AppBarLayout.
- AppBarLayout
  - ToolBar
  - TabLayouyt
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes

### Before:
image

### After:
Tablet in Portrait, Dark Mode
darkmode

Tablet in Landscape, Dark Mode
tablet_in_landscape_dark_mode

Tablet in Portrait, Light Mode
tablet_in_portrait_light_mode

Tablet in Landscape, Light Mode
tablet_in_landscape_light_mode

Phone in Portrait, Dark Mode
pipdm

Phone in Landscape, Dark Mode
pildm

Phone in Portrait, Light Mode
phone_in_portrait_light_mode

Phone in Landscape, Light Mode
pillm

### CODE REVIEW

**Review by adhiamboperes — COMMENTED** [review]
Thanks @ShubhadeepKarmakar, my only comment is please add more screenshots proving that the following screens are still displaying correctly:

- [ ] Tablet in landscape, dark mode
- [ ] Tablet in portrait, light mode
- [ ] Tablet in landscape, light mode 
- [ ] Phone in portrait, dark mode
- [ ] Phone in landscape, dark mode
- [ ] Phone in portrait, light mode
- [ ] Phone in landscape, light mode

This way we can confirm that nothing is broken.

**Comment by ShubhadeepKarmakar** [comment]
> Thanks @ShubhadeepKarmakar, my only comment is please add more screenshots proving that the following screens are still displaying correctly:
> 
>     * [x]  Tablet in landscape, dark mode
> 
>     * [x]  Tablet in portrait, light mode
> 
>     * [x]  Tablet in landscape, light mode
> 
>     * [x]  Phone in portrait, dark mode
> 
>     * [x]  Phone in landscape, dark mode
> 
>     * [x]  Phone in portrait, light mode
> 
>     * [x]  Phone in landscape, light mode
> 
> 
> This way we can confirm that nothing is broken.


@adhiamboperes Done?

**Comment by ShubhadeepKarmakar** [comment]
@adhiamboperes Done.

**Review by adhiamboperes — APPROVED** [review]
Thanks @ShubhadeepKarmakar. LGTM.

**Pull request merged**
