### PR TITLE
Fixes #5244: Technical Analytics Milestone 4 - Document Technical Analytics Changes

### LINKED ISSUE #5244: Implementation Request: Documentation of Changes Made by Technical Analytics TDD.
### Is your feature request related to a problem? Please describe.

Link to Technical Analytics TDD: https://docs.google.com/document/d/1qm2ZkjvWltsw4M8ZQ0KDJoL917KJz1WBx7TiJqeAFog/edit#heading=h.p47sq11zcyy1

### Describe the solution you'd like

Changes to be documented include;
- [x] Document how to add new feature flags.

### Describe alternatives you've considered

N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by kkmurerwa**
## Explanation

Fixes #5244 : When merged, this PR will;
- Modify the Platform Parameter and Feature Flags documentation to reflect changes introduced by the Technical Analytics Milestones 1, 2 and 3 PRs.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by kkmurerwa** [comment]
@adhiamboperes this PR is ready for review now. PTAL

**Review by adhiamboperes — COMMENTED** [review]
Thanks @kkmurerwa. This looks good so far.
I'm wondering if there's some kind of script or runtime failure that will ensure all new feature flags are added to app startup logging

**Comment by kkmurerwa** [comment]
> Thanks @kkmurerwa. This looks good so far. I'm wondering if there's some kind of script or runtime failure that will ensure all new feature flags are added to app startup logging

@adhiamboperes Milestone 2 placed mechanisms to make sure that any feature flags introduced in the future will cause CI to fail as long as they are added to the feature flags logger. However, there is no objective way to make sure that feature flags added to the constants file are also added to the feature flags logger.

**Comment by adhiamboperes** [comment]
> > Thanks @kkmurerwa. This looks good so far. I'm wondering if there's some kind of script or runtime failure that will ensure all new feature flags are added to app startup logging
> 
> @adhiamboperes Milestone 2 placed mechanisms to make sure that any feature flags introduced in the future will cause CI to fail as long as they are added to the feature flags logger. However, there is no objective way to make sure that feature flags added to the constants file are also added to the feature flags logger.

I have filed https://github.com/oppia/oppia-android/issues/5445 so that we can find a way to do this.

**Review by adhiamboperes — APPROVED** [review]
Thanks @kkmurerwa. This LGTM.

**Comment by adhiamboperes** [comment]
Syncing with develop and enabling auto-merge.

**Comment by adhiamboperes** [comment]
@seanlip, could you please approve for oppia/owners?

**Review by seanlip — APPROVED** [review]
Thanks, LGTM for owners.

**Pull request merged**
