### PR TITLE
Fix #3540 : Merge lessons_chapter_view.xml into single xml file 

### LINKED ISSUE #3540: Merge lessons_chapter_view.xml into single xml file
Currently there are 2 versions of `lessons_chapter_view.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

### PR DESCRIPTION
**Pull request by aayushimathur6**
## Explanation
Fix #3540 : Merge lessons_chapter_view.xml into single xml file 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

| BEFORE  | AFTER |
| ------------- | ------------- |
|pixel5potrait | Screenshot_20220130_135926 |
|WhatsApp Image 2022-02-01 at 2 54 51 AM (1)|Screenshot_20220130_141221 |
|nexus9potrait |Screenshot_20220130_141849 |
|WhatsApp Image 2022-02-01 at 2 54 51 AM (2)| Screenshot_20220130_141820|

### CODE REVIEW

**Comment by rishidyno** [comment]
@aayushimathur6 PTAL can you please rearrange the image as they are not correct in their current state.

**Comment by rishidyno** [comment]
Also I think the image are incorrect please rectify them. Thanks!

**Comment by ayush0402** [comment]
Before screenshots for landscape modes are not correct. Rest seems to be fine.

**Comment by aayushimathur6** [comment]
corrected it, please check @ayush0402 @rishidyno  !!

**Comment by ayush0402** [comment]
@aayushimathur6 LGTM, Thanks. Just a nit suggestion, try to keep screenshots for comparison to be of same size, you can use size attributes in markdown to fix it.

**Comment by ayush0402** [comment]
@rt4914 Please approve the workflows. Thanks.

**Comment by aayushimathur6** [comment]
okay @ayush0402  next time I will keep this in my  mind

**Comment by rishidyno** [comment]
LGTM Thanks!

**Comment by rt4914** [comment]
@aayushimathur6 Your PR is 3 commits behind develop. Please update the develop on your fork and also update this branch. You can notice it says "3 commits behind oppia:develop"
Screenshot 2022-02-02 at 1 33 07 PM

Once its up-to-date all CI checks should pass.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by aayushimathur6** [comment]
Hey @rt4914 please review my changes

**Pull request merged**
