### PR TITLE
Fix #1792:Fixed change in keyboard when show password was pressed

### LINKED ISSUE #1792: Toggling show/hide changes soft keyboard
**Describe the bug**
When we are on the screen where we have to input admin pin, we have a show and hide button, toggling which changes the soft keyboard 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install app -> click on the admin profile
2. click on the show -> hide -> soft keyboard changes 

**Expected behaviour**
The soft keyboard should not change

**Video**
https://lh3.googleusercontent.com/2ACs5tLuu3JmS1V248M2flkFCL35GeI4ZaHaj2yXu-AIaXExQFbWXVDkkyeS8vCXBKIyU5RRxhQeJ08=m37

**Device**
- Redmi Note 5 Pro

### PR DESCRIPTION
**Pull request by Victor-Titan**
## Explanation

Fixes #1792 where the soft keyboard changes on pressing the show/hide button.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

@anandwana001 PTAL

ezgif com-video-to-gif

### CODE REVIEW

**Comment by anandwana001** [comment]
Please check my comments and thread here - https://github.com/oppia/oppia-android/issues/1792#issuecomment-690051707

**Comment by Victor-Titan** [comment]
> Please check my comments and thread here - [#1792 (comment)](https://github.com/oppia/oppia-android/issues/1792#issuecomment-690051707)

Where do I apply the setPasswordHidden method, I can't find it

**Comment by Sarthak2601** [comment]
A few things to note about this PR - 
- Add a suitable short title summarising the change in PR title along with `Fix #1792`
- Add relevant screenshots or gifs to verify that the bug has been fixed. 
- Follow the method mentioned by @anandwana001 [here](https://github.com/oppia/oppia-android/issues/1792#issuecomment-690051707) to solve this bug.

**Comment by Victor-Titan** [comment]
@anandwana001 I'm not able to access the setPasswordHidden method. I've changed the version from 1.4.3 to 1.4.4 in 2 places in the files, but on rebuilding the project, the pinView doesn't give me the option to access that method, can you tell me how to upgrade the version please.

**Comment by anandwana001** [comment]
> @anandwana001 I'm not able to access the setPasswordHidden method. I've changed the version from 1.4.3 to 1.4.1 in 2 places in the files, but on rebuilding the project, the pinView doesn't give me the option to access that method, can you tell me how to upgrade the version please.

As per my comment https://github.com/oppia/oppia-android/issues/1792#issuecomment-690051707 you have to update to 1.4.4

**Comment by Victor-Titan** [comment]
> > @anandwana001 I'm not able to access the setPasswordHidden method. I've changed the version from 1.4.3 to 1.4.1 in 2 places in the files, but on rebuilding the project, the pinView doesn't give me the option to access that method, can you tell me how to upgrade the version please.
> 
> As per my comment [#1792 (comment)](https://github.com/oppia/oppia-android/issues/1792#issuecomment-690051707) you have to update to 1.4.4

I mistyped 1.4.1, I updated to 1.4.4 but the problem still persisted, so I'm trying to use the method specified at the end of that issue but binding.inputPin have the setPasswordHidden method show up

**Comment by anandwana001** [comment]
> > > @anandwana001 I'm not able to access the setPasswordHidden method. I've changed the version from 1.4.3 to 1.4.1 in 2 places in the files, but on rebuilding the project, the pinView doesn't give me the option to access that method, can you tell me how to upgrade the version please.
> > 
> > 
> > As per my comment [#1792 (comment)](https://github.com/oppia/oppia-android/issues/1792#issuecomment-690051707) you have to update to 1.4.4
> 
> I mistyped 1.4.1, I updated to 1.4.4 but the problem still persisted, so I'm trying to use the method specified at the end of that issue but binding.inputPin have the setPasswordHidden method show up

@Victor-Titan Let's try to implement it and commit so based on that I can review it more correctly that way.

**Comment by Victor-Titan** [comment]
@anandwana001 please help, the bazel test says there was a build failure with the app due to the function I invoked, but the app is building on my laptop.

**Comment by anandwana001** [comment]
@Victor-Titan The first thing you have to do here is to fix the branch. This PR includes some of the changes from the other branch, so I suggest to update it correctly. Then we can go for bazel failure by updating the pinView version in the bazel files.

**Comment by anandwana001** [comment]
@Victor-Titan Any update on this?

**Comment by Victor-Titan** [comment]
@anandwana001 Hi! I'm sorry I've had a series of tests in college so haven't been able to clean my branch. The build error went away once I updated my branch as @BenHenning specified last week in the gitter chat. I'll try and clean the branch tomorrow. The code works perfectly and the build error only occurred because of the update from the upstream.

**Comment by anandwana001** [comment]
> @anandwana001 Hi! I'm sorry I've had a series of tests in college so haven't been able to clean my branch. The build error went away once I updated my branch as @BenHenning specified last week in the gitter chat. I'll try and clean the branch tomorrow. The code works perfectly and the build error only occurred because of the update from the upstream.

Sounds good, thanks for the follow-up.

**Comment by Victor-Titan** [comment]
I'm closing this PR as I can't reverse the commits from other branches that ended up in my branch. The reason was that I couldn't push code via terminal due to authentication errors which led me to use the Android Studio UI where I was asked to merge the updates from the remote and it accidentally treated these merges as commits.

**Pull request closed without merging**
