### PR TITLE
Fix #3058: Created MIGRATED_PROD_FILES list in domain/BUILD.bazel file

### LINKED ISSUE #3058: Create MIGRATED_PROD_FILES list in the domain BUILD.bazel file
This change will create a setup for modularizing the packages in the domain module.

See https://github.com/oppia/oppia-android/blob/develop/utility/BUILD.bazel for an example of the setup.

1. Define the list using a glob of an empty list for now.

```
MIGRATED_PROD_FILES = glob([])
```

2. Update the library to exclude these files

```python
kt_android_library(
    name = "domain",
    srcs = glob(
        ["src/main/java/org/oppia/android/domain/**/*.kt"],
        exclude = [MIGRATED_PROD_FILES, "src/main/java/org/oppia/android/domain/testing/**/*.kt"],
    ),
```

Now, whenever somone migrates a package, they can add the package to the MIGRATED_PROD_FILES glob.

### PR DESCRIPTION
**Pull request by KartikeySharma**
Fixes #3058.
## Explanation

Created a new empty list MIGRATED_PROD_FILES and added the exclude dependencies in it. Followed the reference of the utility/BAZEL.build file .

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by fsharpasharp** [comment]
Thanks @KartikeySharma. We should keep the list empty for now and leave the test files glob as is. This make sure that we keep the semantics of the variable name, i.e. migrated_prod_files pertain prod files.

Also add a comment explaining the new variable. See other modules' BUILD.bazel file for details.

**Comment by KartikeySharma** [comment]
@fsharpasharp  When I tried the syntax which you gave as an example in the issue, the BUILD.bazel file gave an error. That's the reason I added the exclude dependency inside the MIGRATED_PROD_FILES.

**Comment by fsharpasharp** [comment]
Yes, I see that there's an error in the example's syntax. You will have to concatenate the two lists using +

**Comment by KartikeySharma** [comment]
> Yes, I see that there's an error in the example's syntax. You will have to concatenate the two lists using +

Ok. I will make the necessary changes soon.

**Comment by fsharpasharp** [comment]
Thanks, please add a comment describing MIGRATED_PROD_FILES as well. Check the other BUILD.bazel file for an example.

**Review by fsharpasharp — APPROVED** [review]

**Comment by KartikeySharma** [comment]
> Thanks, please add a comment describing MIGRATED_PROD_FILES as well. Check the other BUILD.bazel file for an example.

Done. PTAL.

**Review by BenHenning — APPROVED** [review]
Thanks @KartikeySharma! This looks good to me.

**Pull request merged**
