### PR TITLE
Fix #2465: Remove textDirection property from textInputLayout

### LINKED ISSUE #2465: Optimise TextInputLayout in admin_settings_dialog
Remove `android:textDirection="locale"` in `TextInputLayout` from the following files
 - layout/admin_settings_dialog
 - layout-land/admin_settings_dialog

### PR DESCRIPTION
**Pull request by dipu989**
Fixes #2465: Optimizing textInputLayout in admin_settings_dialog
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by dipu989** [comment]
@FareesHussain PTAL!

**Review by FareesHussain — APPROVED** [review]

**Comment by BenHenning** [comment]
Sorry for the noise here. I actually shouldn't have codeowners over these files (& I'm in the process of fixing this in #2474) so assigning over to @rt4914 who will need to approve it, anyway.

**Review by rt4914 — APPROVED** [review]
LGTM.

@dipu989 Please update the title to `Fix #2465: Remove textDirection property from TextInputLayout`

**Comment by dipu989** [comment]
@rt4914 Done! Will keep these points in mind 👍

**Comment by rt4914** [comment]
@BenHenning Any specific reason why it is stuck on **Check CODEOWNERS & Repository files** ?

**Comment by BenHenning** [comment]
This needs to be updated with the latest develop since we introduced a new required check. It's waiting for a status that can't be delivered because the branch doesn't include the actions code to run that check. Merging in the latest develop should fix it.

**Comment by BenHenning** [comment]
@dipu989 you'll need to merge in the latest develop branch from oppia/oppia-android & re-push to your fork.

**Comment by dipu989** [comment]
@BenHenning @rt4914 Done! Please check

**Pull request merged**
