### PR TITLE
Fix #607: Add methods to DataProviders to combine two providers together

### LINKED ISSUE #607: Add functionality to combine two data providers
With recent work around story progress, we need support for combining two data providers together (e.g. two transformed ``PersistentCacheStore``s).

### PR DESCRIPTION
**Pull request by BenHenning**
Introduces two new methods to ``DataProviders``: ``combine`` and ``combineAsync``.

These methods allow two data providers to be combined together using a synchronous and asynchronous combination function, respectively. When either of the underlying two data providers are changed, their results are re-combined and observers of the combined data provider are notified of the change.

### CODE REVIEW

**Comment by BenHenning** [comment]
@rt4914 I haven't tested this functionality yet, but I'm failure sure it will work given that the underlying ``AsyncResult`` changes are passing. Please feel free to base off this branch for your other change and see if it solves your issue. I'll wrap up these tests a bit later & send out this PR for review.

**Comment by BenHenning** [comment]
This is now ready for review.

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.

**Comment by BenHenning** [comment]
Thanks!

**Pull request merged**
