### PR TITLE
Fix #5170 [Feature Request]: Display some kind of loading animation/graphic when topics are loading in Home Page

### LINKED ISSUE #5170: [Feature Request]: Display some kind of loading animation/graphic when topics are loading in Home Page
### Is your feature request related to a problem? Please describe.

A loading bar would be good to indicate the user that the topics are being loaded on the home page.

### Describe the solution you'd like

I would like to have a simple indeterminate circular progress at the center of the screen when the topics are loading.

### Describe alternatives you've considered

_No response_

### Additional context

https://github.com/oppia/oppia-android/assets/84731134/11e91377-6da3-45ee-8764-030c59bc375a

### PR DESCRIPTION
**Pull request by Vishwajith-Shettigar**
## Explanation

Fix oppia/oppia-android#5170. Added progressbar to the home fragment to show loading. 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

Light mode

https://github.com/oppia/oppia-android/assets/76042077/d7ac57cb-47e0-43a1-b80c-7c64eaa67ddd

Darkmode

https://github.com/oppia/oppia-android/assets/76042077/1a13dd22-df4d-4dbd-bd06-19882a123d98

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by adhiamboperes** [comment]
Closing this since the issue has been moved to design team.

**Comment by seanlip** [comment]
@Vishwajith-Shettigar Out of interest, could you show a video of your proposed changes here?

**Comment by Vishwajith-Shettigar** [comment]
> @Vishwajith-Shettigar Out of interest, could you show a video of your proposed changes here?

@seanlip I have attached screen recording in PR description

**Comment by seanlip** [comment]
Thanks @Vishwajith-Shettigar. Actually, this seems quite a reasonable interim fix, so I'm reopening this PR.

@adhiamboperes Feel free to accept this if you feel that it looks good from a technical perspective. It looks fine to me from the PM side. Thanks!

**Comment by adhiamboperes** [comment]
@Vishwajith-Shettigar this should be reasonably completed if you add tests for the progressbar being shown and hidden as intended, and also demonstrate that it displays with the correct colors in light mode.

**Comment by adhiamboperes** [comment]
Also update the title and description to 'fix part of'

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar!

From your videos, I noticed that the progressbar is blue in color. The color should be green, and it should be defined per oppia [color guidelines](https://github.com/oppia/oppia-android/wiki/Dark-Mode) for darkmode support. The correct color to use here is `@color/color_def_oppia_green`

**Comment by Vishwajith-Shettigar** [comment]
> Thanks @Vishwajith-Shettigar!
> 
> From your videos, I noticed that the progressbar is blue in color. The color should be green, and it should be defined per oppia [color guidelines](https://github.com/oppia/oppia-android/wiki/Dark-Mode) for darkmode support. The correct color to use here is `@color/color_def_oppia_green`

I made changes, PTAL

**Review by adhiamboperes — APPROVED** [review]
Thanks @Vishwajith-Shettigar! This LGTM.

**Pull request merged**
