### PR TITLE
Fix #3544: Merge ongoing_story_card.xml into single xml file

### LINKED ISSUE #3544: Merge ongoing_story_card.xml into single xml file
Currently there are 4 versions of `ongoing_story_card.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

### PR DESCRIPTION
**Pull request by pandayed**
## Explanation
Fix #3544: Merge ongoing_story_card.xml into single xml file

## Essential Checklist

- [✓] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [✓] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [✓] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [✓] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [✓] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [✓] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

| Before | After |
| ------ | ------|
| Screenshot_2022-01-31-22-55-44-269_org oppia android | Screenshot_2022-01-31-23-28-01-712_org oppia android |
| Screenshot_2022-01-31-22-57-55-290_org oppia android | Screenshot_2022-01-31-23-28-33-263_org oppia android |
|  |  |
|  |  |

### CODE REVIEW

**Comment by rishidyno** [comment]
@xpandeyed  Please add the SS in a Tabular form. Thanks!

**Comment by pandayed** [comment]
@rt4914 Please approve the workflows. Thanks!

**Comment by rt4914** [comment]
Will review it once @rishidyno has approved it.

**Comment by rishidyno** [comment]
LGTM.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
