### PR TITLE
Removed all fuzzy="true" attributes that were introduced in #5258

### PR DESCRIPTION
**Pull request by Rd4dev**
## Explanation

Fix PR #5258
This PR removes all fuzzy="true" attributes that were introduced in PR [#5258](https://github.com/oppia/oppia-android/pull/5258)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by Rd4dev** [comment]
@adhiamboperes PTAL

**Comment by adhiamboperes** [comment]
Hi @Rd4dev, this branch has some conflicts with develop. Could you please resolve them?

**Comment by Rd4dev** [comment]
@adhiamboperes PTAL

**Comment by Rd4dev** [comment]
> Hi @Rd4dev, this branch has some conflicts with develop. Could you please resolve them?

The conflicts in this branch arose from merging the [#5258](https://github.com/oppia/oppia-android/pull/5258) branch, which had `fuzzy="true"` attributes. I've addressed these conflicts and pushed the code again. I hope this resolves the issue.

**Review by adhiamboperes — APPROVED** [review]
Thanks @Rd4dev! Changes LGTM.

**Pull request merged**
