### PR TITLE
Fix part of #1587: Made intent keys consistent in the options and player packages in the app module 

### LINKED ISSUE #1587: Make intent/bundle/saved/tags instance keys consistent.
The keys should be consistent in intents, bundles, tags, etc. They should mainly follow below mentioned structure.

For fragments:
`<PROPERTY_NAME>_ARGUMENT_KEY = "<FileName>.<property_name>"`
Example: `INTERNAL_PROFILE_ID_ARGUMENT_KEY = "SampleFragment.internal_profile_id"`

For activities:
`<PROPERTY_NAME>_EXTRA_KEY = "<FileName>.<property_name>"`
Example: `INTERNAL_PROFILE_ID_EXTRA_KEY = "SampleActivity.internal_profile_id"`

For saved instances:
`<PROPERTY_NAME>_SAVED_KEY = "<FileName>.<property_name>"`
Example: `INTERNAL_PROFILE_ID_SAVED_KEY = "SampleActivity.internal_profile_id"`

### PR DESCRIPTION
**Pull request by janewaitara**
## Explanation

Fixes part of #1587 Made intent keys consistent in the options and player packages in the app module

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by janewaitara** [comment]
@rt4914, PTAL

**Comment by anandwana001** [comment]
@janewaitara Thanks for the PR.

Few points to follow before review:
1. Follow the first point from the checklist `The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)`
2. Follow on how to choose a branch name from our wiki - https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change
3. As we know to fix this issue, we need a lot of changes, so how are we planning with the sub PR's? Are we going to have sub PR's package way? Like fixing 2-3 packages at a time? 
4. As per my point 3, we are fixing a part of an issue, so please follow the second point from the checklist `The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).`

**Comment by janewaitara** [comment]
@anandwana001  Thank you for the corrections.

I have worked on point 1 and 4 for the PR title and description. For the intent keys, tags and bundle keys, I opted to work on files in the same package and have the sub PRs in the package ways since the files would be too many in one PR. However, for the saved instances, the files were few hence I worked on them all in all packages.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @janewaitara 
Defer to @rt4914 for further review

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Blocking this PR just so that @janewaitara can update the branch and merge with latest develop.

**Comment by janewaitara** [comment]
@rt4914  I have updated the branch and merged with the latest develop. PTAL

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
