### PR TITLE
Fixes #1539: Hints & Solution - Animation

### LINKED ISSUE #1181: Hints & Solution - Tablet (Portrait) (Highfi)
Mocks: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/e5d3beb6-6f0a-47cf-bd40-4ef00ef5e53d/P-Hint-Part-1-of-4-

Implement high-fi UI for **Hints & Solution** tablet portrait mode

**Target PR date**: 15 July 2020
**Target completion date**: 19 July 2020

### LINKED ISSUE #1539: Hints & Solution animation
Add animation to Hints & Solution fragment like the one in [this mocks](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/294d3abd-c3d2-4c4b-80f2-1d211e2a69fd/) (click on the second item arrow to see the animation)

### PR DESCRIPTION
**Pull request by MohamedMedhat1998**
## Explanation

- Fixes part of #1539 
- Implemented animation for **Hints&Solution** 
- Mocks: [Hints](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/e5d3beb6-6f0a-47cf-bd40-4ef00ef5e53d/P-Hint-Part-1-of-4-) - [Solution](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/a0681c39-25b2-4fd1-9a27-66fc2b8eb49b/P-Hint-Part-3-of-4-)
- [Implementation doc](https://docs.google.com/document/d/1UxwcQ3nVcq40SCOkLbtaawHvN0r1SX5yf4VZr6byTv0/edit?usp=sharing)

## Important Notes
- All items (hints - solution) already exist in RV and we are just controlling the visibility
- Each `item_view` contains a divider at the bottom
### some approaches
- Current approach - [design doc](https://docs.google.com/document/d/1UxwcQ3nVcq40SCOkLbtaawHvN0r1SX5yf4VZr6byTv0/edit?usp=sharing)
  - Issues: The code is very big and cannot be reused somewhere else because we have to manually move the bottom divider
- Solution 1: Item decorator instead of view for showing line
  - Issues: The reason why it doesn’t work, all the dividers are visible even if the hint itself is invisible
- Solution 2: Put the last divider outside of recyclerview, below the recyclerview itself in the fragment file
  - Issues: It won’t animate the last divider. Instead, it will jump.
- Solution 3: Use different `view_types` for the dividers
  - Still under discussion
  - Approach: We need to add 1 divider after each item (after each hint or solution) so that it will automatically animate by the recyclerview. Adding these dividers can be done using a `class` that will:
    1. Take the available list of hints and solution
    2. Insert 1 divider after each item
    3. Return the new list that contains both hints and dividers
  - This class is playing the role of the adapter in the **Adapter Pattern**
### 1024x768 Emulator
screenshot-2020-06-29_17 20 53 32
screenshot-2020-06-29_17 20 56 73
screenshot-2020-06-29_17 20 59 37
screenshot-2020-06-29_17 24 09 082
screenshot-2020-06-29_17 24 11 114
screenshot-2020-06-29_17 24 13 273
screenshot-2020-06-29_17 25 26 674
screenshot-2020-06-29_17 25 32 209
screenshot-2020-06-29_17 25 34 625

### 2560x1800 Emulator
screenshot-2020-06-29_17 28 55 266
screenshot-2020-06-29_17 28 57 946
screenshot-2020-06-29_17 29 00 841
screenshot-2020-06-29_17 31 39 265
screenshot-2020-06-29_17 31 42 568
screenshot-2020-06-29_17 31 44 801
screenshot-2020-06-29_17 32 17 194
screenshot-2020-06-29_17 32 22 921
screenshot-2020-06-29_17 32 25 754

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by MohamedMedhat1998** [comment]
Closing this PR because it deleted some files by mistake

**Review by rt4914 — CHANGES_REQUESTED** [review]
LGTM, thanks.
You will need to add two animations to this screen:
1. Rotate animation on the arrow icon
2. Expand/contract animation on the content similar to the animation in this screen https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/294d3abd-c3d2-4c4b-80f2-1d211e2a69fd/TP-Lessons-All-Stories-Collpased- (In this mock you can click on arrow of second item to see how animation works).

You will need to create animation similar to that or something which looks nice like this.

Therefore rename the PR is `Fix part of #1181` so that the issue does not get closed. And confirm here whether this will be done in a separate PR of this PR itself.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> LGTM, thanks.
> You will need to add two animations to this screen:
> 
>     1. Rotate animation on the arrow icon
> 
>     2. Expand/contract animation on the content similar to the animation in this screen https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/294d3abd-c3d2-4c4b-80f2-1d211e2a69fd/TP-Lessons-All-Stories-Collpased- (In this mock you can click on arrow of second item to see how animation works).
> 
> 
> You will need to create animation similar to that or something which looks nice like this.
> 
> Therefore rename the PR is `Fix part of #1181` so that the issue does not get closed. And confirm here whether this will be done in a separate PR of this PR itself.

Done. It is done on this PR itself

**Review by rt4914 — CHANGES_REQUESTED** [review]
@MohamedMedhat1998 The arrow animation looks awesome. But the layout which you are showing/hiding has a flickering effect, unfortunately I cannot record this in a gif as its very fast but you can test it too by following these steps:

1. Keep the item in expanded form.
2. Now click on arrow to contract, here focus on the content and you will see a flickering effect.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> LGTM, thanks.
> You will need to add two animations to this screen:
> 
>     1. Rotate animation on the arrow icon
> 
>     2. Expand/contract animation on the content similar to the animation in this screen https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/294d3abd-c3d2-4c4b-80f2-1d211e2a69fd/TP-Lessons-All-Stories-Collpased- (In this mock you can click on arrow of second item to see how animation works).
> 
> 
> You will need to create animation similar to that or something which looks nice like this.
> 
> Therefore rename the PR is `Fix part of #1181` so that the issue does not get closed. And confirm here whether this will be done in a separate PR of this PR itself.

@rt4914 I can't replicate the flickering issue.  
I have also made this [doc ](https://docs.google.com/document/d/1UxwcQ3nVcq40SCOkLbtaawHvN0r1SX5yf4VZr6byTv0/edit?usp=sharing)about the implementation, PTAL!

**Comment by MohamedMedhat1998** [comment]
@rt4914 I have created a separate PR for the high-fi without animation as you suggested, PTAL here #1464  
When that PR gets merged, we can update this PR with the develop then show it to Ben for review.  
He will need to take a look at [this doc](https://docs.google.com/document/d/1UxwcQ3nVcq40SCOkLbtaawHvN0r1SX5yf4VZr6byTv0/edit?usp=sharing) first before reviewing.

**Comment by rt4914** [comment]
> @rt4914 I have created a separate PR for the high-fi without animation as you suggested, PTAL here #1464
> When that PR gets merged, we can update this PR with the develop then show it to Ben for review.
> He will need to take a look at [this doc](https://docs.google.com/document/d/1UxwcQ3nVcq40SCOkLbtaawHvN0r1SX5yf4VZr6byTv0/edit?usp=sharing) first before reviewing.

Sounds good, unassigning myself for now.

**Comment by BenHenning** [comment]
@MohamedMedhat1998 please update this with the latest develop.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Unassigned myself based on this review: https://github.com/oppia/oppia-android/pull/1465#pullrequestreview-447888033

**Comment by MohamedMedhat1998** [comment]
> 
> 
> @MohamedMedhat1998 please update this with the latest develop.

Done

**Comment by MohamedMedhat1998** [comment]
@rt4914 Here are the reasons behind the big number of changed files compared with #1465
1. #1465 is just an example, not a complete PR because it only applies the animation to `sw600dp-land`.  
**But here**, we apply the animation to every single configuration `sw600dp-land`, `sw600dp-port`, `land`, and the normal `port`.
2. In #1465 we don't touch any Kotlin file related to the fragment and its presenter because we simply depend on the visibility which is handled using data-binding.  
**But here**, we manually animate the last item, which requires a lot of Kotlin code. The reason is explained in detail [here in the doc](https://docs.google.com/document/d/1UxwcQ3nVcq40SCOkLbtaawHvN0r1SX5yf4VZr6byTv0/edit). If we can ignore the divider for the last item, 95% we won't have to touch any Kotlin file and the code would be much cleaner.
3. Manually animating the last item requires the portion of animation, which is the `height`, `top_margin`, and `bottom_margin`. And the margin values can't be static in all configurations. So, I had to create some values in `dimens.xml` in different configurations to handle that issue.

**Comment by rt4914** [comment]
> @rt4914 Here are the reasons behind the big number of changed files compared with #1465
> 
> 1. #1465 is just an example, not a complete PR because it only applies the animation to `sw600dp-land`.
>    **But here**, we apply the animation to every single configuration `sw600dp-land`, `sw600dp-port`, `land`, and the normal `port`.
> 2. In #1465 we don't touch any Kotlin file related to the fragment and its presenter because we simply depend on the visibility which is handled using data-binding.
>    **But here**, we manually animate the last item, which requires a lot of Kotlin code. The reason is explained in detail [here in the doc](https://docs.google.com/document/d/1UxwcQ3nVcq40SCOkLbtaawHvN0r1SX5yf4VZr6byTv0/edit). If we can ignore the divider for the last item, 95% we won't have to touch any Kotlin file and the code would be much cleaner.
> 3. Manually animating the last item requires the portion of animation, which is the `height`, `top_margin`, and `bottom_margin`. And the margin values can't be static in all configurations. So, I had to create some values in `dimens.xml` in different configurations to handle that issue.

@MohamedMedhat1998 Sounds good. I will review it and discuss this with Ben and get back to you.

**Comment by BenHenning** [comment]
Could we use an item decorator to paint the divider, instead? That might simplify this implementation quite a bit. @aggarwalpulkit596 might have thoughts on this.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> Could we use an item decorator to paint the divider, instead? That might simplify this implementation quite a bit. @aggarwalpulkit596 might have thoughts on this.

@BenHenning I can't understand how painting the divider would be useful here, can you explain more, please?  

I was thinking of appending a new `view_type` after each "Hint/Solution" and get rid of the dividers inside the `ViewHolder` itself.  
It will be a divider item like what we have in `RecentlyPlayed`.  
But this may cause a lot of change in the implementation because I think we depend on the index of the hint to take some decisions. A simple suggestion to fix that is to divide the index of the "Hint" by 2 before passing it anywhere in order to pass the same value we were passing before adding these dividers.  

Adding such a view will make everything much easier (in terms of animation) because it will animate automatically as explained [here](https://docs.google.com/document/d/1UxwcQ3nVcq40SCOkLbtaawHvN0r1SX5yf4VZr6byTv0/edit), we won't have to manually animate anything.  
@rt4914 @BenHenning What do you see?

**Comment by rt4914** [comment]
@MohamedMedhat1998 Have a look at this implementation, https://gist.github.com/rt4914/6e68eb0c0e4cb584202e0095585e92e7

I have tried to update the implementation such that we only populate data which is accessible the user. Please check this thoroughly and apply the animation similar lessons PR.

**Comment by MohamedMedhat1998** [comment]
Closing this PR because its work is done in #1576

**Pull request closed without merging**
