### PR TITLE
Move Bazel ownership to end of codeowners file

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
This updates Bazel code ownership to ensure that all Bazel files are reviewed by the same team members regardless of local directory ownership. This is becoming more important now that modules are being split up, and because the team isn't yet fully ramped up on maintaining BUILD files.

Note that BUILD file code ownership is a temporary situation. Once the migration from Gradle is complete & we have comprehensive Bazel documentation, we'll be expecting directory-level code owners to take over BUILD file ownership.

This was discovered when reviewing #2959: https://github.com/oppia/oppia-android/pull/2959#pullrequestreview-645278501.

### CODE REVIEW

**Comment by BenHenning** [comment]
@rt4914 PTAL for codeowner adjustment. @fsharpasharp PTAL for policy change in how we manage Bazel owners. @seanlip PTAL as codeowner owner.

**Review by rt4914 — APPROVED** [review]
LGTM.

**Review by fsharpasharp — APPROVED** [review]

**Review by seanlip — APPROVED** [review]
Sorry -- somehow I missed this notification. LGTM but there's a merge conflict that needs to be resolved.

**Comment by BenHenning** [comment]
Thanks @seanlip & others. I addressed the conflicts & will enable auto-merge.

**Pull request merged**
