### PR TITLE
Pin Bazel version to 4.0.0

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Pins the Bazel version in the repository to 4.0.0. This has the effect of producing an error like below if the wrong version is used (4.1.0 was pinned used to demonstrate the error):

```
ERROR: The project you're trying to build requires Bazel 4.1.0 (specified in /home/ben/opensource4/oppia-android/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-4.1.0

If this doesn't work, check Bazel's installation instructions for help:
  https://docs.bazel.build/versions/master/install-ubuntu.html
```

This is meant to help quickly troubleshoot errors caused by incorrect Bazel environments.

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A

### CODE REVIEW

**Comment by BenHenning** [comment]
@seanlip PTAL for codeowners change.

@FareesHussain PTAL for the pinning bit since you made a similar change for Android SDK recently.

**Review by seanlip — APPROVED** [review]
LGTM for codeowners.

**Review by FareesHussain — APPROVED** [review]
LGTM Thanks

**Comment by BenHenning** [comment]
Thanks!

**Pull request merged**
