### PR TITLE
Fix part of #1996: Fix InputInteractionViewTestActivityTest

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation

Fixes part of #1996 
Some failing tests on robolectric are fixed, 3 test cases need to be verified

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Espresso - 
Screenshot from 2020-11-18 22-18-57
Robolectric -
Screenshot from 2020-11-18 21-59-20

### CODE REVIEW

**Comment by prayutsu** [comment]
@rt4914 Should we verify the 3 test cases before merging this PR as SLoP is now over and we now have enough time to correct all the failing test cases?

**Comment by rt4914** [comment]
> @rt4914 Should we verify the 3 test cases before merging this PR as SLoP is now over and we now have enough time to correct all the failing test cases?

@prayutsu No actually. Thats fine because 2 of these tests are related to orientation change which we cannot verify at this point.

**Comment by prayutsu** [comment]
> 
> @prayutsu No actually. Thats fine because 2 of these tests are related to orientation change which we cannot verify at this point.

Actually, 4 test cases are being ignored because of the orientation issue, and the remaining 3 needs verification (in total 7 test cases are being ignored as of now)

**Comment by rt4914** [comment]
> > @prayutsu No actually. Thats fine because 2 of these tests are related to orientation change which we cannot verify at this point.
> 
> Actually, 4 test cases are being ignored because of the orientation issue, and the remaining 3 needs verification (in total 7 test cases are being ignored as of now)

Okay. Got it. Then in that case lets merge these tests first and then we can work on remaining 4 tests.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @prayutsu

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
