### PR TITLE
Fix part of #2210 : Changes in Admin Controls Download Permissions View

### PR DESCRIPTION
**Pull request by 7phalange7**
## Explanation

Fixes part (`Issue-1`) of issue #2210 

### screenshots

| Before | After |
|--------|-------|
| Screenshot_1611312423       | Screenshot_1611314778 |
| Screenshot_1611311879       |   Screenshot_1611314897    |
|  Screenshot_1611312426      |    Screenshot_1611314797   |

### This test fails if constraints of switch button are not changed. But changing the constraints(top,bottom) to `parent` makes this test pass.
image

 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by Arjupta — CHANGES_REQUESTED** [review]
@7phalange7 These tests didn't failed for Mobile Emulator but it some did failed for the Tablet one , but still I don't think they are because of the constraints we have for the `SwitchCompat`, can you post a screenshot for the tests which failed at your end. The ones which failed at my end are 
- testAdministratorControlsFragment_clickEditProfile_opensProfileListActivity()
- testAdministratorControlsFragment_clickAppVersion_opensAppVersionActivity()

**Comment by 7phalange7** [comment]
> 
> 
> @7phalange7 These tests didn't failed for Mobile Emulator but it some did failed for the Tablet one , but still I don't think they are because of the constraints we have for the `SwitchCompat`, can you post a screenshot for the tests which failed at your end. The ones which failed at my end are
> 
>     * testAdministratorControlsFragment_clickEditProfile_opensProfileListActivity()
> 
>     * testAdministratorControlsFragment_clickAppVersion_opensAppVersionActivity()

**In the current commit these two tests (along with the rest ) are passing for me, as in the above screenshot.**

**If I keep the switch constraints as it is (don't change top/bottom to parent) then the following test fails :**
image

**Comment by Arjupta** [comment]
> > @7phalange7 These tests didn't failed for Mobile Emulator but it some did failed for the Tablet one , but still I don't think they are because of the constraints we have for the `SwitchCompat`, can you post a screenshot for the tests which failed at your end. The ones which failed at my end are
> > ```
> > * testAdministratorControlsFragment_clickEditProfile_opensProfileListActivity()
> > 
> > * testAdministratorControlsFragment_clickAppVersion_opensAppVersionActivity()
> > ```
> 
> **In the current commit these two tests (along with the rest ) are passing for me, as in the above screenshot.**
> 
> **If I keep the switch constraints as it is (don't change top/bottom to parent) then the following test fails :**
> image

@rt4914 can you review this problem

**Comment by rt4914** [comment]
Will take a pass tomorrow. Meanwhile @7phalange7 can follow below steps in add a screenshot here:
1. Activate the `Developer Options` in your Android Phone/Emulator
2. Find and on the "Show Layout Bounds" option. This will show girds/lines on your device.
3. Go this screen again and take screenshot.
4. Share screenshot in a comment on this PR.

I think there can be a case where a part of some other UI is overlapping the `Switch` and because of which it's not fully displayed. Thanks.

**Comment by 7phalange7** [comment]
> 
> 
> Will take a pass tomorrow. Meanwhile @7phalange7 can follow below steps in add a screenshot here:
> 
>     1. Activate the `Developer Options` in your Android Phone/Emulator
> 
>     2. Find and on the "Show Layout Bounds" option. This will show girds/lines on your device.
> 
>     3. Go this screen again and take screenshot.
> 
>     4. Share screenshot in a comment on this PR.
> 
> 
> I think there can be a case where a part of some other UI is overlapping the `Switch` and because of which it's not fully displayed. Thanks.

Here are the screenshots. One is with original constraints(which fails test) and the next is with changed constraints(test passes) and then the original before this pull request.



|Original Constraints|Changed Constraints | Before this Pull Request|
|-|-|-|
|fail|pass |orig|

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
