### PR TITLE
Fix #3857: Add support for HasSpecificTermEqualTo

### LINKED ISSUE #3857: Add support for HasSpecificTermEqualTo
HasSpecificTermEqualTo was introduced in Oppia web in https://github.com/oppia/oppia/pull/12103 & isn't yet supported in Android, though we need it for the upcoming MR3 lessons.

### PR DESCRIPTION
**Pull request by BenHenning**
Fix #3857

## Explanation

It was discovered during lesson import that a nerw classifier type was added for ratio input earlier in the year on web: HasSpecificTermEqualTo. The lesson content we want to ship in MR3 was very recently updated to make use of this classifier, so we needed to implement it (or nerf the lesson) in order to unblock MR3. Since introducing new classifiers is fairly streamlined, we decided to implement it as part of MR3.

Note that this work is not technically part of the other MR3-tied localization work, but it's part of its PR chain for easier management & merging.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

Note that this isn't actually a UI-specific PR, but a video has been included using real alpha content to demonstrate it working in a real scenario:

https://user-images.githubusercontent.com/12983742/135444327-122b3f5d-260a-43dc-aada-17b6b2b7f97d.mp4

The above feedback is based on the following state rule:

```textproto
        outcome {
          dest_state_name: "Research on best recipe"
          feedback {
            html: "<p>No, that\'s not correct. If you look at the ratio of milk to yogurt in your answer, it\'s not equivalent to 1:3.</p>\n\n<p>Take a careful look at Uncle Berry\'s explanation, and see if you can figure out what went wrong. Make sure you\'re working with a pencil and paper -- this can be a bit tricky to do in your head. You can do it!</p>"
            content_id: "feedback_10"
          }
        }
        rule_specs {
          input {
            key: "y"
            value {
              non_negative_int: 5
            }
          }
          input {
            key: "x"
            value {
              non_negative_int: 2
            }
          }
          rule_type: "HasSpecificTermEqualTo"
        }
      }
```

(i.e. it matches if the second component of the ratio contains '5' regardless of any other component).

Because this isn't actually a UI change, none of the other UI artifacts are included which are normally required for such changes per the PR template.

### CODE REVIEW

**Comment by BenHenning** [comment]
Reopening to force CI to fully restart (to avoid false passing CI check for base branch since it wasn't set when CI was kicked off).

**Comment by BenHenning** [comment]
@anandwana001 PTAL for review.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Comment by BenHenning** [comment]
Thanks @anandwana001!

**Pull request merged**
