### PR TITLE
Fix #3855: Removed Pinview thirdparty library

### LINKED ISSUE #3855: Remove Pinview thirdparty library.
Older implementation of Pin Verification UI was using PinView library `io_github_chaosleung_pinview`  which was not supporting RTL. To fix this we removed this library and created new UI as per the new mocks implemented in the PR #3684.

This library has to be removed from
```
BUILD.bazel
build.gradle
versions.bzl
```

Then update `maven_intall.json` file.

### PR DESCRIPTION
**Pull request by deepanshu731**
Fixes #3855 removed lib from build bazel,gradle and versions.bzl

### CODE REVIEW

**Comment by deepanshu731** [comment]
@BenHenning i have removed library from build.bazel and gradle and also from versions.bzl after that i removed dependencies from maven_install.json when i tried to repin dependencies its showing error running one into another(kind of loop)
Screenshot from 2021-12-14 11-16-07
following this i added maven_install.json attribute in workspace file and runned the command bazel run@unpinned_maven//:pin
Screenshot from 2021-12-14 11-16-26
but it shows to remove again the maven_install.json attribute and this goes in a continous loop. Can you help me out

**Comment by BenHenning** [comment]
@deepanshu731 I suggest reverting the changes to the maven_install.json file, then re-running the pin command to see if it regenerates correctly. If that doesn't work, you'll need to follow the step-by-step instructions that the error outputted in your screenshot.

**Comment by BenHenning** [comment]
Hi. As of today, some main reviewers have taken time off for the next few weeks, so it may take a little while before we can look at this PR. We appreciate your patience while some of our team members recharge. We'll be fully returning on 4 January 2021.

**Comment by deepanshu731** [comment]
> @deepanshu731 I suggest reverting the changes to the maven_install.json file, then re-running the pin command to see if it regenerates correctly. If that doesn't work, you'll need to follow the step-by-step instructions that the error outputted in your screenshot.

thanks @BenHenning maven dependencies got repinned but some CL checks are failing. can you help me out with that?

**Comment by BenHenning** [comment]
> > @deepanshu731 I suggest reverting the changes to the maven_install.json file, then re-running the pin command to see if it regenerates correctly. If that doesn't work, you'll need to follow the step-by-step instructions that the error outputted in your screenshot.
> 
> thanks @BenHenning maven dependencies got repinned but some CL checks are failing. can you help me out with that?

@deepanshu731 apologies for the late reply.

The Bazel failure is due to an incompatibility between the new dependency graph & the Proguard configuration. Here are the specific errors:
```
2021-12-31T07:04:36.1638303Z Warning: androidx.appcompat.widget.ActivityChooserView: can't find referenced method 'void saveAttributeDataForStyleable(android.content.Context,int[],android.util.AttributeSet,android.content.res.TypedArray,int,int)' in program class androidx.appcompat.widget.ActivityChooserView
2021-12-31T07:04:36.1644332Z Warning: androidx.appcompat.widget.ButtonBarLayout: can't find referenced method 'void saveAttributeDataForStyleable(android.content.Context,int[],android.util.AttributeSet,android.content.res.TypedArray,int,int)' in program class androidx.appcompat.widget.ButtonBarLayout
2021-12-31T07:04:36.1647507Z Warning: there were 2 unresolved references to program class members.
2021-12-31T07:04:36.1648331Z          Your input classes appear to be inconsistent.
2021-12-31T07:04:36.1649000Z          You may need to recompile the code.
2021-12-31T07:04:36.1650210Z          (http://proguard.sourceforge.net/manual/t
```

This is probably happening because removing the pinview library inadvertently downgraded appcompat (see https://github.com/oppia/oppia-android/pull/4041/files#diff-c6821e7e22305da601268ca77e90fa7b1d33be10fc8ea6746832d2c3a794d2feR14). I suggest updating appcompat in versions.bzl to 1.2.0 so that it doesn't get downgraded & see if it builds. To test locally, run:

```
bazel build //:oppia_android_alpha
```

(It'll probably take 10-15 minutes to build since it runs 3 Proguard optimization passes).

The Gradle failure seems like a flake, so after you fix the dependencies & restart CI I'd expect it to then pass.

**Comment by deepanshu731** [comment]
> > > @deepanshu731 I suggest reverting the changes to the maven_install.json file, then re-running the pin command to see if it regenerates correctly. If that doesn't work, you'll need to follow the step-by-step instructions that the error outputted in your screenshot.
> > 
> > 
> > thanks @BenHenning maven dependencies got repinned but some CL checks are failing. can you help me out with that?
> 
> @deepanshu731 apologies for the late reply.
> 
> The Bazel failure is due to an incompatibility between the new dependency graph & the Proguard configuration. Here are the specific errors:
> 
> ```
> 2021-12-31T07:04:36.1638303Z Warning: androidx.appcompat.widget.ActivityChooserView: can't find referenced method 'void saveAttributeDataForStyleable(android.content.Context,int[],android.util.AttributeSet,android.content.res.TypedArray,int,int)' in program class androidx.appcompat.widget.ActivityChooserView
> 2021-12-31T07:04:36.1644332Z Warning: androidx.appcompat.widget.ButtonBarLayout: can't find referenced method 'void saveAttributeDataForStyleable(android.content.Context,int[],android.util.AttributeSet,android.content.res.TypedArray,int,int)' in program class androidx.appcompat.widget.ButtonBarLayout
> 2021-12-31T07:04:36.1647507Z Warning: there were 2 unresolved references to program class members.
> 2021-12-31T07:04:36.1648331Z          Your input classes appear to be inconsistent.
> 2021-12-31T07:04:36.1649000Z          You may need to recompile the code.
> 2021-12-31T07:04:36.1650210Z          (http://proguard.sourceforge.net/manual/t
> ```
> 
> This is probably happening because removing the pinview library inadvertently downgraded appcompat (see https://github.com/oppia/oppia-android/pull/4041/files#diff-c6821e7e22305da601268ca77e90fa7b1d33be10fc8ea6746832d2c3a794d2feR14). I suggest updating appcompat in versions.bzl to 1.2.0 so that it doesn't get downgraded & see if it builds. To test locally, run:
> 
> ```
> bazel build //:oppia_android_alpha
> ```
> 
> (It'll probably take 10-15 minutes to build since it runs 3 Proguard optimization passes).
> 
> The Gradle failure seems like a flake, so after you fix the dependencies & restart CI I'd expect it to then pass.

thanks @BenHenning  PTAL

**Review by BenHenning — APPROVED** [review]
This LGTM @deepanshu731. Thanks again!

**Pull request merged**
