### PR TITLE
Fixes part of #1179: Hints & Solution - Tablet (Landscape) (Highfi)

### LINKED ISSUE #1179: Hints & Solution - Tablet (Landscape) (Highfi)
Mocks: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/cde3ce25-786f-41d6-b967-64b769602b71/L-Hint-Part-1-of-2-

Implement high-fi UI for **Hints & Solution** tablet landscape mode

**Target PR date**: 15 July 2020
**Target completion date**: 19 July 2020

### PR DESCRIPTION
**Pull request by MohamedMedhat1998**
## Explanation

- Implemented high-fi UI for **Hints&Solution** for landscape mode - tablet
- Fixes part of #1179 
- Mocks: [Hints](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/cde3ce25-786f-41d6-b967-64b769602b71/L-Hint-Part-1-of-4-) - [Solution](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/ea83c004-a220-48b7-8bff-dc228360ebae/L-Hint-Part-3-of-4-)
### 1024x768 Emulator
screenshot-2020-06-29_14 45 07 685
screenshot-2020-06-29_14 45 14 266
screenshot-2020-06-29_14 45 19 475
screenshot-2020-06-29_14 46 27 107
screenshot-2020-06-29_14 46 38 019
screenshot-2020-06-29_14 46 44 323
screenshot-2020-06-29_14 47 11 187
screenshot-2020-06-29_14 47 24 299
screenshot-2020-06-29_14 47 34 138
screenshot-2020-06-29_14 47 40 258

### 2560x1800 Emulator
screenshot-2020-06-29_15 13 05 238
screenshot-2020-06-29_15 13 13 258
screenshot-2020-06-29_15 13 26 953
screenshot-2020-06-29_15 14 25 642
screenshot-2020-06-29_15 14 37 705
screenshot-2020-06-29_15 14 48 706
screenshot-2020-06-29_15 15 09 945
screenshot-2020-06-29_15 15 24 273
screenshot-2020-06-29_15 15 39 361

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
LGTM, thanks.
You will need to add two animations to this screen:
1. Rotate animation on the arrow icon
2. Expand/contract animation on the content similar to the animation in this screen https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/294d3abd-c3d2-4c4b-80f2-1d211e2a69fd/TP-Lessons-All-Stories-Collpased- (In this mock you can click on arrow of second item to see how animation works).

You will need to create animation similar to that or something which looks nice like this.

Therefore rename the PR is `Fix part of #1179` so that the issue does not get closed. And confirm here whether this will be done in a separate PR of this PR itself.

**Review by rt4914 — CHANGES_REQUESTED** [review]
LGTM, thanks.
You will need to add two animations to this screen:
1. Rotate animation on the arrow icon
2. Expand/contract animation on the content similar to the animation in this screen https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/294d3abd-c3d2-4c4b-80f2-1d211e2a69fd/TP-Lessons-All-Stories-Collpased- (In this mock you can click on arrow of second item to see how animation works).

You will need to create animation similar to that or something which looks nice like this.

Therefore rename the PR is `Fix part of #1179` so that the issue does not get closed. And confirm here whether this will be done in a separate PR of this PR itself.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> LGTM, thanks.
> You will need to add two animations to this screen:
> 
>     1. Rotate animation on the arrow icon
> 
>     2. Expand/contract animation on the content similar to the animation in this screen https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/294d3abd-c3d2-4c4b-80f2-1d211e2a69fd/TP-Lessons-All-Stories-Collpased- (In this mock you can click on arrow of second item to see how animation works).
> 
> 
> You will need to create animation similar to that or something which looks nice like this.
> 
> Therefore rename the PR is `Fix part of #1179` so that the issue does not get closed. And confirm here whether this will be done in a separate PR of this PR itself.

As we discussed recently, the animation will be in a separate PR.  
@rt4914

**Review by rt4914 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
