### PR TITLE
[Sample PR]Fix #2260: Few tests using EditTextInputAction are freezing on Espresso [BLOCKED on #2289]

### LINKED ISSUE #2260: Few tests using EditTextInputAction are freezing on Espresso
**Describe the bug**
Some of the tests using `EditTextInputAction` are failing as the EditText is not getting focus and not able to set the text to it. All the tests are passing earlier but now they are failing.

**Expected behavior**
Need to investigate why they are failing now on Espresso. 

The possible solution is to perform all three actions click to get focus, set the text and close the keyboard. This solution works in most of the robolectric part as well. But need a few things to investigate.
```kotlin
.perform(click(), replaceText("1234"), closeSoftKeyboard())
```

1. How many tests are failing? Is it limited to only some screens or all the tests using `EditTextInputAction` are failing on espresso?
2. Need to find a better solution which sustains for a longer period and works on both Espresso and Robolectric. 

Files using `EditTextInputAction`
1. `QuestionPlayerActivityLocalTest` - Only Robolectric, all are passing
2. `ProfileRenameActivityTest` - 
3. `ProfileResetPinActivityTest` -

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #2260 

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
If things go correct with Migration to TextInputLayout then all the freezing test will get solved. Else we need to rely on fixing all the tests. 
https://github.com/oppia/oppia-android/pull/2265

**Comment by BenHenning** [comment]
Will comment on the bug for now since I'm unsure what to look at in the PR.

**Comment by anandwana001** [comment]
> Will comment on the bug for now since I'm unsure what to look at in the PR.

I might close this PR, once confirmed with the migration thing. The reviewer added due to code owners.

**Comment by anandwana001** [comment]
Closing this PR as it is fixed at https://github.com/oppia/oppia-android/pull/2300

**Pull request closed without merging**
