### PR TITLE
Fix #3534: Merge help_without_drawer_activity.xml into single xml file

### LINKED ISSUE #3534: Merge help_without_drawer_activity.xml into single xml file
Currently there are 2 versions of `help_without_drawer_activity.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

### PR DESCRIPTION
**Pull request by Akshatkamboj14**
## Explanation
 Fix #3534: Merge help_without_drawer_activity.xml into single xml file

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

| **After**  | **Before** |
| ------------- | ------------- |
| Screenshot_20220130_131952| Screenshot_20220130_131205 |
| Screenshot_20220130_132013  | Screenshot_20220130_131235 |
**Tablet**
| Screenshot_20220130_132122 | Screenshot_20220130_130934 |
| Screenshot_20220130_132140| Screenshot_20220130_131001 |

### CODE REVIEW

**Comment by Akshatkamboj14** [comment]
**_BEFORE_**

Screenshot_20220130_130934
Screenshot_20220130_131001
Screenshot_20220130_131205
Screenshot_20220130_131235



**_AFTER_**

Screenshot_20220130_131952
Screenshot_20220130_132013
Screenshot_20220130_132122
Screenshot_20220130_132140

**Comment by rishidyno** [comment]
Thanks @Akshatkamboj14 LGTM.

**Review by yash10019coder — CHANGES_REQUESTED** [review]
@Akshatkamboj14 arrange the ss in tabular form like this https://github.com/oppia/oppia-android/pull/3523 PR

**Comment by Akshatkamboj14** [comment]
@yash10019coder Done....

**Review by yash10019coder — COMMENTED** [review]
LGTM @Akshatkamboj14  thanks

**Comment by rishidyno** [comment]
@rt4914  Please approve the workflows. Thanks!

**Comment by rishidyno** [comment]
@Akshatkamboj14 Update the project and static check will pass

**Comment by rishidyno** [comment]
@rt4914 Now I understand why this was happening. Because he is 2 commits behind develop, so his code has `TODO`, but the issue is already closed.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
