### PR TITLE
Fix #4026, #4027, #4040, #4076, #4287, #4319, #4329: Fix miscellaneous bugs found while testing alpha MR4

### LINKED ISSUE #4026: Unable to move past a card in Chapter 6 (Fractions)
**Describe the bug**
Cannot go beyond a card in chapter 6 because there is no input method available for the user to enter their answer. The text is also illegible on this card.

**To Reproduce**
1. Go to Chapter 6 - Mixed Numbers and the Number line
2. Reach the card with the following question:
"What are fruit tarts?
1 ⅚
How many sixths of a cake are there in 2 ⅙
Which point on this number line represents 2 ¼ ?" 
3. Scroll down to input or continue button. Input box does not let the user type anything.

**Expected behavior**
There should some form of input method for the user to enter their answer and move to the next card.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
Screenshot_20211205-214452

**Environment**
- Device/emulator being used: Pixel 5
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.6-alpha-7ff1b2bbd2

**Additional context**
Video: https://drive.google.com/file/d/13bwKEotN7DXiw6HMX55C2r8_3xNFGDvh/view?usp=sharing

### LINKED ISSUE #4027: Image size too small or illegible
**Describe the bug**
The image sizes for most of the card with images is too small. 

**To Reproduce**
1. Go to all lessons in the app
4. See error in the cards with images

**Expected behavior**
Images should be clear and legible. Also some of them need to have a zoom in feature for better clarity and visibility.

**Demonstration**
Screenshots available in this drive folder: https://drive.google.com/drive/u/1/folders/1N1FClZIIwo4TT_pvuOlCW62CfoJfbW9s

**Environment**
- Device/emulator being used: Pixel 6 
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.6-alpha-7ff1b2bbd2

**Additional context**

### LINKED ISSUE #4040: Unable to access Admin profile and Admin Controls
**Describe the bug**
After entering the PIN to access the admin profile or admin controls, the app goes back to the profiles screen instead of the admin profile or admin controls screen. The PIN doesn't reset even after uninstalling and reinstalling the app. 

**To Reproduce**
1. Go to Admin profile
2. Enter the admin PIN and hit Submit
3. See error

**Expected behavior**
After entering the PIN the admin profile page or the admin controls page should be visible. 

**Demonstration**
https://drive.google.com/file/d/1cjjD9ub8P6UGPcDf2dxi55X2KEwWDW5n/view

**Environment**
- Device/emulator being used: Pixel 5
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.6-alpha-7ff1b2bbd2

**Additional context**

### LINKED ISSUE #4076: Continue button changes to a conversation message when going backwards in a chapter
**Describe the bug**
Continue button changes to a conversation message (color changes from green to white) that says 'Please continue' once the user goes backwards in a chapter. Please continue looks like a button but is not clickable. Right and left arrows also appear once gone backwards in a chapter for navigation in the lesson. It is confusing to the user whether to click the arrows or the please continue button-like message. 

**To Reproduce**
1. Go to any topic and a chapter in that topic
2. Go over 3 cards
3. Go to previous card
4. See 'Please continue' unclickable button-like message and 2 right and left arrows on the screen

**Expected behavior**
'Please Continue' button should not appear on the screen. Only the front and back arrows for navigation between the lessons are sufficient. 

**Demonstration**
image

**Environment**
- Device/emulator being used: Samsung Galaxy 8
- Android or SDK version (e.g. Android 5 or SDK 21): Android 9
- App version: 0.6-alpha-908d57b2b1

**Additional context**

### LINKED ISSUE #4287: Additional white box added to cards when navigating backwards
**Describe the bug**
When navigating backwards from the card where a question in answered by manual input, an extra white box appears on all cards above the forward arrow button

**To Reproduce**
1. Start an exploration and move forward through all cards till a question comes up which requires manual entry
2. Provide input to text field and press submit 
3. Navigate backwards using back arrow button
4. A white box appears on all cards above forward button. Clicking on the button produces no action.

**Expected behavior**
Such unnecessary elements may confuse the user, who would be confused if an input is required or it has some navigational function.

**Demonstration**
Find screenshots [here](https://docs.google.com/presentation/d/1BiKgarCERYHnbXF6LcU_gJkcFuFBQbnz7_v1UYm5zQg/edit?usp=sharing)

**Environment**
Device/emulator being used: Galaxy Tab S6 Lite / SM-P610
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version: 0.7-alpha-d1b2827517

### LINKED ISSUE #4319: Unable to complete the topic Addition & Subtraction, as chapter 4 is getting crashed while trying to complete it
**Describe the bug**
Unable to complete the topic Addition & Subtraction, as chapter 4 is getting crashed while trying to complete it

**To Reproduce**
1. Login as Admin
2. Go to 'Addition & Subtraction
3. Complete chapters 1,2,3
4. Try to complete chapter 4

**Expected behavior**
Admin should be able to complete chapter 4 to proceed further and complete the topic

Actual Result: 
While trying to complete chapter 4, it is getting auto closed and unable to complete the chapter. Hence unable to proceed further to complete other chapters

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

https://user-images.githubusercontent.com/101634267/165261038-f8bc7676-2f4b-4138-a4ef-dcb2b919cbec.mp4

### LINKED ISSUE #4329: Unable to complete chapter 'What is Division'
**Describe the bug**
Unable to complete chapter 'What is Division'

**To Reproduce**
1. Go to 'All Topics'
2. Click on 'Division'
3. Select Chapter 1 'What is Division'
4. Click on Continue until you get to the cookies question 
5. Enter 6/2 as answer and submit

**Expected behavior**
On giving 6/2 as answer it should display correct and continue button should be enabled

Actual behavior:
On entering 6/2 as answer, 'No, that's not correct' is displayed and unable to proceed further

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

Note: Working fine in web
Screenshot 2022-04-28 10 34 48 AM

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fixes #4026
Fixes #4027
Fixes #4040
Fixes #4076
Fixes #4287
Fixes #4319
Fixes #4329

This PR fixes a bunch of different issues, but specifically:
- It removes the 'Please continue' answer from being rendered for 'Continue' interaction states (plus fixes any cases where other answers are empty, though this shouldn't generally happen in practice).
- It fixes a bunch of image sizing and cut-off issues (explained in more detail below).
- It fixes #4040 (though, only for proto loading) for rare edge cases where topics change across app installs.
- #4026 (kind of): The fix is actually on a private repository branch, but it did unearth a long-standing issue with image region selection that caused answer submission to fail for certain image cases (also explained in more detail below).

### Image fixes
There are images below demonstrating some of the problems and what they look like with the fix in place.

There were three categories of issues that needed to be fixed:
1. The logic for cropping images wasn't set up to support certain parent layout types, so sometimes it just wasn't even activating.
2. Sizing images based on pixels is likely to result in problems since it means images will have different physical sizes depending on the device density. The workaround is to use dp (where we're now translating 1:1 from image pixels to dp). This is a reasonably medium-term workaround, but longer term we'll need to have a way to properly define dp for Android-supported images.
3. Both of the above didn't work for some SVGs because the dimensions were either not correct, or outright missing from the SVG file. This became complicated: we have at least three different places to source the image's dimensions: its filename (reported by Oppia web), its document tag in the SVG (which can omit these attributes), or the SVG's viewport dimensions (which is sometimes too large). Due to these complexities, the app now uses all three of these sizes as heuristics to compute a larger (by 50%) rendering space. It then renders the SVG into this space and uses pixel boundary finding to reduce the image to the smallest possible space that it can consume. This is very computationally (and sometimes memory) expensive, but it's set up such that Glide will cache the result so subsequent loads are much faster (and perform better since the images are now being rendered as bitmaps instead of pictures).

### Image region interaction issue
It's not entirely clear to me after investigating why this issue seems to affect alpha assets but not the local prototype exploration. Nevertheless, the problem is that image regions may not compute correctly when translated to views which makes the interaction impossible to get past (we didn't notice this before because the image itself wasn't being pulled in until #4026 was fixed). The reasonable workaround for the sizing issue was to ensure Android was explicitly told to relayout such that it would definitely recompute the region views' dimensions (https://stackoverflow.com/a/42430695/3689782 explains the flow in much more detail, and there's a detailed comment in ``ClickableAreasImage``).

### Notes on testing and verifications
I mostly focused on introducing regression tests for bugs that I could, but some aren't possible:
- Image region currently can't be tested in Robolectric, and it's difficult to test the race condition flows in Espresso (and very likely impossible to do so reliably).
- The image pipeline can't be tested due to the nature of how it integrates with Glide, and we don't have a solution to make it testable yet.
- ``AssetRepositoryImpl`` doesn't have a test suite, and I didn't want to add that in this PR due to many other priorities.

Beyond that, however, I did add tests for the other parts of the PR. I also verified that the new tests in both ``TopicListControllerTest`` and ``StateFragmentTest`` correctly failed without their corresponding fixes in place. Finally, I manually verified the continue button behavior, the crash, and image behaviors on the branch against develop to verify that the fixes are working as expected.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### Screenshots

| Images cut-off and/or too small (without fixes)  | Same images with the fixes from this PR. |
|---|---|
| image | image |
| image | image |
| image | image |

Images showing the change in continue button behavior:
| Previous behavior (showing 'continue' button answer) | New behavior (no answer is shown for 'continue') |
|---|---|
| image | image |

Note that I didn't add localization cases or the accessibility video since neither should be affected by the UI fixes introduced in this PR.

### Espresso test results
``StateFragmentTest`` results:
oppia_passing_state_fragment_test_misc_fixes

Note that I only ran ``StateFragmentTest`` on Espresso since:
- While questions is affected by the continue response change, questions never use this interaction.
- ``StateFragmentLocalTest`` wasn't updated directly (since the new tests went in ``StateFragmentTest``), and it was verified as passing on Robolectric (given it can't run on Espresso).

### CODE REVIEW

**Comment by BenHenning** [comment]
Issues this will fix:
- #4026 (kind of--the fix is technically in the script, but I'll explain it in this PR & attach it to the submission of this PR)
  - TODO: mention that this uncovered a long-standing issue with image region selection that needed to be fixed
- #4027 specifically:
  - Image cut offs due to incorrect margin calculations for block images within content text views
  - Image cut offs due to an issue in AndroidSVG (for SVGs missing a document size)
  - Image sizing (by ensuring block images are generally rendered using physical units instead of pixels)
- #4040
  - TODO: Mention this is only fixed for proto loading (since it doesn't seem necessary for the JSON pipeline as that's only used by developers)
-  #4076

#4076 isn't included yet, but will be in a follow-up commit.

Once these are all re-verified as implemented, I'll need to audit this PR and clean it up in terms of code layout, architecture, and readability. Then, tests will need to be added & the PR title/description finalized before this can be sent for review.

**Comment by BenHenning** [comment]
Still active.

**Comment by BenHenning** [comment]
@anandwana001 PTAL.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Comment by BenHenning** [comment]
Note that I plan to push more fixes to this branch, and additional tests. I'll re-request a review at that time.

**Comment by BenHenning** [comment]
Note that any additional changes needed in this PR will be covered in #4345 as a fast-follow.

Furthermore, @rt4914's reviews are being deferred (#4266 are tracking each, respectively) as discussed with him previously.

**Review by rt4914 — COMMENTED** [review]
LGTM Thanks.

**Pull request merged**
