### PR TITLE
Fix part #141: Hi-Fi Topic overview tab fragment

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR corresponds to final UI for Topic Overview tab

Mock
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/19cfbacf-854c-4c7d-8691-3b3d117e1866/TP-Overview-/

### Screenshot
image

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
LGTM, just use shortcut `Option+cmd+L` to reorganise.

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM.
@mschanteltc 
PTAL on the below accessibility test. 
screenshot_Oppia_2019-11-14-15_47_07.
Item descriptions
[40,96][449,163]
This non-clickable item's speakable text: "Second Test Topic" is identical to that of 1 other item(s).

If we remove the topic name from topic review screen this would get resolved ... Please suggest ...

**Comment by mschanteltc** [comment]
Can you clarify what this means? What is not passing the Accessibility Checker?

> [40,96][449,163]

We need the heading so users know what Topic they are viewing.

**Comment by nikitamarysolomanpvt** [comment]
> Can you clarify what this means? What is not passing the Accessibility Checker?
> 
> > [40,96][449,163]
> 
> We need the heading so users know what Topic they are viewing.

@mschanteltc 
Topic title (Second Test Topic) is repeated twice in the same screen so was suggested in the accessibility scanner to avoid this.

**Comment by mschanteltc** [comment]
@seanlip and I discussed this issue and despite the Topic name repeated twice, we should keep the design as it is. It's a minor issue and the title of the thumbnail gives clarity to the details and descriptions of the Lesson.

**Comment by seanlip** [comment]
@veena14cs and @nikitamarysolomanpvt, I have a question about this. I looked up the message and it seems like this is an "info" message, not an "error" / "warning". Could you please confirm this?

https://github.com/google/Accessibility-Test-Framework-for-Android/blob/master/src/main/java/com/google/android/apps/common/testing/accessibility/framework/checks/DuplicateSpeakableTextCheck.java#L41

If it's an info message, we can leave it as is. If it's an error/warning, this needs further discussion.

Thanks!

**Comment by veena14cs** [comment]
> @veena14cs and @nikitamarysolomanpvt, I have a question about this. I looked up the message and it seems like this is an "info" message, not an "error" / "warning". Could you please confirm this?
> 
> https://github.com/google/Accessibility-Test-Framework-for-Android/blob/master/src/main/java/com/google/android/apps/common/testing/accessibility/framework/checks/DuplicateSpeakableTextCheck.java#L41
> 
> If it's an info message, we can leave it as is. If it's an error/warning, this needs further discussion.
> 
> Thanks!

It was just a suggestion from scanner that, multiple items have same description. So we can ignore this. Thanks.

**Pull request merged**
