### PR TITLE
Fix #1382, #1340, #1341: Show a dialog when preloading assets for offline support

### LINKED ISSUE #1340: App crashes when entering exploration with voiceover data without internet connectivity
**Describe the bug**
The app crashes when opening an exploration that has audio voiceovers (e.g. "What is a Fraction?") when not connected to the internet.

**To Reproduce**
1. Disable wifi & cellular connectivity on the device
2. Open "What is a Fraction?"
3. Experience crash

**Expected behavior**
App should not crash.

**Screenshots**
oppia_app_crash_no_internet

**Device**
- Latest ``develop``
- Pixel XL
- SDK 29

**Additional context**
Here's the observed stack trace:

```
2020-06-17 10:20:46.452 9808-10180/org.oppia.app W/JMediaDataSource-JNI: java.net.UnknownHostException: Unable to resolve host "storage.googleapis.com": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        at com.android.okhttp.Dns$1.lookup(Dns.java:41)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at java.net.URL.openStream(URL.java:1072)
        at org.oppia.util.caching.AssetRepository.openRemoteStream(AssetRepository.kt:74)
        at org.oppia.util.caching.AssetRepository.openCachingStreamToRemoteFile(AssetRepository.kt:79)
        at org.oppia.util.caching.AssetRepository.access$openCachingStreamToRemoteFile(AssetRepository.kt:23)
        at org.oppia.util.caching.AssetRepository$loadRemoteBinaryAsset$1.invoke(AssetRepository.kt:58)
        at org.oppia.util.caching.AssetRepository$loadRemoteBinaryAsset$1.invoke(AssetRepository.kt:23)
        at org.oppia.domain.audio.AudioPlayerController$prepareDataSource$mediaDataSource$1$audioFileBuffer$2.invoke(AudioPlayerController.kt:157)
        at org.oppia.domain.audio.AudioPlayerController$prepareDataSource$mediaDataSource$1$audioFileBuffer$2.invoke(AudioPlayerController.kt:153)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.oppia.domain.audio.AudioPlayerController$prepareDataSource$mediaDataSource$1.getAudioFileBuffer(Unknown Source:7)
        at org.oppia.domain.audio.AudioPlayerController$prepareDataSource$mediaDataSource$1.readAt(AudioPlayerController.kt:164)
```

It seems that although the media for audio voiceovers are being loaded on a background thread, that thread isn't resilient to exceptions being thrown. While we can probably make this more robust, this seems like a regression: we shouldn't be loading audio right when the exploration is opened. It should only be loaded when we start playing audio, and that should be guarded by an internet connectivity check.

### LINKED ISSUE #1341: Audio fragment can guarantee a crash if loading audio fails
In cases when audio fails, leaving an exploration will trigger a crash. This can be reproed by getting the app into a bad state similar to https://github.com/oppia/oppia-android/issues/1340 (e.g. disabling internet connectivity and then navigating back from the exploration player). The following crash occurs:

```
2020-06-17 12:29:45.755 22593-22593/org.oppia.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.app, PID: 22593
    java.lang.RuntimeException: Unable to stop activity {org.oppia.app/org.oppia.app.player.exploration.ExplorationActivity}: java.lang.IllegalStateException: Media Player not in a prepared state
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4624)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4594)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4669)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: Media Player not in a prepared state
        at org.oppia.domain.audio.AudioPlayerController.pause(AudioPlayerController.kt:214)
        at org.oppia.app.player.audio.AudioViewModel.pauseAudio(AudioViewModel.kt:119)
        at org.oppia.app.player.audio.AudioFragmentPresenter.handleOnStop(AudioFragmentPresenter.kt:161)
        at org.oppia.app.player.audio.AudioFragment.onStop(AudioFragment.kt:57)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2891)
        at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:357)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1256)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2833)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2884)
        at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:357)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1256)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2833)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2884)
        at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:357)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1256)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2833)
        at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:291)
        at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:563)
        at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:207)
2020-06-17 12:29:45.755 22593-22593/org.oppia.app E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1473)
        at android.app.Activity.performStop(Activity.java:8018)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4616)
        	... 13 more
```

### LINKED ISSUE #1382: Show confirmation when all assets have been pre-downloaded
We should show a brief confirmation after all automatically downloaded assets have finished in the pre-alpha. This should only show if caching is enabled.

### PR DESCRIPTION
**Pull request by BenHenning**
Fix #1382
Fix #1340
Fix #1341

Show a dialog when preloading assets for offline support.

### Test instructions

1. Check out this branch locally
1. Enable local file caching by setting this boolean to true: https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/util/caching/CachingModule.kt#L11.
1. If the app is already installed on your device/emulator, go into app settings and clear storage (not just cache)
1. Build & install the app
1. Open the app--the dialog should appear

### Expanded description

This does a bunch of refactoring & hacky workarounds to keep asset priming support fully isolated (just a few files now need to be deleted to clean things up). This also:

1. Fixes actual asset downloading (the GCS asset path templates have changed, so priming didn't actually work anymore).
2. Disables audio file caching since we can't play audio when offline, anyway (there's a dialog that prevents this in-player).
3. Fixes #1340 and #1341 by accounting for error cases when trying to play audio. It turns out that playing audio crashes if you didn't have internet access when going into an exploration (the no connectivity dialog only appears if you lose connectivity within a lesson). There's also some issues with existing view model code that wrongly assumed audio couldn't be in a failure state at that point. This has been fixed.
4. Moves the list of topics to cache to be in the same position as the flag enabling/disabling this functionality.

The download experience isn't perfect, but it's meant to be a helper for user study coordinators so that they know when lessons can be brought offline.

Note that the UI aspects of this change are really hacky. This is by design--I didn't want to overcomplicate the solution, and I wanted to keep the priming changes fully isolated to make future cleanup easier.

Finally, no new tests were added. I clarified in StateFragmentTest that the audio edge cases fixed in this PR need to have corresponding tests, but I'm actually not sure offhand how to test that audio's playing. I think this will require additional work. I prefer to push this off to #388, but I will follow up with tests if anyone wants to push back on this. I'm also not inclined to test the priming behavior since that's meant to be temporary, and is turned off except for alpha (at which point I will retest the behavior before uploading it to the play store).

UI screen recording (happy path):
priming_support

UI screen recording (failure):
priming_failed

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
@BenHenning 
I tried to run the app in following scenarios but I was not able to see the dialog and the app works as before without any changes.
1. Uninstall the app and run the app, with and without internet both. 
2. Created a new emulator and run the app, with and without internet both. 

So are there any specific steps that we will need to do to test this? I was not able to find any specific step in description.

**Comment by BenHenning** [comment]
Thanks for bringing that up @rt4914, I forgot to include instructions. I added them to the PR description, PTAL.

**Review by rt4914 — APPROVED** [review]
Checked again as per your instructions and it does work correctly. Thanks
Also, PTAL at the github actions.

**Comment by BenHenning** [comment]
Thanks @rt4914. Just pushed some changes to fix the tests & CI.

**Comment by BenHenning** [comment]
Looks like everything is passing now. Merging.

**Pull request merged**
