### PR TITLE
Fix #4527: FAQ Inappropriate faqs removed

### LINKED ISSUE #4527: Improper sentence framing is observed in FAQs
**Describe the bug**
Improper sentence framing is observed in FAQs 

**To Reproduce**
1. Go to 'Home' - Click on menu - Select Help
2. Click on 'FAQs'
3. Select How can I change my email/phone number?
4. See steps to change phone number

**Expected behavior**
'If you want to change your phone number' should be seen instead of 'If changing your phone number'

**Demonstration**

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

### PR DESCRIPTION
**Pull request by Rd4dev**
## Explanation

Fixes #4527

The [design team](https://github.com/oppia/design-team/issues/75) and the previous [PRs](https://github.com/oppia/oppia-android/pull/5247) addressed various issues and revised the FAQ list. However, @seanlip pointed out in the [discussions](https://github.com/oppia/design-team/issues/75#issuecomment-1584180125) that the FAQ related to updating mobile numbers or email addresses appears inappropriate. 

After verifying with @adhiamboperes and @BenHenning, the initial commit includes removing [that specific FAQ](https://github.com/oppia/oppia-android/blob/3ced7e14a8bff8c3757ed15a1626b0e63c6ce14d/app/src/main/res/values/strings.xml#L574)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by Rd4dev** [comment]
@adhiamboperes PTAL, Additionally, multiple translation strings are disorganized, for example, In the [FAQ questions](https://github.com/oppia/oppia-android/blob/3ced7e14a8bff8c3757ed15a1626b0e63c6ce14d/app/src/main/res/values-pcm-rNG/strings.xml#L510) 1, 2, 6, 7 and 4, 5, 8, 9 are repeated, followed by several other FAQs in the translations. Should this pull request also address those issues? While I may not possess expertise in all languages, I can use Google Translate to address them and include them in this pull request if deemed appropriate.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks for the careful audit @Rd4dev!

About the duplicate translations, I think this was an error caused by translate wiki conflicts in:
https://github.com/oppia/oppia-android/pull/5258 after manual update in: https://github.com/oppia/oppia-android/pull/5247.

I think you could try to fix this, but instead of using google translate, you can find the value of the translation as it originally was in #5247.

To make sure that translate wiki does not  overwrite your changes, add the `fuzzy=true `attribute to the translations that need to be reverified after your changes.

Finally, please edit your PR title to include the issue number.

**Comment by Rd4dev** [comment]
Thank you for the reference and guidance, @adhiamboperes. I noticed that the duplicate questions seemed to act as placeholders for the new FAQs introduced through the [Translation PR](https://github.com/oppia/oppia-android/pull/5258), and unfortunately, these new FAQs don't have translations in the linked [FAQ Updation PR](https://github.com/oppia/oppia-android/pull/5247). 

I tried to translate the new FAQs that were not available, incorporating the rest from the existing translations. If you feel the translations should not have been done, I'll promptly revert the related commits. Alternatively, if it's acceptable, I'll keep them.

Furthermore, I've appended the `fuzzy="true"` attribute to every translated string and integrated the issue number into the title (Will ensure to consistently include the issue number in the future pull requests). -- PTAL.

**Review by adhiamboperes — APPROVED** [review]
Thanks @Rd4dev. This is quite thorough.

**Pull request merged**
