### PR TITLE
Fix #2749: Fixes Home Card UI

### LINKED ISSUE #2749: Home Topic Card UI Regression
The Home screen topic cards look weird in various devices and that's because of following reasons:
1. Span count is not dynamic.
2. If the extreme end margins of the screen is large then it's because of span count and the cards look really bad. Because span count divides the entire screen in equal parts.
3. We have to keep the inner margins consistent too which is not easy with span count.

Overall we are keeping the extreme margins and span count constant and the width of the topic cards is dynamic and the inner margins are dynamic. Because of all these conditions the UI looks bad.

## Some References:
https://drive.google.com/drive/folders/1SLQVZD5FSJoZASWwpLNrkC_InQiq_61t?usp=sharing
Nexus 7 Device:

### PR DESCRIPTION
**Pull request by theMr17**
## Explanation

Fixes #2749

Modifies margin and padding values

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### 1920 x 1200
|Before|After|
|--|--|
|1920 x 1200 port before|1920 x 1200 port after|
|1920 x 1200 before|1920 x 1200 after|

### 2560 x 1800
|Before|After|
|--|--|
|2560 x 1800 port before|2560 x 1800 port after|
|2560 x 1800 before|2560 x 1800 after|

### 1024 x 600
|Before|After|
|--|--|
|1024 x 600 before|1024 x 600 after|

## Phone Screenshots

|dpi|Screenshots|
|--|--|
|ldpi|image|
|mdpi|image|
|hdpi|image|
|xhdpi|imageimage|
|xxhdpi|imageimage|

### CODE REVIEW

**Comment by adhiamboperes** [comment]
@BenHenning, I'm not really sure what solution is required for this issue... a recalculation or margin adjustments?

**Review by adhiamboperes — COMMENTED** [review]
@theMr17, the issue [linked screenshots](https://drive.google.com/drive/folders/1SLQVZD5FSJoZASWwpLNrkC_InQiq_61t) from different tablet devices. It would be nice to create comparable ones after your final solutions, to show that the screen displays okay in devices where it was previously distorted.

**Comment by BenHenning** [comment]
@adhiamboperes I left a comment in #2749 to try and provide more clarity. Please let me know if additional info is needed.

**Comment by adhiamboperes** [comment]
> @adhiamboperes I left a comment in #2749 to try and provide more clarity. Please let me know if additional info is needed.

Thanks @BenHenning, @theMr17, let's pick up this discussion on the issue thread.

**Comment by theMr17** [comment]
As per Ben's [comment](https://github.com/oppia/oppia-android/issues/2749#issuecomment-1776284512), I revisited the tile sizes across device configurations. I have made the necessary changes with the tile sizes by adjusting the margin and padding values. I have also added screenshots for different tablet devices above, @adhiamboperes PTAL.

**Comment by adhiamboperes** [comment]
@theMr17 I added a comment on the issue https://github.com/oppia/oppia-android/issues/2749 to help make sure we solve this fully.

**Comment by theMr17** [comment]
@adhiamboperes PTAL, I have updated the PR description with different dpi phone screenshots.

**Comment by adhiamboperes** [comment]
I think this needs veryfying with prod assets that everything looks good. ETA tomorrow(Tue/23).

**Review by adhiamboperes — APPROVED** [review]
Thanks @theMr17! I think per https://github.com/oppia/oppia-android/issues/2749#issuecomment-1841063066, the latest screenshots look sufficiently good to solve this issue.

**Pull request merged**
