### PR TITLE
Fix #2718: Resolve ktlint max line in DragDropTestActivity

### LINKED ISSUE #2718: Resolve ktlint max line in DragDropTestActivity
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name.
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the line of code under 100 char length.

Where to start?
1. Complete all installation steps before starting with this issue - https://github.com/oppia/oppia-android/wiki#installation
2. 
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/main/java/org/oppia/android/app/testing/DragDropTestActivity.kt#L11

Possible fix for this issue
```kotlin
class DragDropTestActivity :
  InjectableAppCompatActivity(),
  OnItemDragListener,
  OnDragEndedListener {
```

### PR DESCRIPTION
**Pull request by yashraj-01**
## Explanation

Fixes #2718 . Resolved ktlint max line in DragDropTestActivity.
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by yashraj-01** [comment]
@anandwana001 PTAL.

**Comment by yashraj-01** [comment]
@anandwana001 @rt4914 I donot understand why one of the tests is failing. A similar situation is there in my another PR #2700. Please help me understand it.

**Comment by FareesHussain** [comment]
> @anandwana001 @rt4914 I donot understand why one of the tests is failing. A similar situation is there in my another PR #2700. Please help me understand it.

It is a flaky test.

**Comment by yashraj-01** [comment]
> > @anandwana001 @rt4914 I donot understand why one of the tests is failing. A similar situation is there in my another PR #2700. Please help me understand it.
> 
> It is a flaky test.

Okay. Thanks.

**Comment by yashraj-01** [comment]
@FareesHussain I know you already clarified my doubt but I need one more help. The failing test has **Non-Flaky** written inside brackets. Is it also a flaky test? This question is related to PR #2700 .

**Comment by FareesHussain** [comment]
> @FareesHussain I know you already clarified my doubt but I need one more help. The failing test has **Non-Flaky** written inside brackets. Is it also a flaky test? This question is related to PR #2700 .

It seems the running tests were crashed in the workfow
It just needs to be re-run.

**Comment by yashraj-01** [comment]
> > @FareesHussain I know you already clarified my doubt but I need one more help. The failing test has **Non-Flaky** written inside brackets. Is it also a flaky test? This question is related to PR #2700 .
> 
> It seems the running tests were crashed in the workfow
> It just needs to be re-run.

Thanks a lot for the clarification.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @yashraj-iitr

**Pull request merged**
