### PR TITLE
Fix #122: Introduce interface & partial implementation for ExplorationProgressController

### LINKED ISSUE #122: Introduce interface for ExplorationProgressController
This is tracking introducing a stubbed interface for #115 without the real implementation being complete.

### PR DESCRIPTION
**Pull request by BenHenning**
Introduce mostly complete implementation for ExplorationProgressController.

Other high-level changes that were done as part of this introduction:
1. ExplorationDataController has been refactored such that both the data and progress controllers now depend on a new ExplorationRetriever for actually loading an exploration. These are still temporary objects and not loading from production Oppia. However, this clean separation allows the data controller to be used in a few different ways.
2. AnswerClassificationController has been updated to perform more relevant classification for the two explorations ExplorationRetriever supports loading. These should be correct, but it's still not fully fleshed out classification.

Regarding the actual interface, much of the interface is asynchronous and requires observing both the result of operations like moveToNextState/moveToPreviousState and the result from getCurrentState to have the full picture of what's going on. UIs are expected to rely on getCurrentState for rendering the current UI, and observe the results of moveToNextState/moveToPreviousState/submitAnswer to ensure these each succeeded. Future iterations of ExplorationProgressController will perform all operations on a background thread to improve perceived UI performance.

Starting/stopping an exploration is done via ExplorationDataController rather than ExplorationProgressController. In this way, only in-exploration fragments like StateFragment actually need to observe the progress controller. Fragments transitioning to the in-exploration experience can begin the play using ExplorationDataController. Any other fragment that just needs to retrieve data about an exploration only needs to rely on ExplorationDataController. This hopefully simplifies which controllers are used when, even though the split functionality is a bit different than other controllers.

Much of ExplorationProgressController's implementation is set up to make it really difficult for future changes or incorrect use of the controller from resulting in a broken experience. The interface is robust against failures as well: trying to break the controller state will result in an error that the UI should address.

Finally, see #199 for a really brief sample of integrating with ExplorationProgressController. Note that this sample does not include answer submission due to much more UI work being needed, nor state navigation since that is precluded by the lack of answer submission.

### CODE REVIEW

**Comment by BenHenning** [comment]
FYI @rt4914 & @veena14cs this is probably ready now to branch off of for a mostly functioning exploration UI experience. There might be some issues since I haven't written tests yet to verify correctness. Also note that the different feedback/content bits don't have interesting HTML, but if you'd like me to add something specific just let me know.

**Comment by rt4914** [comment]
> FYI @rt4914 & @veena14cs this is probably ready now to branch off of for a mostly functioning exploration UI experience. There might be some issues since I haven't written tests yet to verify correctness. Also note that the different feedback/content bits don't have interesting HTML, but if you'd like me to add something specific just let me know.

Thanks a lot @BenHenning . Based on this branch I will updated my code in `exploration-player-continue-end-button-2` branch

**Comment by rt4914** [comment]
@BenHenning Please update this PR with latest `develop`

**Comment by veena14cs** [comment]
> FYI @rt4914 & @veena14cs this is probably ready now to branch off of for a mostly functioning exploration UI experience. There might be some issues since I haven't written tests yet to verify correctness. Also note that the different feedback/content bits don't have interesting HTML, but if you'd like me to add something specific just let me know.

Thanks @BenHenning. I will update my code in Content card  based on this branch

**Comment by BenHenning** [comment]
Hoping this unblocks you @rt4914 & others. I updated to the latest develop.

This also includes a new internal locking mechanism that revealed issues in our LiveData interop solution. #90 is the real fix, but we'll need to live with a less-performant solution in the meantime. Either way, the interface has changed a bit with the controller. Please let me know if you have any issues while working off this branch.

**Comment by BenHenning** [comment]
This is now ready for review. @rt4914 and @jamesxu0 I'd like you both to fully review this. @veena14cs & @vinitamurthi it'd be great if you could both take glances if time permitting.

**Review by jamesxu0 — APPROVED** [review]
LGTM

**Review by rt4914 — APPROVED** [review]
LGTM

**Review by vinitamurthi — APPROVED** [review]

**Comment by BenHenning** [comment]
Thanks all!

**Pull request merged**
