### PR TITLE
Fix #798: Hifi admin controls

### LINKED ISSUE #798: Hifi: Admin Controls
`AdminControls` needs to be pixel perfect with the mocks.
Portrait Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/54511d86-eeca-4bf9-a891-22c0a6aa9a08/PC-MP-Admin-Controls-
Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/e740e866-d87a-4115-9a05-9b4f788dbc92/RG-MN-Register-Empty-30/

Mocks have been created for HDPI Devices.
Make sure that the screen passes the accessibility test also.
For reference you can checkout: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by Luffy18346**
## Explanation
Fix #798 Hifi Admin Controls Activity

## Mocks

Portrait Mock: 
https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/54511d86-eeca-4bf9-a891-22c0a6aa9a08/PC-MP-Admin-Controls-
Landscape Mock: 
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/e740e866-d87a-4115-9a05-9b4f788dbc92/RG-MN-Register-Empty-30/

## Screenshots

Screenshot_2020-03-15-10-27-58-04_092c5771dc9bb06bcb5e5b6a9dadbf56

Screenshot_2020-03-15-10-28-03-67_092c5771dc9bb06bcb5e5b6a9dadbf56

Screenshot_2020-03-15-10-38-14-77_092c5771dc9bb06bcb5e5b6a9dadbf56
Screenshot_2020-03-15-10-38-22-37_092c5771dc9bb06bcb5e5b6a9dadbf56
Screenshot_2020-03-15-10-38-30-88_092c5771dc9bb06bcb5e5b6a9dadbf56
Screenshot_2020-03-15-10-38-35-61_092c5771dc9bb06bcb5e5b6a9dadbf56

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Luffy18346** [comment]
Screenshot_2020-03-15-10-27-58-04_092c5771dc9bb06bcb5e5b6a9dadbf56

Screenshot_2020-03-15-10-28-03-67_092c5771dc9bb06bcb5e5b6a9dadbf56

**Comment by Luffy18346** [comment]
Screenshot_2020-03-15-10-38-14-77_092c5771dc9bb06bcb5e5b6a9dadbf56
Screenshot_2020-03-15-10-38-22-37_092c5771dc9bb06bcb5e5b6a9dadbf56
Screenshot_2020-03-15-10-38-30-88_092c5771dc9bb06bcb5e5b6a9dadbf56
Screenshot_2020-03-15-10-38-35-61_092c5771dc9bb06bcb5e5b6a9dadbf56

**Comment by rt4914** [comment]
@Luffy18346 In Highfi based PRs always put mock links in description.

**Comment by Luffy18346** [comment]
> @Luffy18346 In Highfi based PRs always put mock links in description.

Ok done.

**Comment by nikitamarysolomanpvt** [comment]
@Luffy18346 Please change all padding/spacing attributes right and left to start and end i.e. paddingLeft to paddingStart .

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Pull request merged**
