### PR TITLE
Fix #1957: Optimise code in profile_chooser_profile_view.xml

### LINKED ISSUE #1957: Optimise code in profile_chooser_profile_view.xml
This issue is tracking the optimization work of `profile_chooser_profile_view.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all TextViews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be the same as before (or an optimized version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by peculiaruc**
## Explanation
Fixes #1957: Flatten the view hierarchy to use ConstraintLayout and minimal nesting of views and made sure that all TextViews uses the style from styles.xml

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by peculiaruc** [comment]
@rt4914 PTAL

**Comment by anandwana001** [comment]
Few initial points:
1. PR Title `Fix #bugnum: Optimise code in profile_chooser_profile_view.xml`
2. The issue specified in the PR description is already closed. Please correct the issue number.
3. Always do `Reformat Code` from the menu toolbar. Our Wiki Guide - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

**Comment by peculiaruc** [comment]
@anandwana001 I have treated 1 & 2. Implemented 3 before pushing but let me do that again

**Comment by peculiaruc** [comment]
Done.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@peculiaruc Thanks for the PR.

The changes in this PR does not match with previous implementation.
Screenshot_1604411501
Screenshot_1604411530
Screenshot_1604411535



The best way to test such PRs is by comparing screenshots.
1. In latest develop, take screenshots under various circumstances for mobile+tablet in landscape and portrait orientation.
2. Then apply your changes and in your branch, re-run the app and take screenshots in similar circumstances for mobile+tablet in landscape and portrait orientation.
3. Now compare these screenshots and you will find the issues.

Thanks.

**Comment by rt4914** [comment]
Also couple of points related to PR:

1. Your branch name should be all-small characters. Like: `optimise_profile_chooser_profile_view_codes`
2. Please use `Assignees` and `Reviewers` section from now on in your PRs. https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

**Comment by peculiaruc** [comment]
> @peculiaruc Thanks for the PR.
> 
> The changes in this PR does not match with previous implementation.
> Screenshot_1604411501
> Screenshot_1604411530
> Screenshot_1604411535
> 
> The best way to test such PRs is by comparing screenshots.
> 
> 1. In latest develop, take screenshots under various circumstances for mobile+tablet in landscape and portrait orientation.
> 2. Then apply your changes and in your branch, re-run the app and take screenshots in similar circumstances for mobile+tablet in landscape and portrait orientation.
> 3. Now compare these screenshots and you will find the issues.
> 
> Thanks.

Noted. Thanks

**Comment by peculiaruc** [comment]
> Also couple of points related to PR:
> 
> 1. Your branch name should be all-small characters. Like: `optimise_profile_chooser_profile_view_codes`
> 2. Please use `Assignees` and `Reviewers` section from now on in your PRs. https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

Done.

@rt4914 PTAL at PR #2089, I updated my branch name for PR #2068, As I push my code it automatically asked for a new PR. Hope that's okay.

**Comment by rt4914** [comment]
@peculiaruc you can close this PR if not needed.

**Comment by peculiaruc** [comment]
> @peculiaruc you can close this PR if not needed.

Done

**Pull request closed without merging**
