### PR TITLE
Fix #3059: Create test for image view binding adapters

### LINKED ISSUE #3059: Add tests for BindableAdapters in  ImageViewBindingAdapters
### Is your feature request related to a problem? Please describe.

Currently, [ImageViewBindingAdaptersTest](https://github.com/oppia/oppia-android/blob/3ffeedf7e90795ae9b23ec600a19d7cff72f1ca4/app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt#L101) only contains tests for one bindable adapter:

```java
@BindingAdapter("playStateImage")
public static void setPlayStateDrawable(
    @NonNull ImageView imageView,
    ChapterPlayState chapterPlayState
)
```

However, other bindable adapters defined in [ImageViewBindingAdapters](https://github.com/oppia/oppia-android/blob/3ffeedf7e90795ae9b23ec600a19d7cff72f1ca4/app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java#L19) are not yet tested. This results in incomplete coverage and may allow regressions in critical UI logic.

### Describe the solution you'd like

We should expand `ImageViewBindingAdaptersTest` to include dedicated tests for **all bindable adapters in `ImageViewBindingAdapters`**. Each test should verify that the binding adapters behave as expected under different inputs, using Espresso matchers and Robolectric where applicable.

### Tasks / Checklist

Add new tests for the following bindable adapters:

1. **`setImageDrawableCompat(ImageView, @DrawableRes int)`**

     - Verify that the correct drawable resource is set on the `ImageView`.

2. **`setImageDrawableCompat(ImageView, Drawable)`**

     - Verify that a provided `Drawable` object is applied correctly.

3. **`setProfileImage(ImageView, ProfileAvatar)`**

     - Test behavior for `AVATAR_COLOR_RGB` → default avatar with color filter applied.
     - Test behavior for `AVATAR_IMAGE_URI` → correct image loaded with placeholder.
     - Test null `ProfileAvatar` case → `ImageView` should not crash and fallback gracefully.

4. **`setTint(ImageView, int)`**

     - Verify that the correct color filter is applied to the `ImageView`.

5. **`setPlayStateDrawable(ImageView, ChapterPlayState)`**

     - Already partially tested, but ensure coverage for all possible `ChapterPlayState` values.
     - Validate that the fallback/default drawable is correctly applied when no match is found.

### Acceptance Criteria

* All bindable adapters in `ImageViewBindingAdapters` have at least one dedicated test.
* Both **positive paths** (correct input) and **edge cases** (nulls, unexpected values) are covered.
* Tests follow the existing style of `ImageViewBindingAdaptersTest` (using `runWithLaunchedActivity`, Espresso matchers like `withDrawable`, etc.).

### PR Submission Directions

* Add the new test cases in `ImageViewBindingAdaptersTest`.
* Include screenshot of the passing tests.
* Ensure all tests run successfully with `bazel test` and pass static checks (`ktlint`, `oppiaCheck`).

### PR DESCRIPTION
**Pull request by yash10019coder**
## Explanation

Fixes #3059 
Added tests for bindable adapters in ImageViewBindingAdapters
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by yash10019coder** [comment]
@rt4914 @anandwana001 @BenHenning wrote a test case is it correct

**Comment by anandwana001** [comment]
@veena14cs Could you take a lead here, as this is similar to what you had worked on earlier as per our discussion.

**Comment by anandwana001** [comment]
@yash10019coder Please follow this guide - https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

**Comment by yash10019coder** [comment]
@anandwana001 made a commit and added a custom drawable now when I try to run the test I get this error
image
`java.lang.ClassCastException: android.graphics.drawable.GradientDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
at org.oppia.android.app.databinding.ImageViewBindingAdaptersTest$drawableIsCorrect$1.matchesSafely(ImageViewBindingAdaptersTest.kt:137)
at org.oppia.android.app.databinding.ImageViewBindingAdaptersTest$drawableIsCorrect$1.matchesSafely(ImageViewBindingAdaptersTest.kt:121)
at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:527)
at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:105)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:425)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:288)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:272)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`
please help

**Comment by veena14cs** [comment]
> @anandwana001 made a commit and added a custom drawable now when I try to run the test I get this error
> image
> `java.lang.ClassCastException: android.graphics.drawable.GradientDrawable cannot be cast to android.graphics.drawable.BitmapDrawable at org.oppia.android.app.databinding.ImageViewBindingAdaptersTest$drawableIsCorrect$1.matchesSafely(ImageViewBindingAdaptersTest.kt:137) at org.oppia.android.app.databinding.ImageViewBindingAdaptersTest$drawableIsCorrect$1.matchesSafely(ImageViewBindingAdaptersTest.kt:121) at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65) at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:527) at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:105) at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:425) at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:288) at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:272) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:193) at android.app.ActivityThread.main(ActivityThread.java:6669) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `
> please help

Can you try using withDrawable() from EspressoTestsMatchers to compare drawables.
for ex: 
```
onView(withId(R.id.imageView))
      .check(matches(EspressoTestsMatchers.withDrawable(R.drawable.bg_blue_card)))
```

**Comment by veena14cs** [comment]
I suggest once you are ready with your PR add reviewers in Reviewer section and assignes in Assignes section whom you want the PR to be reviewed.

**Comment by yash10019coder** [comment]
@veena14cs I have made a commit I tried it and now I get another error
image
`java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
at org.oppia.android.app.utility.DrawableMatcher.getBitmap(DrawableMatcher.kt:47)
at org.oppia.android.app.utility.DrawableMatcher.matchesSafely(DrawableMatcher.kt:41)
at org.oppia.android.app.utility.DrawableMatcher.matchesSafely(DrawableMatcher.kt:13)
at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:527)
at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:105)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:425)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:288)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:272)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Pull request closed without merging**
