### PR TITLE
Fix #2768: Removed voiceover_java_proto_lite from the list of exports in the model library 

### LINKED ISSUE #2768: Remove :voiceover_java_proto_lite from the list of exports in the model library
This task is part of the build system migration from Gradle to Bazel. A prerequesite before working on this issue is that you are able to build Oppia using Bazel. Check out [Oppia Bazel guide](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Guide) for Bazel terminology and more on what Bazel does.

## 1. Remove the export

In 

`/oppia-android/model/BUILD.bazel`

Remove :voiceover_java_proto_lite from the list of exports in the model library

```BUILD
android_library(
    name = "model",
    visibility = ["//visibility:public"],
    exports = [
        ... # <- Remove it from this list.
    ],
)
```

## 2. Add public visibility to the java_lite_proto_library

Add 

`    visibility = ["//visibility:public"],`

to the java_lite_proto_library that has the name voiceover_java_proto_lite.

## 3. Build the app using Bazel and run the tests

Libraries that are indirectly depending on `voiceover_java_proto_lite` will now fail to build. Try to build the entire app with Bazel and add the deps dependency

`//model:voiceover_java_proto_lite,`

to all the libraries that are now failing to build. You will have to look around for BUILD.bazel files that have libraries that require this replaced dependency.

These libraries will already have the //model dependency and since we removed the :voiceover_java_proto_lite from the model library itself, they will need to add the newly available public library directly as a dependency. (Not all libraries with the //model dependency may require the newly available library)

Once the app builds and all tests pass, you're done!

### PR DESCRIPTION
**Pull request by Karanjot-singh**
## Explanation

 Fixes #2768: Removed voiceover_java_proto_lite from the list of exports in the model library 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Karanjot-singh** [comment]
PTAL @prayutsu The Bazel build was successful with the above changes

**Comment by Karanjot-singh** [comment]
Since the develop branch had recent pushes, I performed a rebase to ensure everything is up-to-date with "develop"

**Comment by prayutsu** [comment]
@Karanjot-singh According to the 5th point of our [Instructions for making a code change](https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change), we do not allow force push, so we'll have to close this PR.
You can create a fresh PR again..

**Comment by Karanjot-singh** [comment]
@prayutsu I apologise for the force-push. Sure, I will create a fresh PR, I had a few queries:
1. If I started working on an issue (and the feature branch is even with oppia:develop) and before I make the PR, there are a few commits oppia:develop, I need to rebase (auto merge) my feature branch before submitting the PR right?
2. How do I lint check my BUILD.bazel file?
3. The following unit Tests failed in this PR Could you help me with these so that I don't make the same mistakes in the new PR
image
image

**Comment by prayutsu** [comment]
@Karanjot-singh Ideally you only require to make it even before you start working on the PR, bit for example, when you submit the PR and it takes too long to merge, so you may have to update it with the latest develop branch again.
Also, you don't need to rebase your branch, you can just merge the latest develop branch by `git pull upstream develop`

**Pull request closed without merging**
