### PR TITLE
Fix #430 : Reduce white space between feedback & answer & content boxes

### LINKED ISSUE #430: Reduce white space between feedback & answer & content boxes
There's too much vertical whitespace which makes it harder to consume all the content on the screen. We should reduce this (see Oppia Web for context).

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation

This PR fixes white spaces between Feedback, answer and content boxes.

Note : `Lerners's response` box width based on its content is being fixed in #412 . This PR focuses only on spacing.

### Mock
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/5954b83a-4bcf-4fa6-8382-f814137fa8ab/PM-Q4-Fill-In-Learn-Again-/

### Accessibility Scanner

- [x] Passes Scanner test successfully.

### Screenshot
Screenshot_20191120-132734
Screenshot_20191120-132741

### CODE REVIEW

**Comment by seanlip** [comment]
@veena14cs One question -- in the second screenshot, can you reduce the vertical whitespace at the top and the bottom of the item selection input? There's quite a lot of it.

Sorry I missed this earlier.

**Review by rt4914 — APPROVED** [review]
@veena14cs LGTM, but it might get updated a little bit when we finish Hifi for exploration/state fragment. For now this should get merged.

**Comment by veena14cs** [comment]
> @veena14cs LGTM, but it might get updated a little bit when we finish Hifi for exploration/state fragment. For now this should get merged.

Thanks.

**Comment by veena14cs** [comment]
> @veena14cs One question -- in the second screenshot, can you reduce the vertical whitespace at the top and the bottom of the item selection input? There's quite a lot of it.
> 
> Sorry I missed this earlier.

PTAL 
Screenshot_20191120-143531

**Review by seanlip — APPROVED** [review]
Thanks, looks good. If it passes accessibility tests (please verify) then LGTM from a UI perspective.

**Comment by veena14cs** [comment]
> Thanks, looks good. If it passes accessibility tests (please verify) then LGTM from a UI perspective.

Yes it does. Thanks.

**Comment by mschanteltc** [comment]
Since this is a checkbox question, can we add a description above the choices that reads "Please select at least one choice" like in this [mock](https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/97bc8e75-0232-4079-be1f-3e935fe73e33/TM-Q4-Checkboxes-No-Answer-)? Also when the user submits the right answers, only their answers are shown, so any answers that were unselected should disappear as well. 

These are the only functional improvements I would make to this, but otherwise the formatting looks great!

**Pull request merged**
