### PR TITLE
Fix #3122 : Dark theme make colors of the images distorted

### LINKED ISSUE #3122: Dark theme make colors of the images distorted
We currently do not support a dark theme but when a device enforces a dark theme on the app, then the colors of some images get distorted - 
Screenshot_2021-04-27-11-24-27-407_org oppia android

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

Fix #3122 : Dark theme make the colors of the images distorted

Solution: Images change their color to white when Dark mode is turned on. That's why we force disabling dark mode for Image Views prevents android from force-inverting the colors in the images.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

| Before Fix | After Fix |
| ------ | ------ |
|   |  |

| Before Fix | After Fix |
| ------ | ------ |
|   |  |

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by MohitGupta121** [comment]
Screenshot_2023-08-28-11-48-43-675_org oppia android

**Review by MohitGupta121 — COMMENTED** [review]
@BenHenning PTAL, Thanks!

Now I am wondering that how I will test this in release version, the solution you give without that also if I test app on my Physical device the output is without any bug as mentioned in screenshot. But now the major concern is how I will test this changes with release data or release app?


| [Debug] Physical device output with and without changes is same |
| ------ |
|  |

**Comment by MohitGupta121** [comment]
Also app is not building with `forceDarkAllowed` giving this [error](https://github.com/oppia/oppia-android/actions/runs/6003167993/job/16281030290?pr=5141#step:13:629)
Error - `error: attribute forceDarkAllowed (aka org.oppia.android.app.databinding:forceDarkAllowed) not found`
Solution - https://stackoverflow.com/questions/56163187/aapt-error-attribute-androidforcedarkallowed-not-found

Everyone saying to update compileSdkVersion but already on 31.

**Comment by BenHenning** [comment]
@MohitGupta121 can you check the build on Bazel to see if the attribute issue exists? Also, I think we need to check that this works on an earlier version of Android to make sure that the attributes won't cause an issue.

Once these are addressed, I can check this PR with production assets.

**Comment by MohitGupta121** [comment]
@BenHenning I getting same errors while building with Bazel, when using `forceDarkAllowed=true`

image

image

**Review by MohitGupta121 — COMMENTED** [review]
@BenHenning @adhiamboperes PTAL, I updated PR description with Productions assests screenshots of my Physical Device and now issue is resolved. Thanks!

**Review by adhiamboperes — COMMENTED** [review]
This LGTM @MohitGupta121.

Could you please edit your PR description to explain the changes that have been made?

**Comment by MohitGupta121** [comment]
Thanks @adhiamboperes , sure I'll explain that.

**Comment by MohitGupta121** [comment]
@adhiamboperes PR description updated. PTAL, Thanks!

**Review by adhiamboperes — APPROVED** [review]
Thanks @MohitGupta121, this LGTM.

**Pull request merged**
