### PR TITLE
Fixes part of #2325: Changes in Cellular dialog[a11y]

### LINKED ISSUE #2325: Changes in Views related to Audio Player [A11y] [BLOCKED]
**Describe the bug**

Some Views related to Audio Player are not fully compatible with some users from the Accessibility point of view.

Issue 1 - The Audio Player Icon in the ToolBar of Exploration Activity does not have a content label 
Issue 2 - The checkbox inside cellular data dialog box has a height of 41dp which is less than the standard one (48dp)
Issue 3 - The SeekBar which shows the progress of Audio that is being played, does not have a content label

Probable Solution for -
Issue 1) The screen reader should say 'Audio, OFF, Double-tap to activate'
Isseu 3) Audio scrub, STATE (ex: Audio scrub, PAUSED)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start Fraction Exploration
3. Try to play the audio to encounter the dialog box and the audio icon
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**
|Issue 1|Issue 2|Issue 3|
|:-:|:-:|:-:|
|Screenshot_2020-12-17-11-24-53-65_80a9469f53bfe75dbc6e8989be28e2f0|Screenshot_2020-12-17-11-25-18-23_80a9469f53bfe75dbc6e8989be28e2f0|Screenshot_2020-12-17-11-25-40-87_80a9469f53bfe75dbc6e8989be28e2f0|

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

### PR DESCRIPTION
**Pull request by Arjupta**
## Explanation

Fixes Issue 2 of #2325 by increasing the clickable checkbox minimum height to be 48dp

| Before Changes | After Changes | Test Result |
|:-:|:-:|:-:|
|Screenshot_1611150898|Screenshot_1611150837|Screenshot_1611150405|

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@ARJUPTA In PRs related to a11y, always post following things: 
1. Before screenshot of UI
2. After screenshot of UI.
3. A11y scanner result.

**Comment by rt4914** [comment]
Update title to `Fixes part of #2325` as this PR is not solving the entire issue.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Overall good. Just need to do the changes mentioned above and remove from draft.

**Comment by Arjupta** [comment]
> @ARJUPTA In PRs related to a11y, always post following things:
> 
> 1. Before screenshot of UI
> 2. After screenshot of UI.
> 3. A11y scanner result.

@rt4914 I have done required changes but as you can see that there is a slight variation in the height of dialog because of the changes. This is not actually breaking the UI but still a bit different from the previous one

**Comment by rt4914** [comment]
> > @ARJUPTA In PRs related to a11y, always post following things:
> > 
> > 1. Before screenshot of UI
> > 2. After screenshot of UI.
> > 3. A11y scanner result.
> 
> @rt4914 I have done required changes but as you can see that there is a slight variation in the height of dialog because of the changes. This is not actually breaking the UI but still a bit different from the previous one

@ARJUPTA That's not an issue because for all AlertDialog we are not trying to copy the UI to pixel perfect instead we reply on Android Native UI to make sure it looks good. So don't worry about this nit change.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
Also update your branch with latest develop. @ARJUPTA

**Comment by Arjupta** [comment]
> Also update your branch with latest develop. @ARJUPTA

done

**Pull request merged**
