### PR TITLE
Fix #1781: Add support for caching images in multiple choice-esque interaction choice lists

### LINKED ISSUE #1781: Images are failing to load sometimes in the exploration player
See https://github.com/oppia/oppia-android/pull/1637#issuecomment-686244303 for specifics. More investigation is needed.

**How to encounter this error?**

1. Using the **scripts** load the oppia-alpha assets.
2. Uninstall your previous app.
3. Go to `MRJeVrKafW6G.json` file and change "init_state_name" to `Recap 1`
4. Using this [function](https://gist.github.com/rt4914/9ca5798836e783ec29215dead870bc5b#file-storyprogresstesthelper-kt-L24) mark dummy progress.
5. Run the app.
6. Go to Multiplications
7. Go to `5. Multiplying by power of 10`
8. Enter 2 incorrect answer.
9. Click on hint -> reveal.
10. Notice it is empty.

**Expected Result**
This image should be visible in hint. https://storage.googleapis.com/oppiaserver-resources/exploration/MRJeVrKafW6G/assets/image/img_20200308_213016_u6ap4qq25c_height_313_width_490.png

### PR DESCRIPTION
**Pull request by BenHenning**
Fixes #1781.

Add support for caching images in multiple choice input, item selection, and drag and drop interactions (specifically their choices lists which can contain images). No tests were added since this only affects the alpha-only on-app pre-cache flow.

Test steps:
- Enable caching in CachingModule
- Clear app storage
- Install app
- Turn off Wifi
- Play through What is a Fraction
- Observe that multiple choice option images load right away rather than being missing

### CODE REVIEW

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @BenHenning 
Just to confirm, this PR has no relation with the extra space below the first option?

Screenshot_1599213928

**Comment by BenHenning** [comment]
Nope, that's not part of either PR (definitely not this one, and pretty sure the previous wouldn't cause this).

@anandwana001 could you file a bug for that?

**Comment by anandwana001** [comment]
> Nope, that's not part of either PR (definitely not this one, and pretty sure the previous wouldn't cause this).
> 
> @anandwana001 could you file a bug for that?

Sure

**Comment by BenHenning** [comment]
Thanks & for the review!

**Pull request merged**
