### PR TITLE
Fix part of #1833: Prepare to rename package to org.oppia.android (part 1/2)

### PR DESCRIPTION
**Pull request by BenHenning**
Fixes part of #1833.

This moves all Kotlin source files to be under an org.oppia.android structure, but does not actually change references. This is done in two steps to try and preserve history, and to simplify the code reviews.

THIS WILL BREAK THE CODEBASE WHEN CHECKED IN. I'll be sending out an email shortly explaining the situation to oppia-android-dev@.

#1876 (or a similar PR) will follow up with the actual import changes to fix everything.

### CODE REVIEW

**Comment by BenHenning** [comment]
@rt4914 @anandwana001 PTAL. Note that checks will fail for this, which means that the PR will need to be force merged.

**Review by anandwana001 — APPROVED** [review]
LGTM, thanks @BenHenning 
Just concern with two points:
1. What about the model package
Screenshot 2020-09-24 at 23 08 35
2. `org.oppia.android.util` is fine or it should be `org.oppia.android.utility`?
although util looks fine, but just to confirm as all other are same as the package name

**Comment by BenHenning** [comment]
@anandwana001 there are no directory structure changes needed in model. The actual package references should be updated in #1876 (see example.proto in that PR--I can't link to it since the PR is so large).

Does this address your question?

**Comment by anandwana001** [comment]
> @anandwana001 there are no directory structure changes needed in model. The actual package references should be updated in #1876 (see example.proto in that PR--I can't link to it since the PR is so large).
> 
> Does this address your question?

Yes, I got it.

**Comment by BenHenning** [comment]
Thanks.

NB: The Gradle tests are passing due to Gradle not actually enforcing that file packages match their directory structure. Bazel is stricter, so it's breaking as expected.

**Comment by BenHenning** [comment]
@rt4914 I will block submission on your review.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by BenHenning** [comment]
Thanks! I will submit this only after #1876 is approved.

**Comment by BenHenning** [comment]
Email is ready to go out, and will be sent immediately after merging. I have updated branch protections to require all PRs are up-to-date with develop, thereby preventing people from submitting changes after this PR goes in (since it breaks the Bazel check). This isn't a super robust way to stop changes, but it should well enough for the next ~30 minutes.

Force merging this PR despite failing checks. Checks will be passing again in #1876.

**Pull request merged**
