### PR TITLE
Sample exploration player - lowfi (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

This PR is a sample for entire playable exploration. Do not merge this PR.

Approach:
The entire StateFragment contains one single RecyclerView  which in turn contains different types of items like ContentItem, InteractionReadOnlyItem, StateButtonsItems, MultipleChoiceInteractionItem, TextInputInteractionItem, NumericInputInteractionItem, etc.

As the state changes these items are inflated in recyclerview which looks similar to mocks.

## Remaining Issues:
1. **Problem:** I have created one `itemList` which contains different items in recyclerview, currently whenever state changes, this `itemList` is cleared and again all the items are added to recyclerview. Though this is in incorrect usage of `itemList` but for now it works correctly and gives a good idea of how the entire Exploration Player can be created. 
**Solution:** Before adding any item to `itemList` we should somehow check if the item already exists and if it exists do not add item again. But the issue currently is that the `itemList` is a `ArrayList<Any>` which makes it complicated to figure out which item is present and which is not.

2. Consider a case where we have a `TextInputInteraction` now if the learner answers it incorrectly, then the state will not change, the wrong answer will be saved and the `TextInputInteraction` will again be displayed to learner to enter correct answer. Here the issue is that when the `TextInputInteraction` is displayed again it contains the pre-filled text as previous answer. Maybe @nikitamarysolomanpvt can have a look at it.
Screenshot_1571314717

3. When learner starts entering answer in any interaction, the recyclerview should scroll-up so that submit-button is visible just above the keyboard. (Can be solved in Hi-Fi #164 )
Screenshot 2019-10-17 at 5 50 15 PM

4. `MutipleChoiceInteraction` and `ItemSelectionInteraction` are WIP and @veena14cs is working on this. There is issue related to `customization_args` (basically we are not getting values from `customization_args`), which @nikitamarysolomanpvt will be discussing with @BenHenning 

5. `TextInputInteraction`, `NumberInputInteraction`, `FractionInputInteraction` and `NumberWithUnitsInputInteraction` are WIP and @nikitamarysolomanpvt is working on them. I have currently used `TextInputInteraction`, `NumberInputInteraction` in this PR and they do work correctly.

6. `AudioPlayer`: @jamesxu0 can work on playing audio using this PR. (Note this PR is just a sample and will change with time, so therefore if @jamesxu0 work on audio player using this PR then it would probably be a sample implementation only.)

7. `Toolbar/Action Bar`: There is one toolbar which contains `Audio Player Icon`, `Help` and `Preferences`, so we can either use ActionBar or Toolbar, which one should be use? Also if toolbar, it can be in ExplorationFragment or `StateFragment`, which one should be use? I prefer `Toolbar` inside `StateFragment` because audio is a part of `State` and also it depends on `StateFragmentPresenter` too.

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is **assigned** to an appropriate reviewer.

### CODE REVIEW

**Comment by rt4914** [comment]
@BenHenning PTAL and check if the approach is correct or not. Also check description of PR too, because I will need some clarification on point 1.

**Comment by BenHenning** [comment]
Overall feedback:
- This looks awesome! I just played through it--it's really exciting to actually see the whole structure starting to come together.
- onBackPressed() breaks the exploration play state--I think we need to make sure that the exploration is properly finished in that situation.

---

Feedback on point 1:
Is this causing any specific problems? I agree it's not ideal, but if we later move this adapter to the generic data binding adapter, and then solve #171 it might solve this problem for us. Otherwise I agree that it's hard, but I'm willing to brainstorm a solution with you if necessary.

---

General feedback on the overall approach:
- Retrieving the ``InteractionObject`` should be generalizable: we can assume the view is an implementation of the retriever interface--let's just cast it and retrieve the object (otherwise it should fail to indicate we set something up wrong somewhere)
- Binding & inflating the interaction views needs to be generic since we'll have potentially dozens of interactions eventually to support. I was talking to @nikitamarysolomanpvt a bit one option to use a custom layout file for each interaction to represent that interaction type. We could make this layout data-bound, and then use a Dagger set to bind available interaction view binders. At first I was going to explain in detail how to do this (and am willing to if you'd like), but it's complicated enough that I think we should file an issue to generalize the adapter and keep with the more specific approach you're doing now.

**Comment by rt4914** [comment]
> Overall feedback:
> 
> * This looks awesome! I just played through it--it's really exciting to actually see the whole structure starting to come together.

Thanks for the feedback.
> * onBackPressed() breaks the exploration play state--I think we need to make sure that the exploration is properly finished in that situation.

Will solve this today.
> 
> Feedback on point 1:
> Is this causing any specific problems? I agree it's not ideal, but if we later move this adapter to the generic data binding adapter, and then solve #171 it might solve this problem for us. Otherwise I agree that it's hard, but I'm willing to brainstorm a solution with you if necessary.

The only issue it will create for now is that we won't be able to control animations because the entire list of items is re-created.
> 
> General feedback on the overall approach:
> 
> * Retrieving the `InteractionObject` should be generalizable: we can assume the view is an implementation of the retriever interface--let's just cast it and retrieve the object (otherwise it should fail to indicate we set something up wrong somewhere)

I am not getting it want you mean by this, can you explain in more detail?
> * Binding & inflating the interaction views needs to be generic since we'll have potentially dozens of interactions eventually to support. I was talking to @nikitamarysolomanpvt a bit one option to use a custom layout file for each interaction to represent that interaction type. We could make this layout data-bound, and then use a Dagger set to bind available interaction view binders. At first I was going to explain in detail how to do this (and am willing to if you'd like), but it's complicated enough that I think we should file an issue to generalize the adapter and keep with the more specific approach you're doing now.

So regarding this final point, I don't need to change anything as of now, right?

**Comment by BenHenning** [comment]
No animations seems fine for now.

---

Regarding retrieving the interaction object, I believe we can do:

```kotlin
(inputInteractionView as InteractionAnswerRetriever).getInteractionObject()
```

Rather than using a ``when`` for each possible interaction type. That part is already generalizable via the interface, so the ``when`` statement isn't needed.

---

Yep, let's keep the solution specific to interactions for now. Please file an issue and add TODOs to track generalizing the adapter & interaction view construction.

**Comment by rt4914** [comment]
> No animations seems fine for now, and that risk makes sense.
> 
> --
> 
> Regarding retrieving the interaction object, I believe we can do:
> 
> ```kotlin
> (inputInteractionView as InteractionAnswerRetriever).getInteractionObject()
> ```
> 
> Rather than using a `when` for each possible interaction type. That part is already generalizable via the interface, so the `when` statement isn't needed.
> 
> Yep, let's keep the solution specific to interactions for now. Please file an issue and add TODOs to track generalizing the adapter & interaction view construction.

Okay everything is clear now. Thanks

**Comment by BenHenning** [comment]
Thanks @rt4914. Deassigning myself for now. Please reassign me if there's something else you'd like me to look at in this PR.

**Comment by nikitamarysolomanpvt** [comment]
> 2. Consider a case where we have a `TextInputInteraction` now if the learner answers it incorrectly, then the state will not change, the wrong answer will be saved and the `TextInputInteraction` will again be displayed to learner to enter correct answer. Here the issue is that when the `TextInputInteraction` is displayed again it contains the pre-filled text as previous answer. Maybe @nikitamarysolomanpvt can have a look at it.

In web on button click its handled.

**Comment by veena14cs** [comment]
Thanks for this implementation, it was really helpful to integrate in my PR.

**Pull request closed without merging**
