### PR TITLE
Fix part of #2502: Fix failing test cases on espresso for AdminPinActivityTest

### LINKED ISSUE #2502: Tests Failing on Espresso in Landscape with small screen size or bug
**Describe the bug**
After the migration to `TextInputLayout`, few test cases are failing on Espresso with small screen size.

**Expected behavior**
All the test case should pass on multiple device screen size. Pixel, Pixel XL, Nexus 4, Tablet.

**How to submit PR**
Add test result screenshot for Espresso and Robolectric on devices mentioned above. 

**Additional context**
```kotlin

// possibly scrolling issue 
(@FareesHussain )
fun testAddProfileActivity_inputPin_inputDifferentConfirmPin_clickCreate_changeConfiguration_checkErrorMessageDisplayed() 

// possibly scrolling issue 
(@FareesHussain )
fun testAddProfileActivity_inputNotUniqueName_clickCreate_changeConfiguration_checkErrorMessageDisplayed()

// here, the error message is not displayed after orientation change. Need to investigate why this is passing earlier and why this is failing now. 
(@FareesHussain )
fun testProfileRenameActivity_inputOldName_clickSave_changeConfiguration_errorIsVisible() 

// Also confirm, can we update this layout file with using Neste Scroll View? 
(@prayutsu )
fun testAdminPinActivity_configurationChange_inputPin_inputWrongConfirmPin_clickImeActionButton_checkConfirmWrongError()

(@prayutsu )
fun testAdminPinActivity_inputPin_inputWrongConfirmPin_clickSubmit_configurationChange_checkConfirmWrongError()

(@prayutsu )
fun testAdminPinActivity_inputPin_inputWrongConfirmPin_clickImeActionButton_configurationChange_checkConfirmWrongError()
```

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation

Fixes part of #2502 
Failing test cases on espresso are now fixed

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.
Screenshot from 2021-01-20 10-19-24

https://user-images.githubusercontent.com/54636525/105128620-5beca200-5b09-11eb-8412-821f905a2cd1.mp4

### CODE REVIEW

**Comment by anandwana001** [comment]
Please follow the installation point 3 - https://github.com/oppia/oppia-android/wiki#installation

**Comment by prayutsu** [comment]
> Please follow the installation point 3 - https://github.com/oppia/oppia-android/wiki#installation

Actually, I have already configured ktlint and bufbuild, I just disabled it for one of the PR and I forgot to re-enable it. I have enabled it now.

**Comment by prayutsu** [comment]
> Please follow the installation point 3 - https://github.com/oppia/oppia-android/wiki#installation

Done, thanks!

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @prayutsu

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
