### PR TITLE
Fix global layout code ownership pattern

### PR DESCRIPTION
**Pull request by BenHenning**
Change Rajat's global ownership to all resource XML files rather than exclusively layouts (+ fix the former--it wasn't actually matching any layout directories).

### CODE REVIEW

**Comment by BenHenning** [comment]
@seanlip please rubber stamp.

**Comment by seanlip** [comment]
CI tests are failing?

**Review by seanlip — APPROVED** [review]
(but yup lgtm)

**Comment by BenHenning** [comment]
Looks like a maven flake. Closing & reopening to re-trigger it.

**Review by rt4914 — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
