### PR TITLE
Fix #2719: Resolve ktlint max line in ViewModelBridgeFactory

### LINKED ISSUE #2719: Resolve ktlint max line in ViewModelBridgeFactory
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name.
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the line of code under 100 char length.

Where to start?
1. Complete all installation steps before starting with this issue - https://github.com/oppia/oppia-android/wiki#installation
2. 
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/main/java/org/oppia/android/app/viewmodel/ViewModelBridgeFactory.kt#L21

Possible fix for this solution
```kotlint
    check(modelClass.isAssignableFrom(viewModel.javaClass)) {
      "Cannot convert between injected generic type and " +
        "runtime assumed generic type for bridge factory."
    }
```

### PR DESCRIPTION
**Pull request by Sparsh1212**
## Explanation

Fixes #2719: Resolve ktlint max line in ViewModelBridgeFactory
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Sparsh1212** [comment]
@anandwana001 PTAL

**Comment by anandwana001** [comment]
@Sparsh1212 Please update the branch with the latest develop branch.

**Comment by Sparsh1212** [comment]
> @Sparsh1212 Please update the branch with the latest develop branch.

Done.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks for nit fix.

**Review by BenHenning — APPROVED** [review]
Thanks @Sparsh1212! LGTM.

**Comment by BenHenning** [comment]
@anandwana001 please watch for merging.

**Pull request merged**
