### PR TITLE
Fixes #4736: revision card textViews line wraps instead of ellipsize and solves accessibility scanner issue

### LINKED ISSUE #4736: [a11y] TextView has fixed width and scalable text
**Describe the bug**

On revision screen, the toolbar text and navigation cards have accessibility issues: TextViews have fixed width and scalable text. Attaching a screenshot of the accessibility scanner output for reference.

 

**To Reproduce**
1. Go to `Fractions` topic
2. Click on `Revision` tab
3. Select `Fractions of a group`
4. Now take screenshot from [accessibility scanner](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide#using-a11y-scanner-in-android) to test the issue.

**Note for assignees**
 This issue will need some debugging to exactly understand the issues and also to find a viable solution. A good starting point can be [Ben's comment](https://github.com/oppia/oppia-android/issues/4736#issuecomment-1376603778)

**Environment**
- Device/emulator being used: <Vivo V25 pro>
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

### PR DESCRIPTION
**Pull request by Abinash6000**
## Explanation
Fixes  #4736:  This PR increases the number of lines of ```prev_subtopic_title``` and ```next_subtopic_title``` if the text doesn't fit within 3 lines for large texts. And solves the accessiblity scanner issue.
imageimage

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- (before)
- image
- image
- (after)
- image
- image
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- image
- image
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by adhiamboperes — COMMENTED** [review]
Thanks @Abinash6000!

Some follow-up comments:
1. In https://github.com/oppia/oppia-android/issues/4736#issuecomment-1640081212, you mentioned adding a `maxLines` attribute as well, but I don't see that here. Could you explain why you have decided to ommit it?
2.  Can you add a screenshot showing you used the accessibility scanner with these changes and the warning is nolonger visible?

**Comment by Abinash6000** [comment]
> Thanks @Abinash6000!
> 
> Some follow-up comments:
> 
> 1. In [[a11y] TextView has fixed width and scalable text #4736 (comment)](https://github.com/oppia/oppia-android/issues/4736#issuecomment-1640081212), you mentioned adding a `maxLines` attribute as well, but I don't see that here. Could you explain why you have decided to ommit it?
> 2. Can you add a screenshot showing you used the accessibility scanner with these changes and the warning is nolonger visible?

1. Omit it because it does the job without maxLines as well, which is to lineWrap instead of ellipsize.
2. The accessibility scanner issue is not gone. This only solves the issue of line wrapping instead of ellipsizing.

**Comment by adhiamboperes** [comment]
> 2. The accessibility scanner issue is not gone. This only solves the issue of line wrapping instead of ellipsizing.

Can you please attach proof?

**Comment by adhiamboperes** [comment]
> 2. The accessibility scanner issue is not gone. This only solves the issue of line wrapping instead of ellipsizing.


Isn't the purpose of this issue to reolve the accessibility scanner issue? If it is not reolved then it means that your solution is incomplete.

**Comment by Abinash6000** [comment]
Yes, should I close this pull request and try something else ? I thought making line wrap is also part of the issue as ben henning suggested. Sorry.

**Comment by adhiamboperes** [comment]
> Yes, should I close this pull request and try something else ? I thought making line wrap is also part of the issue as ben henning suggested. Sorry.


You can push more commits to this branch that cover the outstanding parts of the issue.
That is, trying different combinations of changing the width to wrap content.

If you however choose a different issue, then it will need to be in it's own branch/PR.

**Comment by Abinash6000** [comment]
Ok @adhiamboperes  thanks for replying. I'll try different combinations of changing the width to wrap content.

**Review by adhiamboperes — APPROVED** [review]
Hey @Abinash6000, thanks, this LGTM.

Could you please add the accessibility scanner screenshots showing that the issue has been resolved by your PR?

**Comment by Abinash6000** [comment]
@adhiamboperes I've added accessibility scanner screenshots to PR. Thanks!

**Comment by adhiamboperes** [comment]
Thanks @Abinash6000!

**Pull request merged**
