### PR TITLE
Fix #414: Add StringToFractionParserTest

### LINKED ISSUE #414: Add tests for whitespace & fractions patterns
See #413 for details.

### PR DESCRIPTION
**Pull request by viktoriias**
## Explanation

Fixes #414: Add unit tests for StringToFractionParser.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by viktoriias** [comment]
@rt4914 Please review. Some imports have moved to the new packages, I updated the imports here.

**Comment by rt4914** [comment]
I have checked tests for this file and other app layer tests for robolectric and espresso and all tests are passing. I suppose the only solution is to merge this and check if this creates test failure once again or not.

**Review by rt4914 — APPROVED** [review]
LGTM

**Comment by rt4914** [comment]
Again checked all tests on latest develop and they are passing correctly which was not the case earlier.

**Comment by rt4914** [comment]
Created https://github.com/oppia/oppia-android/pull/3215 to test on CI

**Comment by rt4914** [comment]
Confirmed in #3215 tests are now passing on CI too. Thanks @viktoriias

**Pull request merged**
