### PR TITLE
Fix #2223: Introduce codeowners

### LINKED ISSUE #2223: Establish codeowners
We need an establish codeowners break-down to provide distributed ownership of the codebase, better parallelize code reviews, and provide long-term guidance for building code ownership & reviewer capacity in the future.

### PR DESCRIPTION
**Pull request by BenHenning**
Fix #2223.

Introduce codeowners per the approved document: https://docs.google.com/document/d/1OtGIwG-VMZkE8F5uGU0OMlmT20BjW0sQllWsQryAkiA/edit#.

### CODE REVIEW

**Comment by BenHenning** [comment]
@seanlip FYI you're a redundant codeowner of the CODEOWNERS file (in case something needs to change in a pinch, e.g. if I'm unreachable for urgent code changes).

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @BenHenning

**Comment by BenHenning** [comment]
Thanks! Going ahead & merging since @vinitamurthi is out for the rest of the year. FYI that this will take effect immediately.

**Pull request merged**
