### PR TITLE
Fix #909: Highfi StoryTextSizeActivity

### LINKED ISSUE #909: Highfi StoryTextSize Activity
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/OP-Story-Text-Size-

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/OP-Story-Text-Size-

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #909

Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/OP-Story-Text-Size-

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/OP-Story-Text-Size-

## Screenshot
Screenshot_1585555780
Screenshot_1585555782

## Accessibility Test:
The accessibility test fails because `A` is appearing twice in this screen. This failure is acceptable as the UX is correct for this case.
as_9

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by nikitamarysolomanpvt** [comment]
@rt4914 Neither in your issue nor in you explanation you mentioned any details other than Mock.
Please add test cases ... Please mention Test class name if already existing.

**Review by nikitamarysolomanpvt — CHANGES_REQUESTED** [review]
Please increase thumb size ... people with thick thumb will find it difficult to drag

**Comment by nikitamarysolomanpvt** [comment]
@rt4914 PTAL on test cases 
x
also add UI test for intervals/ticks.

**Comment by rt4914** [comment]
> @rt4914 PTAL on test cases
> x
> also add UI test for intervals/ticks.

As discussed these test cases have failed because of landscape orientation of app. I have filed and issue for this as it deals with the entire `app` module #921 . Meanwhile we can work on this the process that we had been following.

**Comment by nikitamarysolomanpvt** [comment]
@rt4914 Please add tick/interval view to the start of the seekbar and update screen shots.

**Comment by rt4914** [comment]
> @rt4914 Please add tick/interval view to the start of the seekbar and update screen shots.

Screenshot_1585648361
Screenshot_1585648597

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Pull request merged**
