### PR TITLE
Fix Part of #2833 : Added missing named arguments in TopicPracticeFragmentTest

### PR DESCRIPTION
**Pull request by Karanjot-singh**
## Explanation
Fixes Part of #2833, Added Missing Named Argument in TopicPracticeFragmentTest

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Karanjot-singh** [comment]
PTAL @rt4914 @prayutsu 
For some reason, I was unable to add an Assignee.

**Review by prayutsu — COMMENTED** [review]
Thanks @Karanjot-singh, the PR looks good.
Just want to confirm from @rt4914 if we also want named arguments for `skillIdList.add("5RM9KPfQxobH")` on line numbers 102 and 103?

**Comment by prayutsu** [comment]
@Karanjot-singh You will be able to access the Assignee section once your 2 PRs get merged. As of now, PTAL comment would be sufficient. 
And according to our code change guidelines, the branch name should only include lowercase letters where different words should be separated by '-'. For this PR, it's fine but please take care of this in your future PRs.

**Comment by Karanjot-singh** [comment]
Thank you for the feedback @prayutsu I will definitely take care of this in future PRs

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
