### PR TITLE
Fix #4641, #4674, #4579, #4591: Assorted beta fixes

### LINKED ISSUE #4579: The home screen is blank on opening beta app
**Describe the bug**
The home screen is blank on opening beta app

**To Reproduce**
1. Go to 'Playstore'
2. Install Oppia
3. Open Oppia app

**Expected behavior**
Home page should open with Explorations

**Demonstration**

**Environment**
Mobile: One Plus Nord2 5G
Android Version: 11
App Version: 0.9-beta-3f935261e0

### LINKED ISSUE #4591: Incorrect answer responses are not displayed for a question in Mixed numbers and the Number Line 1
**Describe the bug**
Incorrect answer responses are not displayed for a question in Mixed numbers and the Number Line 1

**To Reproduce**
1. Go to 'Fractions' - Mixed numbers and the Number Line 1
2. Click on 'Continue' till you reach the question 'In this picture how many squaers are red?
3. Enter 5 1/12

**Actual behavior**
Submit button is disabled and a few times when it is enabled on giving 5 1/12 as an answer and submitting no response is seen. Hints are displayed instead.

**Demonstration**
https://user-images.githubusercontent.com/101634267/189596305-78842751-5d18-4f4a-8379-58084c666adf.mp4

**Environment**
Mobile: One Plus Nord2 5G
Android Version: 11
App Version: 0.9-beta-3f935261e0

### LINKED ISSUE #4641: Terms of Use needs updating
**Describe the bug**
The Terms of Use need to be updated.
I assume the same Terms are applicable for android app as well.

**To Reproduce**
Navigate to https://www.oppia.org/terms

**Expected behavior**
The terms shouldn't disallow children from using the app/site

**Demonstration**
_IF YOU DO NOT AGREE TO THE TERMS, OR IF YOU ARE UNDER THE AGE OF 13 YEARS OLD AND DO NOT HAVE THE APPROVAL OF A LEGAL PARENT OR GUARDIAN, YOU MUST NOT REGISTER FOR OR ACCESS THIS WEBSITE._

**Environment**
-N/A

### LINKED ISSUE #4674: Hide all downloads options behind downloads flag

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
Fixes #4641
Fixes #4674
Fixes #4579
Fixes #4591

Miscellaneous fixes for Beta MR2. Specifically:
- #4641 is addressed by updating the terms of service wording. No test is needed here since manual verification is sufficient.
- #4674 is addressed by replacing the existing automatic topic updates platform with a generic "all downloads" one (which will be used for all downloads gating moving forward). Admin controls, add profile, and profile edit pages have been updated to only show downloads-related settings if this flag is enabled. Corresponding tests have been updated. FAQ question 8 was also removed since it asks about how to download lessons, and this support isn't in the app yet. Some strings referencing downloads have also been updated.
- #4579 is addressed by properly handling the case where unpublish topics with previous progress would cause the topic list to fail to load. A test was added to verify the fix, but it required a new FakeAssetRepository to be introduced.
- #4591 is addressed by fixing FractionInputHasIntegerPartEqualToRuleClassifierProvider's input type (which should be SIGNED_INT but was incorrectly NON_NEGATIVE_INT before; this seems to have been wrong since the classifier was introduced).

Test exemption: FakeAssetRepository doesn't have a test added since it uses a real production AssetRepository, and tests don't yet exist for that). They ought to be tested together.

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
Screenshots showing the before & after changes due to hiding downloads options:
|                  | Without changes                                                                                                 | With changes                                                                                                    |
|------------------|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| Profile creation | image | image |
| Profile edit     | image | image |
| Admin controls   | image | image |

Espresso test rules for affected UI tests:
| Affected Test                     | Test Results                                                                                                                                                             |
|-----------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| AdministratorControlsActivityTest | (Skipped since there are tablet tests to also run, so the suite won't actually pass cleanly)                                                                             |
| ProfileEditActivityTest           | (Same as above)                                                                                                                                                          |
| AdministratorControlsFragmentTest | oppia_assorted_beta_fixes_passing_admin_controls_fragment_test |
| ProfileEditFragmentTest           | oppia_assorted_beta_fixes_passing_profile_edit_fragment_test   |

New Robolectric tests failing for corresponding regressions:
| Issue | Test Suite                                                   | Failure Specifics | Failure Results                                                                                                                       |
|-------|--------------------------------------------------------------|-------------------|---------------------------------------------------------------------------------------------------------------------------------------|
| #4579 | TopicListControllerTest                                      | 1/36 tests fail   | failing_topic_list_test     |
| #4591 | FractionInputHasIntegerPartEqualToRuleClassifierProviderTest | 22/23 tests fail  | oppia_failing_fraction_test |

Missing artifacts:
- Accessibility: not particularly relevant to these changes since the user-facing changes are either crash fixes or removing UI elements (except in the case of terms of service, but that doesn't require additional a11y testing coverage or demonstration here).
- RTL: nothing in this change affects RTL specifically.
- Landscape: since the main UI changes are removing elements, the changes to tablet aren't very "interesting" to show off.
- Tablet: same rationale as for landscape.
- Internationalization: same rationale as RTL.

### CODE REVIEW

**Comment by BenHenning** [comment]
The changes are fairly self explanatory, I think, but I'll follow up with a clearer description & tests in the next 1-2 days.

**Comment by BenHenning** [comment]
@seanlip PTAL. As an FYI I have also self-reviewed the whole PR.

**Review by seanlip — APPROVED** [review]

**Comment by seanlip** [comment]
Thanks, took a pass. No concerns.

**Comment by BenHenning** [comment]
Thanks @seanlip! Going ahead and merging this without @rt4914’s approval since it’s release blocking.

**Pull request merged**
