### PR TITLE
Fix #5143: Update Robolectric to 4.7

### LINKED ISSUE #5143: Update Robolectric to 4.7+
### Describe the bug

Since Robolectric 4.7, there have been major updates and improvements including:
- Native support for M1 Macs
- Native support for ShadowSql for both M1 Macs and Linux.
- Improved timing and performance

We are unable to update to this on Bazel  because of a compatibility issue introduced by the required incidental update of the Espresso-Core dependency (Required minimum is 3.5.0-alpha03), likely due to the use of kotlin 1.5.

### Steps To Reproduce

1. In `third_party/versions.bzl`:
Change roboloctric to 4.7
Update espresso-core to  3.5.0-alpha03

2. In the `WORKSPACE` file"
Update the robolectric http_archive to download version 4.7.

3. Follow the Wiki [instructions](https://github.com/oppia/oppia-android/wiki/Updating-Maven-Dependencies) on updating dependencies on bazel.

Run bazel

### Expected Behavior

Project builds successfully.

### Screenshots/Videos

Here is the stacktrace:

`merged_manifests\debug\AndroidManifest.xml:23: AAPT: error: unexpected element <queries> found in <manifest>.`

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

I found similar error reports for Gradle, but none for Bazel. Assuming that the root cause is the same, updating to a newer version of Bazel should resolve this. The cause being newer versions of dependencies introduce a <query> element to manifest, but older build systems are unaware of this.

https://stackoverflow.com/a/62969918/11396524

https://stackoverflow.com/questions/62969917/how-can-i-fix-unexpected-element-queries-found-in-manifest-error

https://forum.ionicframework.com/t/how-do-i-fix-unexpected-element-queries-found-in-manifest/206645

### PR DESCRIPTION
**Pull request by sandy99405**
## Explanation

According to issue #5143, there was an error ```unexpected element <queries> found in <manifest>``` during the Bazel build.
That issue has been resolved in this PR.

1) #### Robolectric version has been changed to 4.7 and espresso-core to 3.5.0-alpha03 in every build.gadle file

2) #### In scripts/assets folder, the maven_dependencies.textproto file has been changed due to an exception.

### This is the Bazel output after updating the Robolectric to 4.7 and maven_install
image

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @sandy99405!

1. Could you please also update the robolectric versions in the` build.gradle `files for app, domain,  utility and testing modules?
2. The PR description has a checklist of what the PR should look like, mainly the Explanation bit and the title bit. Could you ensure this PR is compliant? You can copy the template from a different PR like https://github.com/oppia/oppia-android/pull/5310

**Comment by sandy99405** [comment]
@adhiamboperes  can you kindly confirm if I have to change Robolectric version in data and maven_install.json as well?

**Comment by adhiamboperes** [comment]
> @adhiamboperes can you kindly confirm if I have to change Robolectric version in data and maven_install.json as well?

Yes, in data too. You can search each of the build.gradle files for ocurrances of robolectric and espresso-core to make sure you don't miss anything.

maven_install.json  is specific to bazel and it is never updated manually -- it uses the update script that you previously ran.

**Comment by sandy99405** [comment]
Thank you for the confirmation @adhiamboperes 👍

**Comment by sandy99405** [comment]
@adhiamboperes , may I close this PR and create a new one? Because I erased all the rules before writing the comment and I don't know where to find the checklist rules. Please help

**Comment by adhiamboperes** [comment]
> @adhiamboperes , may I close this PR and create a new one? Because I erased all the rules before writing the comment and I don't know where to find the checklist rules. Please help


Please copy the template from here: https://github.com/oppia/oppia-android/blob/develop/.github/PULL_REQUEST_TEMPLATE.md?plain=1

**Comment by sandy99405** [comment]
All the changes are done @adhiamboperes. BTW the git-hub actions asked me to fill out the CLA sheet only then the PR will be accepted. It's [this form](https://forms.gle/jEytndtgdsx7BrnV6) right? Do I have to talk to you guys and stuff after filling out the form?

**Comment by sandy99405** [comment]
Hi @adhiamboperes  all the conflicts and updates have been finished. Please check this PR.

**Pull request closed without merging**
