### PR TITLE
Fix #5428: Remove kotlin-android-extensions plugin

### LINKED ISSUE #5428: [Feature Request]: Remove Kotlin Android extensions
### Is your feature request related to a problem? Please describe.

We use some synthetics generated by the Kotlin Android extensions plugin. Per https://developer.android.com/topic/libraries/view-binding/migration it's deprecated.

### Describe the solution you'd like

https://developer.android.com/topic/libraries/view-binding/migration has alternative migration pathways, where appropriate. In most cases, we just need to use the direct view based on ID or via the local binding rather than synthetics.

### Describe alternatives you've considered

None since this is a deprecation.

### Additional context

This might be causing some incremental build incompatibilities between the old version of Gradle we're using and Jetpack Compose (being introduced as part of #5344).

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
Fixes #5428

This PR removes all occurrences of the kotlin-android-extensions plugin.

See the issue for specifics, but it seems the plugin wasn't actually being used anywhere (due to it never being enabled in Bazel and the old code that depended on it being removed years ago), so this only affects Gradle builds & tests. It should be a mostly benign change.

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
This isn't expected to impact the user experience at all. For Gradle builds, it's possible the final build changes a bit, but that should be innocuous since the plugin isn't actually being used for anything. Bazel builds are unaffected.

### CODE REVIEW

**Review by BenHenning — COMMENTED** [review]
Self-reviewed changes.

**Comment by BenHenning** [comment]
PTAL @adhiamboperes & @theMr17. I suspect we can mainly rely on CI here, so I'm happy to enable auto-merge.

It might be nice to wait for build stats to run in ~10-11 hours, but if this is imminently blocking your work @theMr17 then I'd prefer we merge it sooner rather than waiting.

**Comment by adhiamboperes** [comment]
I'll approve this after the build stats. Thanks @BenHenning!

**Comment by BenHenning** [comment]
> I'll approve this after the build stats. Thanks @BenHenning!

It actually occurred to me well after the above comment that build stats will be a no-op for this PR. :) The Bazel build is unaffected.

**Review by BenHenning — COMMENTED** [review]
Self-reviewed merge (went in cleanly).

**Comment by theMr17** [comment]
> It might be nice to wait for build stats to run in ~10-11 hours, but if this is imminently blocking your work @theMr17 then I'd prefer we merge it sooner rather than waiting.

I am fine with waiting for a few hours for the build stats.

**Review by adhiamboperes — APPROVED** [review]
LGTM, Thanks @BenHenning!

**Pull request merged**
