### PR TITLE
Fix #1535, part of #4120: Upgrade to rules_kotlin v1.5.0 beta 3

### LINKED ISSUE #1535: Remove kt_download_local_dev_dependencies() from WORKSPACE file once rules_kotlin() is released
**Is your feature request related to a problem? Please describe.**
In order for Bazel to properly build Oppia Android, `rules_kotiln` must support data-binding. The current release of `rules_kotlin` does not include https://github.com/bazelbuild/rules_kotlin/pull/346, which adds this necessary support. Thus, we have created our own fork of `rules_kotlin` (https://github.com/oppia/rules_kotlin) and released this fork (https://github.com/oppia/rules_kotlin/releases/tag/legacy-1.4.0-rcx-oppia-exclusive-rc01) in order to import the most recent version of `rules_kotlin` in Oppia Android's WORKSPACE file. However, in doing this, it has become clear that our release is missing certain dependencies that the official `rules_kotlin` release includes. In order to include those dependencies, we added the following lines to our WORKSPACE file:
`load("@io_bazel_rules_kotlin//kotlin:dependencies.bzl", "kt_download_local_dev_dependencies")`
`kt_download_local_dev_dependencies()`

However, once `rules_kotlin` releases a  version with data-binding support, these lines will not be necessary. 

**Describe the solution you'd like**
Once `rules_kotlin` releases a version with data-binding support, we should delete the two lines mentioned above.

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
Fixes #1535
Fixes part of #4120

This PR preps for the codebase-wide migration to Kotlin 1.6 (done in #4937) by first upgrading rules_kotlin from 1.5.0 alpha 2 to 1.5.0 beta 3. This upgrade, while small, produces a few nice benefits:
- It removes the need for extra WORKSPACE dependency setup (thus addressing #1535).
- It moves a bunch of rules_kotlin macros to new locations which results in changing nearly every ``BUILD.bazel`` file in the codebase.

The changes are straightforward to review in isolation, so this PR acts as a means to help reduce the complexity of #4937 by pulling ahead these groups of ``BUILD.bazel`` changes while also moving rules_kotlin the smallest number of versions (ahead of the more major upgrades which will occur downstream).

Note that this change is needed because:
- We'll need to upgrade to a newer version of rules_kotlin in order to bring in Kotlin 1.6 support.
- rules_kotlin moved these macros and using the old ones results in a _lot_ of build warnings that spam the local console when trying to build.

Separately, this PR includes some minor trailing space cleanup in wiki/Oppia-Bazel-Setup-Instructions.md that was noticed when editing the file (since my local development environment auto-strips trailing spaces).

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A -- This should only affect build infrastructure, and barely impact resulting binary builds.

### CODE REVIEW

**Review by BenHenning — COMMENTED** [review]
Self-reviewed all changes.

**Comment by BenHenning** [comment]
PTAL @adhiamboperes. Note that I suspect this will be a quicker PR to review compared to some of the others that I've sent recently.

**Review by seanlip — APPROVED** [review]
LGTM for 1 codeowner file

**Review by BenHenning — COMMENTED** [review]
Acking that the latest commits were merged in cleanly.

**Review by adhiamboperes — APPROVED** [review]
LGTM, thanks @BenHenning!

**Comment by BenHenning** [comment]
Thanks @adhiamboperes and @seanlip! Going ahead and merging this.

**Pull request merged**
