### PR TITLE
Fixes #3827: [Portuguese] Translated text overlap

### LINKED ISSUE #3827: [Portuguese] Translated text overlap
**Describe the bug**
Text overlap has been observed with the translated text in Portuguese.

**To Reproduce**
1. Go to Oppia app
2. Click on admin profile
3. See error 

**Expected behavior**
Text should be separated and should not overlap over one another. 

**Demonstration**
image

**Environment**
- Device: TBD
- Android: TBD
- App version: 0.6-alpha-908d57b2b1

**Additional context**
Device language was selected as Portuguese for testing.
Per discussion with @BenHenning this could be a size length or a text wrapping issue.

### PR DESCRIPTION
**Pull request by coder2699**
## Explanation

Fixes #3827 : [Portuguese] Translated text overlap

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

Screenshot:-

### CODE REVIEW

**Comment by coder2699** [comment]
@srushtirk PTAL

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
@coder2699 Just merge with latest develop after which we can merge this.

**Review by srushtirk — APPROVED** [review]

**Comment by coder2699** [comment]
@rt4914 @srushtirk two tests regarding roboelectric-bazel are failing, can you help me on how to fix them

**Comment by BenHenning** [comment]
> @rt4914 @srushtirk two tests regarding roboelectric-bazel are failing, can you help me on how to fix them

@coder2699 I can help with that.

I think you're hitting an unusual flake in StateFragmentLocalTest that's unrelated to your PR. We recently added a retry mechanism in #3969 that might at least work around this issue. Can you try merging with the latest develop & then see if CI is passing?

**Comment by coder2699** [comment]
> > @rt4914 @srushtirk two tests regarding roboelectric-bazel are failing, can you help me on how to fix them
> 
> @coder2699 I can help with that.
> 
> I think you're hitting an unusual flake in StateFragmentLocalTest that's unrelated to your PR. We recently added a retry mechanism in #3969 that might at least work around this issue. Can you try merging with the latest develop & then see if CI is passing?

@BenHenning , thanks I will try it out

**Comment by coder2699** [comment]
@BenHenning it worked, thanks. @rt4914, PTAL

**Comment by BenHenning** [comment]
Thanks @coder2699. Given this is approved and there are no open comment threads, going ahead & merging this.

**Pull request merged**
