### PR TITLE
Fixes part of #726 : Lowfi Landscape : ProfileList

### LINKED ISSUE #726: Lowfi Landscape: ProfileList
Mock: 
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/0a5af83d-4b03-4a71-bf01-0c0a6e97e0c2/RG-MN-Register-Empty-34/

Currently app supports only portrait mode for `ProfileListActivity`, so add landscape mode too.
Add test cases for landscape mode too.

### PR DESCRIPTION
**Pull request by Sarthak2601**
## Explanation
 
- Fixes #726 
- Landscape XML Addition

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.

**Comment by Sarthak2601** [comment]
> Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.

Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?

**Comment by rt4914** [comment]
> > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> 
> Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?

No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.

**Comment by Sarthak2601** [comment]
> > > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> > 
> > 
> > Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?
> 
> No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.

@rt4914 Actually, in my local all the tests in the project are failing. Maybe there's some glitch. I have added a few tests which are completely based on the previous existing tests. Should I put them up for review or not ? :-)

**Comment by rt4914** [comment]
> > > > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> > > 
> > > 
> > > Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?
> > 
> > 
> > No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.
> 
> @rt4914 Actually, in my local all the tests in the project are failing. Maybe there's some glitch. I have added a few tests which are completely based on the previous existing tests. Should I put them up for review or not ? :-)

Okay got it. It must be because of android studio problem. You will need to downgrade your android studio version to 3.4.2

**Comment by Sarthak2601** [comment]
> > > > > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> > > > 
> > > > 
> > > > Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?
> > > 
> > > 
> > > No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.
> > 
> > 
> > @rt4914 Actually, in my local all the tests in the project are failing. Maybe there's some glitch. I have added a few tests which are completely based on the previous existing tests. Should I put them up for review or not ? :-)
> 
> Okay got it. It must be because of android studio problem. You will need to downgrade your android studio version to 3.4.2

Okay I'll downgrade to 3.4.2 
Thank you :)

**Comment by Sarthak2601** [comment]
> > > > > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> > > > 
> > > > 
> > > > Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?
> > > 
> > > 
> > > No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.
> > 
> > 
> > @rt4914 Actually, in my local all the tests in the project are failing. Maybe there's some glitch. I have added a few tests which are completely based on the previous existing tests. Should I put them up for review or not ? :-)
> 
> Okay got it. It must be because of android studio problem. You will need to downgrade your android studio version to 3.4.2

I downgraded Android Studio to 3.4.2 
But still the tests are failing... 
It gives Assertion error, any further modifications that I should do ?

**Comment by rt4914** [comment]
> > > > > > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> > > > > 
> > > > > 
> > > > > Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?
> > > > 
> > > > 
> > > > No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.
> > > 
> > > 
> > > @rt4914 Actually, in my local all the tests in the project are failing. Maybe there's some glitch. I have added a few tests which are completely based on the previous existing tests. Should I put them up for review or not ? :-)
> > 
> > 
> > Okay got it. It must be because of android studio problem. You will need to downgrade your android studio version to 3.4.2
> 
> I downgraded Android Studio to 3.4.2
> But still the tests are failing...
> It gives Assertion error, any further modifications that I should do ?

No actually, can you share a video or screenshot of that on my email?

**Comment by Sarthak2601** [comment]
> > > > > > > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> > > > > > 
> > > > > > 
> > > > > > Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?
> > > > > 
> > > > > 
> > > > > No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.
> > > > 
> > > > 
> > > > @rt4914 Actually, in my local all the tests in the project are failing. Maybe there's some glitch. I have added a few tests which are completely based on the previous existing tests. Should I put them up for review or not ? :-)
> > > 
> > > 
> > > Okay got it. It must be because of android studio problem. You will need to downgrade your android studio version to 3.4.2
> > 
> > 
> > I downgraded Android Studio to 3.4.2
> > But still the tests are failing...
> > It gives Assertion error, any further modifications that I should do ?
> 
> No actually, can you share a video or screenshot of that on my email?

Sent :)

**Comment by rt4914** [comment]
> > > > > > > > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> > > > > > > 
> > > > > > > 
> > > > > > > Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?
> > > > > > 
> > > > > > 
> > > > > > No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.
> > > > > 
> > > > > 
> > > > > @rt4914 Actually, in my local all the tests in the project are failing. Maybe there's some glitch. I have added a few tests which are completely based on the previous existing tests. Should I put them up for review or not ? :-)
> > > > 
> > > > 
> > > > Okay got it. It must be because of android studio problem. You will need to downgrade your android studio version to 3.4.2
> > > 
> > > 
> > > I downgraded Android Studio to 3.4.2
> > > But still the tests are failing...
> > > It gives Assertion error, any further modifications that I should do ?
> > 
> > 
> > No actually, can you share a video or screenshot of that on my email?
> 
> Sent :)

@sarthak2601 Your issue is correct, unfortunately I don't know the correct solution for that yet. But because of that let's not block you on this. Lets divide our work in two parts:
1. I will finish the landscape part with test cases.
2. You can finish the final HighFi part of this Activity, as the final highfi does not need any test cases.

How does this sound to you?

**Comment by Sarthak2601** [comment]
> > > > > > > > > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?
> > > > > > > 
> > > > > > > 
> > > > > > > No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.
> > > > > > 
> > > > > > 
> > > > > > @rt4914 Actually, in my local all the tests in the project are failing. Maybe there's some glitch. I have added a few tests which are completely based on the previous existing tests. Should I put them up for review or not ? :-)
> > > > > 
> > > > > 
> > > > > Okay got it. It must be because of android studio problem. You will need to downgrade your android studio version to 3.4.2
> > > > 
> > > > 
> > > > I downgraded Android Studio to 3.4.2
> > > > But still the tests are failing...
> > > > It gives Assertion error, any further modifications that I should do ?
> > > 
> > > 
> > > No actually, can you share a video or screenshot of that on my email?
> > 
> > 
> > Sent :)
> 
> @Sarthak2601 Your issue is correct, unfortunately I don't know the correct solution for that yet. But because of that let's not block you on this. Lets divide our work in two parts:
> 
> 1. I will finish the landscape part with test cases.
> 2. You can finish the final HighFi part of this Activity, as the final highfi does not need any test cases.
> 
> How does this sound to you?

Great ! Let's do it. 
About the HighFi part.. is there some existing issue? 
And how are we going to go about it ? Like should I assign this PR to you or implement the HiFi in this only.

**Comment by rt4914** [comment]
> > > > > > > > > > Please add test cases also. Always make sure that appropriate test cases are added before requesting a review.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Actually, I wanted to talk about that. Whenever I run the existing test cases, they fail. Is there any thing specific that causes them to fail ?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > No actually they should not fail in develop code. If they are failing by chance, fix them in your PR, if you can or else inform me and I will create a separate PR for that to fix them.
> > > > > > > 
> > > > > > > 
> > > > > > > @rt4914 Actually, in my local all the tests in the project are failing. Maybe there's some glitch. I have added a few tests which are completely based on the previous existing tests. Should I put them up for review or not ? :-)
> > > > > > 
> > > > > > 
> > > > > > Okay got it. It must be because of android studio problem. You will need to downgrade your android studio version to 3.4.2
> > > > > 
> > > > > 
> > > > > I downgraded Android Studio to 3.4.2
> > > > > But still the tests are failing...
> > > > > It gives Assertion error, any further modifications that I should do ?
> > > > 
> > > > 
> > > > No actually, can you share a video or screenshot of that on my email?
> > > 
> > > 
> > > Sent :)
> > 
> > 
> > @Sarthak2601 Your issue is correct, unfortunately I don't know the correct solution for that yet. But because of that let's not block you on this. Lets divide our work in two parts:
> > 
> > 1. I will finish the landscape part with test cases.
> > 2. You can finish the final HighFi part of this Activity, as the final highfi does not need any test cases.
> > 
> > How does this sound to you?
> 
> Great ! Let's do it.
> About the HighFi part.. is there some existing issue?
> And how are we going to go about it ? Like should I assign this PR to you or implement the HiFi in this only.

Let's close this PR. I will work on the this issue in a separate PR. You can till than work on https://github.com/oppia/oppia-android/issues/839

**Pull request closed without merging**
