### PR TITLE
Fix #4169 : Topic name text is cut off in topic_info_fragment for ratios and proportional reasoning

### LINKED ISSUE #4169: Topic name text is cut off in topic_info_fragment for ratios and proportional reasoning
**Describe the bug**
Text in `topic_name_text_view` under topic_info_fragment for `Ratios and Proportional Reasoning` is extending outside screen borders.

**To Reproduce**
1. Go to All Topics.
2. Click on Ratios and Proportional Reasoning.
3. See error

**Expected behavior**
Topic name should be completely visible.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

**Environment**
- Device/emulator being used: Pixel 3A
- Android or SDK version (e.g. Android 5 or SDK 21): API 28

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

Fix #4169 : Topic name text is cut off in `topic_info_fragment` for ratios and proportional reasoning

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

<table role="table">
<thead>
<tr>
<th>Before Screenshots Mobile</th>
<th>After Screenshots Mobile</th>
</tr>
</thead>
<tbody>
<tr>
<td>Screenshot_20210804_152357</td>
<td>Screenshot_20210804_152357</td>
</tr>
<tr>
<td>Screenshot_20210804_152412</td>
<td>Screenshot_20210804_152412</td>
</tr>

<tr>
<td>Screenshot_20210804_152357</td>
<td>Screenshot_20210804_152357</td>
</tr>
<tr>
<td>Screenshot_20210804_152412</td>
<td>Screenshot_20210804_152412</td>
</tr>

<table role="table">
<thead>
<tr>
<th>Before Screenshots Tablet</th>
<th>After Screenshots Tablet</th>
</tr>
</thead>
<tbody>
<tr>
<td>Screenshot_20210804_152357</td>
<td>Screenshot_20210804_152357</td>
</tr>
<tr>
<td>Screenshot_20210804_152412</td>
<td>Screenshot_20210804_152412</td>
</tr>

<tr>
<td>Screenshot_20210804_152357</td>
<td>Screenshot_20210804_152357</td>
</tr>
<td>Screenshot_20210804_152412</td>
<td>Screenshot_20210804_152412</td>
</tr>

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@rt4914 I close the last and open that for the cutoff issue, can you please review that.

**Comment by MohitGupta121** [comment]
@rt4914 I already add reviewer to you.
Can you please check it's done or not.

**Comment by rt4914** [comment]
@MohitGupta121 You should change the user in "Assignees" section. I just did that. "Assignees" section point to the person who has to take action. For example once I review and suggest changes, I will assign it to you so that you can know that you have to work on it now.

**Comment by MohitGupta121** [comment]
> @MohitGupta121 You should change the user in "Assignees" section. I just did that. "Assignees" section point to the person who has to take action. For example once I review and suggest changes, I will assign it to you so that you can know that you have to work on it now.

Okay sure

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.

**Comment by MohitGupta121** [comment]
> LGTM, Thanks.

Thanks you 😊

**Pull request merged**
