### PR TITLE
Fix #823:Introduce question player ui update -question content item Hi-fi 

### LINKED ISSUE #823: Question Player Content item UI update -Hi-fi
Question Player Content item UI update -Hi-fi
## Mock
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8fbb663a-39aa-4be1-83bd-73bde6f85dcc/PM-Q1-Fraction-Input-No-Answer-

### PR DESCRIPTION
**Pull request by nikitamarysolomanpvt**
## Explanation
Question Player Content item UI update -Hi-fi
## Mock
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8fbb663a-39aa-4be1-83bd-73bde6f85dcc/PM-Q1-Fraction-Input-No-Answer-
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
Screenshot_1584447138

The image background is not correct. As this is High-fi we will need to fix this also.

**Comment by nikitamarysolomanpvt** [comment]
> Screenshot_1584447138
> 
> The image background is not correct. As this is High-fi we will need to fix this also.

@rt4914 We are getting images with white borders PTAL on below link
https://storage.googleapis.com/oppiatestserver-resources/skill/5RM9KPfQxobH/assets/image/img_20191031_012521_sq67z4euz8_height_132_width_145.png 
@seanlip Is it possible to get images with transparent background or no background colors from backend?.

**Comment by rt4914** [comment]
> > Screenshot_1584447138
> > The image background is not correct. As this is High-fi we will need to fix this also.
> 
> @rt4914 We are getting images with white borders PTAL on below link
> https://storage.googleapis.com/oppiatestserver-resources/skill/5RM9KPfQxobH/assets/image/img_20191031_012521_sq67z4euz8_height_132_width_145.png @seanlip Is it possible to get images with transparent background or no background colors from backend.

Okay, in that case it is something which cannot be controller from android app. Thanks.

**Review by rt4914 — APPROVED** [review]
LGTM.

**Comment by nikitamarysolomanpvt** [comment]
#889 duplicate

**Pull request closed without merging**
