### PR TITLE
Fix #1762 : Navigation drawer cancel switch profile always mark home

### LINKED ISSUE #1762: NavigationDrawer cancel switch profile always mark home
**Describe the bug**
After cancelling the exit profile dialog, home menu get's marked no matter on which menu I was on previously 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open nav drawer
2. click option
3. open nav drawer
4. click switch profile
5. click cancel
6. home gets marked but we are on the options screen

**Expected behaviour**
Mark that menu Item which was on the screen before opening the switch dialog not home as always

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation
Fixes #1762 
Navigation drawer now shows the correct last marked item

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

**Sample bug-fix video**
last

### CODE REVIEW

**Comment by prayutsu** [comment]
@anandwana001 PTAL

**Comment by anandwana001** [comment]
@prayutsu Could you post a complete bug fix for this including below points:
 - try checking options menu
 - try checking help menu
 - try checking administrator controls menu (this might need some extra effort)

Two of the bugs I see is while changing orientation when we are on administrator control
1. open nav drawer -> Go to the Administrator control 
2. open nav drawer -> Click on the Administrator control -> some weird lag will come up

1. Sometimes when we are on the Administrator control and switch profile clicks and cancel and while orientation change both switch profile and Administrator control gets selected
didn't remember the exact steps to repo this issue but this arises when we change orientation and do some cancel stuff with switch profile

Also, test your implementation by changing orientation in multiple cases if selections are there or not
This PR might be blocked on https://github.com/oppia/oppia-android/pull/1757

**Comment by prayutsu** [comment]
> @prayutsu Could you post a complete bug fix for this including below points:
> 
> * try checking options menu
> * try checking help menu
> * try checking administrator controls menu (this might need some extra effort)
> 
> Two of the bugs I see is while changing orientation when we are on administrator control
> 
> 1. open nav drawer -> Go to the Administrator control
> 2. open nav drawer -> Click on the Administrator control -> some weird lag will come up
> 3. Sometimes when we are on the Administrator control and switch profile clicks and cancel and while orientation change both switch profile and Administrator control gets selected
>    didn't remember the exact steps to repo this issue but this arises when we change orientation and do some cancel stuff with switch profile
> 
> Also, test your implementation by changing orientation in multiple cases if selections are there or not
> This PR might be blocked on #1757

Currently, it's working fine only with the options menu and help menu, and I can try fixing it for administrator controls as well, but other mentioned bugs (on orientation change) might not get fixed. I think this should be tackled once #1757 gets completed.

**Comment by prayutsu** [comment]
@rt4914 What's your say? Should I try it further?

**Comment by anandwana001** [comment]
> > @prayutsu Could you post a complete bug fix for this including below points:
> > 
> > * try checking options menu
> > * try checking help menu
> > * try checking administrator controls menu (this might need some extra effort)
> > 
> > Two of the bugs I see is while changing orientation when we are on administrator control
> > 
> > 1. open nav drawer -> Go to the Administrator control
> > 2. open nav drawer -> Click on the Administrator control -> some weird lag will come up
> > 3. Sometimes when we are on the Administrator control and switch profile clicks and cancel and while orientation change both switch profile and Administrator control gets selected
> >    didn't remember the exact steps to repo this issue but this arises when we change orientation and do some cancel stuff with switch profile
> > 
> > Also, test your implementation by changing orientation in multiple cases if selections are there or not
> > This PR might be blocked on #1757
> 
> Currently, it's working fine only with the options menu and help menu, and I can try fixing it for administrator controls as well, but other mentioned bugs (on orientation change) might not get fixed. I think this should be tackled once #1757 gets completed.

Yes, I guess. By the time we car wrap your previous PR - https://github.com/oppia/oppia-android/pull/1740

**Comment by prayutsu** [comment]
Closing this PR as this branch got deleted by mistake. New PR - #1816

**Pull request closed without merging**
