### PR TITLE
Fix part of #726 Lowfi Landscape: ProfileList

### PR DESCRIPTION
**Pull request by rounaakk**
## Explanation

Fix part of #726 added landscape layout for profile_list_activity.xml

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by SayantanBanerjee16** [comment]
@Rounak122 Update the PR Title to :-

Fix part of #726: Lowfi Landscape: ProfileList 

Thanks :)

**Comment by rounaakk** [comment]
Done @SayantanBanerjee16 can you please check the files changed if they are ok or not.

**Review by SayantanBanerjee16 — CHANGES_REQUESTED** [review]
Don't push these systems codes (`.idea/gradle.xml `and `.idea/codeStyles/Project.xml`) auto-generated by Android Studio. Please revert them back.

Also, add test cases related to the landscape mode. For adding test case, refer to the page https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing to get started and particularly read the Espresso section as it relates to UI testing. There are already many tests written in the project. You can refer to them.

**Comment by rt4914** [comment]
@SayantanBanerjee16 Thanks for initial review on this PR.

**Comment by rt4914** [comment]
Closing this PR as @Rounak122 Is busy right now. Will assign him new issue once he is back.

**Pull request closed without merging**
