### PR TITLE
Fix #3394: Ktlint Custom RuleSet

### LINKED ISSUE #3394: Ktlint check comment block
**Describe the bug**
Currently, ktlint is not catching the comment block bad format.

```kt
/**
 * 
 * 
 * */
```

**Expected behavior**
Ktlint should catch this bad format. 

Correct format
```kt
/**
 *
 */
```

### PR DESCRIPTION
**Pull request by manas-yu**
Fix: #3394
This PR introduces two key features:

- **Custom Ruleset Provider**: A new custom ruleset provider is implemented, allowing the integration of custom Ktlint rules.

- **KDocFormatRule**: The `KDocFormatRule` is added to enforce correct closing syntax in KDoc comments.

To create the JAR file for the custom ruleset:
`gradlew.bat :utility:customRulesJar`

Use the custom ruleset with Ktlint by executing:
`ktlint --ruleset=../oppia-android-tools/custom-ktlint-rules.jar "path/to/file"`

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by manas-yu** [comment]
@adhiamboperes PTAL, i will integrate the custom rules into scripts too.
please review and tell if there is anything else to do.

**Comment by manas-yu** [comment]
@adhiamboperes The best solution to this issue seems to be creating a custom ruleset for KtLint. However, generating the custom rules JAR file will require running the command `gradlew.bat :utility:customRulesJar` as part of the script execution.

**Review by adhiamboperes — COMMENTED** [review]
@manas-yu, after reviewing this solution, I do not think it is the best approach to solve this for now. Your solution proposes a custom Gradle integration, which is not ideal for two reasons:
1. This won't work with Bazel, and we will soon remove Gradle in favor of Bazel. https://github.com/oppia/oppia-android/issues/4106 proposes creating Bazel scripts for lint checks, to run in parallel with our existing custom Bash scripts until Gradle is removed.
2. https://github.com/oppia/oppia-android/issues/2799 proposes using ktfmt, which is still pending invvestigation.

https://github.com/oppia/oppia-android/issues/3195 was created to track KDoc checks. Ben's [comment](https://github.com/oppia/oppia-android/issues/3195#issuecomment-2026392849) was inconclusive on the approach (cc/ @jainv4156). It is my opinion that the two best options for this issue is:
1. Use the existing script pattern to write a script that a)finds Kdocs and b)checks the Kdoc formatting.
2. Investigate and do a writeup on https://github.com/oppia/oppia-android/issues/2799, e.g. https://github.com/oppia/oppia-android/issues/1720#issuecomment-2471691984, so we can make a decision on how to go about this.

Either way, I am closing this PR, and you can create a new. replacement once we have chosen a better approach. (Please feel free to use Discussions or the relevant issue thread to explore options.)

**Comment by manas-yu** [comment]
I encountered some issues with this approach, so i marked it as a draft to investigate further. If I find a more effective solution, I’ll open a new PR.

**Pull request closed without merging**
