### PR TITLE
Fix #2309: Changes in Content Item View [A11y]

### LINKED ISSUE #2309: Changes in Content Item View [A11y]
**Describe the bug**

Content Item View is not fully compatible with some users from the Accessibility point of view.

Issue - The height of the text view inside a content_item.xml is 22dp where for a clickable view the required height is 48dp

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start First Test Topic Exploration
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

|  |  | 
|:-------:|:-------:|
| Screenshot_2020-12-17-11-04-27-58_80a9469f53bfe75dbc6e8989be28e2f0 (2) | Screenshot_2020-12-17-11-05-08-10_80a9469f53bfe75dbc6e8989be28e2f0 (1) |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Certain Views does not have the correct contrast ratios (Inactive state) as mentioned in the screenshots. To solve this, one must find a way to make the views disabled instead of being in non-clickable state only

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

### PR DESCRIPTION
**Pull request by Mehul-Bisht**
## Explanation

  
  Fixes #2309 Changes in Content Item View [A11y]
  fixed accessibility issues with content item views for all layouts
  
  ## Portrait Mode
| Before | After |
:-------------------------:|:-------------------------:
portrait_before_feedback | portrait_content_after

## Landscape Mode
| Status |
:-------------------------:
## Before changes
land_before_feedback

## After changes
landscape_content_after

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Mehul-Bisht** [comment]
@ARJUPTA kindly tell me about any required changes.

**Comment by Arjupta** [comment]
@rt4914 can you rerun the tests

**Review by rt4914 — CHANGES_REQUESTED** [review]
The overall logic in this PR is correct (which is shifting the outer padding to TextView's padding.)
But this current implementation will work for exploration player and will give bad results for question player.
Go to Fractions -> Practice -> Select few skills -> Start. This is question player.

## Question Player After


## Question Player Before


The content is slightly displaced.

**Comment by Mehul-Bisht** [comment]
> The overall logic in this PR is correct (which is shifting the outer padding to TextView's padding.)
> But this current implementation will work for exploration player and will give bad results for question player.
> Go to Fractions -> Practice -> Select few skills -> Start. This is question player.
> 
> ## Question Player After
> 
> 
> ## Question Player Before
> 
> 
> The content is slightly displaced.

@rt4914 So any suggestions from your side that I can implement in this PR?

**Comment by Arjupta** [comment]
> @rt4914 So any suggestions from your side that I can implement in this PR?

@Mehul-Bisht try to change the question_view padding dimensions according to the exploration_view padding.

**Comment by Mehul-Bisht** [comment]
> > @rt4914 So any suggestions from your side that I can implement in this PR?
> 
> @Mehul-Bisht try to change the question_view padding dimensions according to the exploration_view padding.

@ARJUPTA @rt4914 Inside the feedback_item the questionViewPadding is already set to 0 dp, and I find the output for before and after to be exactly same on my real device ( Asus Max Pro M1 ). Is there anything else that can help me solving this issue?

**Review by rt4914 — CHANGES_REQUESTED** [review]
@Mehul-Bisht Following approach might help.
For working on such PRs you need to make sure that the initial margin/padding for any view does not change after this PR. Now considering that you have added padding to internal item that means that we will need to subtract similar amount of padding or margin from its outer item. 
Based on this theory I can confirm that the current solution does change the UI.
Now, unfortunately working on this issue is really complex and require lot of concentration. I did try to solve it but turned out that I wrote one number incorrectly and which resulted in my completed UI to be incorrect.
You will need to first find out the existing padding/margin for items and then subtract from one attribute and add same amount to another attribute to adjust these things.

If this approach does not make sense, it's fine. Also, if you want to leave this issue, that's also fine.

**Comment by Luffy18346** [comment]
@Mehul-Bisht any updates on this?

**Comment by Mehul-Bisht** [comment]
> @Mehul-Bisht any updates on this?

@Luffy18346 I will see this again today and let you know.

**Comment by Luffy18346** [comment]
> > @Mehul-Bisht any updates on this?
> 
> @Luffy18346 I will see this again today and let you know.

Ok thanks.

**Comment by Mehul-Bisht** [comment]
@rt4914 @ARJUPTA The issue is fixed now, kindly review

**Comment by Mehul-Bisht** [comment]
@rt4914 @ARJUPTA any further updates from you on the latest changes?

**Comment by rt4914** [comment]
@Mehul-Bisht Checking this PR only.

**Comment by Arjupta** [comment]
> @rt4914 @ARJUPTA any further updates from you on the latest changes?

Testing it

**Comment by Arjupta** [comment]
Screenshot_1612350335

@rt4914 should the content_item cover the screen width like this only? I checked it with develop and it looked the same.

**Comment by rt4914** [comment]
@rt4914 Yes, I noticed this issue. I will fix it and mostly this issue too. Just wait for today and I will update you guys.

**Comment by rt4914** [comment]
@ARJUPTA and @Mehul-Bisht 

Update:
This above issue is solved in https://github.com/oppia/oppia-android/pull/2608

Also, review the above PR as it will solve the issue number #2309 currently assigned to Mehul but I am assigning it to myself now considering based on PRs I create Mehul can follow similar steps for the Feedback related UI. 

@Mehul-Bisht Similar to what I have done in #2608 You can create a similar PR for `feedback item` (not right now as there will be conflicts but later on when #2608 is merged completely). This way you will be actually either code or review one major UI portion for which we have been dependent on me because of its complexity but if you review my PRs and follow that same approach in your PRs I think we can create a nice pattern and fix entire Question and Exploration Player.

**Comment by Luffy18346** [comment]
@ARJUPTA and @Mehul-Bisht  PTAL

**Comment by rt4914** [comment]
> @ARJUPTA and @Mehul-Bisht PTAL

@Luffy18346 PTAL at my previous comments. This PR will take time.

**Comment by Luffy18346** [comment]
> > @ARJUPTA and @Mehul-Bisht PTAL
> 
> @Luffy18346 PTAL at my previous comments. This PR will take time.

Ok thanks

**Comment by BenHenning** [comment]
@Mehul-Bisht please update this with the latest changes from develop. I think you have some conflicts that need to be resolved.

**Comment by Mehul-Bisht** [comment]
@rt4914 Can this PR and #2311 be merged now?

**Comment by rt4914** [comment]
@Mehul-Bisht No actually there is lot of verification steps pending in this. Suggest closing both the PRs and I will be creating PRs so that I can send to you for review. These PRs mainly need following steps:
1. First checking that current code looks correct as per the mocks, if not then we need to fix it.
2. Once fixed adjust the padding/margin so that the app passes on scanner. t

The verification part is too long because there are two many situations for each xml file.

**Comment by Mehul-Bisht** [comment]
> @Mehul-Bisht No actually there is lot of verification steps pending in this. Suggest closing both the PRs and I will be creating PRs so that I can send to you for review. These PRs mainly need following steps:

Ok, yes send to me for review then.

**Comment by rt4914** [comment]
Closing this, as this will get covered once the entire Highfi work of Explorations/Question player is finished.

**Pull request closed without merging**
