### PR TITLE
Fix #2518 : Optimise onboarding fragment portrait layout

### LINKED ISSUE #2518: Optimise onboarding_fragment.xml portrait layout
The layout tree of `onboarding_fragment` (phone-portrait) can be optimized by removing the extra parent layout.

**Solution -**
Optimize the layout by deleting extra parent layouts and make it similar to the landscape version

### PR DESCRIPTION
**Pull request by chrk2205**
## Explanation

Fixes #2518 
In `onboardingfragment` a framelayout has been removed, preserving the previous view.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

after video
https://user-images.githubusercontent.com/44704035/105514673-c7956180-5cf9-11eb-9837-27b0fa612817.mp4

before
Screenshot_20210122-173112

After
Screenshot_20210122-173459

### CODE REVIEW

**Review by prayutsu — APPROVED** [review]
@chrk2205 LGTM, just add a video in the PR description in which you scroll to different slides.

**Comment by chrk2205** [comment]
> @chrk2205 LGTM, just add a video in the PR description in which you scroll to different slides.

Thanks @prayutsu 
Added the required video to PR description

**Comment by rt4914** [comment]
Will check this on Monday.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
