### PR TITLE
 Fixed Issue #2809. 'AddProfileActivity' Label Added in AndroidManifest.xml.

### PR DESCRIPTION
**Pull request by ihrishix**
## Explanation
 Fixed Issue #2809 

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
@rushikeshsuryawanshi Could you please check the Checklist in the PR description and follow as per given? Let me know if need any help. 

Also, check a reference PR for similar issues - https://github.com/oppia/oppia-android/pull/2750

**Comment by rt4914** [comment]
@rushikeshsuryawanshi In this original issue I have mentioned one sample PR. Please take guidance from that and create this PR accordingly.

**Comment by ihrishix** [comment]
@anandwana001 Do i need to check all boxes ? My PR doesn't fix any bug . So can't check the first one 
Also, if you could please tell me what to do exactly. I'm new to OpenSource. This is my First PR

**Comment by prayutsu** [comment]
Hi @rushikeshsuryawanshi 
I suggest looking at our [wiki](https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change) for making a code change.
Also, the checkboxes in the PR explanation refer to the PR title, PR explanation, and our other PR guidelines.
- Tick the first checkbox if your PR title starts with `Fix #issueNumber` e.g- `Fix #2809: Add label for AddProfileActivity`. If your title doesn't match with those formats, you should change the title and then tick the box.
- Tick the second checkbox if you have included `Fixes #issueNumber` in the PR explanation(it should not include any other words in between) e.g - `Fixes #2809: Added a label to the AndroidManifests.xml for AddProfileActivity`.

Similarly for other checkboxes.

**Comment by rt4914** [comment]
Closing this because of no updates for a week.

**Pull request closed without merging**
