### PR TITLE
Fix #3959: Bump version codes for new release-0.6 RC

### LINKED ISSUE #3959: Bump version codes since a rebuild of 0.6 is needed
Per https://github.com/oppia/oppia-android/pulls?q=is%3Apr+label%3A%22PR%3A+Cherrypick+requested%22+milestone%3A%22Alpha+MR3%22+ there are PRs that need to be cherry-picked into release-0.6. Thus, we need to bump version codes so that a rebuild can occur.

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fix #3959

This PR bumps the version codes so that a new release-0.6 release candidate can be created.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A

### CODE REVIEW

**Comment by BenHenning** [comment]
@anandwana001 PTAL.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Comment by BenHenning** [comment]
Thanks @anandwana001!

**Comment by BenHenning** [comment]
This requires no further verification for the release-0.6 build.

**Pull request merged**
