### PR TITLE
Fixes part of #3325: Add ExplorationStorageModule to UI tests

### LINKED ISSUE #3325: Implement domain layer mechanism to save checkpoints
Modify the class of the domain layer to implement checkpointing. 

Target | Date
--|--
**PR creation:** | 2021-06-24
**PR completion:** | 2021-06-29

### PR DESCRIPTION
**Pull request by MaskedCarrot**
## Explanation

Fixes part of #3325 

This PR is stacked on top of PR #3337 

This PR adds the ExplorationStorageModule to UI tests so that the app layer tests do not fail once the mechanism to save checkpoints is introduced.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by MaskedCarrot** [comment]
@aggarwalpulkit596 PTAL.

**Review by aggarwalpulkit596 — APPROVED** [review]

**Comment by vinitamurthi** [comment]
@MaskedCarrot this seems to be mainly UI related. Is there anything I need to take a pass on? The test in the domain layer LGTM

**Comment by MaskedCarrot** [comment]
@vinitamurthi This PR just adds a dagger module to all test files.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by vinitamurthi — APPROVED** [review]

**Comment by BenHenning** [comment]
It appears my review isn't needed here. Assigning back to you @MaskedCarrot.

**Pull request merged**
