### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by BobinMathew**
## Explanation

Having a CODE_OF_CONDUCT.md file in the repository will strengthen your community profile.
## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@BobinMathew I think we already have it. https://github.com/oppia/oppia-android/blob/develop/.github/CODE_OF_CONDUCT.md

**Comment by BenHenning** [comment]
Hi @BobinMathew thanks much for creating this PR--I'm glad you identified the importance of having a code of conduct. As @rt4914 mentioned we fortunately already have on checked in, so no additional work is needed here. :) So far as we can tell, the code of conduct is properly hooked up to GitHub as well (e.g. it shows up when creating new PRs & issues), so it seems like it's been set up correctly. Please let us know if you noticed any discrepancies in the code of conduct or how it was setup.

Closing this PR since no additional work is needed here.

**Comment by BobinMathew** [comment]
image
The CODE_OF_CONDUCT.md file is not reflected on your community profile that's why I created one.

**Comment by BenHenning** [comment]
Ah interesting. That profile seems incorrect on multiple accounts: we do have a PR template, contributing guidelines, code of conduct, and README. It surprises me that GitHub supports multiple locations for these files elsewhere but not on the community profile.

**Comment by BenHenning** [comment]
Interesting. This might also be because we use a very slightly modified version of the contributor covenant. Apparently GitHub expects a specific code of conduct without changes per https://github.community/t/code-of-conduct-is-present-in-repo-but-insights-community-tab-doesnt-detect-it/1534/7. Not yet sure why the others aren't working.

**Comment by BenHenning** [comment]
Yeah...I think this is just broken. It thinks we don't have a readme, but clicking 'edit' goes straight to the existing readme.

**Comment by BenHenning** [comment]
Filed #2684 to track improving our community profile. Thanks for bringing this to our attention @BobinMathew!

**Comment by BobinMathew** [comment]
> Filed #2684 to track improving our community profile. Thanks for bringing this to our attention @BobinMathew!

Glad I could be of some help 😀

**Pull request closed without merging**
