### PR TITLE
Fix #4007 : Backstap loop error in profile edit fragment error

### LINKED ISSUE #4007: ProfileEditFragment Backstack loop error
**Describe the bug**
In tablet When we reset or rename the Profile by Administrator controls in ProfileEditFragment and then on Pressing the back button we get stuck in a loop
**To Reproduce**
1. Go to Administrator Controls and click on any profile and then reset the pin or rename the name 
2. Click on the BackButton
3. Again Click on the back button
4. You get stuck in a loop of ProfileEditFragment and ProfileListFragment

**Expected behavior**
You should go back to administrator controls activity after pressing back button

**Demonstration**
|   |    |   |
| - | - | - |
| Screenshot_20211122_210529 | Screenshot_20211122_210618 | Screenshot_20211122_210644 |
| Screenshot_20211122_210701 | Screenshot_20211122_210706 |

https://user-images.githubusercontent.com/76404817/142893869-2f33edc5-0c89-4267-a5ff-af8bfe17f3e4.mp4

**Environment**
- Device/emulator being used: <device version/emulator>
- Android or SDK version : Android 9 Oreo/ api 28
- App version : latest dev

### PR DESCRIPTION
**Pull request by chrk2205**
## Explanation

Fixes #4007
Instead of creating a new activity before submitting I am just finishing the present activity and going to the previous activity.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by chrk2205** [comment]
@yash10019coder some tests are still failing.

**Review by yash10019coder — COMMENTED** [review]
Hi @chrk2205  look for the tests in the file ProfileRenameActivityTest.kt and ProfileResetPinActivityTest.kt and read about intent checking in espresso tests and try to figure out the code in above files in which this intents are checked
Thansk

**Comment by BenHenning** [comment]
Hi. As of today, some main reviewers have taken time off for the next few weeks, so it may take a little while before we can look at this PR. We appreciate your patience while some of our team members recharge. We'll be fully returning on 4 January 2021.

**Comment by yash10019coder** [comment]
Hi @chrk2205 I think that you should not work on this pr as #3241 gets closed then this issue will also get closed so there's no need to do this.

**Comment by chrk2205** [comment]
@yash10019coder 
issue #3241 won't be able to solve this issue. As a part of that is already merged, I cross-checked, and the is still persisting.
and about the failing tests, we cannot make them pass because the tests are starting from that particular activity and when the submit button is closed the one stored in the stack will be opened up, which won't be present in the tests.

**Comment by yash10019coder** [comment]
> @yash10019coder issue #3241 won't be able to solve this issue. As a part of that is already merged, I cross-checked, and the is still persisting. and about the failing tests, we cannot make them pass because the tests are starting from that particular activity and when the submit button is closed the one stored in the stack will be opened up, which won't be present in the tests.

@chrk2205 as we proceed to the step 4 of the issue #3241  then in tablets there will be no activities opening all the fragments will be inflated in the multipane frame layout therefore I think that it might close this issue.

**Pull request closed without merging**
