### PR TITLE
Maybe fix part of #2684: Move PR template to subdirectory

### PR DESCRIPTION
**Pull request by BenHenning**
Maybe fix part of #2684 by moving the PR template to its own subdirectory to have parity with issue templates (per @anandwana001's suggestion [here](https://github.com/oppia/oppia-android/issues/2684#issuecomment-777400643)).

### CODE REVIEW

**Comment by BenHenning** [comment]
Note that we won't know if this is working until after the PR is merged.

**Comment by FareesHussain** [comment]
> Note that we won't know if this is working until after the PR is merged.

I think we can test this in a forked repo.

**Comment by BenHenning** [comment]
Are you sure? I thought forks didn't have the community section available. That being said, we could probably test this in a test repository but I also think the organization change here is reasonable & not worth the additional effort.

**Review by anandwana001 — APPROVED** [review]
LGTM, let's try this out, apart from checks are failing. 

If fixing the test takes more time, then we can try at any other test profile.

**Comment by BenHenning** [comment]
Test failure is a flake, but the codeowners file one seems legitimate. Will update codeowners and get Sean's approval.

**Comment by BenHenning** [comment]
@seanlip PTAL for codeowners.

**Review by seanlip — APPROVED** [review]

**Comment by BenHenning** [comment]
Thanks!

**Pull request merged**
