### PR TITLE
Fix #4765: The Continue animation isn't interactive

### LINKED ISSUE #4765: The Continue animation isn't interactive
**Describe the bug**

The current continue button animation is too subtle and the user has to squint carefully to see what is going on.

### PR DESCRIPTION
**Pull request by JishnuGoyal**
## Explanation

fixes #4765

This PR tries to handle the problem of the continue interaction button's animation not being eye-catching to the users. Currently, it does so by augmenting the intensity of the scale in animation. Only with further testing and trial, will we know how the animation appeals to the users and resolves the problem at hand.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

https://user-images.githubusercontent.com/64526117/204109499-127e7c54-05bc-4473-8b02-41aaa1b2608b.mp4

### CODE REVIEW

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning . Assigning this to you to have a look at the high level if everything looks correct and in the going (which is a requirement stated in the email). The current status of the work is, the animation works such that-
half pulse -- stop for 1 sec -- half pulse.

The suggested animation by @seanlip is:
full pulse -- stop for 1 sec -- repeat

I'm currently facing some trouble achieving the suggested anim flow.

**Comment by seanlip** [comment]
> I'm currently facing some trouble achieving the suggested anim flow.

@JishnuGoyal In order for Ben to help you effectively, I would suggest creating a [debugging doc](https://github.com/oppia/oppia/wiki/Debugging-Docs) that explains what you've tried, what is wrong with what you observe, and where exactly you're stuck with. Feel free to link it here.

**Comment by seanlip** [comment]
Also @JishnuGoyal I don't see a screencast in the PR description?

**Comment by JishnuGoyal** [comment]
Hello @seanlip , I have updated the description by adding the video for reference. I have also had a chat with Ben about fixing it, and will be discussing this further when he's available.

**Comment by JishnuGoyal** [comment]
Attaching a debug doc: https://docs.google.com/document/d/1w5zCq-tEEQID2IY3hPFLxObcPy6X3zWyEc4iLTyynV4/edit#

**Comment by BenHenning** [comment]
@JishnuGoyal is the video in the opening comment still up-to-date? Also, could you bring this up-to-date with the latest develop changes?

**Pull request closed without merging**
