### PR TITLE
Fix part of #4203 : Renamed colors to contain file name for CI regex checks.

### PR DESCRIPTION
**Pull request by ayush0402**
## Explanation

Fixes part of #4203 
Renaming color in all 4 color files to contain file name as prefix to help writing checks using existing regex scripts.
Creating this PR as per discussion with Ben on #4205 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by ayush0402** [comment]
@rt4914 Updated the color names. PTAL.

**Comment by ayush0402** [comment]
@rt4914 PTAL now.

**Comment by rt4914** [comment]
This is solved as per this comment : https://github.com/oppia/oppia-android/pull/4205#issuecomment-1055033468

**Review by rt4914 — APPROVED** [review]
LGTM. Just merge with latest develop.

**Comment by BenHenning** [comment]
I only looked through the first ~20 files, but the approach looks like a good start. Let me know if you'd like me to review the whole PR, but I'm happy to defer to @rt4914 on this.

**Pull request merged**
