### PR TITLE
Fix #2531: Changes in DropShadow[a11y]

### LINKED ISSUE #2531: Changes in DropShadow View [a11y] [BLOCKED on discussion]
**Describe the bug**
 Drop shadow View of TabBar is causing the checkbox directly below it to have an unacceptable contrast ratio and hence Accessibility checks fail here.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start Fraction Exploration
3. Switch to the Practice Tab
4. Keep the device in landscape mode and scroll the contents upwards till the checkboxes start coming directly below it.
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**
|||
|:-:|:-:|
|Screenshot_1611207456|Screenshot_1611207443|

**Device**
- Pixel - 3 Emulator
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

### PR DESCRIPTION
**Pull request by Arjupta**
## Explanation

Fixes #2531 by contraining the Viewpager to be below the dropshadow view
hence introducing a minute UI.

|Before|After|Tests|
|:-:|:-:|:-:|
|Screenshot_1612451419|Screenshot_1612451264|Screenshot_1612449875|

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
This solution won't work because this introduces a gap in UI.

**Comment by rt4914** [comment]
@ARJUPTA Any updates on this?

**Comment by Arjupta** [comment]
> @ARJUPTA Any updates on this?

@rt4914 based on previous discussion I guess we decided to ignore this issue.

**Comment by rt4914** [comment]
Yes, now i remember. Closing this for now.

**Pull request closed without merging**
