### PR TITLE
Fix #2487: Required reformatting for some individual xml files

### LINKED ISSUE #2487: Required reformatting for some individual xml files
The following files require reformatting
 - audio_fragment.xml
 - profile_picture_edit_dialog.xml
 - submitted_html_answer_item.xml
 - test_text_view_for_int_no_data_binding.xml
 - test_text_view_for_int_with_data_binding.xml
 - test_text_view_for_string_no_data_binding.xml
 - test_text_view_for_string_with_data_binding.xml

Recommended to setup [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References 
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

### PR DESCRIPTION
**Pull request by Mehul-Bisht**
## Explanation

Fixes #2487 Required reformatting for some individual xml files.
I used macros in android studio to reformat code and optimise imports for the mentioned individual XML files.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Mehul-Bisht** [comment]
@rt4914 please review the changes.

**Comment by FareesHussain** [comment]
tests needs to be re-run

**Review by chrk2205 — COMMENTED** [review]
LGTM

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
