### PR TITLE
Fix #136: Topic overview download preference save (part 3) [ON HOLD]

### LINKED ISSUE #136: UI Structure: Topic overview tab fragment [Blocked: #135]
This is tracking introducing the UI structure for the topic overview tab.

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

This PR is based on #236 

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/b98da363-bac6-4f7d-b1d2-ee0f9aa048c4/Topic-w-o-Play-8

This PR mainly introduces the TopicDownloadDialogController which saves user preference related to topic download.

Download topic and delete topic low-fi part finished in this PR.

For testing purpose make following change in code:
1. Launcher activity should be `TopicActivity`
2. Inside `TopicActivityPresenter` change `TopicFragment` to `TopicOverviewFragment`

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is **assigned** to an appropriate reviewer.

### CODE REVIEW

**Comment by rt4914** [comment]
@nikitamarysolomanpvt @veena14cs This PR does not contain test but is ready for overview review.

**Review by veena14cs — APPROVED** [review]
LGTM

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Comment by rt4914** [comment]
@BenHenning This PR is ready for your view.

**Comment by BenHenning** [comment]
Since this hasn't seen progress in a while, closing it. We can still use it as a reference, or reopen if we want to continue contributing to this branch.

**Pull request closed without merging**
