### PR TITLE
Fix #4710 Resume Lesson Fragment Button Responsiveness, Icon Layout, and Dark Mode Color

### LINKED ISSUE #4710: Improve support for scaling in resume lesson screen
**Describe the bug**
When we increase the font size to very large and open resume lesson screen the button's won't scaled properly. 

**To Reproduce**
1. Increase font size to very large (largest)
2. Open resume lesson's screen

**Expected behavior**
Buttons in resume lesson screen should scale properly when we have maximum font size. 

**Demonstration**
image

**Environment**
- Device/emulator being used: Nexus 5X
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

### PR DESCRIPTION
**Pull request by XichengSpencer**
Fix #4710 the button scaling problem in largest text setting in the resume fragment, and fix the color change in dark mode.

The use of material button has better control for the icon inside the button so that it can group icons and text together as responsive design guidelines suggested. Particularly the icon gravity part that attached the icon to the text. Also, add flex layout so that button will wrap to two lines when the screen is too small. 

Set app:backgroundTint = "@null" fixes the auto color change made by the app in the dark mode.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:

Here are the testing on my own cell phone, even the second smallest text is too large for the screen so the buttons are wrapped in two rows. Only the smallest text can fit.
|Screenshot 1|Screenshot 2|Screeshot 3|
|--|--|--|
|Weixin Image_20230606114148|Weixin Image_20230606114203|Weixin Image_20230606114209|

- Add a screenshot demonstrating UI of tablet
|Screenshot 1| Screenshot 2|
|--|--|
|Screenshot 2023-06-05 120237|Screenshot 2023-06-05 120223|

LTR
|Screenshot 1|Screenshot 2|Screeshot 3|
|--|--|--|
|Image_20230606114738|Image_20230606114706|Image_20230606114719|

- Dark Mode Fix
| Before | After |
|:------:|:-----:|
| image | image |

|image|image|

### CODE REVIEW

**Review by MohitGupta121 — APPROVED** [review]
@XichengSpencer LGTM, Thanks!

**Review by kkmurerwa — APPROVED** [review]
Hi @XichengSpencer. The PR looks good to me. I have a few issues with the PR title and description. The title could use some more explanation. Something like `Fix #4710: Button Scaling and Dark Mode issues on Resume Lesson Fragment`.  The description should give a general explanation of the changes the fix makes. See PR #5098, #5115, and #5111 for reference.

**Comment by adhiamboperes** [comment]
Hi @XichengSpencer, is this PR ready for my review?

**Review by adhiamboperes — APPROVED** [review]
Thanks @XichengSpencer!

This LGTM.

**Pull request merged**
