### PR TITLE
Fix part of #23: Topic Tab Icons updated

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Topic Tabs updated icons:

Screenshot 2019-12-03 at 12 48 52 AM

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@mschanteltc These icons are way better, but I still think that topic-train icon is comparatively smaller than others, can we fix that?

Thanks.

**Comment by mschanteltc** [comment]
@rt4914 I updated the train icon so that the height and width are equal. All the other icons LGTM.

**Comment by rt4914** [comment]
> @rt4914 I updated the train icon so that the height and width are equal. All the other icons LGTM.

Yeah, the updated train icon looks perfect. Check description for screenshot.

**Comment by mschanteltc** [comment]
It seems that the stroke width of the train icon makes the set of icons appear inconsistent. I updated the train icon again with a different brain image and omitted the weight. Can you update the mock with this new icon please?

**Comment by rt4914** [comment]
> It seems that the stroke width of the train icon makes the set of icons appear inconsistent. I updated the train icon again with a different brain image and omitted the weight. Can you update the mock with this new icon please?

Check this @mschanteltc 
Screenshot 2019-12-03 at 1 21 00 AM

**Comment by mschanteltc** [comment]
Looks good! One last thing is to make sure the sizing of icons fits the [Material Guidelines](https://material.io/design/iconography/system-icons.html#grid-keyline-shapes). I updated the Review Icon to follow these standards, so please update this on mocks.

Overview, Play, and Train icons (circle icons): 

- Height: 20 dp

- Width: 20 dp

Review icon (vertical rectangle icon):

- Height: 20 dp

- Width: 16 dp

**Review by nikitamarysolomanpvt — COMMENTED** [review]
Design looks good to me please address @mschanteltc's suggestions and assign me back.

**Comment by rt4914** [comment]
> Looks good! One last thing is to make sure the sizing of icons fits the [Material Guidelines](https://material.io/design/iconography/system-icons.html#grid-keyline-shapes). I updated the Review Icon to follow these standards, so please update this on mocks.
> 
> Overview, Play, and Train icons (circle icons):
> 
> * Height: 20 dp
> * Width: 20 dp
> 
> Review icon (vertical rectangle icon):
> 
> * Height: 20 dp
> * Width: 16 dp

Used all latest icons from the drive.

Result:
Screenshot 2019-12-03 at 1 21 00 AM

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Comment by mschanteltc** [comment]
LGTM!

**Pull request merged**
