### PR TITLE
Fix #5225: Remove the EnableLanguageSelectionUi Feature Flag

### LINKED ISSUE #5225: [Feature Request]: Remove the EnableLanguageSelectionUi Feature Flag
### Is your feature request related to a problem? Please describe.

Since the EnableLanguageSelectionUi has been officially rolled out, the related feature flag can now be removed.

### Describe the solution you'd like

I would like to have the EnableLanguageSelectionUi feature flag removed from the FeatureFlagConstants file since the feature it was gating has officially been released and is stable. Any of its related constants and dagger module declarations should also be removed. Lastly, I would like the if statements surrounding any functionality that is gated using this feature flag to be removed as well.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kmanikanta335**
## Explanation

Fix https://github.com/oppia/oppia-android/issues/5225

Remove declarations and usages of the EnableLanguageSelectionUi PlatformParameter.

## Essential Checklist

-  The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

-

### CODE REVIEW

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Hi @kmanikanta335, thanks for your PR.

According to the CI results(see: https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results), you still have leftover refrences to the removed platform param. Use Ctrl+Shift+F to search for all usages.

Additionally, please deploy the app locally to confirm nothing is broken, before pushing new commits.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
@kmanikanta335 per the CI results I can see two failing tests for this platform param being disabled. These tests should be removed because we nolonger have this feature flag. `testOptionsFragment_featureDisabled_appLanguageOptionIsNotDisplayed`. 
We have two `OptionsFragmentTest` files.

**Comment by adhiamboperes** [comment]
@kmanikanta335, please resolve the merge conflict, and also upload a screenshot confirming that the failing test is passing locally on your machine.

Once done, please assign the PR back to me.

**Comment by adhiamboperes** [comment]
@kmanikanta335, could you please focus on completing this PR before beginning to work on other issues? Please ask questions in case you need some assistance.

**Comment by kmanikanta335** [comment]
@adhiamboperes 
can you please help in these failing checks

**Comment by adhiamboperes** [comment]
> @kmanikanta335 per the CI results I can see two failing tests for this platform param being disabled. These tests should be removed because we nolonger have this feature flag. `testOptionsFragment_featureDisabled_appLanguageOptionIsNotDisplayed`. We have two `OptionsFragmentTest` files.


I left a comment here explaining what needs to be done. Please let me know of any specific questions that I clarify on.

**Comment by adhiamboperes** [comment]
@kmanikanta335, I reviewed your changes and you still haven't fully addressed my previous comment. You still have a failing test.

**Comment by kmanikanta335** [comment]
@adhiamboperes I hope now its done

**Comment by kmanikanta335** [comment]
@adhiamboperes pls review it

**Review by adhiamboperes — APPROVED** [review]
Thanks @kmanikanta335, this LGTM!

**Pull request merged**
