### PR TITLE
Fix part of #4064: Integrate learner analytics components

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fix part of #4064

This PR integrates the constituent Dagger modules introduced in #4267 broadly in the app so that new logs can be easily added without changing a bunch of files (see #4270).

Some notes on the history of this PR:
- This PR is a rebase of #4257 to remove dependencies on #2173 (which has since been merged into developer) for a much cleaner history.
- This PR is pulling out elements from #4118, #4247, and #4248 which contained completed work by @Sarthak2601.
- This PR extracts just the 'domain integration' pieces from the above, and makes some fixes

For a high-level on the design, please refer to [this design document](https://docs.google.com/document/d/1c8lpH-IUvoU1t4LUoYNqNilP2e9yCnzGnSSG0yBxBrY/edit).

For the most part, this PR only changes module lists except for:
- Changes in ``AnalyticsController`` (& corresponding tests)
- Changes in ``LogUploadWorker`` (& corresponding tests)
- ``OptionsFragmentTest`` (both of them) since they need to provide custom parameter overrides (the new override needed to be added)

The non-test changes above were done to "partially integrate" the necessary pieces that couldn't be done in #4267 without blowing up the PR, and to ensure #4270 can stay focused on just introducing new events & their verification tests.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

N/A -- This PR doesn't make UI changes, and existing flows shouldn't be affected.

### CODE REVIEW

**Comment by BenHenning** [comment]
Still active.

**Comment by BenHenning** [comment]
PTAL @anandwana001 at the whole PR (as you'll be the sole reviewer for this change).

I'm also planning to defer @vinitamurthi's review per earlier conversations.

**Review by anandwana001 — APPROVED** [review]
All LGTM

**Comment by BenHenning** [comment]
Deferring @rt4914's review (tracked in #4266) to help get this merged sooner, and since @anandwana001 has reviewed the whole PR.

**Review by rt4914 — COMMENTED** [review]
Approved for code-owners. Straight-forward changes.

**Pull request merged**
