### PR TITLE
Audio Content highlight [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

This PR function in following way:
If you play audio, the content-card corresponding to it will get highlighted.
If you play audio, the content-card corresponding to it will come to normal.

audio-content

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by seanlip** [comment]
This is nice :) But, when there are multiple parts to be spoken on a page (like the feedback after you submit an answer), does the highlight move accordingly?

**Comment by rt4914** [comment]
> This is nice :) But, when there are multiple parts to be spoken on a page (like the feedback after you submit an answer), does the highlight move accordingly?

Yes it will. The logic is that the highlight is dependent on contentId that we get from AudioPlayer, so  only the corresponding contentId will get highlighted.

But, I still believe if we have a exploration in which we can test this thoroughly, it will be good. @BenHenning any suggestions on any such exploration.

**Comment by seanlip** [comment]
You could just use the fractions "equal parts" lesson and submit some wrong answers, right?

**Comment by rt4914** [comment]
> You could just use the fractions "equal parts" lesson and submit some wrong answers, right?

I did check that it does have everything that we need. But there is one issue, I believe in current audioplayer only first audio is getting played and others are not getting played. Unless, others are not played, we cannot check if this PR works perfectly or not.

@jamesxu0 @BenHenning does Audio player handles multiple audios corresponding to different contentId in same state? If so, then how can we play those multiple audios?

**Comment by rt4914** [comment]
> This is nice :) But, when there are multiple parts to be spoken on a page (like the feedback after you submit an answer), does the highlight move accordingly?

After detailed checking, I have found that, unless and until, multiple audios are not played in same state, this PR won't work. Currently it will fail.

**Comment by BenHenning** [comment]
Once #358 is checked in the audio player should properly switch audio focus between different content IDs in the same state.

**Comment by BenHenning** [comment]
Please re-assign back to me when this is ready to review.

**Comment by mschanteltc** [comment]
This is a great design. What color did you use for the border? I want to make sure I have a copy of this on my mocks. Otherwise LGTM.

**Comment by nikitamarysolomanpvt** [comment]
Please assign back to me once it ready for review.

**Comment by veena14cs** [comment]
Highlighting works nice. But we need to test with other states as discussed in this thread. Assign back once it is ready.

**Comment by rt4914** [comment]
This PR has been recreated on #514 which solves all the issues mentioned in this PR.

**Pull request closed without merging**
