### PR TITLE
Fixes: #2092 dialog dismiss issue fixed

### LINKED ISSUE #2092: Dialog disappears on orientation change
**Describe the bug**
In `ProfileEdit` screen on orientation change if the dialog is already shown, it will disappear.

**To Reproduce**
1. Go to ProfileChooser screen and create atleast 2 profiles.
2. In `ProfileChooser` screen click on `Administrator Controls`
3. Enter your pin and go to `AdministratorControlsActivity`
4. Click `Edit Profiles`
5. Select `non-admin` profile.
6. Scroll and click on `Profile Deletion`
7. Once the alert dialog appears, change the orientation to landscape.
8. Notice that the alert dialog disappears.

**Expected behavior**
Alert dialog should persist on orientation change. Also add test for the same in respective file.

### PR DESCRIPTION
**Pull request by prathamk22**
Fixes: #2092 dialog dismiss issue fixed

ProfileEditViewModel, ProfileEditActivityTest, ProfileEditActivityPresenter is changed

## Explanation
I have added a flag in ProfileEditViewModel to check if dialog is shown or not and dialog flag is changed to false when dialog is dismissed by user.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@prathamk22 Update your PR title to `Fixes #2092: dialog dismiss issue fixed`. `:` should be after the issue number. Also will review it tomorrow. Thanks.

**Comment by FareesHussain** [comment]
@rt4914 as force push is not allowed. Can we close this?

**Comment by rt4914** [comment]
@prathamk22 Please create a new PR as I will have to close this PR because of **force-push**. Force push tampers the commit history which is not correct and it becomes really hard to review such PRs. Also have a look at the wiki instructions its mentioned in there (5. point) that force push is not allowed. https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

Thanks.

**Comment by prathamk22** [comment]
@rt4914 @FareesHussain Sorry for the force push. I had some problem in AS Git, that's why I had to make 7 commits and sometime force push. Sure will make a new PR according to the Styles. 

Thanks

**Pull request closed without merging**
