### PR TITLE
Fix #4602, #4449: Modify the design of the chapter list in lessons tab

### LINKED ISSUE #4449: Modify the design of the chapter list in lessons tab
**Is your feature request related to a problem? Please describe.**
The chapters (recycler items) on the lessons tab do not look clickable. Users do not get an idea of how to start a chapter from that screen.

**Describe the solution you'd like**
Modify the design of the chapter list so that it clearly shows chapters that are completed, ready to start and locked. Also, make sure that the chapter list  drop down is open by default.

### LINKED ISSUE #4602: Develop branch is broken
**Describe the bug**
Two PRs were merged in succession that led to develop breaking, despite no conflicts.

**To Reproduce**
See develop branch.

**Expected behavior**
Develop shouldn't be broken.

**Demonstration**
N/A

**Environment**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by JishnuGoyal**
## Explanation

Fixes #4602
Fixes #4449

In response to the revert commit in #4603, this PR aims to remove an extra resource entry whose collision with [the original PR](https://github.com/oppia/oppia-android/pull/4535) resulted in a breakdown. This PR should also close #4449.

The original PR (which should be referred to for any context on this issue) aims to change the look of the recycler view adapter items on the topic lessons tab.
Now there are different looking item view holders for completed, in-progress, locked and not-started chapter which results in a clear CTA for the users, and they are more likely to click on the correct option. Link to the UI mock: https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/558af437-bec4-4719-8d30-291da10bbc9d/specs/

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @JishnuGoyal. I needed to re-run one workflow due to a timeout, so waiting to see if that passes.

Otherwise, the PR LGTM for code, but for the description and title can you please:
- Make sure to use the original title, but update it to include both issues being fixed
- Make sure to use the original description, but include a new part where you mention the regression & what was specifically changed compared to the original PR (which should be linked) to make it clear what was fixed?

**Comment by JishnuGoyal** [comment]
Thanks,  @BenHenning. PTAL and let me know if further context should be added.

**Comment by JishnuGoyal** [comment]
@BenHenning could this be merged? PTAL, thanks!

**Comment by BenHenning** [comment]
As mentioned over chat, please update the PR to properly include the changes and assign back @JishnuGoyal.

**Comment by JishnuGoyal** [comment]
I'm closing this PR since this has undergone a lot of changes and reversion attempts, and is only going to be difficult to review.
Opening #4621.

**Pull request closed without merging**
