### PR TITLE
Fix #839 : Highfi: StoryTextSizeActgivity

### LINKED ISSUE #839: Highfi: StoryTextSizeActgivity
`StoryTextSizeActivity` needs to be pixel perfect with the mocks.
Portrait Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/OP-Story-Text-Size-
Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/OP-Story-Text-Size-

Mocks have been created for HDPI Devices.
Make sure that the screen passes the accessibility test also.
For reference you can checkout: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by Sarthak2601**
## Explanation

- Fixes #839 
- Made both the XMLs according to the mocks 
- Portrait Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/OP-Story-Text-Size-
- Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/OP-Story-Text-Size-
- Tested in Accessibility Scanner. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by nikitamarysolomanpvt — COMMENTED** [review]
Lines/tick/intervals on seek bar is not found please add them.

**Comment by veena14cs** [comment]
There is typo error in your PR title, please correct it.

**Comment by veena14cs** [comment]
Please add intervals to the seekbar.

**Comment by rt4914** [comment]
Closing this PR as the developer was not able to finish this and I have already finish this now.

**Comment by Sarthak2601** [comment]
> Closing this PR as the developer was not able to finish this and I have already finish this now.

Hey @rt4914, 
I am sorry, I got caught up in the GSoC proposal. 
Was hoping to get back to contributing today, no problem. 
Can you please assign me something else :)

**Comment by rt4914** [comment]
> > Closing this PR as the developer was not able to finish this and I have already finish this now.
> 
> Hey @rt4914,
> I am sorry, I got caught up in the GSoC proposal.
> Was hoping to get back to contributing today, no problem.
> Can you please assign me something else :)

We will start assigning you issues by this weekend. Thanks.

**Comment by Sarthak2601** [comment]
> > > Closing this PR as the developer was not able to finish this and I have already finish this now.
> > 
> > 
> > Hey @rt4914,
> > I am sorry, I got caught up in the GSoC proposal.
> > Was hoping to get back to contributing today, no problem.
> > Can you please assign me something else :)
> 
> We will start assigning you issues by this weekend. Thanks.

Okay, looking forward to it. :)

**Pull request closed without merging**
