### PR TITLE
Fix part of #1824 : Full UI: Tablet: StoryActivity Landscape + Portrait 

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation

Fixes part of #1824
Added layout files for tablet
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by prayutsu** [comment]
I guess it matches nicely with the mock design.

**Comment by prayutsu** [comment]
@rt4914 PTAL

**Comment by rt4914** [comment]
@prayutsu I think you have added incorrect screenshot. Can you please fix that? Thanks.

**Comment by rt4914** [comment]
I am actually not able to understand which UI you are following, because if I run this, I get following UI for `StoryActivity`.
Screenshot_1600155612
Screenshot_1600155616

But instead we have to implement a UI similar to this: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/d70a3ade-826a-4ac6-95e6-907a24d7b896/

**Comment by prayutsu** [comment]
> @prayutsu I think you have added incorrect screenshot. Can you please fix that? Thanks.

I'll correct it.

**Comment by prayutsu** [comment]
@rt4914 Actually, I took the SS of the HomeActivity, because the link in the description of the issue shows HomeActivity mock. So, I didn't test it correctly, but anyways I am working on it.
One thing I want to ask that how can I bring that Vertical progressBar like thing in my layout. I have also made a comment in the mock itself.

**Comment by prayutsu** [comment]
@rt4914 A sample ss, please review it and suggest changes.

Screenshot_1600177725

Currently "0 of 2 chapters completed" is in left, but I think when we get that progressBar thing, it should look fine

**Review by rt4914 — APPROVED** [review]
LGTM, thanks. Now you can work on the exact UI part.

**Pull request merged**
