### PR TITLE
Fix #362: Add congratulations message when a correct answer is submitted

### LINKED ISSUE #362: Add congratulations message when a correct answer is submitted
Similar to Oppia web, users should receive a congratulations indicator when they submit a correct answer.

See mocks: https://xd.adobe.com/spec/bee1fced-33bd-4f69-6a89-2c30fe1c4f65-c8d0/screen/cf6a4999-56aa-4c3c-802f-7573a0457f9b/PM-Q1-Fraction-Input-Correct-Toaster-.

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR shows congratulation message when correct answer is submitted. This message has got fading animation

### Mocks
https://xd.adobe.com/spec/bee1fced-33bd-4f69-6a89-2c30fe1c4f65-c8d0/screen/cf6a4999-56aa-4c3c-802f-7573a0457f9b/PM-Q1-Fraction-Input-Correct-Toaster-.

### Screenshot

un

### CODE REVIEW

**Comment by veena14cs** [comment]
@BenHenning to identify correct answer is submitted , we are using `result.labelledAsCorrectAnswer`.
But this is not working on some explorations.

**Comment by rt4914** [comment]
> @BenHenning to identify correct answer is submitted , we are using `result.labelledAsCorrectAnswer`.
> But this is not working on some explorations.

@veena14cs Please mention those explorations too.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@veena14cs The text is visible behind state buttons. I think to solve this you will need to make the elevation of textview to be around 6-8dp. You might need to introduce CardView also.

**Comment by BenHenning** [comment]
The gif looks awesome--nice!

**Comment by veena14cs** [comment]
> The gif looks awesome--nice!

Thanks!

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Comment by veena14cs** [comment]
> @veena14cs The text is visible behind state buttons. I think to solve this you will need to make the elevation of textview to be around 6-8dp. You might need to introduce CardView also.

I fixed this by giving elevation to framelayout. I have not used cardview. PTAL once.

**Comment by veena14cs** [comment]
> > @BenHenning to identify correct answer is submitted , we are using `result.labelledAsCorrectAnswer`.
> > But this is not working on some explorations.
> 
> @veena14cs Please mention those explorations too.

For Prototype Exploration `result.labelledAsCorrectAnswer` is not working.

**Review by rt4914 — APPROVED** [review]
LGTM. Its great.

**Comment by rt4914** [comment]
@veena14cs Do not delete this branch. Needs this to track another issue.

**Comment by mschanteltc** [comment]
This animation looks great and would be suitable if the app is on battery saving mode. 

When it's not on battery saving mode, can we animate it so that the "Correct" toaster rises, then fades down? It would use an "[Ease-In-Out](https://developers.google.com/web/fundamentals/design-and-ux/animations/the-basics-of-easing#ease-in-out_animations)" animation going up with a duration of 0.4 s. The correct toaster will stay for 3s. After it would fade and move down also with an Ease-In-Out animation with a duration of 0.4 s. The beginning and ending state of the "Correct" toaster is 20 px below the middle state where the toaster stays in place.

**Pull request merged**
