### PR TITLE
Fix #3356:[RTL] High-fi Coming Soon Topics card

### LINKED ISSUE #3356: [RTL] High-fi Coming Soon Topics card
Coming soon Topics card need to RTL support.

screenshot

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR fixes #3356 . This PR fixes the coming soon banner for RTL.

## Screenshot LTR and RTL
Mobile
screenshot.... screenshot
screenshot..... screenshot

Tablet 
screenshot........screenshot
screenshot......... screenshot

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@veena14cs  Define both these colors in colors.xml file so that when one value is changed it gets reflected in LTR and RTL both

**Comment by veena14cs** [comment]
> @veena14cs Define both these colors in colors.xml file so that when one value is changed it gets reflected in LTR and RTL both

Done.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
