### PR TITLE
[RunAllTests] Fix part of #3974: Cherry-pick MR3 release blocker fixes

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fix part of #3974

This branch cherry-picks the following commits into the release-0.6 branch:
- #3973
- #3964
- #3963
- #3957
- #3955

Please compare against the base PRs if you want to verify the correctness of the cherry-picks. Note that none of them introduced conflicts, so all five cherry-picks were clean.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] ~The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".~ (N/A -- this PR is changing a release branch)
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A -- this isn't changing functionality, it's cherry-picking already approved PRs with no additional changes.

### CODE REVIEW

**Comment by BenHenning** [comment]
Reopening the branch with a specific indication that all tests should be run as part of this PR (I suspect that most will be, anyway, given that the affected files).

**Comment by BenHenning** [comment]
@rt4914 PTAL for codeowners (though I'm happy if you just rubberstamp this since you've already approved the develop version of these changes & it was a clean cherry-pick).

@anandwana001 can you please take a quick pass on this and make sure that it essentially matches the cherry-picked PRs? I'd expect this to be a quick verification since the cherry-picks were clean. I'll be manually verifying the fixes & functionality when I do the release tomorrow after this is merged.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Comment by BenHenning** [comment]
Thanks @anandwana001!

**Review by rt4914 — APPROVED** [review]
LgTM thanks.

**Comment by BenHenning** [comment]
Thanks all! Merging this to unblock the (hopefully) last RC for MR3.

**Pull request merged**
