### PR TITLE
Fix toolbar shadow and text cutoff on scrolling to top.

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR fixes toolbar shadow and text cutoff on scrolling to top.

### Mock
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/2b6c8e95-5ac7-4472-bc2b-1c318a3f7e5c/HP-Continue-Playing-

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
LGTM

**Comment by rt4914** [comment]
Screenshot_1575011425

Just for conext: The toolbar shadow is above the content, which is correct.

**Comment by veena14cs** [comment]
> Screenshot_1575011425
> 
> Just for conext: The toolbar shadow is above the content, which is correct.

Thanks @rt4914 .

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Pull request merged**
