### PR TITLE
Fix #1903 added regex check to ensure analytics/crashlytics is explicitly disab…

### LINKED ISSUE #1903: Add regex checks to ensure Firebase analytics + Crashlytics stay disabled in the codebase.
The Firebase activation parameters (https://github.com/oppia/oppia-android/blob/2d14066/app/src/main/AndroidManifest.xml#L17) shouldn't be enabled ever in develop. We should have a CI check to ensure these parameters are always off.

### PR DESCRIPTION
**Pull request by chrislee115**
## Explanation
Fix #1903 

Adds a regex check in file content validation to ensure Firebase analytics are disabled in the codebase. Both regex are tested in https://regex101.com/r/l14O5J/1, https://regex101.com/r/QVHGxi/1 for Firebase analytics, Crashlytics, respectively.
  - "Fixes ##1903:" Adds a regex check that ensures that firebase analytics and crashlytics are explicitly disabled in AndroidManifest.xml, new pull requests based on oppia/oppia-android/pull/4944

Manual testing:
Case 1: firebase_analytis_collection_deactivated = false in AndroidManifest.xml; want = true (line 19)
image

Case 2: firebase_analytis_collection_deactivated = true not found in AndroidManifest.xml; want = explicit line (line 19)
image

Case 3: firebase_crashlytics_collection_enabled = true in AndroidManifest.xml; want = false (line 20)
image

Case 4: firebase_crashlytics_collection_enabled = false not found in AndroidManifest.xml; want = explicit line (line 20)
image

Case 5: happy case
image

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [X] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Hi @chrislee115, thanks for your PR!

Your changes look good, just a couple of things:
- You have a failing lint check on CI that you should fix. Ktlint usually runs pre-push, and it is likely that you missed this step while setting up your project. Please refer to https://github.com/oppia/oppia-android/discussions/4842#discussioncomment-4681547 on how to set this up, so that this will always fail locally before pushing.
- Please add a demonstration (e.g. screenshots) in the PR description showing these checks correctly failing when the values are reverted in the main AndroidManifest.xml file.

**Comment by chrislee115** [comment]
> * You have a failing lint check on CI that you should fix. Ktlint usually runs pre-push, and it is likely that you missed this step while setting up your project. Please refer to [Gradle Build Failure in Mac M1 #4842 (comment)](https://github.com/oppia/oppia-android/discussions/4842#discussioncomment-4681547) on how to set this up, so that this will always fail locally before pushing.

Is there an equivalent link for Windows?

**Comment by adhiamboperes** [comment]
> > * You have a failing lint check on CI that you should fix. Ktlint usually runs pre-push, and it is likely that you missed this step while setting up your project. Please refer to [Gradle Build Failure in Mac M1 #4842 (comment)](https://github.com/oppia/oppia-android/discussions/4842#discussioncomment-4681547) on how to set this up, so that this will always fail locally before pushing.
> 
> Is there an equivalent link for Windows?

Please refer to [wiki page](https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android), for windows instructions to run  `bash scripts/setup.sh`.

**Comment by adhiamboperes** [comment]
> > > * You have a failing lint check on CI that you should fix. Ktlint usually runs pre-push, and it is likely that you missed this step while setting up your project. Please refer to [Gradle Build Failure in Mac M1 #4842 (comment)](https://github.com/oppia/oppia-android/discussions/4842#discussioncomment-4681547) on how to set this up, so that this will always fail locally before pushing.
> > 
> > 
> > Is there an equivalent link for Windows?
> 
> Please refer to [wiki page](https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android), for windows instructions to run `bash scripts/setup.sh`.

Alternatively, in android studio, go to the .github folder and find the [static_checks.yml](https://github.com/oppia/oppia-android/blob/develop/.github/workflows/static_checks.yml) file. Search for the line that corresponds to the name of the job that failed, and you can  copy and run the same script on your terminal if you have bazel set up.

**Comment by chrislee115** [comment]
Got it thanks! Sorry for the basic questions - As for testing the changes, should the scripts be run if I run
```
bazel build //:oppia
```
If so, it seems like my checks aren't properly working as the build is successfully completing.

**Comment by adhiamboperes** [comment]
> Got it thanks! Sorry for the basic questions - As for testing the changes, should the scripts be run if I run
> 
> ```
> bazel build //:oppia
> ```
> 
> If so, it seems like my checks aren't properly working as the build is successfully completing.

Similar to the ktlint check(and any other static check), you can get the command for name: Regex Patterns Validation Check from the static_checks.yml and run it on your terminal. [Reference](https://github.com/oppia/oppia-android/wiki/Static-Analysis-Checks)

**Comment by chrislee115** [comment]
Updated the description! I was wondering if we should also prohibit the commented version of the correct lines. I.e. 
```
  <!--  <meta-data android:name="firebase_analytics_collection_deactivated" android:value="true" /> -->
```

I'm not sure how feasible this is since matching beginning/end of strings appear to not work as intended and matching anything less granular might be too fragile - https://github.com/oppia/oppia-android/discussions/4949#discussion-5098466

**Comment by adhiamboperes** [comment]
Hi @chrislee115 , if you have finished making changes, please [re-assign the PR over to the reviewers. ](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#step-3-address-review-comments-until-all-reviewers-give-lgtm)

**Review by chrislee115 — COMMENTED** [review]
Added Screenshots in description for manual testing results + fixed kt lint changes in the kt file by shortening test case names.

**Comment by chrislee115** [comment]
I requested another review from you - is that the same as re-assigning? Sorry still new to this

**Comment by adhiamboperes** [comment]
> I requested another review from you - is that the same as re-assigning? Sorry still new to this

No, you can assign by writing: "@adhiamboperes, PTAL" and oppiabot should assign the person mentioned.

**Comment by adhiamboperes** [comment]
> Updated the description! I was wondering if we should also prohibit the commented version of the correct lines. I.e.
> 
> ```
>   
> ```
> 
> I'm not sure how feasible this is since matching beginning/end of strings appear to not work as intended and matching anything less granular might be too fragile - [#4949 (comment)](https://github.com/oppia/oppia-android/discussions/4949#discussion-5098466)

I will defer to @BenHenning on this.

**Review by adhiamboperes — APPROVED** [review]
Thanks @chrislee115, these changes look good to me.

**Review by BenHenning — APPROVED** [review]
Thanks @chrislee115! This looks great! LGTM.

**Comment by BenHenning** [comment]
> > Updated the description! I was wondering if we should also prohibit the commented version of the correct lines. I.e.
> > ```
> >   
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm not sure how feasible this is since matching beginning/end of strings appear to not work as intended and matching anything less granular might be too fragile - [#4949 (comment)](https://github.com/oppia/oppia-android/discussions/4949#discussion-5098466)
> 
> I will defer to @BenHenning on this.

I think it's fine to ignore this @adhiamboperes @chrislee115 since it's a bit of an edge case, and we still always have codeowners to check for such things happening. This seems like a completely reasonable stop-gap for #1903.

**Comment by BenHenning** [comment]
Updating to latest develop & enabling auto-merge.

**Pull request merged**
