### PR TITLE
Fix part of #2003: Replacing space_32dp

### PR DESCRIPTION
**Pull request by Arjupta**
## Explanation
Fixes part of #2003
This PR replaces the use of space_32dp with the dimensions having
contextful names.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Arjupta** [comment]
@rt4914 The branch of this PR will act as a base for all the stacked PRs which will be solving this issue. So this must be merged only when all the previous PRs

-  [#2115](https://github.com/oppia/oppia-android/pull/2115)
-  [#2114](https://github.com/oppia/oppia-android/pull/2114)
-  [#2111](https://github.com/oppia/oppia-android/pull/2111)

referencing this issue #2003 are merged before this one.

**Comment by rt4914** [comment]
@ARJUPTA As per our discussion you can update this PR now. Thanks for your patience.

**Comment by Arjupta** [comment]
> @ARJUPTA As per our discussion you can update this PR now. Thanks for your patience.

@rt4914 I will be updating this after all the PRs before this one gets merged. So that every new branch forked from this one doesn't have to be resolved

**Comment by Arjupta** [comment]
@rt4914 I don't know why the tests didn't start in the first place. There are no conflicts present which can cause this. Can you help starting them?

**Comment by BenHenning** [comment]
Closing & reopening to restart the actions checks since they recently broke.

**Comment by Arjupta** [comment]
@rt4914 it can be merged

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
