### PR TITLE
Fix #4006: Hide Edit Accounts option from AdministratorControls

### LINKED ISSUE #4006: Hide Edit Accounts option from AdministratorControls
Hide `Edit Accounts` option from `AdministratorControls` as currently it is of no use. 

Note: Do not remove it, just hide it. Add appropriate test case too.

### PR DESCRIPTION
**Pull request by JishnuGoyal**
## Explanation

This PR changes the value of editAccountsOptionsUi feature flag to false which was mistakenly turned true.
 
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning

**Comment by JishnuGoyal** [comment]
@BenHenning Could this be re-run? This test passes on my machine.

**Review by BenHenning — APPROVED** [review]
Thanks @JishnuGoyal!

**Review by BenHenning — CHANGES_REQUESTED** [review]
Ah, actually it looks like per CI there is now a failing test. PTAL.

**Review by BenHenning — APPROVED** [review]
Ah I see the test is unrelated and thus likely a flake. It's the first time I've seen that particular flake, so I'm a bit surprised. Enabling auto-merge for when it finishes. Thanks @JishnuGoyal!

**Pull request merged**
