### PR TITLE
Fix #2035: File formatting under dragAndDropSortInput Package

### LINKED ISSUE #2035: Fix file formatting under dragAndDropSortInput package
**Describe the bug**
All the files, under the package `domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput` are not in the correct format. 

**Expected behavior**
File format should be follow from this file - [TextInputEqualsRuleClassifierProviderTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt
)

**Correct Order**
Constant values
Dagger injection
Local variables
Test Before setup
Tests
Dagger Setup

### PR DESCRIPTION
**Pull request by Aarkin7**
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Aarkin7** [comment]
In files DragDropSortInputIsEqualToOrderingClassifierProviderTest.kt and DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt

@anandwana001 Should I create a new variable to store the value returned from method createHtmlStringList and then pass that variable to method createListOfSetsOfHtmlStrings? I think calling method createHtmlStringList inside method createListOfSetsOfHtmlStrings might have caused the error.

**Comment by anandwana001** [comment]
@Aarkin7 why this new PR?
There is already a PR for this. https://github.com/oppia/oppia-android/pull/2053

**Comment by Aarkin7** [comment]
@anandwana001 generated this pr accidentally. Sorry for replying back so late, was not well since a few days.

**Comment by anandwana001** [comment]
closing this pr as per @Aarkin7 comment.

**Pull request closed without merging**
