### PR TITLE
profile input view alignment updates

### PR DESCRIPTION
**Pull request by nikitamarysolomanpvt**
## Explanation
 Alignment change with respect to ProfileInputView as per new mock updates and also updates in ProfileInputView.

## Mocks
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/9603eda8-8d20-4377-9458-d5deec58b4d9/PC-NP-Admin-Settings-Dialog-Empty-/
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/a841330e-efe5-4bdb-acdd-4d6e52a59571/PC-MP-Admin-Authorization-Empty-
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/6f83fcd9-e72d-4941-a16f-6754a869e083/RG-MN-Register-Empty-37
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/d0227921-1c24-4bb7-8667-a8fa5f4742dd/AC-EP-Rename-
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/acdbeb30-745f-46da-b0fd-3d6a83f83937/PC-SP-Add-PIN-Dialog-Empty-
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/c3809dea-7afa-4905-9a93-ea4273459a68/PC-SP-Create-PIN-Empty-
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/32c9276d-072c-4edf-abf9-435323bb475a/AC-EP-Reset-PIN-Empty-

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/b7447549-a7c3-48a9-8ad2-876d0a347708/RG-MN-Register-Empty-36

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/a0c84710-3970-4488-beea-6fe6abbdb38a/PC-MP-Admin-Authorization-Admin-Controls-Empty-
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/a841330e-efe5-4bdb-acdd-4d6e52a59571/PC-MP-Admin-Authorization-Empty-/

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/785546bd-b160-4d9b-b5d6-53ddc1b4a80a/PC-SP-Admin-Authorization-Empty-
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/a0c84710-3970-4488-beea-6fe6abbdb38a/PC-MP-Admin-Authorization-Admin-Controls-Empty-

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@nikitamarysolomanpvt Just an update, I will review this PR later tomorrow before EOD. As this is big PR, I will need to focus on this correctly and unfortunately I had been working late tonight, so won't able to review on time tomorrow morning.

**Comment by nikitamarysolomanpvt** [comment]
> @nikitamarysolomanpvt Just an update, I will review this PR later tomorrow before EOD. As this is big PR, I will need to focus on this correctly and unfortunately I had been working late tonight, so won't able to review on time tomorrow morning.

No problem

**Review by rt4914 — APPROVED** [review]
LGTM, there is just one issue. 
The `Save` button is not aligned correctly because it is dependent on `ProfileInputView`. You can either fix this in this PR or a separate PR.

Screenshot_1589950805

**Comment by nikitamarysolomanpvt** [comment]
> LGTM, there is just one issue.
> The `Save` button is not aligned correctly because it is dependent on `ProfileInputView`. You can either fix this in this PR or a separate PR.
> 
> Screenshot_1589950805

https://github.com/oppia/oppia-android/issues/1090 issue is created
this PR wont be including any other fix than ProfileInputView alignments fix with respect to mock updates and ProfileInputView hence another PR will be created for the same.

**Pull request merged**
