### PR TITLE
Fix part of #2234: Shift assertThrows function from utility module to testing module

### PR DESCRIPTION
**Pull request by ShridharGoel**
## Explanation
Fixes part of #2234 

## Checklist
- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

## Screenshot
Screenshot

### CODE REVIEW

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks @ShridharGoel 
Looks pretty straight. Could you add a screenshot showing all test passing.

**Comment by ShridharGoel** [comment]
@anandwana001 Thanks, added the screenshot.

**Review by anandwana001 — APPROVED** [review]
Thaks @ShridharGoel 
LGTM

**Review by BenHenning — COMMENTED** [review]
Thanks @ShridharGoel! See my question in #2284 since that applies here, too.

**Comment by ShridharGoel** [comment]
@BenHenning Thanks, I have removed the dependency on kotlin-reflect from the utility module.

**Review by BenHenning — APPROVED** [review]
Thanks!

**Pull request merged**
