### PR TITLE
Fix #923: Lowfi Landscape PinPasswordActivity

### LINKED ISSUE #923: Lowfi Landscape PinPasswordActivity
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/afb412a3-db42-4538-bbdd-7d38c84d963e/PC-NP-Shake-Error-/

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/6722d327-0ea3-4a80-8370-69ce85f308f5/RG-MN-Register-Empty-22/

Add test cases for this landscape support.

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #923 

This PR adds support for landscape mode for PinPasswordActivity

Mocks: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/afb412a3-db42-4538-bbdd-7d38c84d963e/PC-NP-Shake-Error-/

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/6722d327-0ea3-4a80-8370-69ce85f308f5/RG-MN-Register-Empty-22/

## Screenshot for landscape layout 
Screenshot_1585737449
Screenshot_1585737456
Screenshot_1585737462
Screenshot_1585737466
Screenshot_1585737495
Screenshot_1585737498
Screenshot_1585737503
Screenshot_1585737506
Screenshot_1585737512
Screenshot_1585737521
Screenshot_1585737526
Screenshot_1585737532
Screenshot_1585737535

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by nikitamarysolomanpvt** [comment]
@rt4914 Please add screen shots after explanation.

**Review by nikitamarysolomanpvt — CHANGES_REQUESTED** [review]
PTAL one test case failed
x

**Comment by rt4914** [comment]
> PTAL one test case failed
> x

Actually the test cases were passing on my emulator and failed on other emulator. I have updated the test cases  and checked that they pass on following resolution devices:
HDPI
XHDPI
560DPI

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Pull request merged**
