### PR TITLE
Fix #3199: [RTL] High-fi Profile chooser screen

### LINKED ISSUE #3199: [RTL] High-fi Profile Chooser
Profile chooser fix UI spacing and make sure all the texts support RTL.

Tablet Landscape : https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/33741ea7-89da-4e5d-b2a4-9872f6db48b4/
Tablet Portrait : https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/d63eabcd-f0bf-4e06-9c08-f4d77429c356/

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR fixes #3199. Fixes the spacing issue in between the Profile image and the name.

**Note :**
Please test this PR with tablet as I was not able to test this on my emulator. 

## Screenshot LTR and RTL
screenshot ......  screenshot

screenshot.......  screenshot
screenshot ...... screenshot

screenshot .....   screenshot

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
In this please add screenshots for tablet (portrait + landscape) and mobile landscape too as the UI for landscape mode is quite different.

**Comment by veena14cs** [comment]
> In this please add screenshots for tablet (portrait + landscape) and mobile landscape too as the UI for landscape mode is quite different.

@rt4914 I was unable to test on tablet emulator, could you please check it and assign someone to test on tablet and send screenshot.
I have updated landscape screenshot for phone in the description.

**Comment by rt4914** [comment]
@veena14cs On Tablet device the RTL is not working. Please take a look.

**Comment by veena14cs** [comment]
> @veena14cs On Tablet device the RTL is not working. Please take a look.
> 
>  
>  

Thanks for these screenshots Rajat! I will make corrections and update the PR.

**Comment by veena14cs** [comment]
> @veena14cs On Tablet device the RTL is not working. Please take a look.
> 
>  
>  

@rt4914  I have updated Tablet screenshots in the description. PTAL.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
