### PR TITLE
Fix #1788: Prepare build for production

### LINKED ISSUE #1788: Prepare app for production builds
We need to:
1. Make sure that proguard is reasonably set up for production builds
2. Verify that a production optimized build succeeds and is playable

### PR DESCRIPTION
**Pull request by BenHenning**
Fixes #1788.

This PR does a few things:
- Increase build resources to max 1GB of ram (needed for running the R8 optimization step)
- Enable minification using R8 for release builds
- Enable resource shrinking using AGP (see https://developer.android.com/studio/build/shrink-code)
- Add support for split APKs (see https://developer.android.com/studio/build/configure-apk-splits); we'll probably be using app bundles for the actual upload, but this lets us analyze the APK sizes people will actually install for a given device type

No additional proguard work is needed. I verified that the universal APK on my Pixel XL using a test signature (since the release flavors are not signed by default) is working.

Note that this removes two of the min sdk declarations that break both Gradle syncing & APK signing. AGP is a bit sensitive about this min sdk property even though it's valid, so I'm hoping Bazel will build without issues. Long-term we will define min SDK in the manifest when AGP is out of the picture.

### CODE REVIEW

**Comment by BenHenning** [comment]
Looks like I just needed to update the compile SDK version to 29. I'll send out an announcement to the team that this update is coming once the PR goes in.

**Comment by BenHenning** [comment]
@anandwana001 can you PTAL?

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @BenHenning 
Tested app on the emulator as well as a physical device, working fine. What should we do with these failing cases in checks?

**Comment by BenHenning** [comment]
Thanks @anandwana001! Looking into the failures--presuming that the new SDK targets are probably causing them.

**Comment by BenHenning** [comment]
Looks like https://github.com/robolectric/robolectric/issues/5207. Per http://robolectric.org/configuring/ this is fairly easy to work around in the interim, but long-term we should run Robolectric tests by default in the same environment as the prod build is targeting (filed #1794 to track updating Robolectric tests).

**Comment by BenHenning** [comment]
I also verified that at least domain tests build & pass with Bazel, so I'm assuming they work broadly.

**Comment by BenHenning** [comment]
Thanks for the review! PR seems good to merge now.

**Comment by BenHenning** [comment]
Forgot to add context earlier, but one of the reasons SDK 29 was needed is I *think* we were running into an R8 bug that was essentially mixing up different versions of the LifecycleOwner class (or others) which caused none of the AndroidX lifecycle callbacks to work correctly, which means we never transitioned past SplashActivity. This seems fixed in a later release of R8, or in some way is fixed by targeting SDK 29.

**Comment by anandwana001** [comment]
Two reference with respect to your latest comment 
1. https://issuetracker.google.com/issues/142778206
2. https://android.googlesource.com/platform/frameworks/support.git/+/refs/heads/androidx-master-dev/lifecycle/lifecycle-runtime/src/main/java/androidx/lifecycle/ReportFragment.java#41

```

public static void injectIfNeededIn(Activity activity) {
--
  | if (Build.VERSION.SDK_INT >= 29) {
  | // On API 29+, we can register for the correct Lifecycle callbacks directly
  | LifecycleCallbacks.registerIn(activity);
  | }
  | // Prior to API 29 and to maintain compatibility with older versions of
  | // ProcessLifecycleOwner (which may not be updated when lifecycle-runtime is updated and
  | // need to support activities that don't extend from FragmentActivity from support lib),
  | // use a framework fragment to get the correct timing of Lifecycle events
  | android.app.FragmentManager manager = activity.getFragmentManager();
  | if (manager.findFragmentByTag(REPORT_FRAGMENT_TAG) == null) {
  | manager.beginTransaction().add(new ReportFragment(), REPORT_FRAGMENT_TAG).commit();
  | // Hopefully, we are the first to make a transaction.
  | manager.executePendingTransactions();
  | }
  | }
```

Solved here - https://developer.android.com/jetpack/androidx/releases/lifecycle#2.2.0-rc02

**Pull request merged**
