### PR TITLE
Fix part of #4064: Learner Analytics platform parameter

### PR DESCRIPTION
**Pull request by Sarthak2601**
## Explanation

Fixes part of #4064 
This PR gates Learner Study Analytics behind a feature flag. This means that Profile and Devices Id screen and learner study related analytics logging would only occur if this flag is set to `true`. 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by BenHenning** [comment]
Thanks @Sarthak2601. I'll need to follow up with a review on this tomorrow.

**Review by BenHenning — COMMENTED** [review]
Thanks @Sarthak2601. Generally LGTM. Could you please update to the latest develop and send it back to me to double check before approving?

**Comment by Sarthak2601** [comment]
> Thanks @Sarthak2601. Generally LGTM. Could you please update to the latest develop and send it back to me to double check before approving?

Thanks for the review @BenHenning. I've updated to the latest develop, PTAL.

**Review by BenHenning — APPROVED** [review]
LGTM. Thanks @Sarthak2601!

**Pull request merged**
