### PR TITLE
Fix #1484 :Topic Lesson items getting repeated

### LINKED ISSUE #1484: Topic Lesson items getting repeated
**Describe the bug**

**To Reproduce**
1. Uninstall the app
2. Click on `First Test Topic`
3. Click on `Lessons`
4. Expand on `Second Story`
5. Click on `Second Exploration` (mostly nothing will load in new screen)
6. Click on `back arrow` in Toolbar 
7. You will notice that the lesson items are repeating.

**Expected behavior**
Lesson items should not repeat.

**Screenshots**
Screenshot_1595008736

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fixes #1484 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
This looks better but there is still one issue.

Follow these specific steps:
1. Open any topic.
2. Click on Lessons.
3. Click on Story-name to go to `StoryActivity`
4. Click on chapter to open exploration.
5. Leave exploration
6. Now, go back using android-navigation button and **not** the top-left back arrow button.
7. Now, once you are TopicActivity, click on on back-arrow available on top-left corner.
8. You will notice that the `StoryActivity` is visible again.

**Comment by rt4914** [comment]
@anandwana001 I took some extra time to review this, because while checking this first time, I found one issue but I was not able to reproduce that issue. Now finally I was able to find that bug. (mentioned above)

**Comment by anandwana001** [comment]
> This looks better but there is still one issue.
> 
> Follow these specific steps:
> 
> 1. Open any topic.
> 2. Click on Lessons.
> 3. Click on Story-name to go to `StoryActivity`
> 4. Click on chapter to open exploration.
> 5. Leave exploration
> 6. Now, go back using android-navigation button and **not** the top-left back arrow button.
> 7. Now, once you are TopicActivity, click on on back-arrow available on top-left corner.
> 8. You will notice that the `StoryActivity` is visible again.

@rt4914 Please try running with the latest commit now, it works fine for me. Also, as per your suggestion, I had checked the left-right animation of activity, which is also coming and going correctly.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
