### PR TITLE
Fix #2486: Replace `Switch` in `add_profile_activity.xml`

### LINKED ISSUE #2486: Replace `Switch` with `androidx.appcompat.widget.SwitchCompat` in `add_profile_activity.xml`
Replace `Switch` with `androidx.appcompat.widget.SwitchCompat` in `add_profile_activity.xml` files. Also make sure that it is still functional and all tests pass in `AddProfileActivityTest` file.

### PR DESCRIPTION
**Pull request by khushal1707**
## Explanation
Fix #2486: Replace `Switch` with `androidx.appcompat.widget.SwitchCompat` in `add_profile_activity.xml`

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by FareesHussain — APPROVED** [review]

**Comment by FareesHussain** [comment]
@khushal1707 please add screenshots of espresso tests as mentioned in the issue

Ref - https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#espresso

**Comment by khushal1707** [comment]
There are two espresso test which are failing in API 29, namely:
`testAddProfileActivity_inputPin_inputDifferentConfirmPin_clickCreate_changeConfiguration_checkErrorMessageDisplayed()`
`testAddProfileActivity_inputNotUniqueName_clickCreate_changeConfiguration_checkErrorMessageDisplayed()`
 having the same error.
Both of these tests are not related to commit I have made, should I fix these issues?

Screenshot (350)
Screenshot (351)

**Comment by FareesHussain** [comment]
@khushal1707 thanks for mentioning I'll have a look at this

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
