### PR TITLE
Fix #629: Limitation of ActivityScenario's Launch Method - Found in Kitkat 

### LINKED ISSUE #629: Limitation of ActivityScenario's Launch Method - Found in Kitkat
The test-cases which use ActivityScenario are failing throughout oppia-android tests when tested in Kitkat.
small

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fixes #629: Introducing Progaurd file for testing when multidex enabled

Tested `FAQListFragmentTest` on Pixel XL API 19 and all test case are passing. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
@MaskedCarrot  Could you help me here and try to run multiple espresso test files on API 19/20/21/22/23/24/25 from app module and see if tests are running correctly.

**Comment by MaskedCarrot** [comment]
> @MaskedCarrot Could you help me here and try to run multiple espresso test files on API 19/20/21/22/23/24/25 from app module and see if tests are running correctly.

@anandwana001 sure

**Comment by MaskedCarrot** [comment]
I ran a few tests and some or all of the tests are failing for 
`AudioFragmentTest` -->  `testAudioFragment_invokePrepared_changeDifferentLanguage_checkResetSeekBarAndPaused` on api 19
`SplashActivityTest`
`DragDropActivityTest` on api 19
`StoryFragmentTest` --> `testStoryFragment_configChange_chapterMissingPrerequisiteThumbnailIsBlurred`

**Comment by anandwana001** [comment]
Are these test failing only on API 19 or they are failing everywhere?
You can ignore the test files mentioned here as they need few fixes - https://github.com/oppia/oppia-android/issues/2417

**Comment by MaskedCarrot** [comment]
some test is only failing on API 19 and some (like splashActivityTest is failing on 19 21 24)

**Comment by anandwana001** [comment]
Steps to follow from here:
1. Could you please try running maximum test files from the app module sharedTest folder, example - `AdministratorControlsActivityTest` and all other in the same folder. 
2. As `DragDropActivityTest` is failing only on API 19, so could you please try running app, open the first test topic, answer the questions and reach out to drag and drop question and see if it is not working there!! 

We can confirm either only tests are failing or is the feature is not working properly on API 19.

**Comment by MaskedCarrot** [comment]
I ran more tests on API 19 and a lot of them failed. These failing tests are mentioned [here](https://gist.github.com/MaskedCarrot/0e4efaa78f3d5f8723b6b9050db235b2).

**Comment by MaskedCarrot** [comment]
Also, I ran the app on API 19 and dragAndDropActivity is not working properly


drag and drop

**Comment by MaskedCarrot** [comment]
also filled a new issue here #2698

**Comment by MaskedCarrot** [comment]
@anandwana001 PTAL

**Comment by anandwana001** [comment]
Looks like this is not the correct way to solve this issue. Closing this PR.

**Pull request closed without merging**
