### PR TITLE
Fix #1899: Format ItemsSelectionInputEqualsRuleClassifieProviderTest

### LINKED ISSUE #1899: Thoroughly test ItemsSelectionInputEqualsRuleClassifier
Since the ItemsSelectionInputEqualsRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

### PR DESCRIPTION
**Pull request by peculiaruc**
## Explanation

- Fix #1899, Format ItemsSelectionInputEqualsRuleClassifierProviderTest

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by peculiaruc** [comment]
@BenHenning PTAL

**Comment by anandwana001** [comment]
@peculiaruc Before anyone reviews this PR, please fix the PR. 
1. It seems like there are many unwanted files are included in this PR. 
2. Please update this PR branch with the latest develop branch.
3. Fix the PR title
4. File format should be follow from this file - [TextInputEqualsRuleClassifierProviderTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt
)
5. Check this for code formatting - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

**Comment by peculiaruc** [comment]
Done @anandwana001 PTAL

**Comment by anandwana001** [comment]
@peculiaruc 
PR is not clean, it includes different commit. As per my above comment, it's the first point to complete.

**Comment by rt4914** [comment]
@peculiaruc Please update this PR by merging it with latest develop so that we can start reviewing this.

**Comment by peculiaruc** [comment]
> @peculiaruc Please update this PR by merging it with latest develop so that we can start reviewing this.

@rt4914 I am working on this now. I don't have this branch again locally because I removed my first repo, can I create a new PR for this issue

**Comment by rt4914** [comment]
> > @peculiaruc Please update this PR by merging it with latest develop so that we can start reviewing this.
> 
> @rt4914 I am working on this now. I don't have this branch again locally because I removed my first repo, can I create a new PR for this issue

@peculiaruc Yes you can create a new PR. Thanks.

**Comment by peculiaruc** [comment]
> > > @peculiaruc Please update this PR by merging it with latest develop so that we can start reviewing this.
> > 
> > 
> > @rt4914 I am working on this now. I don't have this branch again locally because I removed my first repo, can I create a new PR for this issue
> 
> @peculiaruc Yes you can create a new PR. Thanks.

Ok. Thanks. 
@rt4914 . Please working on this, there is no direct method in InteractionObjectTestBuilder for it. It requires SetOfHtmlString. but we have ListOfSetOfHtmlString which can not be used for it. Please I will like this method SetOfHtmlString eg, createSetOfHtmlString,  to be added in InteractionObjectTestBuilder or what do you think? Thanks

**Comment by peculiaruc** [comment]
> > > > @peculiaruc Please update this PR by merging it with latest develop so that we can start reviewing this.
> > > 
> > > 
> > > @rt4914 I am working on this now. I don't have this branch again locally because I removed my first repo, can I create a new PR for this issue
> > 
> > 
> > @peculiaruc Yes you can create a new PR. Thanks.
> 
> Ok. Thanks.
> @rt4914 . Please working on this, there is no direct method in InteractionObjectTestBuilder for it. It requires SetOfHtmlString. but we have ListOfSetOfHtmlString which can not be used for it. Please I will like this method SetOfHtmlString eg, createSetOfHtmlString, to be added in InteractionObjectTestBuilder or what do you think? Thanks

Nevermind. I got this

**Pull request closed without merging**
