### PR TITLE
Fix #2143: Move InteractionObjectTestBuilder to a main-level testing library[BLOCKED ON #1904]

### LINKED ISSUE #2143: Move InteractionObjectTestBuilder to a main-level testing library
InteractionObjectTestBuilder is a non-test file under the test directory. Test utilities should be in a testing directory under main, not test, or be in the dedicated testing module.

This issue can be resolved by moving this file to package `org.oppia.android.app.player.state.testing`. 
 - All usages must have the imports updated(automatically done by Android Studio).
 - Ktlint formatting check `java -jar ../oppia-android-tools/ktlint -F --android domain/src/**/*.kt utility/src/**/*.kt data/src/**/*.kt app/src/**/*.kt testing/src/**/*.kt scripts/src/**/*.kt  instrumentation/src/**/*.kt` should be run to ensure unused imports are removed, and imports are ordered correctly.
 - Tests using this util should build correctly in Bazel.

### PR DESCRIPTION
**Pull request by FareesHussain**
## Explanation

Fixes #2143 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by FareesHussain** [comment]
@rt4914 please check

**Comment by BenHenning** [comment]
Thanks @FareesHussain. FYI that this isn't actually complete yet. There are a few additional changes needed:
1. You need to update the package of the class & all references to it
2. The utility should be under a 'testing' folder (e.g. domain/src/main/org/oppia/android/domain/testing/...)
3. You'll need to update Bazel BUILD files to make sure the new package is properly updated/included, and remove the corresponding TODO (this has to wait for #1904 to be submitted first), so this PR is blocked until that PR can be submitted

**Comment by anandwana001** [comment]
@FareesHussain any update on this?

**Comment by FareesHussain** [comment]
As Ben said it is blocked on #1904 so I'll push the changes as it gets merged

**Comment by FareesHussain** [comment]
Closing this to make the issue available for the onboarding contributors

**Pull request closed without merging**
