### PR TITLE
Fix #911 & Fix #912: Highfi ProfileResetPin and highfi ProfileRename

### LINKED ISSUE #911: Highfi ProfileRenameActivity
Mock:
https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/d0227921-1c24-4bb7-8667-a8fa5f4742dd/Settings-1-Profile-Chantel-Rename-1
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/b7447549-a7c3-48a9-8ad2-876d0a347708/RG-MN-Register-Empty-36/

### LINKED ISSUE #912: Highfi ProfileResetPinActivity
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/32c9276d-072c-4edf-abf9-435323bb475a/Settings-1-Profile-Chantel-Make-Admin-no-pw-3/

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/6f83fcd9-e72d-4941-a16f-6754a869e083/RG-MN-Register-Empty-37/

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #911 and #912 

## Mocks
https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/32c9276d-072c-4edf-abf9-435323bb475a/Settings-1-Profile-Chantel-Make-Admin-no-pw-3/
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/6f83fcd9-e72d-4941-a16f-6754a869e083/RG-MN-Register-Empty-37/
https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/d0227921-1c24-4bb7-8667-a8fa5f4742dd/Settings-1-Profile-Chantel-Rename-1
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/b7447549-a7c3-48a9-8ad2-876d0a347708/RG-MN-Register-Empty-36/

## Screenshots
Screenshot_1585562417
Screenshot_1585562424
Screenshot_1585562431
Screenshot_1585562433

## Known issues:
1. The ProfileInputInput includes margin which is creating issues at various places. For now all UIs have been adjusted to make sure that they match the mock with an error margin of maximum 4dp. That too in very few layouts and not all.
2. The toolbar title textsizse is inconsistent and therefore used `20sp` standard text size everywhere.
3. The bottom padding for landscape mode is not consistent. Kept it 108dp instead of 167dp in reset pin activity.

## Accessibility Tests:
1. The first accessibility test fails as per the reason mentioned in the image which is again acceptable.
2. Without any data accessbility test fails on all three views which is acceptable because of following points:
a. Throughout the profile related UIs we are not using hint for edittext and instead we are using TextView. So in that case if hint is not available it is correct.
b. The button is deactive, so the test fails here which is acceptable.

as_7
as_8

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM

**Comment by nikitamarysolomanpvt** [comment]
Seems the mock provided is not matching your screen nor was not able to find them in mocks list so please confirm with @mschanteltc also.

**Comment by rt4914** [comment]
> Seems the mock provided is not matching your screen nor was not able to find them in mocks list so please confirm with @mschanteltc also.

@nikitamarysolomanpvt What is the exact issue here because even @mschanteltc won't be able to help unless you post a clear issue.

**Comment by nikitamarysolomanpvt** [comment]
> > Seems the mock provided is not matching your screen nor was not able to find them in mocks list so please confirm with @mschanteltc also.
> 
> @nikitamarysolomanpvt What is the exact issue here because even @mschanteltc won't be able to help unless you post a clear issue.

@rt4914 Please compare the screen shot you had given with mock links that you provided.

**Comment by rt4914** [comment]
> > > Seems the mock provided is not matching your screen nor was not able to find them in mocks list so please confirm with @mschanteltc also.
> > 
> > 
> > @nikitamarysolomanpvt What is the exact issue here because even @mschanteltc won't be able to help unless you post a clear issue.
> 
> @rt4914 Please compare the screen shot you had given with mock links that you provided.

This has been clarified the mock used for comparison was incorrect and therefore the implementation is correct after pointing out to the correct flow.

**Pull request merged**
