### PR TITLE
Fix #73: Add default configuration for CircleCI using Gradle

### LINKED ISSUE #73: Introduce continuous integration testing
#64 broke the build due to a last minute Gradle file change that wasn't identified during review. This could have been prevented by running tests in a CI environment and blocking the PR on those tests passing. To prevent situations like this from occurring, we should set up a blocking CI environment to build the app & run tests.

We may want to wait until #59 is completed since it may be challenging to find a CI option that works easily for both Gradle and Bazel tests.

### PR DESCRIPTION
**Pull request by BenHenning**
This fixes #73 by setting up CircleCI using Gradle. This configuration will need to change or we'll need to adopt a different service once #59 is resolved.

This includes adding the Gradle wrapper to a special .circleci directory for the specific purposes of .circleci (we do not include the Gradle wrapper in the top-level directory as is customary for Gradle projects). ``gradlew`` was generated by Gradle, but partially modified to support not being in the project root directory.

### CODE REVIEW

**Comment by BenHenning** [comment]
See the CircleCI output--tests appear to be running correctly and reporting to GitHub. This won't be marked as a blocking check yet. We need to fix existing broken tests before we can do that. #295 is tracking this.

**Comment by BenHenning** [comment]
Also, note that I'm not sure if Espresso is actually running here. I expect the top-level ``gradle test`` to run the app tests as Espresso by default, but I'm not actually starting up an emulator (maybe Gradle does automatically?) This may require additional research as we work to fix the current broken tests.

**Review by seanlip — APPROVED** [review]
This looks fine to me, thanks @BenHenning! Feel free to merge.

**Comment by BenHenning** [comment]
Thanks @seanlip.

FYI @oppia/oppia-android that this is going in. It's not blocking, but you'll see it on your PRs. I'll make a broader announcement once this check is enforced.

**Comment by rt4914** [comment]
> Thanks @seanlip.
> 
> FYI @oppia/oppia-android that this is going in. It's not blocking, but you'll see it on your PRs. I'll make a broader announcement once this check is enforced.

@BenHenning Thanks for the heads up.

**Pull request merged**
