### PR TITLE
Fix part of #1874: Fix few RecentlyPlayedFragment tests for Robolectric

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix part of #1874 
Fixing RecentlyPlayedFragmentTest for robolectric Test

## Reviewer
Modified 2 test for Tablet in Espresso
Fix all the required test for Robolectric
Skipping 2 tests, as both required a bit deep investigation with Delay in Robolectric. 
 - `testRecentlyPlayedTestActivity_configurationChange_checkSpanForItem2_spanSizeIsThreeOrFour`
 - `testRecentlyPlayedTestActivity_configurationChange_checkSpanForItem0_spanSizeIsThreeOrFour`

Both these tests are failing on Robolectric but Passing on Espresso. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
In this PR itself we should update the test names to make sure that the character limit is fulfilled for ktlint check.

Thanks @anandwana001

**Comment by anandwana001** [comment]
> In this PR itself we should update the test names to make sure that the character limit is fulfilled for ktlint check.
> 
> Thanks @anandwana001

But there's a ongoing pr from a new contributor and it's in review process already. Might lead to lot of conflicts.

**Comment by rt4914** [comment]
> > In this PR itself we should update the test names to make sure that the character limit is fulfilled for ktlint check.
> > Thanks @anandwana001
> 
> But there's a ongoing pr from a new contributor and it's in review process already. Might lead to lot of conflicts.

Makes sense. Approving and merging now.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
