### PR TITLE
Fix #1739 : Lowfi update walkthrough header

### LINKED ISSUE #1739: Lowfi update Walkthrough
Currently Walkthrough implementation does work in develop but to implement the final UI correctly we will need to make changes to the UI first.
**References**
https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/92becc49-3a10-498b-885c-4cde95f73d51/
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/7f7a12db-2dde-442c-a236-5953e36ca840/

**Issue**
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/7f7a12db-2dde-442c-a236-5953e36ca840/
In the above mentioned link, the progress-bar and the `What do you want to lean?` consumes major part of the screen which does not look good in landscape.

**Suggested Solution**
When the user scrolls down, we hide the progress bar and move the "What do you want to learn?" heading to the top and stay fixed as the user scrolls. 

When the user scrolls back to the top of the page, the progress bar appears and the "What do you want to learn?" heading shifts a little bit down to make room for the progress bar. However if the user scrolls up and is not at the top of the page, only the heading will show. Although scrolling up, regardless of the user's placement on the screen, to see a header/menu/navbar is a common interaction on mobile apps, in this case, the user's call CTA is to browse through a list of topics and select one to learn. Having the progress bar appear as the user is searching for a topic obstructs their view and limits the number of topics they can see at a time.

**Changes needed**
1. In the `WalkthroughActivity` we will need to control `progress-bar` so that it goes out of screen (or hides) when user scrolls and it is not on top.
2. In the `WalkthroughTopicList` the `text` is actually the first item of recyclerview as `WalkthroughTopicHeaderViewModel` but because we want this text to stick to top when scrolled, we should move this out of recyerlerview and make it part of `WalkthroughTopicListFragment` directly.

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation

Fixes #1739 
Implemented progressBar control when the user is not on top. 

Changes to be done as mentioned in the issue - 
**What do you want to learn?** should be a part of the fragment rather than recyclerview.

Problem with this change - 
As **What do you want to learn?**  would be a part of the fragment (above recycler view but inside the fragment) and when the user scrolls down, the **What do you want to learn?** should then go up (at the position of the progressBar) which would then make increase the recyclerview size suddenly which is not a smooth transition and items would move up with a jerk and there also might be some flickering which would lead to bad user experience. 
Alternative way - 
Just keep the **What do you want to learn?** inside the recylerview and as user scrolls down it will automatically go up and we can display another header Textview over progressBar(hiding it). This implementation looks something like this - 

ezgif com-optimize

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by prayutsu** [comment]
@rt4914 PTAL

**Review by rt4914 — CHANGES_REQUESTED** [review]
This is actually nice, but I will actually need to have @mschanteltc approval first on this approach.

Meanwhile can you add test cases for this implementation.

Note for @mschanteltc Have a look at https://github.com/oppia/oppia-android/issues/1739 for the entire description. This is related to one of the discussion that you, me and Pulkit had on an email thread.

**Comment by prayutsu** [comment]
> This is actually nice, but I will actually need to have @mschanteltc approval first on this approach.
> 
> Meanwhile can you add test cases for this implementation.
> 
> Note for @mschanteltc Have a look at #1739 for the entire description. This is related to one of the discussion that you, me and Pulkit had on an email thread.

@rt4914 Actually, I have previously written only unit tests before, so I might need help.

**Comment by rt4914** [comment]
> > This is actually nice, but I will actually need to have @mschanteltc approval first on this approach.
> > Meanwhile can you add test cases for this implementation.
> > Note for @mschanteltc Have a look at #1739 for the entire description. This is related to one of the discussion that you, me and Pulkit had on an email thread.
> 
> @rt4914 Actually, I have previously written only unit tests before, so I might need help.

Check this out for refernece:
https://github.com/oppia/oppia-android/tree/develop/app/src/sharedTest/java/org/oppia/app/walkthrough

https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing

**Comment by prayutsu** [comment]
@rt4914 Do I need to create another PR for tests or I should commit changes here only?

**Comment by rt4914** [comment]
> @rt4914 Do I need to create another PR for tests or I should commit changes here only?

Commit here only. Tests should always be the part of PF itself.

**Comment by prayutsu** [comment]
@rt4914 I am not able to run tests on my local machine.

Screenshot from 2020-08-29 21-23-41

I tried this - [process crashed](https://stackoverflow.com/questions/52605267/instrumentation-run-failed-due-to-process-crashed/52754353)
but then Gradle sync failed.

**Comment by prayutsu** [comment]
@rt4914 PTAL, I wrote the tests for the implementation but couldn't test them, so please review it

**Comment by rt4914** [comment]
@prayutsu I have confirmed with @mschanteltc about the approach.
This does look good. The only main feedback that she gave was to make sure that the `Header` is aligned to left in both cases (before and after animation).

**Comment by rt4914** [comment]
@prayutsu I will keep this assigned to me, I will do full pass tomorrow, but meanwhile if you can check above comment, that would be great. Thanks.

**Comment by prayutsu** [comment]
> @prayutsu I have confirmed with @mschanteltc about the approach.
> This does look good. The only main feedback that she gave was to make sure that the `Header` is aligned to left in both cases (before and after animation).


Sure, I'll fix that up

**Review by rt4914 — CHANGES_REQUESTED** [review]
Test cases are incorrect but thats not the point right now.

I see that you have run test cases on roboelectric. Can you run these tests on espresso also?

Also, please mention what is current version of your android studio?

**Comment by prayutsu** [comment]
> Test cases are incorrect but thats not the point right now.
> 
> I see that you have run test cases on roboelectric. Can you run these tests on espresso also?
> 
> Also, please mention what is current version of your android studio?

I can try that, and my version of Android Studio is 4.0.1

**Comment by prayutsu** [comment]
@rt4914 Any further instructions for me?

**Comment by anandwana001** [comment]
@prayutsu You need to update the branch with `develop` before working more on this PR as we had updated the package names.

**Comment by prayutsu** [comment]
Closing this PR, as this already had a large number of conflicts.
Link to new PR [#1911](https://github.com/oppia/oppia-android/pull/1911)

**Pull request closed without merging**
