### PR TITLE
Fix part of #5508: Limit APK/AAB Difference analysis reports in the PR Comment Thread

### LINKED ISSUE #5533: [BUG][CRITICAL]: Github Actions upload artifact deprecated
### Describe the bug

All module test runs are failing with error:

`Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/`

### Steps To Reproduce

Push a commit to a new or existing PR.

### Expected Behavior

The actions should run to completion.

### Screenshots/Videos

Screenshot 2024-09-11 at 15 04 16

### What device/emulator are you using?

CI

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

### PR DESCRIPTION
**Pull request by Rd4dev**
## Explanation

Fixes #5533 
Fixes part of #5508 

### This PR includes

1. Updates the workflow to use v4 of the upload-artifact 

2. Steps to locate the previous `stats.yml` workflow run, download its build artifact, and compare it with the current build log. If changes are detected, a comment will be uploaded to help minimize comment thread overload.

**The implementation:**
- Download the previous build log artifact (if available).
- Run the script.
- Compare the current generated build log with the previous build log artifact:
  - if no differences are found -> skip commenting.
  - if differences are found -> comment the current generated build log
  - if no previous artifact is found -> comment the current generated build log
    - This occurs in 2 instances:
      - 1. It's the first run of the PR.
      - 2. An error occurred during the previous stat check (since the previous build is from the second-to-last run ID).
- Upload the current build log as an artifact (for the next stat run).
- Comment/skip the stat report based on the comparison result.

#

### Tested with a cloned PR
_(with stats.yml implementation on develop)_

Tested PR: https://github.com/Rd4dev/Oppia-Android-Fork-from-Fork/pull/40

Reference for proof of implementation:

- [x] should comment on initial run | [comment](https://github.com/Rd4dev/Oppia-Android-Fork-from-Fork/pull/40#issuecomment-2336828924) | [stack trace](https://github.com/Rd4dev/Oppia-Android-Fork-from-Fork/actions/runs/10762876260/job/29843752198#step:19:26)
- [x] shouldn't comment when no change | [reference1](https://github.com/Rd4dev/Oppia-Android-Fork-from-Fork/pull/40#issuecomment-2337237045) | [reference2](https://github.com/Rd4dev/Oppia-Android-Fork-from-Fork/pull/40#issuecomment-2337278404)
- [x] should comment on change | [comment](https://github.com/Rd4dev/Oppia-Android-Fork-from-Fork/pull/40#issuecomment-2337251971) | [reference](https://github.com/Rd4dev/Oppia-Android-Fork-from-Fork/pull/40#issuecomment-2337260315)
- [x] comment on previous build fail (replicated!) | [comment](https://github.com/Rd4dev/Oppia-Android-Fork-from-Fork/pull/40#issuecomment-2337297618) | [reference](https://github.com/Rd4dev/Oppia-Android-Fork-from-Fork/pull/40#issuecomment-2337310429)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by Rd4dev** [comment]
@BenHenning, would this approach work in limiting the report thread in the right way? Can you PTAL?

Also, Noticing that previous stat runs sometimes fail [[workflow run](https://github.com/oppia/oppia-android/actions/runs/10765603663)], if the artifacts aren’t uploaded, the next check would treat it as if no previous log was found, potentially leading to duplicated comments.

**Review by BenHenning — APPROVED** [review]
Ah this is a really clever solution--great idea! Thanks for creating this @Rd4dev and for the thorough testing that you included in the PR! I have no additional suggestions, this LGTM as-is. :)

**Comment by BenHenning** [comment]
Given how much the build stats workflow has been 'spamming' PRs (and keeping them from being auto-closed from Oppiabot stale detection), enabling auto-merge to get this in soon.

**Comment by Rd4dev** [comment]
Thank you so much @BenHenning. I’d like to clarify the failure cases with the stats reports, as they seem to fail often. Is this likely a flake, or can it be fixed? I’m concerned it might lead to duplicated comments with previous failure stats.

The artifact approach seemed straightforward and clean, but wondering if it’s unreliable, would checking actual comments via the GitHub API to compare changes be a viable alternative? (I haven’t tried this yet...) but just like to know the best approach.

**Comment by BenHenning** [comment]
> Thank you so much @BenHenning. I’d like to clarify the failure cases with the stats reports, as they seem to fail often. Is this likely a flake, or can it be fixed? I’m concerned it might lead to duplicated comments with previous failure stats.
> 
> The artifact approach seemed straightforward and clean, but wondering if it’s unreliable, would checking actual comments via the GitHub API to compare changes be a viable alternative? (I haven’t tried this yet...) but just like to know the best approach.

What failures are you observing? It seems that the stats workflow has been fairly reliable, but admittedly I haven't actually analyzed it in detail.

Separately, I notice that CI workflows are failing due to us using a very old version of upload artifact in existing workflows. Could you maybe update those in this PR? Since we're going to merge this soon, it would be convenient to go ahead and fix that here so that we can unblock the rest of the team (it seems something changed on GitHub's side that's presumably going to cause all PRs to fail).

**Comment by Rd4dev** [comment]
Updated this PR to use v4 upload-artifact.

>What failures are you observing?

Though the last couple of stats.yml failures are due to the deprecated v2 artifact, the previous checks to them too seem to fail in most cases (with ProGuard issues, I guess).

**Actions/stats check:** 

[[Actions Tab](https://github.com/oppia/oppia-android/actions/workflows/stats.yml)]

Screenshot_20240912-135444

Stat runs:

Screenshot_20240912-140742

Failure at build - feature branch step: (Run # 154)

[[Failure stack trace # 154](https://github.com/oppia/oppia-android/actions/runs/10756437126/job/29829297932#step:14:6542)]

Screenshot_20240912-140918

The same PR passing checks (Run # 155)

[[Passing stack trace # 155](https://github.com/oppia/oppia-android/actions/runs/10765603663/job/29850099146)]

Screenshot_20240912-141019

**Comment by BenHenning** [comment]
Thanks @Rd4dev! As far as I can tell, all the failures were due to the v4 issue but I'll keep an eye out for any other build flakes that might be occurring.

**Pull request merged**
