### PR TITLE
Fix #5079: Gradle Build Failed - Task :utility:kaptGenerateStubsDebugKotlin FAILED

### LINKED ISSUE #5079: [BUG]: Gradle Build Failed - Task :utility:kaptGenerateStubsDebugKotlin FAILED
### Describe the bug

New contributors try to build oppia-android getting this error:

### Error Log

```bash
> Task :utility:kaptGenerateStubsDebugKotlin FAILED
Execution failed for task ':utility:kaptGenerateStubsDebugKotlin'.
> Could not resolve all files for configuration ':utility:debugCompileClasspath'.
   > Failed to transform model.jar (project :model) to match attributes {artifactType=android-classes, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=15, org.gradle.libraryelements=jar, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: E:\Android\open-source\oppia-android\model\build\libs\model.jar.
         > Failed to transform 'E:\Android\open-source\oppia-android\model\build\libs\model.jar' using Jetifier. Reason: Unsupported class file major version 59. (Run with --stacktrace for more details.)
```

### Steps To Reproduce

1. Clone oppia-android
2. Run gradle build 1st time in Android studio

### Expected Behavior

Gradle build successful

### Screenshots/Videos

_No response_

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by theMr17**
## Explanation

Fixes #5079

The error message indicates that there's a compatibility issue with the Java version being used for the project. The `Unsupported class file major version 59` suggests that the code in the model.jar (project :model) file is compiled with a Java version higher than the one being used by the project.

This PR explicitly set the source and target compatibility to Java 8 for the project. This ensures that the project uses Java 8, which is compatible with class files compiled with major version 59 (Java 15).

By making this change, we ensure that the project's Java version aligns with the Java version used to compile the model.jar file, thus resolving the compatibility issue and allowing the build process to proceed without errors.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
@the-mr17, could you please add an explanation to the PR description as to why the solution fixes the error? What does the error message mean and what do the new lines of code do?

**Review by adhiamboperes — APPROVED** [review]
Thanks @the-mr17, this LGTM.

**Comment by theMr17** [comment]
Hi @adhiamboperes, just out of curiosity, can you please tell me why this test is failing and how shall I handle this in future PRs?

image

**Comment by adhiamboperes** [comment]
> Hi @adhiamboperes, just out of curiosity, can you please tell me why this test is failing and how shall I handle this in future PRs?
> 
> image


Sometimes the CI times out because the jobs are large, or some other internal issue.

**Pull request merged**
