### PR TITLE
Dark mode implementation - Fixed Post PR Changes Part 1

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

Dark mode implementation - Fixed Post PR Changes Part 1

This PR changes following Dark Mode Post PR :-

1. Remove `component_color_shared_text_view_text_color` and `color_palette_secondary_text_color`and use other defined text colors.
2. Check all drawable,colors,styles files to make sure that we are using `component_colors` only.
3. Remove ‘component_color_shared_content_item_text_view_color’  as we have ‘component_color_shared_primary_text_color’   
4. Remove ‘ToolbarTitle’  and use ‘ToolbarTextAppearance’ in titleTextAppearance  for ToolBar in different xml’s files. 
5. Remove `component_color_general_item_background_solid_color` and `component_color_general_item_background_stroke_color` and `general_item_border.xml`
6. Remove all other component_colors which are using `color_palette_dark_text_color` and only use `component_color_shared_primary_dark_text_color`
7. Remove `general_item_background_border_light` and use `general_item_background_border`.
8. Remove `general_item_background_border_black`

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@rt4914 PTAL, I make changes for Dark Mode Post PR changes as per docs.

**Review by MohitGupta121 — COMMENTED** [review]
@rt4914 PTAL, I make changes for Dark Mode Post PR changes as per docs.
As file changes running huge. So make it easy to review I divided this changes in 2 parts.

**Review by rt4914 — APPROVED** [review]
Really nice work @MohitGupta121

**Comment by MohitGupta121** [comment]
Thanks @rt4914 
I discussed with Rajat related screenshots in Google Chat, and according to him, this PR is clear without screenshots.

**Comment by MohitGupta121** [comment]
@BenHenning PTAL, if you have any suggestions.

**Review by BenHenning — APPROVED** [review]
Thanks @MohitGupta121. LGTM for codeowners

**Pull request merged**
