### PR TITLE
Fix #4602: Revert "Fix #4449: Modify the design of the chapter list in lessons tab "

### LINKED ISSUE #4449: Modify the design of the chapter list in lessons tab
**Is your feature request related to a problem? Please describe.**
The chapters (recycler items) on the lessons tab do not look clickable. Users do not get an idea of how to start a chapter from that screen.

**Describe the solution you'd like**
Modify the design of the chapter list so that it clearly shows chapters that are completed, ready to start and locked. Also, make sure that the chapter list  drop down is open by default.

### LINKED ISSUE #4602: Develop branch is broken
**Describe the bug**
Two PRs were merged in succession that led to develop breaking, despite no conflicts.

**To Reproduce**
See develop branch.

**Expected behavior**
Develop shouldn't be broken.

**Demonstration**
N/A

**Environment**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by BenHenning**
Reverts oppia/oppia-android#4535

/cc @JishnuGoyal

### CODE REVIEW

**Comment by BenHenning** [comment]
PTAL @rt4914.

**Comment by BenHenning** [comment]
@seanlip since this is a clean reversion, could you please approve? I'll force merge it (I don't want to wait on this review since it's blocking develop).

**Review by seanlip — APPROVED** [review]

**Comment by seanlip** [comment]
Looks fine, tests seem to be passing.

**Comment by BenHenning** [comment]
Thanks--force merging this to unblock folks.

**Pull request merged**
