### PR TITLE
Fix #2329: Enabled pseudolocales

### LINKED ISSUE #2329: Enable pseudoLocales for RTL language testing
For RTL Layout testing we need to enable pseudoLocales in debug mode.
Reference: https://developer.android.com/guide/topics/resources/pseudolocales

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #2329

Enabled pseudo locales so that the english language can look like arabic in application.

### Reference
https://github.com/oppia/oppia-android/wiki/RTL-Guidelines
https://developer.android.com/guide/topics/resources/pseudolocales

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
cc: @FareesHussain @ForgottenProgramme @ShridharGoel for future RTL PRs testing.

**Review by FareesHussain — APPROVED** [review]
LGTM,

@rt4914 As Bazel build is passed this won't affect when switched to bazel right?

I've tested it and I think this is better than force RTL 
and #2229 and #2245 should be closed according to the below screenshots

**Comment by rt4914** [comment]
`testAudioWithWifi_openFractionsExploration_changeLanguage_clickNext_checkLanguageIsHinglish ` test failed twice on this PR.

**Comment by FareesHussain** [comment]
> `testAudioWithWifi_openFractionsExploration_changeLanguage_clickNext_checkLanguageIsHinglish ` test failed twice on this PR.

But it passes locally
image

**Comment by rt4914** [comment]
> > `testAudioWithWifi_openFractionsExploration_changeLanguage_clickNext_checkLanguageIsHinglish ` test failed twice on this PR.
> 
> But it passes locally
> image

@FareesHussain Yes, i did check that locally and it passes.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Pull request merged**
