### PR TITLE
Remove self-code ownership until 2021-01-05

### PR DESCRIPTION
**Pull request by BenHenning**
Removing self code ownership until I return from holiday on 2021-01-05.

#2304 is tracking restoring ownership for after I return.

### CODE REVIEW

**Comment by BenHenning** [comment]
@seanlip I think you need to approve as a repo owner.

**Review by seanlip — APPROVED** [review]
Hm, weird. Done, thanks!

**Comment by BenHenning** [comment]
@seanlip I set it up this way for redundancy (CODEOWNERS is owned by @oppia/owners), and since I can't approve my own PR you automatically get added. :)

**Comment by seanlip** [comment]
Ah, makes sense. Got it, thanks!

**Pull request merged**
