### PR TITLE
Fix part of #2258: Improvements in Add Profile Activity (Accessibility point of view)

### PR DESCRIPTION
**Pull request by yk1ax**
## Explanation

Fixes part of #2258 
I have taken care of the accessibility issues other than adding contentDescription to the three editTexts. I'm still trying to figure out how to set contentDescription for the editTexts as they are binding through ProfileInputView so I'm trying to do something from ProfileInputView.kt
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by yk1ax** [comment]
@ARJUPTA can you have a look at my approach for resolving the contrast issues. Especially the change made at app/src/main/res/values/colors.xml line 79.

**Comment by rt4914** [comment]
@ARJUPTA Suggest not assigning any issues related to `Accessibility` to anyone and marking all issues as blocked because we need more details for these PRs. For example, the content description is correct or not and also the color change in this PR does solve the issue but does not mean that its correct.

Therefore I am closing this PR.

@yk1ax Apologies for inconvenience but this issue needs more details and cannot be solved right now. Thanks.

**Comment by yk1ax** [comment]
Okay @rt4914

**Comment by Arjupta** [comment]
> @ARJUPTA Suggest not assigning any issues related to `Accessibility` to anyone and marking all issues as blocked because we need more details for these PRs. For example, the content description is correct or not and also the color change in this PR does solve the issue but does not mean that its correct.
> 
> Therefore I am closing this PR.
> 
> @yk1ax Apologies for inconvenience but this issue needs more details and cannot be solved right now. Thanks.

Okay @rt4914 , actually this issue was already assigned to @yk1ax before we decided to keep them blocked. I have also mentioned about this condition on the issue - [link](https://github.com/oppia/oppia-android/issues/2258#issuecomment-751163839)

**Pull request closed without merging**
