### PR TITLE
Fix #3239: Hi-Fi Admin Auth Tablet Fix

### LINKED ISSUE #3239: Hi-Fi Admin Auth Tablet
Mobile - https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/785546bd-b160-4d9b-b5d6-53ddc1b4a80a/

Tablet - https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/f2b8acef-b71a-40c3-a4f4-e426e6be563f/

**Follow this guide**: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### PR DESCRIPTION
**Pull request by Pranav-Bobde**
## Explanation
Fix #3239 : Corrected the text-size of button from 14sp to 16sp.
Did not notice any other difference.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## Screenshots
BEFORE &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; AFTER
PORTRAIT 
Mobile (Pixel)
&emsp;&emsp; 
Tablet (Pixel C)
&emsp;&emsp;

### CODE REVIEW

**Comment by rt4914** [comment]
@Pranav-Bobde Please add screenshots and assign it back to me.

**Comment by Pranav-Bobde** [comment]
@rt4914 Uploaded the screenshots. PTAL.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@Pranav-Bobde This textsize change is not needed as I have checked the mocks links and it clearly mentions `14sp` only for both mocks. Therefore closing this PR and issue. Thanks a lot.

**Pull request closed without merging**
