### PR TITLE
Fix #3962: Embed proguard.map in optimized AAB builds

### LINKED ISSUE #3962: Add Proguard map file to AABs
AABs can include Proguard map files directly to simplify artifact storage & uploading to Play Store. It'd be nice to add this functionality to our own AAB build rules.

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fix #3962

This PR updates the oppia_android_application macro to support embedding the generated proguard.map file in optimized builds within the AAB. This is something that Gradle does, and it's especially convenient since it'll make both archiving & uploading the build to Play Store overall nicer. To verify that it works, download the alpha build from the CI artifacts and open it in a zip/archive viewer to see the proguard.map file under the top-level BUNDLE-METADATA directory.

APK and non-optimized AAB builds should be uanffected.

Note that the specific solution here came after multiple iterations of trying to determine how Gradle went about embedding the file since bundletool wasn't making it simple to add the metadata directory. The final solution was to add a new stage at the end of the pipeline to update the generated AAB to include the directory, though this needed to be done such that no directories were added themselves as zip entries (since this breaks bundletool). See https://github.com/google/bundletool/issues/251 for a more detailed description of the issues discovered as part of this PR.

No tests are added since this is a Bazel infrastructure-only change, and we don't currently have tests for our Starlark rules. Manual verification should suffice.

Finally, I updated the other rules to accept single inputs since none of them actually pass multiple inputs. And, I'm planning to cherry-pick this into the release-0.6 branch to make the release archiving & upload easier, even though #3962 is not actually a release blocker.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A -- infrastructural change that doesn't affect any user flows

### CODE REVIEW

**Comment by BenHenning** [comment]
@anandwana001 PTAL as a full reviewer.

**Review by anandwana001 — APPROVED** [review]
LGTM,

@BenHenning Just to confirm, am I looking at the correct file here?
Screenshot 2021-10-27 at 17 30 01

**Comment by BenHenning** [comment]
> LGTM,
> 
> @BenHenning Just to confirm, am I looking at the correct file here? Screenshot 2021-10-27 at 17 30 01

That's correct @anandwana001 -- thanks for checking & for the review!

**Comment by BenHenning** [comment]
Merging since it seems that there are no outstanding items.

**Comment by BenHenning** [comment]
This is verified as working on the release-0.6 build.

**Pull request merged**
